Repository zowe/api-layer, pull requests merged in 2018-12, with the labels that each got.

#117 api catalog ui unit test results
  Jenkinsfile
  api-catalog-ui/frontend/package-lock.json
  api-catalog-ui/frontend/package.json
Labels: passed CA tests, review

#144 Fix grid in IE 11 with polyfill
  api-catalog-ui/frontend/package-lock.json
  api-catalog-ui/frontend/package.json
  api-catalog-ui/frontend/src/components/Dashboard/Dashboard.css
  api-catalog-ui/frontend/src/components/Header/Header.jsx
  api-catalog-ui/frontend/src/components/Swagger/Swagger.css
  api-catalog-ui/frontend/src/index.js
Labels: passed CA tests, review, under CA testing

#128 CII - Sonar Integration
  Jenkinsfile
  build.gradle
  gradle.properties
  gradle/sonar.gradle
Labels: review, under CA testing

#148 Certificates for zLUX
  helloworld-expressjs/apiLayerService.js
  helloworld-expressjs/index.js
  keystore/localhost/localhost.keystore.cer
  keystore/localhost/localhost.keystore.csr
  keystore/localhost/localhost.keystore.key
  keystore/localhost/localhost.keystore.p12
  keystore/localhost/localhost.keystore.p12.csr
  keystore/localhost/localhost.keystore.p12_signed.cer
  keystore/localhost/localhost.keystore_signed.cer
  keystore/localhost/localhost.truststore.p12
  scripts/apiml_cm.sh
  zowe-install/src/main/resources/scripts/setup-apiml-certificates-template.sh
Labels: review

#147 HTTPS for integration-enabler-jersey #75
  docs/local-configuration.md
  helloworld-jersey/build.gradle
  helloworld-jersey/src/main/resources/eureka-client.properties
  helloworld-jersey/src/main/webapp/WEB-INF/web.xml
  integration-enabler-java/src/main/java/com/ca/mfaas/eurekaservice/RestDiscoveryListener.java
  integration-enabler-java/src/test/resources/eureka-client.properties
Labels: passed CA tests, review

#152 Trust z/OSMF and external certificates
  helloworld-expressjs/index.js
  keystore/README.md
  keystore/local_ca/extca.1.cer
  keystore/local_ca/extca.2.cer
  keystore/local_ca/extca.3.cer
  keystore/local_ca/localca.cer
  keystore/local_ca/localca.keystore.p12
  scripts/apiml_cm.sh
  zowe-install/src/main/resources/scripts/api-mediation-start-catalog-template.sh
  zowe-install/src/main/resources/scripts/api-mediation-start-discovery-template.sh
  zowe-install/src/main/resources/scripts/api-mediation-start-gateway-template.sh
  zowe-install/src/main/resources/scripts/setup-apiml-certificates-template.sh
Labels: passed CA tests, ready for CA testing, review

#158 Better message for insufficient privileges for z/OSMF keyring during installation
  scripts/apiml_cm.sh
Labels: ready for CA testing, review

#159 Set release version (0.3.0.)
  gradle.properties
Labels: review, under CA testing

#160 Set new snapshot version (0.3.1-SNAPSHOT)
  gradle.properties
Labels: review, under CA testing

#164 Fixed a alias name when exporting a certificate
  scripts/apiml_cm.sh
Labels: ready for CA testing, review

#165 Better messages for z/OSMF trust and external certificates
  scripts/apiml_cm.sh
  zowe-install/src/main/resources/scripts/setup-apiml-certificates-template.sh
Labels: ready for CA testing, review

#166 Use ZOWE_ROOT_DIR in instructions for importing z/OSMF certificates
  zowe-install/src/main/resources/scripts/setup-apiml-certificates-template.sh
Labels: ready for CA testing, review
