Repository zowe/api-layer, pull requests merged in 2019-01, with the labels that each got.

#163 Release documentation
  docs/release.md
Labels: review, under CA testing

#170 Use local CA signed certificate for discoverable-client on localhost
  config/local/discoverable-client.yml
Labels: review, under CA testing

#175 Do not require superuser to run z/OSMF keyring import
  scripts/apiml_cm.sh
Labels: review, under CA testing

#169 Add debug profiles for APIML
  api-catalog-services/src/main/resources/application.yml
  config/local/api-catalog-service.yml
  discovery-service/src/main/resources/application.yml
  gateway-service/src/main/resources/application.yml
Labels: passed CA tests

#177 Convert security token in query parameter to cookie
  gateway-service/src/main/java/com/ca/mfaas/gateway/filters/post/ConvertAuthTokenInUriToCookieFilter.java
  gateway-service/src/main/java/com/ca/mfaas/gateway/routing/MfaasRoutingConfig.java
  gateway-service/src/test/java/com/ca/mfaas/gateway/filters/post/ConvertAuthTokenInUriToCookieFilterTest.java
Labels: passed CA tests, review

#183 APIML authentication service for zLUX
  .gitignore
  apiml-auth/README.md
  apiml-auth/lib/apimlAuth.js
  apiml-auth/lib/apimlAuth.test.js
  apiml-auth/lib/tokenInjector.js
  apiml-auth/package.json
  apiml-auth/pluginDefinition.json
  keystore/local_ca/localca.cer
  keystore/local_ca/localca.keystore.p12
  keystore/localhost/localhost.keystore.cer
  keystore/localhost/localhost.keystore.csr
  keystore/localhost/localhost.keystore.key
  keystore/localhost/localhost.keystore.p12
  keystore/localhost/localhost.keystore_signed.cer
  keystore/localhost/localhost.truststore.p12
  package.json
  zlux-api-catalog/README.md
  zlux-api-catalog/images/api-catalog.png
  zlux-api-catalog/pluginDefinition.json
  zlux-api-catalog/web/index.html
  zowe-install/build.gradle
  zowe-install/src/main/resources/scripts/setup-apiml-certificates-template.sh
Labels: passed CA tests, review

#184 Add z/OSMF provider
  api-catalog-services/src/main/java/com/ca/mfaas/apicatalog/security/SecurityConfiguration.java
  api-catalog-services/src/main/resources/application.yml
  api-catalog-ui/frontend/.env.test
  api-catalog-ui/frontend/package.json
  api-catalog-ui/frontend/src/components/Login/Login.jsx
  api-catalog-ui/frontend/src/e2e/README.md
  api-catalog-ui/frontend/src/e2e/e2e.test.jsx
  apiml-auth/lib/apimlAuth.js
  gateway-service/src/main/java/com/ca/mfaas/gateway/routing/MfaasRouteLocator.java
  gateway-service/src/main/resources/application.yml
  gateway-service/src/main/resources/templates/home.html
  integration-tests/README.md
  integration-tests/src/test/java/com/ca/mfaas/apicatalog/ApiCatalogSecurityTest.java
  integration-tests/src/test/resources/environment-configuration.yml
  security-module/src/main/java/com/ca/mfaas/security/config/SecurityConfigurationProperties.java
  security-module/src/main/java/com/ca/mfaas/security/login/ZosmfAuthenticationProvider.java
  security-module/src/main/java/com/ca/mfaas/security/token/TokenService.java
  zlux-api-catalog/web/images/api-catalog.png
  zlux-api-catalog/web/index.html
Labels: passed CA tests, review

#186 Configure z/OSMF security for Zowe
  api-catalog-services/src/main/resources/application.yml
  config/local/api-defs/zosmf-sample.yml
  zowe-install/src/main/resources/scripts/api-mediation-start-catalog-template.sh
  zowe-install/src/main/resources/scripts/api-mediation-start-gateway-template.sh
Labels: review

#178 override isMultipart method
  api-catalog-ui/frontend/package-lock.json
  gateway-service/src/main/java/com/ca/mfaas/gateway/config/MultipartConfig.java
  gateway-service/src/test/java/com/ca/mfaas/gateway/config/MultipartConfigTest.java
Labels: passed CA tests, review

#185 Add z/OSMF filter to change JWT token to LTPA
  gateway-service/src/main/java/com/ca/mfaas/gateway/filters/pre/ZosmfFilter.java
  gateway-service/src/main/java/com/ca/mfaas/gateway/routing/MfaasRoutingConfig.java
  gateway-service/src/test/java/com/ca/mfaas/gateway/filters/pre/ZosmfFilterTest.java
  integration-tests/README.md
  security-module/src/main/java/com/ca/mfaas/security/token/TokenService.java
  security-module/src/test/java/com/ca/mfaas/security/token/TokenServiceTest.java
Labels: passed CA tests, review

#187 Fixes for APIML authentication plugin Zowe on z/OS
  apiml-auth/README.md
  apiml-auth/lib/apimlAuth.js
  apiml-auth/lib/apimlAuth.test.js
  apiml-auth/lib/tokenInjector.js
  apiml-auth/package.json
  apiml-auth/pluginDefinition.json
Labels: ready for CA testing, review

#188 Secure initialization of the JWT token service secret from APIML private key
  api-catalog-services/src/main/java/com/ca/mfaas/apicatalog/swagger/SubstituteSwaggerGenerator.java
  api-catalog-services/src/test/java/com/ca/mfaas/apicatalog/swagger/SubstituteSwaggerGeneratorTest.java
  common-service-core/src/main/java/com/ca/mfaas/security/HttpsFactory.java
  common-service-core/src/test/java/com/ca/mfaas/security/HttpsFactoryTest.java
  common-service-core/src/test/java/com/ca/mfaas/security/SecurityTestUtils.java
  common-service-core/src/test/java/com/ca/mfaas/tomcat/TomcatHttpsTest.java
  gateway-common/src/main/java/com/ca/mfaas/product/web/HttpConfig.java
  security-module/src/main/java/com/ca/mfaas/security/config/InitializeTokenSecret.java
  security-module/src/main/java/com/ca/mfaas/security/config/SecurityConfigurationProperties.java
  security-module/src/main/java/com/ca/mfaas/security/token/TokenService.java
  security-module/src/test/java/com/ca/mfaas/security/token/TokenServiceTest.java
Labels: passed CA tests, review

#190 Updated development documentation and ability to read EBCDIC certificates
  README.md
  apiml-auth/README.md
  apiml-auth/lib/apimlAuth.js
Labels: review

#189 Add /query endpoint
  api-catalog-services/src/main/java/com/ca/mfaas/apicatalog/security/SecurityConfiguration.java
  integration-tests/build.gradle
  integration-tests/src/test/java/com/ca/mfaas/apicatalog/ApiCatalogEndpointIntegrationTest.java
  integration-tests/src/test/java/com/ca/mfaas/gatewayservice/LoginIntegrationTest.java
  integration-tests/src/test/java/com/ca/mfaas/gatewayservice/QueryIntegrationTest.java
  integration-tests/src/test/java/com/ca/mfaas/gatewayservice/SecurityUtils.java
  security-module/src/main/java/com/ca/mfaas/security/config/SecurityConfigurationProperties.java
  security-module/src/main/java/com/ca/mfaas/security/login/ZosmfAuthenticationProvider.java
  security-module/src/main/java/com/ca/mfaas/security/query/QueryFilter.java
  security-module/src/main/java/com/ca/mfaas/security/query/QueryResponse.java
  security-module/src/main/java/com/ca/mfaas/security/query/SuccessfulQueryHandler.java
  security-module/src/main/java/com/ca/mfaas/security/token/TokenService.java
  security-module/src/test/java/com/ca/mfaas/security/login/ZosmfAuthenticationProviderTest.java
  security-module/src/test/java/com/ca/mfaas/security/query/QueryFilterTest.java
  security-module/src/test/java/com/ca/mfaas/security/query/SuccessfulQueryHandlerTest.java
  security-module/src/test/java/com/ca/mfaas/security/token/TokenServiceTest.java
Labels: passed CA tests, review

#196 Update API catalog HP link
  api-catalog-services/src/main/resources/application.yml
  api-catalog-services/src/test/resources/application.yml
  api-catalog-ui/frontend/package-lock.json
Labels: passed CA tests, review

#195 Update copyright in footer
  api-catalog-ui/frontend/src/components/Footer/Footer.jsx
Labels: passed CA tests, review

#206 Specific release support
  scripts/publish_and_release.sh
Labels: review, under CA testing

#207 Remove security options from GW homepage & Update legal in footer
  api-catalog-ui/frontend/.eslintrc
  api-catalog-ui/frontend/src/components/Footer/Footer.jsx
  api-catalog-ui/frontend/src/components/Footer/Footer.test.jsx
  api-catalog-ui/frontend/src/components/Footer/footer.css
  gateway-service/src/main/resources/templates/home.html
Labels: review, under CA testing

#208 Archive source code during releasing
  scripts/publish_and_release.sh
Labels: review, under CA testing

#211 Remove gradle wrapper
  .gitignore
  Jenkinsfile
  bootstrap_gradlew.bat
  bootstrap_gradlew.sh
  gradle/wrapper/gradle-wrapper.jar
  scripts/publish_and_release.sh
Labels: review, under CA testing

#214 Change z/OSMF service Id
  config/local/api-defs/zosmf-sample.yml
Labels: review, under CA testing

#212 Never show header on login screen
  api-catalog-ui/frontend/.eslintrc
  api-catalog-ui/frontend/mocked-backend/assets/apidoc/apicatalog.json
  api-catalog-ui/frontend/mocked-backend/assets/services/apicatalog.json
  api-catalog-ui/frontend/mocked-backend/routes/routes.js
  api-catalog-ui/frontend/mocked-backend/server.js
  api-catalog-ui/frontend/src/components/App/App.css
  api-catalog-ui/frontend/src/components/App/App.jsx
  api-catalog-ui/frontend/src/components/App/App.test.js
  api-catalog-ui/frontend/src/components/App/AppContainer.jsx
  api-catalog-ui/frontend/src/services/user.service.jsx
Labels: passed CA tests, review

#217 Configurable z/OSMF keyring and user in Zowe Installation
  zowe-install/src/main/resources/scripts/setup-apiml-certificates-template.sh
Labels: passed CA tests, review

#210 Clear search filter on page transition
  api-catalog-ui/frontend/.eslintrc
  api-catalog-ui/frontend/src/components/Dashboard/Dashboard.jsx
  api-catalog-ui/frontend/src/components/Dashboard/Dashboard.test.jsx
  api-catalog-ui/frontend/src/components/Dashboard/DashboardContainer.jsx
  api-catalog-ui/frontend/src/components/DetailPage/DetailPage.test.jsx
Labels: passed CA tests, review

#218 Update manual test guidelines
  docs/manual_tests.md
Labels: review, under CA testing

#222 Login error messages formating
  api-catalog-services/src/main/resources/application.yml
  api-catalog-ui/frontend/mocked-backend/assets/hello/hello.html
  api-catalog-ui/frontend/mocked-backend/assets/services/login_success.json
  api-catalog-ui/frontend/mocked-backend/assets/services/user-name-invalid.json
  api-catalog-ui/frontend/mocked-backend/routes/routes.js
  api-catalog-ui/frontend/src/components/Login/Login.jsx
  api-catalog-ui/frontend/src/components/Login/Login.test.jsx
  api-catalog-ui/frontend/src/epics/fetch-tiles.jsx
Labels: passed CA tests, ready for CA testing, review
