Repository zowe/api-layer, pull requests merged in 2019-03, with the labels that each got.

#251 Add Good README.md
  .circleci/config.yml
  README.md
Labels: review

#249 bean overriding problem
  integration-enabler-spring-v1/src/main/java/com/ca/mfaas/enable/EnableApiDiscovery.java
  integration-enabler-spring-v1/src/main/java/com/ca/mfaas/enable/EnablerV1Config.java
  integration-enabler-spring-v1/src/main/java/com/ca/mfaas/enable/EnablerV1SpringFoxConfig.java
  integration-enabler-spring-v1/src/main/java/com/ca/mfaas/enable/api/ApiDocController.java
  integration-enabler-spring-v1/src/main/java/com/ca/mfaas/enable/services/LocalApiDocService.java
  integration-enabler-spring-v2/src/main/java/com/ca/mfaas/enable/EnableApiDiscovery.java
  integration-enabler-spring-v2/src/main/java/com/ca/mfaas/enable/EnablerV2Config.java
  integration-enabler-spring-v2/src/main/java/com/ca/mfaas/enable/EnablerV2SpringFoxConfig.java
  integration-enabler-spring-v2/src/main/java/com/ca/mfaas/enable/api/ApiDocController.java
  integration-enabler-spring-v2/src/main/java/com/ca/mfaas/enable/model/ApiPropertiesContainer.java
  integration-enabler-spring-v2/src/main/java/com/ca/mfaas/enable/services/LocalApiDocService.java
Labels: passed CA tests, review

#256 revert changes
  .circleci/config.yml
  README.md
Labels: passed CA tests, review

#265 New ADR format
  .adr-dir
  design-decisions/README.md
  design-decisions/TEMPLATE.md
  design-decisions/supported-java-versions.md
  docs/architecture/decisions/0001-record-architecture-decisions.md
  docs/architecture/decisions/0002-target-platform-and-supported-runtimes.md
  docs/architecture/decisions/README.md
Labels: review, under CA testing

#267 ADR - Discovery of externally accessible URL of API Gateway
  docs/architecture/decisions/0003-discovery-of-externally-accessible-url-of-api-gateway.md
Labels: passed CA tests, review

#262 Defect/cache refresh service
  api-catalog-services/src/main/java/com/ca/mfaas/apicatalog/model/APIService.java
  api-catalog-services/src/main/java/com/ca/mfaas/apicatalog/services/cached/CacheRefreshService.java
  api-catalog-services/src/main/java/com/ca/mfaas/apicatalog/services/cached/CachedProductFamilyService.java
  api-catalog-services/src/main/java/com/ca/mfaas/apicatalog/services/cached/CachedServicesService.java
  api-catalog-services/src/test/java/com/ca/mfaas/apicatalog/services/cached/CacheRefreshServiceTest.java
  api-catalog-services/src/test/java/com/ca/mfaas/apicatalog/util/ContainerServiceMockUtil.java
  api-catalog-services/src/test/java/com/ca/mfaas/apicatalog/util/ContainerServiceState.java
Labels: passed CA tests, review
