Repository zowe/api-layer, pull requests merged in 2019-04, with the labels that each got.

#277 API Catalog - Tile change not visible
  api-catalog-services/src/main/java/com/ca/mfaas/apicatalog/services/cached/CachedProductFamilyService.java
  api-catalog-services/src/test/java/com/ca/mfaas/apicatalog/services/cached/CachedProductFamilyTest.java
Labels: passed CA tests, review

#229 Cypress tests
  api-catalog-ui/frontend/.gitignore
  api-catalog-ui/frontend/README.md
  api-catalog-ui/frontend/cypress.json
  api-catalog-ui/frontend/cypress/integration/e2e/dashboard/dashboard.test.js
  api-catalog-ui/frontend/cypress/integration/e2e/detail-page/detail-page.test.js
  api-catalog-ui/frontend/cypress/integration/e2e/login/login-bad.test.js
  api-catalog-ui/frontend/cypress/integration/e2e/login/login-ok.test.js
  api-catalog-ui/frontend/cypress/integration/integration/dashboard/dashboard.test.js
  api-catalog-ui/frontend/cypress/integration/integration/detail/detail.test.js
  api-catalog-ui/frontend/cypress/integration/integration/login/login-bad.test.js
  api-catalog-ui/frontend/cypress/integration/integration/login/login-ok.test.js
  api-catalog-ui/frontend/cypress/plugins/index.js
  api-catalog-ui/frontend/cypress/support/commands.js
  api-catalog-ui/frontend/cypress/support/index.js
  api-catalog-ui/frontend/mocked-backend/routes/routes.js
  api-catalog-ui/frontend/package-lock.json
  api-catalog-ui/frontend/package.json
  gradle.properties
Labels: failed CA tests, review

#279 Private/khavs01/tls12
  api-catalog-services/src/main/resources/application.yml
  api-catalog-services/src/test/resources/application.yml
  discoverable-client/src/main/resources/application.yml
  discoverable-client/src/test/resources/application.yml
  discovery-service/src/main/resources/application.yml
  gateway-common/src/main/java/com/ca/mfaas/product/security/WebServerSecurityConfig.java
  gateway-common/src/test/resources/application.yml
  gateway-service/src/main/resources/application.yml
  gateway-service/src/test/resources/application.yml
Labels: do not merge, review, under CA testing

#291 Fix for non verifying sslcontext to use specific protocol
  api-catalog-services/src/main/java/com/ca/mfaas/apicatalog/ApiCatalogApplication.java
  api-catalog-services/src/main/resources/application.yml
  common-service-core/src/main/java/com/ca/mfaas/security/HttpsFactory.java
  discoverable-client/src/main/java/com/ca/mfaas/client/DiscoverableClientSampleApplication.java
  discoverable-client/src/main/resources/application.yml
  discoverable-client/src/test/resources/application.yml
  discovery-service/src/main/java/com/ca/mfaas/discovery/DiscoveryServiceApplication.java
  discovery-service/src/main/resources/application.yml
  docs/ciphers.md
  gateway-service/src/main/resources/application.yml
  gateway-service/src/test/resources/application.yml
  security-module/src/main/java/com/ca/mfaas/security/config/SecurityConfigurationProperties.java
Labels: review, under CA testing

#286 TransformService defects
  gateway-common/src/main/java/com/ca/mfaas/product/routing/RoutedServices.java
  gateway-common/src/main/java/com/ca/mfaas/product/routing/transform/TransformService.java
  gateway-common/src/test/java/com/ca/mfaas/product/routing/RoutedServicesTest.java
  gateway-common/src/test/java/com/ca/mfaas/product/routing/transform/TransformServiceTest.java
Labels: passed CA tests, review

#296 zD&T compatible ciphers
  api-catalog-services/src/main/resources/application.yml
  discoverable-client/src/main/resources/application.yml
  discovery-service/src/main/resources/application.yml
  docs/ciphers.md
  gateway-service/src/main/resources/application.yml
Labels: review
