Repository zowe/api-layer, pull requests merged in 2019-06, with the labels that each got.

#317 SHA-1 ciphers TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA and TLS_ECDHE_RSA_WI…
  api-catalog-services/src/main/resources/application.yml
  discoverable-client/src/main/resources/application.yml
  discovery-service/src/main/resources/application.yml
  docs/ciphers.md
  gateway-service/src/main/resources/application.yml
Labels: passed CA tests

#304 JWT configuration
  api-catalog-services/src/main/resources/application.yml
  common-service-core/build.gradle
  common-service-core/src/main/java/com/ca/mfaas/security/HttpsFactory.java
  common-service-core/src/main/java/com/ca/mfaas/security/SecurityUtils.java
  common-service-core/src/test/java/com/ca/mfaas/security/HttpsFactoryTest.java
  common-service-core/src/test/java/com/ca/mfaas/security/SecurityTestUtils.java
  common-service-core/src/test/java/com/ca/mfaas/security/SecurityUtilsTest.java
  common-service-core/src/test/resources/jwt-public-key.pub
  gateway-common/src/main/java/com/ca/mfaas/product/web/HttpConfig.java
  gateway-service/src/main/java/com/ca/mfaas/gateway/security/config/InitializeTokenSecret.java
  gateway-service/src/main/java/com/ca/mfaas/gateway/security/service/AuthenticationService.java
  gateway-service/src/main/java/com/ca/mfaas/gateway/security/service/JwtSecurityInitializer.java
  gateway-service/src/main/resources/application.yml
  gateway-service/src/test/java/com/ca/mfaas/gateway/security/query/SuccessfulQueryHandlerTest.java
  gateway-service/src/test/java/com/ca/mfaas/gateway/security/service/AuthenticationServiceTest.java
  gateway-service/src/test/java/com/ca/mfaas/gateway/security/service/JwtSecurityInitializerTest.java
  gateway-service/src/test/resources/application.yml
  keystore/localhost/localhost.keystore.p12
  scripts/README.md
  scripts/apiml_cm.sh
  security-module/build.gradle
  security-module/src/main/java/com/ca/mfaas/security/config/InitializeTokenSecret.java
  security-module/src/main/java/com/ca/mfaas/security/config/SecurityConfigurationProperties.java
  security-module/src/main/java/com/ca/mfaas/security/token/JwtSecurityInitializer.java
  security-module/src/main/java/com/ca/mfaas/security/token/TokenService.java
  security-module/src/test/java/com/ca/mfaas/security/login/ZosmfAuthenticationProviderTest.java
  security-module/src/test/java/com/ca/mfaas/security/query/QueryFilterTest.java
  security-module/src/test/java/com/ca/mfaas/security/query/SuccessfulQueryHandlerTest.java
  security-module/src/test/java/com/ca/mfaas/security/token/JwtSecurityInitializerTest.java
  security-module/src/test/java/com/ca/mfaas/security/token/TokenServiceTest.java
  security-module/src/test/resources/application.yml
  security-service-client-spring/src/main/java/com/ca/apiml/security/config/SecurityConfigurationProperties.java
Labels: passed CA tests

#322 change export shell command
  scripts/apiml_cm.sh
Labels: under CA testing

#320 Fix sonar problems
  api-catalog-services/src/main/java/com/ca/mfaas/apicatalog/controllers/api/ApiCatalogController.java
  api-catalog-services/src/main/java/com/ca/mfaas/apicatalog/health/AuthHealthIndicator.java
  api-catalog-services/src/test/java/com/ca/mfaas/apicatalog/health/AuthHealthIndicatorTest.java
  api-catalog-services/src/test/java/com/ca/mfaas/apicatalog/services/cached/CachedProductFamilyTest.java
  common-service-core/src/main/java/com/ca/mfaas/security/HttpsFactory.java
  discovery-service/src/main/java/com/ca/mfaas/discovery/staticdef/ServiceDefinitionProcessor.java
  gateway-common/src/main/java/com/ca/mfaas/product/service/BuildInfo.java
  gateway-common/src/main/java/com/ca/mfaas/product/service/BuildInfoDetails.java
  gateway-common/src/main/java/com/ca/mfaas/product/service/ServiceStartupEventHandler.java
  gateway-service/src/main/java/com/ca/mfaas/gateway/controllers/GatewayHomepageController.java
  gateway-service/src/main/java/com/ca/mfaas/gateway/filters/post/PageRedirectionFilter.java
  gradle.properties
  gradle/sonar.gradle
  integration-enabler-java/src/main/java/com/ca/mfaas/eurekaservice/client/config/EurekaClientConfiguration.java
  integration-enabler-java/src/main/java/com/ca/mfaas/eurekaservice/client/impl/ApimlEurekaInstanceConfig.java
  integration-enabler-spring-v1/src/main/java/com/ca/mfaas/enable/discovery/EurekaClientSecurityConfiguration.java
  integration-enabler-spring-v2/src/main/java/com/ca/mfaas/enable/discovery/EurekaClientSecurityConfiguration.java
  integration-enabler-spring-v2/src/main/java/com/ca/mfaas/enable/services/ServiceInstances.java
  integration-tests/nosonar/README.md
  security-module/src/main/java/com/ca/mfaas/security/config/SecurityConfigurationProperties.java
  security-module/src/main/java/com/ca/mfaas/security/login/LoginAuthenticationProvider.java
  security-module/src/main/java/com/ca/mfaas/security/login/LoginFilter.java
  security-module/src/main/java/com/ca/mfaas/security/token/TokenAuthenticationProvider.java
  security-module/src/main/java/com/ca/mfaas/security/token/TokenService.java
  security-module/src/main/java/com/ca/mfaas/security/user/InMemoryUserDetailsService.java
Labels: passed CA tests

#295 Fix Pull Requests label bug
  scripts/post_actions.py
Labels: review, under CA testing

#306 Custom Logback layout
  api-catalog-services/src/main/resources/application.yml
  discoverable-client/src/main/resources/application.yml
  discovery-service/src/main/resources/application.yml
  gateway-common/src/main/java/com/ca/mfaas/product/logging/UseridFilter.java
  gateway-common/src/main/resources/logback.xml
  gateway-service/src/main/resources/application.yml
Labels: passed CA tests, review

#310 Create Dan Kelosky-api-layer.txt
  dco_signoffs/Dan Kelosky-api-layer.txt
Labels: failed CA tests

#324 fix for issue #290
  api-catalog-services/src/main/java/com/ca/mfaas/apicatalog/security/ComponentsConfiguration.java
  api-catalog-services/src/main/resources/application.yml
  api-catalog-ui/frontend/src/e2e/e2e.test.jsx
  integration-tests/src/test/java/com/ca/mfaas/gatewayservice/LoginIntegrationTest.java
  security-module/src/main/java/com/ca/mfaas/security/config/SecurityConfigurationProperties.java
  security-service-client-spring/src/main/java/com/ca/apiml/security/config/SecurityConfigurationProperties.java
Labels: passed CA tests
