Repository zowe/api-layer, pull requests merged in 2020-02, with the labels that each got.

#487 Change error message for encodedCharacterFilter
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/pre/EncodedCharactersFilter.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/routing/ApimlRoutingConfig.java
  gateway-service/src/main/resources/gateway-log-messages.yml
  gateway-service/src/test/java/org/zowe/apiml/gateway/filters/pre/EncodedCharactersFilterTest.java
Labels: passed CA tests

#493 Fixed MultipartPutIntegrationTest tests
  integration-tests/src/test/java/org/zowe/apiml/discoverableclient/MultipartPutIntegrationTest.java
Labels: passed CA tests

#495 Replace URL to the Commit Guideline with working one
  CONTRIBUTING.md
Labels: docs, passed CA tests

#497 Improve guide to IDEA based on the encountered issues
  docs/idea-setup.md
Labels: On-boarding enhancement, passed CA tests

#492 Add passticket support to enablers
  common-service-core/src/main/java/org/zowe/apiml/constants/EurekaMetadataDefinition.java
  config/local/api-defs/onboarding-sample.yml-sample
  config/local/api-defs/staticclient.yml
  config/local/api-defs/zosmf-sample.yml_
  discoverable-client/src/main/resources/application.yml
  discovery-service/src/test/java/org/zowe/apiml/discovery/staticdef/ServiceDefinitionProcessorTest.java
  helloworld-jersey/src/main/resources/service-configuration.yml
  helloworld-jersey/src/test/java/org/zowe/apiml/hwsjersey/listener/ServletContextListenerTest.java
  helloworld-spring/src/main/resources/service-configuration.yml
  helloworld-spring/src/test/java/org/zowe/apiml/hellospring/listener/ServletContextListenerTest.java
  integration-tests/src/test/resources/environment-configuration.yml
  onboarding-enabler-java/src/main/java/org/zowe/apiml/eurekaservice/client/config/ApiMediationServiceConfig.java
  onboarding-enabler-java/src/main/java/org/zowe/apiml/eurekaservice/client/config/Authentication.java
  onboarding-enabler-java/src/main/java/org/zowe/apiml/eurekaservice/client/impl/ApiMediationClientImpl.java
  onboarding-enabler-java/src/main/java/org/zowe/apiml/eurekaservice/client/util/ApiMediationServiceConfigReader.java
  onboarding-enabler-java/src/test/java/org/zowe/apiml/eurekaservice/client/impl/ApiMediationClientImplTest.java
  zowe-install/src/main/resources/component-scripts/configure.sh
Labels: passed CA tests

#490 US601302: Clean up - build scripts, etc
  Jenkinsfile
  apiml-common/build.gradle
  apiml-utility/build.gradle
  apiml-utility/src/main/java/org/zowe/apiml/product/logging/ApimlDependencyLogHider.java
  apiml-utility/src/main/java/org/zowe/apiml/product/logging/ApimlLogInjector.java
  apiml-utility/src/main/java/org/zowe/apiml/product/logging/LogLevelInfoFilter.java
  apiml-utility/src/main/java/org/zowe/apiml/product/logging/LoggingConfiguration.java
  apiml-utility/src/main/java/org/zowe/apiml/product/logging/UseridFilter.java
  apiml-utility/src/main/java/org/zowe/apiml/product/logging/annotations/EnableApimlLogger.java
  apiml-utility/src/main/java/org/zowe/apiml/product/logging/annotations/InjectApimlLogger.java
  apiml-utility/src/main/java/org/zowe/apiml/product/monitoring/LatencyUtilsConfigInitializer.java
  apiml-utility/src/main/java/org/zowe/apiml/product/service/ServiceStartupEventHandler.java
  apiml-utility/src/test/java/org/zowe/apiml/product/logging/ApimlDependencyLogHiderTest.java
  apiml-utility/src/test/java/org/zowe/apiml/product/logging/ApimlLogInjectorTest.java
  apiml-utility/src/test/java/org/zowe/apiml/product/logging/LogLevelInfoFilterTest.java
  apiml-utility/src/test/java/org/zowe/apiml/product/monitoring/LatencyUtilsConfigInitializerTest.java
  discoverable-client/README.md
  discoverable-client/build.gradle
  gradle/coverage.gradle
  gradle/license.gradle
  gradle/publish.gradle
  gradle/sonar.gradle
  gradle/versions.gradle
  onboarding-enabler-spring-v1/build.gradle
  onboarding-enabler-spring-v2/build.gradle
  onboarding-enabler-spring/build.gradle
  onboarding-enabler-spring/src/main/java/org/zowe/apiml/enable/register/RegisterToApiLayer.java
  settings.gradle
Labels: passed CA tests

#499 Add pom file to improve Code Insight scan results
  Jenkinsfile
  build.gradle
  gradle/generate-pom.gradle
  gradle/versions.gradle
Labels: under CA testing

#500 Hardboiled/refactor/sonarcloud major
  common-service-core/src/main/java/org/zowe/apiml/security/HttpsConfigError.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/ws/WebSocketProxyError.java
  integration-enabler-spring-v1/src/main/java/org/zowe/apiml/enable/model/ApiPropertiesContainerV1.java
Labels: passed CA tests

#453 Fix npm vulnerabilities
  package-lock.json
  package.json
Labels: under CA testing

#506 Hardboiled/refactor/test speed
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/services/cached/CachedProductFamilyTest.java
  helloworld-jersey/src/main/java/org/zowe/apiml/hwsjersey/listener/ApiDiscoveryListener.java
  helloworld-jersey/src/test/java/org/zowe/apiml/hwsjersey/listener/ServletContextListenerTest.java
  helloworld-spring/src/main/java/org/zowe/apiml/hellospring/listener/ApiDiscoveryListener.java
  helloworld-spring/src/test/java/org/zowe/apiml/hellospring/listener/ServletContextListenerTest.java
  onboarding-enabler-java/src/main/java/org/zowe/apiml/eurekaservice/client/EurekaClientProvider.java
  onboarding-enabler-java/src/main/java/org/zowe/apiml/eurekaservice/client/impl/ApiMediationClientImpl.java
  onboarding-enabler-java/src/main/java/org/zowe/apiml/eurekaservice/client/impl/DiscoveryClientProvider.java
  onboarding-enabler-java/src/test/java/org/zowe/apiml/eurekaservice/client/impl/ApiMediationClientImplTest.java
Labels: passed CA tests

#509 Fix z/OSMF authorization header
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/pre/ZosmfFilter.java
Labels: passed CA tests

#505 enabler custom metadata support
  common-service-core/src/main/java/org/zowe/apiml/util/MapUtils.java
  common-service-core/src/test/java/org/zowe/apiml/util/MapUtilsTest.java
  config/local/discoverable-client.yml
  discoverable-client/src/main/resources/application.yml
  discovery-service/src/main/java/org/zowe/apiml/discovery/staticdef/Service.java
  discovery-service/src/main/java/org/zowe/apiml/discovery/staticdef/ServiceDefinitionProcessor.java
  discovery-service/src/test/java/org/zowe/apiml/discovery/staticdef/ServiceDefinitionProcessorTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/EncodedCharactersTest.java
  onboarding-enabler-java/build.gradle
  onboarding-enabler-java/src/main/java/org/zowe/apiml/eurekaservice/client/config/ApiMediationServiceConfig.java
  onboarding-enabler-java/src/main/java/org/zowe/apiml/eurekaservice/client/impl/ApiMediationClientImpl.java
  onboarding-enabler-java/src/main/java/org/zowe/apiml/eurekaservice/client/util/EurekaInstanceConfigCreator.java
  onboarding-enabler-java/src/test/java/org/zowe/apiml/eurekaservice/client/util/ApiMediationServiceConfigReaderTest.java
  onboarding-enabler-java/src/test/java/org/zowe/apiml/eurekaservice/client/util/EurekaInstanceConfigCreatorTest.java
  onboarding-enabler-java/src/test/resources/additional-service-configuration.yml
  onboarding-enabler-java/src/test/resources/service-configuration.yml
  onboarding-enabler-spring/src/main/java/org/zowe/apiml/enable/register/RegisterToApiLayer.java
  onboarding-enabler-spring/src/test/resources/application.yml
Labels: passed CA tests

#510 Added missed libraries for discoverable client's ui
  discoverable-client/build.gradle
Labels: Please review!, passed CA tests

#496 Remove usage of enablers from AC and GW to only use spring cloud
  api-catalog-services/build.gradle
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/ApiCatalogApplication.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/discovery/DiscoveryConfigProperties.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/instance/InstanceInitializeService.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/instance/InstanceRefreshService.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/services/cached/CachedProductFamilyService.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/SwaggerConfiguration.java
  api-catalog-services/src/main/resources/application.yml
  api-catalog-services/src/test/resources/application.yml
  api-catalog-ui/frontend/cypress/integration/e2e/dashboard/dashboard.test.js
  config/local-multi/api-catalog-service.yml
  config/local/api-catalog-service-ui-testing.yml
  config/local/api-catalog-service.yml
  config/local/discoverable-client.yml
  discoverable-client/src/test/resources/application.yml
  discoverable-client/src/test/resources/bootstrap.yml
  docs/local-configuration.md
  gateway-service/build.gradle
  gateway-service/src/main/java/org/zowe/apiml/gateway/GatewayApplication.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/apidoc/reader/ApiDocController.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/apidoc/reader/ApiDocReader.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/apidoc/reader/ApiDocReaderException.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/WebConfig.java
  gateway-service/src/main/resources/application.yml
  gateway-service/src/test/java/org/zowe/apiml/gateway/apidoc/reader/ApiDocControllerTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/apidoc/reader/ApiDocReaderTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/cache/ServiceCacheEvictorTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/controllers/AuthControllerTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/controllers/CacheServiceControllerTest.java
  gateway-service/src/test/resources/api-doc-invalid-content.json
  gateway-service/src/test/resources/api-doc.json
  gateway-service/src/test/resources/application.yml
  gradle/versions.gradle
  helloworld-spring/src/test/resources/service-config.yml
Labels: failed CA tests, passed CA tests

#508 Enable encoded slashes on Tomcat
  apiml-utility/src/main/java/org/zowe/apiml/product/monitoring/LatencyUtilsConfigInitializer.java
  config/local/gateway-service.yml
  discoverable-client/src/main/java/org/zowe/apiml/client/configuration/TomcatConfiguration.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/TomcatConfiguration.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/pre/EncodedCharactersFilter.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/pre/TomcatFilter.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/routing/ApimlRoutingConfig.java
  gateway-service/src/main/resources/application.yml
  gateway-service/src/main/resources/gateway-log-messages.yml
  gateway-service/src/test/java/org/zowe/apiml/gateway/filters/pre/EncodedCharactersFilterTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/filters/pre/TomcatFilterTest.java
  gateway-service/src/test/resources/gateway-messages.yml
  gateway-service/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/EncodedCharactersTest.java
  zowe-install/src/main/resources/component-scripts/start.sh
  zowe-install/src/main/resources/scripts/api-mediation-start-gateway-template.sh
Labels: passed CA tests

#512 Enablers some fixes
  onboarding-enabler-java/src/main/java/org/zowe/apiml/eurekaservice/client/config/Authentication.java
  onboarding-enabler-spring/build.gradle
  onboarding-enabler-spring/src/main/java/org/zowe/apiml/enable/config/EnableApiDiscoveryConfig.java
  onboarding-enabler-spring/src/main/java/org/zowe/apiml/enable/register/RegisterToApiLayer.java
Labels: Please review!, passed CA tests

#513 enabler sample apps improvements
  config/local/integration-enabler-spring-v1-sample-app.yml
  discoverable-client/build.gradle
  discoverable-client/src/main/java/org/zowe/apiml/client/DiscoverableClientSampleApplication.java
  discoverable-client/src/main/resources/application.yml
  discovery-service/src/main/java/org/zowe/apiml/discovery/GatewayNotifier.java
  integration-enabler-spring-v1-sample-app/build.gradle
  integration-enabler-spring-v1-sample-app/src/main/java/org/zowe/apiml/sample/enable/v1/EnablerV1SampleApplication.java
  integration-enabler-spring-v1-sample-app/src/main/java/org/zowe/apiml/sample/enable/v1/config/SwaggerConfiguration.java
  integration-enabler-spring-v1-sample-app/src/main/resources/application.yml
  integration-enabler-spring-v1-sample-app/src/main/resources/swagger.json
Labels: passed CA tests

#516 change location of ehCache's storage files
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/CacheConfig.java
  gateway-service/src/main/resources/ehcache.xml
  zowe-install/src/main/resources/component-scripts/start.sh
Labels: passed CA tests

#521 Changed scripts for publishing
  Jenkinsfile
  gradle/publish.gradle
Labels: failed CA tests

#523 Migration to Junit5 platform
  build.gradle
  gradle/versions.gradle
Labels: passed CA tests

#517 EE - Increase code coverage in Gateway
  gateway-service/src/main/java/org/zowe/apiml/gateway/controllers/GatewayHomepageController.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/ws/ServletSslContextFactoryProvider.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/ws/SslContextFactoryProvider.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/ws/WebSocketProxyServerHandler.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/ws/WebSocketRoutedSessionFactory.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/ws/WebSocketRoutedSessionFactoryImpl.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/apidoc/reader/ApiDocControllerTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/apidoc/reader/ApiDocReaderTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/cache/ServiceCacheEvictorTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/config/GatewayConfigTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/config/MultipartConfigTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/controllers/AuthControllerTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/controllers/CacheServiceControllerTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/controllers/GatewayHomepageControllerTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/error/ErrorUtilsTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/error/InternalServerErrorControllerTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/error/check/SecurityTokenErrorCheckTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/error/check/TlsErrorCheckTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/filters/post/ConvertAuthTokenInUriToCookieFilterTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/filters/post/PageRedirectionFilterTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/filters/pre/EncodedCharactersFilterTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/filters/pre/LocationFilterTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/filters/pre/ServiceAuthenticationFilterTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/filters/pre/SlashFilterTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/filters/pre/ZosmfFilterTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/health/GatewayHealthIndicatorTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/ribbon/GatewayRibbonLoadBalancingHttpClientImplTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/config/AuthProviderInitializerTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/login/dummy/DummyAuthenticationProviderTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/login/dummy/InMemoryUserDetailsServiceTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/login/zosmf/ZosmfAuthenticationProviderTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/query/QueryFilterTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/query/SuccessfulQueryHandlerTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/AuthenticationServiceTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/JwtSecurityInitializerTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/ServiceAuthenticationServiceImplTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/AuthenticationCommandTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/AuthenticationSchemeFactoryTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/ByPassSchemeTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/HttpBasicPassTicketSchemeTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/ZoweJwtSchemeTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/ticket/SuccessfulTicketHandlerTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/token/TokenAuthenticationProviderTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/utils/CleanCurrentRequestContextTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/ws/WebSocketActuatorEndpointTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/ws/WebSocketProxyServerHandlerTest.java
Labels: passed CA tests

#525 handle exception on notification gateways by discovery to have safe registration process
  discovery-service/src/main/java/org/zowe/apiml/discovery/EurekaInstanceCanceledListener.java
  discovery-service/src/main/java/org/zowe/apiml/discovery/EurekaInstanceRegisteredListener.java
  discovery-service/src/main/java/org/zowe/apiml/discovery/GatewayNotifier.java
  discovery-service/src/main/resources/discovery-log-messages.yml
  discovery-service/src/test/java/org/zowe/apiml/discovery/EurekaInstanceCanceledListenerTest.java
  discovery-service/src/test/java/org/zowe/apiml/discovery/EurekaInstanceRegisteredListenerTest.java
  discovery-service/src/test/java/org/zowe/apiml/discovery/GatewayNotifierTest.java
Labels: passed CA tests

#527 fix keystore in rest template and http client by configuration
  common-service-core/src/main/java/org/zowe/apiml/security/HttpsFactory.java
Labels: passed CA tests

#522 Use env variable to specify keystore type value
  zowe-install/src/main/resources/component-scripts/start.sh
Labels: passed CA tests

#526 Removing old enablers
  Api-Layer-Java.ppf
  Jenkinsfile
  gradle/license.gradle
  integration-enabler-spring-v1/README.md
  integration-enabler-spring-v1/build.gradle
  integration-enabler-spring-v1/src/main/java/org/zowe/apiml/enable/EnableApiDiscovery.java
  integration-enabler-spring-v1/src/main/java/org/zowe/apiml/enable/EnablerV1SpringFoxConfig.java
  integration-enabler-spring-v1/src/main/java/org/zowe/apiml/enable/EurekaDiscovery.java
  integration-enabler-spring-v1/src/main/java/org/zowe/apiml/enable/api/ApiDocController.java
  integration-enabler-spring-v1/src/main/java/org/zowe/apiml/enable/conditions/ConditionalOnMissingProperty.java
  integration-enabler-spring-v1/src/main/java/org/zowe/apiml/enable/discovery/EurekaClientSecurityConfiguration.java
  integration-enabler-spring-v1/src/main/java/org/zowe/apiml/enable/model/ApiDocConfigException.java
  integration-enabler-spring-v1/src/main/java/org/zowe/apiml/enable/model/ApiPropertiesContainerV1.java
  integration-enabler-spring-v1/src/main/java/org/zowe/apiml/enable/model/ApplicationWrapper.java
  integration-enabler-spring-v1/src/main/java/org/zowe/apiml/enable/services/LocalApiDocService.java
  integration-enabler-spring-v1/src/test/java/org/zowe/apiml/SpringBootTestClassForIntegrationEnablement.java
  integration-enabler-spring-v1/src/test/java/org/zowe/apiml/enable/controllers/ContextPathTestController.java
  integration-enabler-spring-v1/src/test/java/org/zowe/apiml/enable/controllers/V3Controller.java
  integration-enabler-spring-v1/src/test/java/org/zowe/apiml/enable/controllers/v1/V1Controller.java
  integration-enabler-spring-v1/src/test/java/org/zowe/apiml/enable/controllers/v2/V2Controller.java
  integration-enabler-spring-v1/src/test/java/org/zowe/apiml/enable/health/EndpointsTest.java
  integration-enabler-spring-v1/src/test/java/org/zowe/apiml/enable/swagger/ScannedSwaggerTests.java
  integration-enabler-spring-v1/src/test/java/org/zowe/apiml/enable/swagger/ScannedSwaggerTests2.java
  integration-enabler-spring-v1/src/test/java/org/zowe/apiml/enable/swagger/StaticSwaggerFailureTests.java
  integration-enabler-spring-v1/src/test/java/org/zowe/apiml/enable/swagger/StaticSwaggerLoaderTests.java
  integration-enabler-spring-v1/src/test/resources/application.yml
  integration-enabler-spring-v1/src/test/resources/bootstrap.yml
  integration-enabler-spring-v1/src/test/resources/swagger.json
  integration-enabler-spring-v2/README.md
  integration-enabler-spring-v2/build.gradle
  integration-enabler-spring-v2/src/main/java/org/zowe/apiml/enable/EnableApiDiscovery.java
  integration-enabler-spring-v2/src/main/java/org/zowe/apiml/enable/EnablerV2SpringFoxConfig.java
  integration-enabler-spring-v2/src/main/java/org/zowe/apiml/enable/api/ApiDocController.java
  integration-enabler-spring-v2/src/main/java/org/zowe/apiml/enable/conditions/ConditionalOnMissingProperty.java
  integration-enabler-spring-v2/src/main/java/org/zowe/apiml/enable/discovery/EurekaClientSecurityConfiguration.java
  integration-enabler-spring-v2/src/main/java/org/zowe/apiml/enable/model/ApiDocConfigException.java
  integration-enabler-spring-v2/src/main/java/org/zowe/apiml/enable/model/ApiPropertiesContainer.java
  integration-enabler-spring-v2/src/main/java/org/zowe/apiml/enable/services/LocalApiDocService.java
  integration-enabler-spring-v2/src/test/java/org/zowe/apiml/SpringBootTestClassForIntegrationEnablement.java
  integration-enabler-spring-v2/src/test/java/org/zowe/apiml/enable/controllers/ContextPathTestController.java
  integration-enabler-spring-v2/src/test/java/org/zowe/apiml/enable/controllers/v1/V1Controller.java
  integration-enabler-spring-v2/src/test/java/org/zowe/apiml/enable/controllers/v2/V2Controller.java
  integration-enabler-spring-v2/src/test/java/org/zowe/apiml/enable/swagger/ScannedSwaggerTests.java
  integration-enabler-spring-v2/src/test/java/org/zowe/apiml/enable/swagger/ScannedSwaggerTests2.java
  integration-enabler-spring-v2/src/test/java/org/zowe/apiml/enable/swagger/StaticSwaggerApplication.java
  integration-enabler-spring-v2/src/test/java/org/zowe/apiml/enable/swagger/StaticSwaggerFailureTests.java
  integration-enabler-spring-v2/src/test/java/org/zowe/apiml/enable/swagger/StaticSwaggerLoaderTests.java
  integration-enabler-spring-v2/src/test/resources/application.yml
  integration-enabler-spring-v2/src/test/resources/swagger.json
  onboarding-enabler-spring/build.gradle
  settings.gradle
  zowe-install/build.gradle
Labels: passed CA tests

#531 Increase WebSocket related code coverage
  gateway-service/src/main/java/org/zowe/apiml/gateway/ws/WebSocketActuatorEndpoint.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/ws/WebSocketRoutedSession.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/ws/WebSocketActuatorEndpointTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/ws/WebSocketProxyServerHandlerTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/ws/WebSocketRoutedSessionTest.java
Labels: passed CA tests

#534 Increase API catalog UI test coverage
  Jenkinsfile
  api-catalog-ui/frontend/package.json
  api-catalog-ui/frontend/pnpm-lock.yaml
  api-catalog-ui/frontend/src/actions/catalog-tile-actions.test.jsx
  api-catalog-ui/frontend/src/actions/error-actions.test.jsx
  api-catalog-ui/frontend/src/actions/filter-actions.jsx
  api-catalog-ui/frontend/src/actions/filter-actions.test.jsx
  api-catalog-ui/frontend/src/actions/selected-service-actions.test.jsx
  api-catalog-ui/frontend/src/actions/user-actions.jsx
  api-catalog-ui/frontend/src/components/Header/HeaderContainer.jsx
  api-catalog-ui/frontend/src/components/Login/LoginContainer.jsx
  api-catalog-ui/frontend/src/components/ServiceTab/ServiceTab.test.jsx
  api-catalog-ui/frontend/src/constants/error-constants.jsx
  api-catalog-ui/frontend/src/constants/user-constants.jsx
  api-catalog-ui/frontend/src/epics/fetch-tiles.jsx
  api-catalog-ui/frontend/src/reducers/authentication-reducer.jsx
  api-catalog-ui/frontend/src/reducers/error-reducer.jsx
  api-catalog-ui/frontend/src/reducers/error-reducer.test.jsx
  api-catalog-ui/frontend/src/reducers/fetch-tile-reducer.test.jsx
  api-catalog-ui/frontend/src/reducers/filter-reducer.test.jsx
  api-catalog-ui/frontend/src/reducers/index.jsx
  package-lock.json
Labels: under CA testing
