Repository zowe/api-layer, pull requests merged in 2020-06, with the labels that each got.

#674 Add the key changes for the 1.12 release
  CHANGELOG.md
Labels: size/S, under CA testing

#676 AuthenticationOnDeploymentTest and ServiceHaMode requires the Gateway…
  integration-tests/src/test/java/org/zowe/apiml/discoveryservice/EurekaInstancesIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/AuthenticationOnDeploymentTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/ServiceHaMode.java
Labels: passed CA tests

#680 Fix evicting of expired authentication tokens
  gateway-service/build.gradle
  gateway-service/src/main/java/org/zowe/apiml/gateway/GatewayApplication.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/cache/RetryIfExpired.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/cache/RetryIfExpiredAspect.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/ServiceAuthenticationServiceImpl.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/cache/RetryIfExpiredAspectTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/ServiceAuthenticationServiceImplTest.java
Labels: passed CA tests

#685 Return protection by filtering for certificate other than issued by API ML
  apiml-common/src/main/java/org/zowe/apiml/product/web/HttpConfig.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/config/ApimlX509AuthenticationFilter.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/config/SecurityConfiguration.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/config/ApimlX509AuthenticationFilterTest.java
Labels: passed CA tests

#679 Export z/OSMF public JWK to PEM certificate
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/zosmf/JwkToPublicKeyConverter.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/zosmf/SaveZosmfPublicKeyConsoleApplication.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/zosmf/ZosmfJwkToPublicKey.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/login/zosmf/JwkToPublicKeyConverterTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/login/zosmf/ZosmfJwkToPublicKeyTest.java
Labels: failed CA tests, ready for CA testing

#686 Add SAF keyring support to ZAAS client
  discoverable-client/build.gradle
  discoverable-client/src/main/java/org/zowe/apiml/client/api/ZaasClientTestController.java
  discoverable-client/src/main/java/org/zowe/apiml/client/configuration/ZaasClientConfig.java
  discoverable-client/src/main/java/org/zowe/apiml/client/service/ZaasClientService.java
  discoverable-client/src/main/resources/application.yml
  discoverable-client/src/test/java/org/zowe/apiml/client/api/ZaasClientTestControllerTest.java
  integration-tests/src/test/java/org/zowe/apiml/discoverableclient/IntegratedZaasClientTest.java
  zaas-client/src/main/java/org/zowe/apiml/zaasclient/service/internal/HttpsClientProvider.java
  zaas-client/src/main/java/org/zowe/apiml/zaasclient/service/internal/TokenServiceHttpsJwt.java
  zaas-client/src/main/java/org/zowe/apiml/zaasclient/service/internal/ZaasClientHttps.java
  zaas-client/src/test/java/org/zowe/apiml/zaasclient/service/internal/CloseableClientProviderTest.java
Labels: passed CA tests

#690 adjust timeout in zowe start script
  gateway-service/src/main/resources/application.yml
  zowe-install/src/main/resources/component-scripts/start.sh
Labels: size/XS

#694 Remove ciphers from validation as they are optional
  onboarding-enabler-java/src/main/java/org/zowe/apiml/eurekaservice/client/util/EurekaInstanceConfigValidator.java
Labels: under CA testing

#695 Remove tests requiring the Discoverable Client from Zowe RC tests
  integration-tests/src/test/java/org/zowe/apiml/discoverableclient/IntegratedZaasClientTest.java
Labels: passed CA tests

#697 US644826 - add Slack contacts
  CONTRIBUTING.md
  README.md
Labels: size/XS

#696 Refactor the configuration to make sure it is properly excluded from …
  gateway-service/src/test/java/org/zowe/apiml/config/error/check/MessageServiceConfiguration.java
  gateway-service/src/test/java/org/zowe/apiml/config/ribbon/IClientConfiguration.java
  gateway-service/src/test/java/org/zowe/apiml/config/service/security/MockedAuthenticationServiceContext.java
  gateway-service/src/test/java/org/zowe/apiml/config/service/security/MockedSecurityContext.java
  gateway-service/src/test/java/org/zowe/apiml/config/service/security/MockedSecurityInitializer.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/error/check/SecurityTokenErrorCheckTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/filters/post/ApiDocController.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/filters/post/TestConfiguration.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/ribbon/ApimlRetryableClientTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/ribbon/ApimlZoneAwareLoadBalancerTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/AuthenticationServiceTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/JwtSecurityInitializerTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/ServiceAuthenticationServiceImplTest.java
Labels: passed CA tests

#700 Create Bean From CacheUtils
  common-service-core/src/main/java/org/zowe/apiml/util/CacheUtils.java
  common-service-core/src/test/java/org/zowe/apiml/util/CacheUtilsTest.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/CacheConfig.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/AuthenticationService.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/ServiceAuthenticationServiceImpl.java
  gateway-service/src/test/java/org/zowe/apiml/config/service/security/MockedAuthenticationServiceContext.java
  gateway-service/src/test/java/org/zowe/apiml/config/service/security/MockedSecurityContext.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/query/SuccessfulQueryHandlerTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/AuthenticationServiceTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/ServiceAuthenticationServiceImplTest.java
  gateway-service/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
Labels: passed CA tests

#702 Add the requirement for existing issue as prerequisite for PR
  CONTRIBUTING.md
Labels: size/XS

#684 Removing APIML cookie on using Passticket scheme, new Integration tests to verify the transformation
  discoverable-client/src/main/java/org/zowe/apiml/client/api/RequestInfoController.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/HttpBasicPassTicketScheme.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/HttpBasicPassTicketSchemeTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/AuthenticationOnDeploymentTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/PassTicketTest.java
Labels: passed CA tests, ready for CA testing

#707 Timeout per service implementation
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/EurekaEventsRegistry.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/metadata/service/EurekaApplications.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/metadata/service/MetadataProcessor.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/config/EurekaEventsRegistryTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/metadata/service/EurekaApplicationsTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/metadata/service/MetadataProcessorTest.java
Labels: passed CA tests

#708 Prepare architecture for writing acceptance tests for the Gateway ser…
  gateway-service/build.gradle
  gateway-service/src/main/java/org/zowe/apiml/gateway/routing/ApimlRouteLocator.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/AcceptanceTest.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/config/ApimlRoutingConfig.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/config/DiscoveryClientTestConfig.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/config/GatewayOverrideConfig.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/config/GatewayTestApplication.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/config/ribbon/RibbonTestConfiguration.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/netflix/ApimlDiscoveryClientStub.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/netflix/ApimlRouteLocatorStub.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/netflix/ApimlZoneAwareLoadBalancerStub.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/netflix/ApplicationRegistry.java
  gateway-service/src/test/resources/application.yml
Labels: passed CA tests

#710 Verify the configuration override of the timeouts
  gateway-service/src/test/java/org/zowe/apiml/acceptance/TimeoutPerServiceTest.java
Labels: passed CA tests

#650 remove apiml-auth module
  apiml-auth/README.md
  apiml-auth/lib/apimlAuth.js
  apiml-auth/lib/apimlAuth.test.js
  apiml-auth/lib/tokenInjector.js
  apiml-auth/package.json
  apiml-auth/pluginDefinition.json
  zowe-install/build.gradle
Labels: passed CA tests, size/L

#711 First version of the PR template
  .github/pull_request_template.md
Labels: passed CA tests, size/S

#713 Remove Codecov dependency
  .adr-dir
  .codecov.yml
  Jenkinsfile
Labels: passed CA tests, size/S

#715 Tidy up API ML repo
  Api-Layer-Java.ppf
  CONTRIBUTING.md
  Jenkinsfile
  README.md
  api-catalog-ui/frontend/mocked-backend/assets/apidoc/discoverableclient.json
  api-catalog-ui/frontend/mocked-backend/assets/services/cademoapps.json
  config/local/onboarding-enabler-spring-v1-sample-app.yml
  discoverable-client/README.md
  discoverable-client/src/main/resources/application.yml
  discoverable-client/src/test/resources/application.yml
  docs/idea-setup.md
  docs/local-configuration.md
  gradle/license.gradle
  onboarding-enabler-spring-v1-sample-app/README.md
  onboarding-enabler-spring-v1-sample-app/build.gradle
  onboarding-enabler-spring-v1-sample-app/src/main/java/org/zowe/apiml/sample/enable/v1/EnablerV1SampleApplication.java
  onboarding-enabler-spring-v1-sample-app/src/main/java/org/zowe/apiml/sample/enable/v1/config/SwaggerConfiguration.java
  onboarding-enabler-spring-v1-sample-app/src/main/java/org/zowe/apiml/sample/enable/v1/controller/Sample.java
  onboarding-enabler-spring-v1-sample-app/src/main/java/org/zowe/apiml/sample/enable/v1/controller/SampleController.java
  onboarding-enabler-spring-v1-sample-app/src/main/resources/application.yml
  onboarding-enabler-spring-v1-sample-app/src/test/java/org/zowe/apiml/sample/enable/v1/controller/SampleControllerUnitTests.java
  onboarding-enabler-spring/src/test/resources/application-apiml-disabled.yml
  onboarding-enabler-spring/src/test/resources/application.yml
  package.json
  settings.gradle
  zowe-install/build.gradle
  zowe-install/src/main/resources/scripts/api-mediation-start-catalog-template.sh
  zowe-install/src/main/resources/scripts/api-mediation-start-discovery-template.sh
  zowe-install/src/main/resources/scripts/api-mediation-start-gateway-template.sh
Labels: passed CA tests

#714 Private/dj/retry loadbalancer race condition
  gateway-service/src/main/java/org/zowe/apiml/gateway/cache/ServiceCacheEvictor.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/controllers/CacheServiceController.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/ribbon/ApimlLoadBalancer.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/ribbon/GatewayRibbonConfig.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/config/ribbon/RibbonTestConfiguration.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/netflix/ApimlLoadBalancerStub.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/cache/ServiceCacheEvictorTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/controllers/CacheServiceControllerTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/ribbon/ApimlLoadBalancerTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/ribbon/http/ServiceAuthenticationDecoratorTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/AuthenticationOnDeploymentTest.java
  integration-tests/src/test/java/org/zowe/apiml/startup/impl/ApiMediationLayerStartupChecker.java
  integration-tests/src/test/java/org/zowe/apiml/util/service/RequestVerifier.java
  settings.gradle
Labels: passed CA tests

#718 Clean acceptance tests
  gateway-service/src/test/java/org/zowe/apiml/acceptance/TimeoutPerServiceTest.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/common/AcceptanceTest.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/common/AcceptanceTestWithBasePath.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/common/AcceptanceTestWithTwoServices.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/common/Service.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/netflix/ApplicationRegistry.java
Labels: passed CA tests

#717 Add instructions for IDEA community edition isers
  docs/idea-setup.md
Labels: size/S, under CA testing

#722 set ribbon retry parameter per service
  gateway-service/src/main/java/org/zowe/apiml/gateway/metadata/service/RibbonMetadataProcessor.java
  gateway-service/src/main/resources/application.yml
  gateway-service/src/test/java/org/zowe/apiml/acceptance/RetryPerServiceTest.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/common/AcceptanceTestWithTwoServices.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/netflix/ApplicationRegistry.java
  gateway-service/src/test/resources/application.yml
Labels: under CA testing

#723 Add Cors parameter in the start.sh
  zowe-install/src/main/resources/component-scripts/start.sh
Labels: passed CA tests, size/XS

#724 CORS headers provided by Southbound services are ignored
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/config/SecurityConfiguration.java
  gateway-service/src/main/resources/application.yml
  gateway-service/src/test/java/org/zowe/apiml/acceptance/CorsPerServiceTest.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/common/AcceptanceTestWithTwoServices.java
  gateway-service/src/test/resources/application.yml
Labels: passed CA tests

#726 Move and rename CORS related tests for improved readability
  gateway-service/src/test/java/org/zowe/apiml/acceptance/GatewayCorsEnabledTest.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/corsTests/CorsPerServiceTest.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/corsTests/GatewayCorsEnabledTest.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/corsTests/GatewaySpecificEndpointsCorsDisabledTest.java
Labels: passed CA tests

#728 Remove origin header from call to Southbound service if CORS is delegated to API ML
  gateway-service/src/main/resources/application.yml
  gateway-service/src/test/java/org/zowe/apiml/acceptance/corsTests/GatewayCorsEnabledTest.java
  gateway-service/src/test/resources/application.yml
Labels: passed CA tests

#729 Rip/gh682/request context issue no2
  discovery-service/src/main/java/org/zowe/apiml/discovery/ApimlInstanceRegistry.java
  discovery-service/src/main/java/org/zowe/apiml/discovery/EurekaInstanceRegisteredListener.java
  discovery-service/src/main/java/org/zowe/apiml/discovery/EurekaStatusUpdateEvent.java
  discovery-service/src/main/java/org/zowe/apiml/discovery/config/EurekaConfig.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/AuthenticationOnDeploymentTest.java
  integration-tests/src/test/java/org/zowe/apiml/util/service/VirtualService.java
Labels: passed CA tests

#730 Publish Core services as libraries to depend upon.
  gradle/publish.gradle
Labels: passed CA tests, size/XS
