Repository zowe/api-layer, pull requests merged in 2020-08, with the labels that each got.

#762 Create ApiMediationClient.isRegistered Interface
  discoverable-client/src/main/java/org/zowe/apiml/client/api/ApiMediationClientTestController.java
  discoverable-client/src/main/java/org/zowe/apiml/client/model/DiscoverableClientConfig.java
  discoverable-client/src/main/java/org/zowe/apiml/client/model/Registered.java
  discoverable-client/src/main/java/org/zowe/apiml/client/service/ApiMediationClientService.java
  discoverable-client/src/test/java/org/zowe/apiml/client/api/ApiMediationClientTestControllerTest.java
  discoverable-client/src/test/java/org/zowe/apiml/client/service/ApiMediationClientServiceTest.java
  integration-tests/src/test/java/org/zowe/apiml/discoverableclient/IntegratedApiMediationClientTest.java
  onboarding-enabler-java/src/main/java/org/zowe/apiml/eurekaservice/client/ApiMediationClient.java
Labels: passed CA tests

#771 Route locator refactor
  gateway-service/src/main/java/org/zowe/apiml/gateway/routing/ApimlRoutingConfig.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/routing/NewApimlRouteLocator.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/routing/RoutedServicesNotifier.java
  gateway-service/src/main/resources/application.yml
  gateway-service/src/test/java/org/zowe/apiml/gateway/routing/NewApimlRouteLocatorTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/routing/RoutedServicesNotifierTest.java
Labels: passed CA tests

#775 Add warning logging for poorly formed URL config parameters
  onboarding-enabler-java/src/main/java/org/zowe/apiml/eurekaservice/client/util/EurekaInstanceConfigValidator.java
  onboarding-enabler-java/src/test/java/org/zowe/apiml/eurekaservice/client/util/EurekaInstanceConfigValidatorTest.java
Labels: under CA testing

#776 Add key improvements in 1.14 version
  CHANGELOG.md
Labels: passed CA tests, size/XS

#778 Mark the test as excluded from the Zowe testing.
  integration-tests/src/test/java/org/zowe/apiml/discoverableclient/IntegratedApiMediationClientTest.java
Labels: passed CA tests

#779 Implement API Path Pattern with serviceId as first element
  api-catalog-ui/frontend/cypress/integration/e2e/detail-page/detail-page.test.js
  apiml-common/src/main/java/org/zowe/apiml/product/routing/transform/TransformService.java
  apiml-common/src/test/java/org/zowe/apiml/product/routing/transform/TransformServiceTest.java
  common-service-core/src/main/java/org/zowe/apiml/product/routing/RoutedServices.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/pre/LocationFilter.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/pre/SlashFilter.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/routing/ApimlRouteLocator.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/routing/NewApimlRouteLocator.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/filters/post/PageRedirectionFilterTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/filters/pre/LocationFilterTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/filters/pre/SlashFilterTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/routing/NewApimlRouteLocatorTest.java
  integration-tests/src/test/java/org/zowe/apiml/discoverableclient/DownloadApiIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/discoverableclient/GreetingApiIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/discoverableclient/IntegratedApiMediationClientTest.java
  integration-tests/src/test/java/org/zowe/apiml/discoverableclient/IntegratedZaasClientTest.java
  integration-tests/src/test/java/org/zowe/apiml/discoverableclient/MultipartPutIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/discoverableclient/RequestInfoIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/discoverableclient/UiIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/PageRedirectionTest.java
Labels: passed CA tests

#780 Return to the external environment Eureka related Flaky tests
  integration-tests/src/test/java/org/zowe/apiml/discoveryservice/EurekaInstancesIntegrationTest.java
Labels: passed CA tests

#782 Carsoncook/gh774/assert log messages
  apiml-utility/src/main/java/org/zowe/apiml/product/logging/LogMessageTracker.java
  apiml-utility/src/test/java/org/zowe/apiml/product/logging/LogMessageTrackerTest.java
  onboarding-enabler-java/build.gradle
  onboarding-enabler-java/src/main/java/org/zowe/apiml/eurekaservice/client/util/EurekaInstanceConfigValidator.java
  onboarding-enabler-java/src/test/java/org/zowe/apiml/eurekaservice/client/util/EurekaInstanceConfigValidatorTest.java
  onboarding-enabler-java/src/test/resources/bad-url-slash-formatting.yml
  onboarding-enabler-java/src/test/resources/no-home-page-or-ui-route.yml
  onboarding-enabler-java/src/test/resources/no-relative-urls.yml
Labels: passed CA tests, ready for CA testing

#784 Return Passticket related pen tests to the CICD pipeline
  integration-tests/src/test/java/org/zowe/apiml/penetration/JwtPenTest.java
Labels: passed CA tests

#786 Repair zowe-api-dev
  config/zowe-api-dev/alternative_start.sh
  config/zowe-api-dev/run-wrapper.sh
  config/zowe-api-dev/template-bpxbatch.jcl
  docs/ad-hoc-mainframe-deployment.md
  zowe-api.json
Labels: passed CA tests, ready for CA testing, size/L

#788 Provide simple configuration for CircleCI
  .circleci/config.yml
  gateway-service/src/test/java/org/zowe/apiml/acceptance/corsTests/CorsPerServiceTest.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/corsTests/GatewayCorsEnabledTest.java
  gateway-service/src/test/resources/application-test.yml
Labels: passed CA tests, size/M

#789 Add SAF Provider as a possible authentication provider
  .circleci/config.yml
  build.gradle
  gateway-service/src/main/java/org/zowe/apiml/gateway/controllers/AuthProviderController.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/config/AuthProviderInitializer.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/config/CompoundAuthProvider.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/LoginProvider.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/saf/MockPlatformUser.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/saf/PlatformClassFactory.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/saf/PlatformReturned.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/saf/PlatformUser.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/saf/SafPlatformClassFactory.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/saf/SafPlatformUser.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/saf/ZosAuthenticationException.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/saf/ZosAuthenticationProvider.java
  gateway-service/src/main/resources/application.yml
  gateway-service/src/main/resources/gateway-log-messages.yml
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/config/AuthProviderInitializerTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/config/CompoundAuthProviderTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/login/saf/MockPlatformClassFactory.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/login/saf/SafPlatformUserTests.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/login/saf/ZosAuthenticationProviderTests.java
  gateway-service/src/test/resources/gateway-messages.yml
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/authentication/DummyAuthenticationLoginIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/authentication/Login.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/authentication/SafAuthenticationLoginIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/authentication/ZosmfAuthenticationLoginIntegrationTest.java
  package.json
Labels: passed CA tests

#791 Fix handling of zosmf sid
  gateway-service/src/main/java/org/zowe/apiml/gateway/controllers/GatewayHomepageController.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/health/GatewayHealthIndicator.java
Labels: passed CA tests

#793 rip/GH472/two tokens tests
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/AuthenticationOnDeploymentTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/ServiceHaMode.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/ZosmfAuthenticationTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/authentication/DummyAuthenticationLoginIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/authentication/DummyLogoutTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/authentication/Login.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/authentication/LogoutTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/authentication/SafAuthenticationLoginIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/authentication/SafLogoutTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/authentication/ZosmfAuthenticationLoginIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/authentication/ZosmfLogoutTest.java
  integration-tests/src/test/java/org/zowe/apiml/util/config/RandomPort.java
Labels: passed CA tests

#795 Fix SSL validation when Eureka is running in HTTP mode
  onboarding-enabler-java/src/main/java/org/zowe/apiml/eurekaservice/client/util/EurekaInstanceConfigValidator.java
  onboarding-enabler-java/src/test/java/org/zowe/apiml/eurekaservice/client/util/EurekaInstanceConfigValidatorTest.java
  onboarding-enabler-java/src/test/resources/bad-ssl-configuration.yml
  onboarding-enabler-java/src/test/resources/missing-ssl-configuration.yml
  onboarding-enabler-java/src/test/resources/service-configuration-wildcard.yml
Labels: failed CA tests

#798 Adapt changelog to the new requirements for structure and content.
  CHANGELOG.md
Labels: passed CA tests, size/M

#799 Handle zosmf SID with saf auth
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/config/AuthConfigurationProperties.java
  config/zowe-api-dev/alternative_start.sh
  zowe-install/src/main/resources/component-scripts/start.sh
Labels: passed CA tests

#801 Fix problem in error handling when no api-doc is available
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/services/cached/CachedApiDocService.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/services/cached/CachedApiDocServiceTest.java
Labels: passed CA tests

#800 Provide the Swagger URL for zOSMF
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/services/status/APIDocRetrievalService.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/api/AbstractApiDocService.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/services/status/LocalApiDocServiceTest.java
  config/local/api-defs/zosmf-sample.yml_
  zowe-install/src/main/resources/component-scripts/configure.sh
Labels: passed CA tests

#804 Allow character encoding by default
  config/local/gateway-service.yml
  config/zowe-api-dev/alternative_start.sh
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/pre/EncodedCharactersFilter.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/pre/TomcatFilter.java
  gateway-service/src/main/resources/application.yml
  gateway-service/src/test/java/org/zowe/apiml/gateway/filters/pre/EncodedCharactersFilterTest.java
  gateway-service/src/test/resources/application-test.yml
  gateway-service/src/test/resources/application.yml
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/EncodedCharactersTest.java
  zowe-install/src/main/resources/component-scripts/start.sh
Labels: passed CA tests

#805 Improve performance of query endpoint and ZAAS client
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/AuthenticationService.java
  zaas-client/src/main/java/org/zowe/apiml/zaasclient/service/internal/CloseableClientProvider.java
  zaas-client/src/main/java/org/zowe/apiml/zaasclient/service/internal/HttpsClientProvider.java
  zaas-client/src/main/java/org/zowe/apiml/zaasclient/service/internal/PassTicketServiceHttps.java
  zaas-client/src/main/java/org/zowe/apiml/zaasclient/service/internal/TokenServiceHttpsJwt.java
  zaas-client/src/main/java/org/zowe/apiml/zaasclient/service/internal/ZaasClientHttps.java
  zaas-client/src/test/java/org/zowe/apiml/zaasclient/service/internal/CloseableClientProviderTest.java
  zaas-client/src/test/java/org/zowe/apiml/zaasclient/service/internal/ZaasClientHttpsTest.java
Labels: passed CA tests

#806 Add Changelog notes for 1.15.0
  CHANGELOG.md
Labels: passed CA tests, size/XS

#802 Rip/ta16215/x509 spring security
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/error/AuthenticationTokenException.java
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/login/LoginFilter.java
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/token/X509AuthenticationToken.java
  apiml-security-common/src/test/java/org/zowe/apiml/security/common/login/LoginFilterTest.java
  apiml-security-common/src/test/java/org/zowe/apiml/security/common/token/X509AuthenticationTokenTest.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/config/ApimlX509AuthenticationFilter.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/config/ApimlX509Filter.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/config/SecurityConfiguration.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/config/X509AuthenticationFilter.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/x509/X509Authentication.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/x509/X509AuthenticationProvider.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/zosmf/X509AuthenticationService.java
  gateway-service/src/main/resources/application.yml
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/config/ApimlX509FilterTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/config/X509AuthenticationFilterTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/login/x509/X509AuthenticationProviderTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/zosmf/X509AuthenticationServiceTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/utils/X509Utils.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/authentication/Login.java
  integration-tests/src/test/java/org/zowe/apiml/util/config/TlsConfiguration.java
  integration-tests/src/test/resources/environment-configuration.yml
  keystore/client_cert/APIML_External_Certificate_Authority.cer
  keystore/client_cert/APIML_External_Certificate_Authority.key
  keystore/client_cert/APIMTST_APIML_External_Certificate_Authority_.cer
  keystore/client_cert/APIMTST_APIML_External_Certificate_Authority_.key
  keystore/client_cert/cert_key.p12
  keystore/client_cert/client_auth.cert.pem
  keystore/client_cert/client_auth.key.pem
  keystore/client_cert/openssl.conf
  keystore/localhost/localhost.truststore.p12
  security-service-client-spring/src/main/java/org/zowe/apiml/security/client/service/GatewaySecurityService.java
Labels: passed CA tests

#807 Change default expiration time value for JWT token
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/config/AuthConfigurationProperties.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/AuthenticationServiceTest.java
Labels: passed CA tests
