Repository zowe/api-layer, pull requests merged in 2020-03, with the labels that each got.

#530 Configuration for helloworld-jersey
  Api-Layer-Java.ppf
  gradle/coverage.gradle
  gradle/license.gradle
  helloworld-jersey/build.gradle
  helloworld-jersey/src/main/java/org/zowe/apiml/hwsjersey/HelloJerseyListener.java
  helloworld-jersey/src/main/java/org/zowe/apiml/hwsjersey/greeting/Greeting.java
  helloworld-jersey/src/main/java/org/zowe/apiml/hwsjersey/greeting/GreetingController.java
  helloworld-jersey/src/main/java/org/zowe/apiml/hwsjersey/health/HealthController.java
  helloworld-jersey/src/main/java/org/zowe/apiml/hwsjersey/resource/Greeting.java
  helloworld-jersey/src/main/resources/openapi-configuration.yaml
  helloworld-jersey/src/main/resources/service-configuration.yml
  helloworld-jersey/src/main/webapp/WEB-INF/web.xml
  helloworld-jersey/src/test/java/org/zowe/apiml/hwsjersey/ServletContextListenerTest.java
  helloworld-jersey/src/test/java/org/zowe/apiml/hwsjersey/greeting/GreetingControllerTest.java
  helloworld-jersey/src/test/java/org/zowe/apiml/hwsjersey/health/HealthControllerTest.java
  helloworld-jersey/src/test/java/org/zowe/apiml/hwsjersey/resource/GreetingControllerTest.java
  helloworld-jersey/src/test/java/org/zowe/apiml/hwsjersey/resource/GreetingTest.java
  helloworld-spring/README.md
  helloworld-spring/build.gradle
  helloworld-spring/src/main/java/org/zowe/apiml/hellospring/configuration/SwaggerConfiguration.java
  helloworld-spring/src/main/java/org/zowe/apiml/hellospring/controller/GreetingController.java
  helloworld-spring/src/main/java/org/zowe/apiml/hellospring/controller/MfaasController.java
  helloworld-spring/src/main/java/org/zowe/apiml/hellospring/listener/ApiDiscoveryListener.java
  helloworld-spring/src/main/java/org/zowe/apiml/hellospring/model/EmptyJsonResponse.java
  helloworld-spring/src/main/resources/service-configuration.yml
  helloworld-spring/src/main/webapp/WEB-INF/spring-servlet.xml
  helloworld-spring/src/main/webapp/WEB-INF/web.xml
  helloworld-spring/src/test/java/org/zowe/apiml/hellospring/controller/GreetingControllerTest.java
  helloworld-spring/src/test/java/org/zowe/apiml/hellospring/controller/MfaasControllerTest.java
  helloworld-spring/src/test/java/org/zowe/apiml/hellospring/listener/ServletContextListenerTest.java
  helloworld-spring/src/test/resources/service-config.yml
  helloworld-spring/src/test/resources/spring-servlet.xml
  integration-enabler-spring-v1-sample-app/src/main/resources/application.yml
  integration-tests/src/test/java/org/zowe/apiml/helloworldspring/HelloWorldSpringIntegrationTest.java
  onboarding-enabler-java/src/main/java/org/zowe/apiml/eurekaservice/model/Health.java
  settings.gradle
Labels: passed CA tests

#535 Hb/de444149/refresh static api
  apiml-utility/src/main/java/org/zowe/apiml/product/logging/ApimlDependencyLogHider.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/error/InternalServerErrorController.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/error/NotFound.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/error/check/ServiceNotFoundCheck.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/pre/EncodedCharactersFilter.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/pre/LocationFilter.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/pre/RequestContextProvider.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/pre/RequestContextProviderThreadLocal.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/pre/ServiceAuthenticationFilter.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/pre/ServiceNotFoundFilter.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/pre/SlashFilter.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/routing/ApimlRoutingConfig.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/error/check/ServiceNotFoundCheckTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/filters/pre/EncodedCharactersFilterTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/filters/pre/LocationFilterTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/filters/pre/ServiceAuthenticationFilterTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/filters/pre/ServiceNotFoundFilterTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/filters/pre/SlashFilterTest.java
Labels: passed CA tests

#539 rename helloworld-jersey to onboarding-enabler-java-sample-app
  Api-Layer-Java.ppf
  docs/local-configuration.md
  gradle/coverage.gradle
  gradle/license.gradle
  helloworld-jersey/src/main/resources/openapi-configuration.yaml
  integration-tests/src/test/java/org/zowe/apiml/enablejavasampleapp/EnablerJavaSampleAppEndpointTest.java
  onboarding-enabler-java-sample-app/README.md
  onboarding-enabler-java-sample-app/build.gradle
  onboarding-enabler-java-sample-app/src/main/java/org/zowe/apiml/hwsjersey/HelloJerseyListener.java
  onboarding-enabler-java-sample-app/src/main/java/org/zowe/apiml/hwsjersey/greeting/Greeting.java
  onboarding-enabler-java-sample-app/src/main/java/org/zowe/apiml/hwsjersey/greeting/GreetingController.java
  onboarding-enabler-java-sample-app/src/main/java/org/zowe/apiml/hwsjersey/health/HealthController.java
  onboarding-enabler-java-sample-app/src/main/resources/openapi-configuration.yaml
  onboarding-enabler-java-sample-app/src/main/resources/service-configuration.yml
  onboarding-enabler-java-sample-app/src/main/webapp/WEB-INF/web.xml
  onboarding-enabler-java-sample-app/src/main/webapp/index.jsp
  onboarding-enabler-java-sample-app/src/test/java/org/zowe/apiml/hwsjersey/ServletContextListenerTest.java
  onboarding-enabler-java-sample-app/src/test/java/org/zowe/apiml/hwsjersey/greeting/GreetingControllerTest.java
  onboarding-enabler-java-sample-app/src/test/java/org/zowe/apiml/hwsjersey/health/HealthControllerTest.java
  onboarding-enabler-java-sample-app/src/test/resources/service-config.yml
  settings.gradle
Labels: passed CA tests

#536 Check that the ignoring SslContextFactory has empty keystore
  common-service-core/src/main/java/org/zowe/apiml/security/HttpsFactory.java
  common-service-core/src/test/java/org/zowe/apiml/security/HttpsFactoryTest.java
Labels: passed CA tests

#543 Fix problem with log message not displayed
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/services/cached/CachedProductFamilyService.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/services/cached/CachedProductFamilyTest.java
Labels: passed CA tests

#544 Enablers for effective usage of the gradle remote cache
  api-catalog-services/build.gradle
  api-catalog-ui/build.gradle
  api-catalog-ui/frontend/package.json
  api-catalog-ui/frontend/pnpm-lock.yaml
  apiml-common/build.gradle
  apiml-security-common/build.gradle
  apiml-utility/build.gradle
  common-service-core/build.gradle
  discoverable-client/build.gradle
  discovery-service/build.gradle
  gateway-service/build.gradle
  onboarding-enabler-java-sample-app/build.gradle
  onboarding-enabler-java/build.gradle
  onboarding-enabler-spring/build.gradle
  security-service-client-spring/build.gradle
Labels: passed CA tests, ready for CA testing

#537 Fixed error with not found codes from common-log-messages.yml in DiscoverableClient
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/config/BeanConfig.java
  apiml-common/src/main/resources/common-log-messages.yml
  apiml-utility/src/main/java/org/zowe/apiml/product/logging/LogLevelInfoFilter.java
  apiml-utility/src/main/resources/utility-log-messages.yml
  apiml-utility/src/test/java/org/zowe/apiml/product/logging/LogLevelInfoFilterTest.java
  discoverable-client/src/main/java/org/zowe/apiml/client/configuration/ApplicationConfiguration.java
  discovery-service/src/main/java/org/zowe/apiml/discovery/config/BeanConfig.java
  docs/docgen/config.yml
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/MessageServiceConfiguration.java
Labels: passed CA tests

#545 fix incorrect merge
  config/local/discoverable-client.yml
Labels: passed CA tests

#546 Switch to React.lazy for code splitting and use async components
  api-catalog-ui/frontend/package.json
  api-catalog-ui/frontend/pnpm-lock.yaml
  api-catalog-ui/frontend/src/components/App/App.jsx
  api-catalog-ui/frontend/src/components/App/AsyncModules.jsx
Labels: passed CA tests

#548 US574268/stop service repetitive messages
  apiml-common/src/main/resources/logback.xml
Labels: passed CA tests

#482 Using JWT token from z/OSMF instead of Zowe's token
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/security/SecurityConfiguration.java
  apiml-common/src/main/java/org/zowe/apiml/product/web/HttpConfig.java
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/config/AuthConfigurationProperties.java
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/token/QueryResponse.java
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/token/TokenAuthentication.java
  apiml-security-common/src/test/java/org/zowe/apiml/security/common/token/QueryResponseTest.java
  apiml-security-common/src/test/java/org/zowe/apiml/security/common/token/TokenAuthenticationTest.java
  common-service-core/src/main/java/org/zowe/apiml/util/CookieUtil.java
  common-service-core/src/test/java/org/zowe/apiml/util/CookieUtilTest.java
  config/local/gateway-service.yml
  discovery-service/src/main/java/org/zowe/apiml/discovery/EurekaInstanceRegisteredListener.java
  discovery-service/src/main/java/org/zowe/apiml/discovery/GatewayNotifier.java
  discovery-service/src/main/java/org/zowe/apiml/discovery/metadata/MetadataTranslationService.java
  discovery-service/src/test/java/org/zowe/apiml/discovery/EurekaInstanceRegisteredListenerTest.java
  discovery-service/src/test/java/org/zowe/apiml/discovery/metadata/MetadataTranslationServiceTest.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/pre/ZosmfFilter.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/routing/ApimlRoutingConfig.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/config/ComponentsConfiguration.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/config/SecurityConfiguration.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/zosmf/ZosmfAuthenticationProvider.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/AuthenticationService.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/ZosmfService.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/ZosmfScheme.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/zosmf/AbstractZosmfService.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/zosmf/ZosmfServiceFacade.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/zosmf/ZosmfServiceV1.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/zosmf/ZosmfServiceV2.java
  gateway-service/src/main/resources/ehcache.xml
  gateway-service/src/test/java/org/zowe/apiml/gateway/filters/pre/ZosmfFilterTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/login/zosmf/ZosmfAuthenticationProviderTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/query/SuccessfulQueryHandlerTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/AuthenticationServiceTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/ServiceAuthenticationServiceImplTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/AuthenticationSchemeFactoryTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/HttpBasicPassTicketSchemeTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/ZosmfSchemeTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/zosmf/ZosmfServiceFacadeTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/zosmf/ZosmfServiceV1Test.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/zosmf/ZosmfServiceV2Test.java
  integration-tests/src/test/java/org/zowe/apiml/apicatalog/ApiCatalogLoginIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/AuthenticationOnDeploymentTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/LoginIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/LogoutTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/SecurityUtils.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/ZosmfAuthenticationTest.java
  integration-tests/src/test/java/org/zowe/apiml/util/service/VirtualService.java
  security-service-client-spring/src/test/java/org/zowe/apiml/security/client/service/GatewaySecurityServiceTest.java
  security-service-client-spring/src/test/java/org/zowe/apiml/security/client/token/GatewayTokenProviderTest.java
  zowe-install/src/main/resources/scripts/api-mediation-start-gateway-template.sh
Labels: passed CA tests

#551 Integration test for logout has sence only on mainframe, not on localhost
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/LogoutTest.java
Labels: passed CA tests

#532 Version endpoint in API Gateway
  apiml-common/src/main/java/org/zowe/apiml/product/version/VersionInfo.java
  apiml-common/src/main/java/org/zowe/apiml/product/version/VersionInfoDetails.java
  apiml-common/src/main/java/org/zowe/apiml/product/version/VersionService.java
  apiml-common/src/test/java/org/zowe/apiml/product/version/VersionServiceTest.java
  apiml-common/src/test/resources/zowe.version/zowe-manifest-encoded.json
  apiml-common/src/test/resources/zowe.version/zowe-manifest-invalid.json
  apiml-common/src/test/resources/zowe.version/zowe-manifest-no-build-info.json
  apiml-common/src/test/resources/zowe.version/zowe-manifest.json
  common-service-core/src/main/java/org/zowe/apiml/util/FileUtils.java
  common-service-core/src/test/java/org/zowe/apiml/util/FileUtilsTest.java
  docs/diagnostics.md
  gateway-service/src/main/java/org/zowe/apiml/gateway/controllers/VersionController.java
  gateway-service/src/main/resources/application.yml
  gateway-service/src/main/resources/gateway-api-doc.json
  gateway-service/src/test/java/org/zowe/apiml/gateway/controllers/VersionControllerTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/VersionEndpointTest.java
  onboarding-enabler-java/src/main/java/org/zowe/apiml/eurekaservice/client/util/ApiMediationServiceConfigReader.java
  zowe-install/src/main/resources/component-scripts/start.sh
  zowe-install/src/main/resources/scripts/api-mediation-start-gateway-template.sh
Labels: passed CA tests

#538 GatewayNotifier (make calls asynchronous) and logout improvement (distributing invalidated tokens between Gateways)
  common-service-core/src/main/java/org/zowe/apiml/util/CacheUtils.java
  common-service-core/src/test/java/org/zowe/apiml/util/CacheUtilsTest.java
  discovery-service/build.gradle
  discovery-service/src/main/java/org/zowe/apiml/discovery/EurekaInstanceRegisteredListener.java
  discovery-service/src/main/java/org/zowe/apiml/discovery/GatewayNotifier.java
  discovery-service/src/test/java/org/zowe/apiml/discovery/EurekaInstanceRegisteredListenerTest.java
  discovery-service/src/test/java/org/zowe/apiml/discovery/GatewayNotifierTest.java
  gateway-service/build.gradle
  gateway-service/src/main/java/org/zowe/apiml/gateway/controllers/AuthController.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/AuthenticationService.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/controllers/AuthControllerTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/query/SuccessfulQueryHandlerTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/AuthenticationServiceTest.java
Labels: passed CA tests

#547 Upgrade to Gradle 6.2.2
  api-catalog-services/build.gradle
  api-catalog-ui/build.gradle
  apiml-common/build.gradle
  apiml-common/src/main/java/org/zowe/apiml/product/version/VersionService.java
  apiml-security-common/build.gradle
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/token/QueryResponse.java
  apiml-security-common/src/test/java/org/zowe/apiml/security/common/login/LoginFilterTest.java
  apiml-utility/build.gradle
  apiml-utility/src/main/java/org/zowe/apiml/product/logging/ApimlDependencyLogHider.java
  build.gradle
  common-service-core/build.gradle
  common-service-core/src/main/java/org/zowe/apiml/cache/CompositeKey.java
  common-service-core/src/main/java/org/zowe/apiml/message/core/Message.java
  common-service-core/src/main/java/org/zowe/apiml/passticket/PassTicketService.java
  common-service-core/src/main/java/org/zowe/apiml/util/ClassOrDefaultProxyUtils.java
  common-service-core/src/main/java/org/zowe/apiml/util/CookieUtil.java
  common-service-core/src/main/java/org/zowe/apiml/util/ObjectUtil.java
  common-service-core/src/main/java/org/zowe/apiml/util/UrlUtils.java
  discoverable-client/build.gradle
  discovery-service/build.gradle
  gateway-service/build.gradle
  gradle/coverage.gradle
  gradle/publish.gradle
  gradle/versions.gradle
  gradle/wrapper/gradle-wrapper.properties
  integration-enabler-spring-v1-sample-app/build.gradle
  integration-tests/build.gradle
  integration-tests/src/test/java/org/zowe/apiml/util/service/VirtualService.java
  onboarding-enabler-java-sample-app/build.gradle
  onboarding-enabler-java/build.gradle
  onboarding-enabler-spring/build.gradle
  security-service-client-spring/build.gradle
Labels: passed CA tests

#556 Override all the properties with the system properties
  integration-tests/src/test/java/org/zowe/apiml/util/config/ConfigReader.java
Labels: passed CA tests

#528 protectors/zosmfidInConfig
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/instance/InstanceInitializeServiceTest.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/instance/InstanceRetrievalServiceTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/login/zosmf/ZosmfAuthenticationProviderTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/ZosmfAuthenticationTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/ZosmfSsoIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/util/config/ConfigReader.java
  integration-tests/src/test/java/org/zowe/apiml/util/config/ZosmfServiceConfiguration.java
Labels: failed CA tests

#559 Allow overwriting of the zosmf service Id
  integration-tests/src/test/java/org/zowe/apiml/util/config/ConfigReader.java
  integration-tests/src/test/resources/environment-configuration.yml
Labels: passed CA tests

#558 Removed helloworld-expressjs
  helloworld-expressjs/.gitignore
  helloworld-expressjs/README.md
  helloworld-expressjs/apiLayerService.js
  helloworld-expressjs/index.js
  helloworld-expressjs/package.json
  helloworld-expressjs/static/swagger.json
Labels: passed CA tests

#554 Catalog health status depends on authorization service availability
  gateway-service/src/main/java/org/zowe/apiml/gateway/controllers/GatewayHomepageController.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/controllers/GatewayHomepageControllerTest.java
Labels: passed CA tests

#560 Change default settings to the ones with better performance
  gradle.properties
Labels: passed CA tests

#564 Low impact cleanup of the Build
  Jenkinsfile
Labels: passed CA tests

#567 Clean unused files from the keystore folders
  keystore/README.md
  keystore/local_ca/extca.1.cer
  keystore/local_ca/extca.2.cer
  keystore/local_ca/extca.3.cer
  keystore/local_ca/localca2.cer
  keystore/local_ca/localca2.keystore.p12
  keystore/localhost/localhost.keystore.csr
  keystore/localhost/localhost.keystore.p12.csr
  keystore/localhost/localhost.keystore.p12_signed.cer
  keystore/localhost/localhost.keystore_signed.cer
Labels: under CA testing

#568 Enhance issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
Labels: passed CA tests

#549 Penetration testing of JWT
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/pre/JwtValidatorFilter.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/routing/ApimlRoutingConfig.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/filters/pre/JwtValidatorFilterTest.java
  integration-tests/build.gradle
  integration-tests/src/test/java/org/zowe/apiml/apicatalog/ApiCatalogSecurityIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/penetration/JwtPenTest.java
Labels: passed CA tests

#566 Export z/OSMF JWT public key
  gateway-service/build.gradle
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/zosmf/JwkConversionError.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/zosmf/JwkToPublicKeyConverter.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/zosmf/SaveZosmfPublicKeyConsoleApplication.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/zosmf/ZosmfJwkToPublicKey.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/login/zosmf/JwkToPublicKeyConverterTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/login/zosmf/ZosmfJwkToPublicKeyTest.java
  gradle/versions.gradle
  zowe-install/src/main/resources/component-scripts/start.sh
Labels: failed CA tests

#572 Fix OAS3 parser when no tags are present
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/api/ApiDocV3Service.java
Labels: passed CA tests

#575 Use ZosmfServiceV2 only if the authentication endpoint exists
  .gitignore
  config/local/api-defs/zosmf-sample.yml_
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/ZosmfService.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/zosmf/ZosmfServiceFacade.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/zosmf/ZosmfServiceV1.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/zosmf/ZosmfServiceV2.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/AuthenticationServiceTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/zosmf/ZosmfServiceFacadeTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/zosmf/ZosmfServiceV1Test.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/zosmf/ZosmfServiceV2Test.java
Labels: passed CA tests

#578 Update Issue Templates with the new Issue Management guidelines
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
Labels: passed CA tests

#576 zowe-api-dev deploy
  .gitignore
  api-catalog-services/build.gradle
  build.gradle
  config/zowe-api-dev/run-wrapper.sh
  config/zowe-api-dev/template-bpxbatch.jcl
  discovery-service/build.gradle
  docs/ad-hoc-mainframe-deployment.md
  gateway-service/build.gradle
  gateway-service/src/main/java/org/zowe/apiml/gateway/apidoc/reader/ApiDocReader.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/apidoc/reader/ApiDocReaderTest.java
  zowe-api.json
Labels: passed CA tests, ready for CA testing

#580 Error message instead of exception during z/OSMF JWK import
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/zosmf/SaveZosmfPublicKeyConsoleApplication.java
Labels: failed CA tests
