Repository zowe/api-layer, pull requests merged in 2020-04, with the labels that each got.

#585 Update version of JJWT library #563
  gateway-service/build.gradle
  gradle/versions.gradle
  integration-tests/build.gradle
Labels: passed CA tests

#586 fix JwtValidatorFilter to support expired tokens to services
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/pre/JwtValidatorFilter.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/routing/ApimlRoutingConfig.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/filters/pre/JwtValidatorFilterTest.java
Labels: passed CA tests

#581 Add IRRRacf.jar to classpath of the API gateway
  zowe-install/src/main/resources/component-scripts/start.sh
Labels: passed CA tests

#584 Increase cypress timeout
  api-catalog-ui/frontend/cypress.json
Labels: under CA testing

#591 Log the errors found in the static definitions
  discovery-service/src/main/java/org/zowe/apiml/discovery/staticdef/ServiceDefinitionProcessor.java
  discovery-service/src/main/java/org/zowe/apiml/discovery/staticdef/StaticRegistrationResult.java
  discovery-service/src/main/resources/discovery-log-messages.yml
  discovery-service/src/test/java/org/zowe/apiml/discovery/staticdef/ServiceDefinitionProcessorTest.java
Labels: passed CA tests

#589 US654070: Try-out enabled
  api-catalog-ui/build.gradle
  api-catalog-ui/frontend/README.md
  api-catalog-ui/frontend/cypress/integration/e2e/detail-page/detail-page.test.js
  api-catalog-ui/frontend/package.json
  api-catalog-ui/frontend/pnpm-lock.yaml
  api-catalog-ui/frontend/src/components/ServiceTab/ServiceTab.css
  api-catalog-ui/frontend/src/components/Swagger/Swagger.css
  api-catalog-ui/frontend/src/components/Swagger/Swagger.jsx
  api-catalog-ui/frontend/src/integration-tests/README.md
Labels: passed CA tests

#592 Use uppercase parameters for PassTicket service
  common-service-core/src/main/java/org/zowe/apiml/passticket/PassTicketService.java
  common-service-core/src/test/java/org/zowe/apiml/passticket/PassTicketServiceTest.java
  discoverable-client/src/test/java/org/zowe/apiml/client/api/PassTicketTestControllerTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/HttpBasicPassTicketSchemeTest.java
  passticket/test-programs/PtGen.java
Labels: under CA testing

#593 Prevent null pointer in case of missing SSL configuration
  common-service-core/src/main/java/org/zowe/apiml/exception/MetadataValidationException.java
  onboarding-enabler-java/src/main/java/org/zowe/apiml/eurekaservice/client/impl/ApiMediationClientImpl.java
Labels: passed CA tests

#596 Fix throughput via ZUUL with bypass authentication scheme
  apiml-common/src/main/java/org/zowe/apiml/product/web/HttpConfig.java
  common-service-core/src/main/java/org/zowe/apiml/security/SecurityUtils.java
  common-service-core/src/test/java/org/zowe/apiml/security/SecurityUtilsTest.java
  config/local/api-defs/staticclient.yml
  discoverable-client/src/main/java/org/zowe/apiml/client/api/RequestInfoController.java
  discoverable-client/src/main/resources/application.yml
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/pre/JwtValidatorFilter.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/pre/ServiceAuthenticationFilter.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/ribbon/ApimlCloseableHttpClientConfig.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/ribbon/GatewayRibbonConfig.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/ribbon/GatewayRibbonLoadBalancingHttpClientImpl.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/routing/ApimlRoutingConfig.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/config/ApimlX509AuthenticationFilter.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/config/AuthProviderInitializer.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/config/CertificateAuthenticationProvider.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/config/SecurityConfiguration.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/PassTicketException.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/ServiceAuthenticationServiceImpl.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/AbstractAuthenticationScheme.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/AuthenticationCommand.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/AuthenticationSchemeFactory.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/ByPassScheme.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/HttpBasicPassTicketScheme.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/ServiceAuthenticationService.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/ZosmfScheme.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/ZoweJwtScheme.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/filters/pre/JwtValidatorFilterTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/filters/pre/ServiceAuthenticationFilterTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/ribbon/ApimlCloseableHttpClientConfigTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/ribbon/GatewayRibbonLoadBalancingHttpClientImplTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/config/ApimlX509AuthenticationFilterTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/config/AuthProviderInitializerTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/config/CertificateAuthenticationProviderTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/ServiceAuthenticationServiceImplTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/AuthenticationCommandTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/AuthenticationSchemeFactoryTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/ByPassSchemeTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/HttpBasicPassTicketSchemeTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/ZosmfSchemeTest.java
  integration-tests/src/test/java/org/zowe/apiml/apicatalog/ApiCatalogSecurityIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/discoverableclient/RequestInfoIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/PassTicketTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/ZosmfSsoIntegrationTest.java
Labels: passed CA tests

#598 Trust public DigiCert certificate
  keystore/localhost/localhost.truststore.p12
Labels: passed CA tests

#561 Endpoints to get public keys for JWT verification (z/OSMF and Zowe)
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/api/AbstractApiDocService.java
  discovery-service/src/main/java/org/zowe/apiml/discovery/GatewayNotifier.java
  discovery-service/src/test/java/org/zowe/apiml/discovery/GatewayNotifierTest.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/controllers/AuthController.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/controllers/CacheServiceController.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/config/SecurityConfiguration.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/AuthenticationService.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/JwtSecurityInitializer.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/zosmf/ZosmfServiceFacade.java
  gateway-service/src/main/resources/application.yml
  gateway-service/src/main/resources/gateway-api-doc.json
  gateway-service/src/test/java/org/zowe/apiml/gateway/controllers/AuthControllerTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/controllers/CacheServiceControllerTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/AuthenticationServiceTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/JwtSecurityInitializerTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/zosmf/ZosmfServiceFacadeTest.java
  integration-tests/build.gradle
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/AuthenticationOnDeploymentTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/PublicKeyIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/ZosmfAuthenticationTest.java
  integration-tests/src/test/java/org/zowe/apiml/util/service/DiscoveryUtils.java
Labels: passed CA tests

#600 thin jar fixes
  api-catalog-services/build.gradle
  discoverable-client/build.gradle
  discovery-service/build.gradle
  gateway-service/build.gradle
Labels: passed CA tests, size/S

#590 Rip/refactor/openapi serialization
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/SecuritySchemeSerializer.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/api/ApiDocV3Service.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/swagger/SecuritySchemeSerializerTest.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/apidoc/reader/ApiDocController.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/apidoc/reader/ApiDocReader.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/WebConfig.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/apidoc/reader/ApiDocControllerTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/apidoc/reader/ApiDocReaderTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/utils/JsonReaderUtil.java
  gateway-service/src/test/resources/api-doc.json
Labels: passed CA tests

#602 Upgrade Integration Tests to JUnit 5.
  integration-tests/build.gradle
  integration-tests/src/test/java/org/zowe/apiml/apicatalog/ApiCatalogEndpointIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/apicatalog/ApiCatalogHttpHeadersIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/apicatalog/ApiCatalogLoginIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/discoverableclient/DownloadApiIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/discoverableclient/GreetingApiIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/discoverableclient/MultipartPutIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/discoverableclient/UiIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/discoveryservice/EurekaInstancesIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/discoveryservice/staticdef/StaticClientRoutingEndpointsTest.java
  integration-tests/src/test/java/org/zowe/apiml/enablejavasampleapp/EnablerJavaSampleAppEndpointTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/AuthenticationOnDeploymentTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/EncodedCharactersTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/GatewaySecurityTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/GatewayTimeoutTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/LoginIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/LogoutTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/PageRedirectionTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/PassTicketTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/PublicKeyIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/QueryIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/VersionEndpointTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/ZosmfAuthenticationTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/ZosmfSsoIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/penetration/JwtPenTest.java
  integration-tests/src/test/java/org/zowe/apiml/startup/ApiMediationLayerStartTest.java
  integration-tests/src/test/java/org/zowe/apiml/startup/impl/ApiMediationLayerStartupChecker.java
  integration-tests/src/test/java/org/zowe/apiml/util/categories/AdditionalLocalTest.java
  integration-tests/src/test/java/org/zowe/apiml/util/categories/MainframeDependentTests.java
  integration-tests/src/test/java/org/zowe/apiml/util/categories/SlowTests.java
  integration-tests/src/test/java/org/zowe/apiml/util/categories/StartupCheck.java
  integration-tests/src/test/java/org/zowe/apiml/util/categories/TestsNotMeantForZowe.java
  integration-tests/src/test/java/org/zowe/apiml/util/categories/WebsocketTest.java
  integration-tests/src/test/java/org/zowe/apiml/util/http/HttpClientUtils.java
  integration-tests/src/test/java/org/zowe/apiml/util/http/HttpRequestUtils.java
  integration-tests/src/test/java/org/zowe/apiml/util/http/HttpSecurityUtils.java
  integration-tests/src/test/java/org/zowe/apiml/util/service/VirtualService.java
  integration-tests/src/test/java/org/zowe/apiml/ws/WebSocketProxyTest.java
Labels: passed CA tests

#606 Discoverable Client Thin jar fix
  discoverable-client/build.gradle
Labels: passed CA tests, size/XS

#605 US654071: Added auth for catalog swagger endpoints
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/controllers/api/ApiCatalogController.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/controllers/api/CatalogApiDocController.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/SwaggerConfiguration.java
  api-catalog-ui/frontend/cypress/integration/e2e/detail-page/detail-page.test.js
  api-catalog-ui/frontend/cypress/integration/e2e/detail-page/swagger-try-out.test.js
  api-catalog-ui/frontend/src/components/ServiceTab/ServiceTab.css
  gateway-service/src/main/resources/gateway-api-doc.json
Labels: passed CA tests, ready for CA testing, under CA testing

#609 Update gradle tomcat plugin
  onboarding-enabler-java-sample-app/build.gradle
Labels: size/XS, under CA testing

#603 Rip/gh577/archaius log
  build.gradle
  onboarding-enabler-java/src/main/resources/eureka-client.properties
Labels: passed CA tests, ready for CA testing, size/XS

#610 Set up remote cache for CI environment
  Jenkinsfile
  gradle.properties
  settings.gradle
Labels: passed CA tests, size/S

#611 fix PassTicket scheme when call without JWT
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/HttpBasicPassTicketScheme.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/HttpBasicPassTicketSchemeTest.java
Labels: passed CA tests

#613 Pza/eureka client config provider 2
  onboarding-enabler-java/build.gradle
  onboarding-enabler-java/src/main/java/org/zowe/apiml/eurekaservice/client/EurekaClientConfigProvider.java
  onboarding-enabler-java/src/main/java/org/zowe/apiml/eurekaservice/client/config/EurekaClientConfiguration.java
  onboarding-enabler-java/src/main/java/org/zowe/apiml/eurekaservice/client/impl/ApiMediationClientImpl.java
  onboarding-enabler-java/src/main/java/org/zowe/apiml/eurekaservice/client/impl/ApiMlEurekaClientConfigProvider.java
  onboarding-enabler-java/src/test/java/org/zowe/apiml/eurekaservice/client/impl/ApiMediationClientImplTest.java
  onboarding-enabler-spring/build.gradle
  onboarding-enabler-spring/src/main/java/org/zowe/apiml/enable/config/EnableApiDiscoveryConfig.java
Labels: passed CA tests

#618 Use Spring @Conditional)v4) instead of @Nullable(v5) for optional beans
  onboarding-enabler-spring/src/main/java/org/zowe/apiml/enable/config/EnableApiDiscoveryConfig.java
Labels: passed CA tests

#619 Improve CICD on external Jenkins
  Jenkinsfile
  scripts/publish_and_release.sh
Labels: passed CA tests, size/XS

#588 Zaas client
  docs/docgen/config.yml
  gradle/coverage.gradle
  gradle/license.gradle
  gradle/publish.gradle
  integration-tests/build.gradle
  integration-tests/src/test/java/org/zowe/apiml/util/config/ConfigReaderZaasClient.java
  integration-tests/src/test/java/org/zowe/apiml/zaasclient/ZaasClientIntegrationTest.java
  integration-tests/src/test/resources/configFile-properties.yml
  settings.gradle
  zaas-client/README.md
  zaas-client/build.gradle
  zaas-client/src/main/java/org/zowe/apiml/zaasclient/config/ConfigProperties.java
  zaas-client/src/main/java/org/zowe/apiml/zaasclient/exception/ZaasClientErrorCodes.java
  zaas-client/src/main/java/org/zowe/apiml/zaasclient/exception/ZaasClientException.java
  zaas-client/src/main/java/org/zowe/apiml/zaasclient/exception/ZaasConfigurationErrorCodes.java
  zaas-client/src/main/java/org/zowe/apiml/zaasclient/exception/ZaasConfigurationException.java
  zaas-client/src/main/java/org/zowe/apiml/zaasclient/passticket/ZaasClientTicketRequest.java
  zaas-client/src/main/java/org/zowe/apiml/zaasclient/passticket/ZaasPassTicketResponse.java
  zaas-client/src/main/java/org/zowe/apiml/zaasclient/service/ZaasClient.java
  zaas-client/src/main/java/org/zowe/apiml/zaasclient/service/ZaasToken.java
  zaas-client/src/main/java/org/zowe/apiml/zaasclient/service/internal/CloseableClientProvider.java
  zaas-client/src/main/java/org/zowe/apiml/zaasclient/service/internal/HttpsClientProvider.java
  zaas-client/src/main/java/org/zowe/apiml/zaasclient/service/internal/PassTicketService.java
  zaas-client/src/main/java/org/zowe/apiml/zaasclient/service/internal/PassTicketServiceHttps.java
  zaas-client/src/main/java/org/zowe/apiml/zaasclient/service/internal/TokenService.java
  zaas-client/src/main/java/org/zowe/apiml/zaasclient/service/internal/TokenServiceHttpsJwt.java
  zaas-client/src/main/java/org/zowe/apiml/zaasclient/service/internal/ZaasClientHttps.java
  zaas-client/src/main/resources/zaas-client-log-messages.yml
  zaas-client/src/test/java/org/zowe/apiml/zaasclient/service/internal/CloseableClientProviderTest.java
  zaas-client/src/test/java/org/zowe/apiml/zaasclient/service/internal/ZaasClientHttpsTest.java
  zaas-client/src/test/java/org/zowe/apiml/zaasclient/service/internal/ZaasClientTest.java
  zaas-client/src/test/resources/configFile.properties
  zaas-client/src/test/resources/localhost.keystore.p12
  zaas-client/src/test/resources/localhost.truststore.p12
Labels: 20PI2, passed CA tests

#620 us654068/leverage ha modes for downstream services
  api-catalog-services/src/main/resources/apicatalog-log-messages.yml
  apiml-security-common/src/main/resources/security-common-log-messages.yml
  common-service-core/src/main/java/org/zowe/apiml/util/Cookies.java
  common-service-core/src/main/java/org/zowe/apiml/util/RequestUtils.java
  common-service-core/src/main/resources/core-log-messages.yml
  common-service-core/src/test/java/org/zowe/apiml/util/CookiesTest.java
  common-service-core/src/test/java/org/zowe/apiml/util/RequestUtilsTest.java
  discovery-service/src/main/resources/discovery-log-messages.yml
  gateway-service/build.gradle
  gateway-service/src/main/java/org/zowe/apiml/gateway/error/InternalServerErrorController.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/error/check/RibbonRetryErrorCheck.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/post/DebugHeaderFilter.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/ribbon/AbortingRetryListener.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/ribbon/ApimlCloseableHttpClientConfig.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/ribbon/ApimlRetryableClient.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/ribbon/ApimlRibbonRetryFactory.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/ribbon/ApimlZoneAwareLoadBalancer.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/ribbon/GatewayRibbonConfig.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/ribbon/GatewayRibbonLoadBalancingHttpClient.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/ribbon/GatewayRibbonLoadBalancingHttpClientImpl.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/ribbon/RequestContextUtils.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/ribbon/http/BeanConfig.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/ribbon/http/HttpClientChooser.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/ribbon/http/HttpClientProxyConfig.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/ribbon/http/RequestAbortException.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/ribbon/http/RequestContextNotPreparedException.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/ribbon/http/ServiceAuthenticationDecorator.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/ServiceAuthenticationServiceImpl.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/AuthenticationCommand.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/ByPassScheme.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/HttpBasicPassTicketScheme.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/ServiceAuthenticationService.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/ZosmfScheme.java
  gateway-service/src/main/resources/application.yml
  gateway-service/src/main/resources/ehcache.xml
  gateway-service/src/main/resources/gateway-log-messages.yml
  gateway-service/src/test/java/org/zowe/apiml/gateway/error/check/RibbonRetryErrorCheckTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/ribbon/ApimlCloseableHttpClientConfigTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/ribbon/ApimlRetryableClientTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/ribbon/ApimlZoneAwareLoadBalancerTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/ribbon/GatewayRibbonLoadBalancingHttpClientImplTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/ribbon/RequestContextUtilsTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/ribbon/http/HttpClientChooserTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/ribbon/http/HttpClientProxyConfigTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/ribbon/http/ServiceAuthenticationDecoratorTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/ByPassSchemeTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/HttpBasicPassTicketSchemeTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/ZosmfSchemeTest.java
  gateway-service/src/test/resources/gateway-messages.yml
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/AuthenticationOnDeploymentTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/ServiceHaMode.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/ZosmfAuthenticationTest.java
  integration-tests/src/test/java/org/zowe/apiml/util/service/VirtualService.java
  zaas-client/src/main/resources/zaas-client-log-messages.yml
Labels: passed CA tests

#625 Add Changelog with the more relevant changes
  CHANGELOG.md
Labels: passed CA tests, size/S
