Repository zowe/api-layer, pull requests merged in 2020-07, with the labels that each got.

#733 apiml 1.13 changes
  CHANGELOG.md
Labels: failed CA tests, size/XS

#732 resolve ip address for spring enabler
  config/local/discoverable-client.yml
  discoverable-client/src/main/resources/application.yml
  onboarding-enabler-java/src/main/java/org/zowe/apiml/eurekaservice/client/config/ApiMediationServiceConfig.java
  onboarding-enabler-java/src/main/java/org/zowe/apiml/eurekaservice/client/util/ApiMediationServiceConfigReader.java
  onboarding-enabler-java/src/main/java/org/zowe/apiml/eurekaservice/client/util/EurekaInstanceConfigCreator.java
  onboarding-enabler-java/src/test/java/org/zowe/apiml/eurekaservice/client/util/EurekaInstanceConfigCreatorTest.java
  onboarding-enabler-java/src/test/resources/service-configuration-prefer-ip.yml
  onboarding-enabler-spring/src/main/java/org/zowe/apiml/enable/config/EnableApiDiscoveryConfig.java
  onboarding-enabler-spring/src/test/java/org/zowe/apiml/enable/config/EnableApiDiscoveryConfigTest.java
  onboarding-enabler-spring/src/test/java/org/zowe/apiml/enable/register/ApimlEnabledRegisterToApiLayerTest.java
  onboarding-enabler-spring/src/test/resources/application.yml
Labels: passed CA tests

#734 Replace deprecated properties with the new ones
  api-catalog-services/build.gradle
  discovery-service/build.gradle
  gateway-service/build.gradle
Labels: passed CA tests, size/S

#739 Clean smells found by the SonarCube
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/controllers/api/ApiCatalogController.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/controllers/api/CatalogApiDocController.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/controllers/handlers/ApiCatalogControllerExceptionHandler.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/exceptions/ContainerStatusRetrievalThrowable.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/api/ApiTransformationConfig.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/controllers/api/ApiCatalogControllerTests.java
  common-service-core/src/main/java/org/zowe/apiml/cache/CompositeKey.java
  common-service-core/src/main/java/org/zowe/apiml/message/api/ApiMessage.java
  common-service-core/src/main/java/org/zowe/apiml/util/ObjectUtil.java
  common-service-core/src/test/java/org/zowe/apiml/util/ObjectUtilTest.java
  discovery-service/src/main/java/org/zowe/apiml/discovery/staticdef/ServiceDefinitionProcessor.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/zosmf/SaveZosmfPublicKeyConsoleApplication.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/AuthenticationService.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/error/check/SecurityTokenErrorCheckTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/error/check/ServiceNotFoundCheckTest.java
  integration-tests/src/test/java/org/zowe/apiml/penetration/JwtPenTest.java
Labels: passed CA tests

#740 Rip/gh682/request context n3
  gateway-service/src/main/java/org/zowe/apiml/gateway/cache/ServiceCacheEvictor.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/DiscoveryClientConfig.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/EurekaEventsRegistry.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/metadata/service/CorsMetadataProcessor.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/metadata/service/EurekaApplications.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/metadata/service/LoadBalancerRegistry.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/metadata/service/MetadataProcessor.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/metadata/service/RefreshEventListener.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/metadata/service/RibbonMetadataProcessor.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/ribbon/ApimlLoadBalancer.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/ribbon/GatewayRibbonConfig.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/routing/ApimlRouteLocator.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/config/ribbon/RibbonTestConfiguration.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/netflix/ApimlLoadBalancerStub.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/cache/ServiceCacheEvictorTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/config/EurekaEventsRegistryTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/metadata/service/RefreshEventListenerTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/metadata/service/RibbonMetadataProcessorTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/ribbon/ApimlLoadBalancerTest.java
  integration-tests/build.gradle
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/AuthenticationOnDeploymentTest.java
  integration-tests/src/test/java/org/zowe/apiml/util/categories/NotForMainframeTest.java
  integration-tests/src/test/java/org/zowe/apiml/util/service/VirtualService.java
  integration-tests/src/test/resources/logback.xml
Labels: passed CA tests

#741 Storing password into char arrays instead of String
  apiml-common/src/main/java/org/zowe/apiml/product/web/HttpConfig.java
  common-service-core/src/main/java/org/zowe/apiml/security/HttpsConfig.java
  common-service-core/src/main/java/org/zowe/apiml/security/HttpsFactory.java
  common-service-core/src/main/java/org/zowe/apiml/security/SecurityUtils.java
  common-service-core/src/test/java/org/zowe/apiml/security/HttpsFactoryTest.java
  common-service-core/src/test/java/org/zowe/apiml/security/SecurityTestUtils.java
  common-service-core/src/test/java/org/zowe/apiml/security/SecurityUtilsTest.java
  common-service-core/src/test/java/org/zowe/apiml/tomcat/TomcatServerFactory.java
  discoverable-client/src/main/java/org/zowe/apiml/client/configuration/ZaasClientConfig.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/zosmf/JwkToPublicKeyConverter.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/zosmf/SaveZosmfPublicKeyConsoleApplication.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/zosmf/ZosmfJwkToPublicKey.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/JwtSecurityInitializer.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/login/zosmf/JwkToPublicKeyConverterTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/login/zosmf/ZosmfJwkToPublicKeyTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/SecurityUtils.java
  integration-tests/src/test/java/org/zowe/apiml/util/config/ConfigReader.java
  integration-tests/src/test/java/org/zowe/apiml/util/config/TlsConfiguration.java
  integration-tests/src/test/java/org/zowe/apiml/zaasclient/ZaasClientIntegrationTest.java
  onboarding-enabler-java/src/main/java/org/zowe/apiml/eurekaservice/client/config/Ssl.java
  onboarding-enabler-java/src/main/java/org/zowe/apiml/eurekaservice/client/util/EurekaInstanceConfigValidator.java
  onboarding-enabler-java/src/test/java/org/zowe/apiml/eurekaservice/client/impl/ApiMediationClientImplTest.java
  onboarding-enabler-java/src/test/java/org/zowe/apiml/eurekaservice/client/util/ApiMediationServiceConfigReaderTest.java
  zaas-client/src/main/java/org/zowe/apiml/zaasclient/config/ConfigProperties.java
  zaas-client/src/main/java/org/zowe/apiml/zaasclient/service/internal/HttpsClientProvider.java
  zaas-client/src/test/java/org/zowe/apiml/zaasclient/service/internal/CloseableClientProviderTest.java
  zaas-client/src/test/java/org/zowe/apiml/zaasclient/service/internal/ZaasClientHttpsTest.java
Labels: passed CA tests

#746 Created api-def for zosmf now allows encoded url characters by default
  zowe-install/src/main/resources/component-scripts/configure.sh
Labels: passed CA tests, size/XS

#748 Fix Veracode CWE ID 316
  common-service-core/src/main/java/org/zowe/apiml/security/HttpsConfig.java
Labels: passed CA tests, ready for CA testing

#750 Don't check validity of certs when calling discovery/** apis when verify ssl certs false
  discovery-service/src/main/java/org/zowe/apiml/discovery/config/HttpsWebSecurityConfig.java
Labels: passed CA tests

#754 common run configurations
  .run/ApiCatalogApplication.run.xml
  .run/DiscoverableClientSampleApplication.run.xml
  .run/DiscoveryServiceApplication.run.xml
  .run/EnablerV1SampleApplication.run.xml
  .run/GatewayApplication.run.xml
Labels: passed CA tests, size/M

#755 Remove cipher property from apiml.security
  api-catalog-services/src/main/resources/application.yml
  discoverable-client/src/main/resources/application.yml
  discoverable-client/src/test/resources/application.yml
  discovery-service/src/main/resources/application.yml
  gateway-service/src/main/resources/application.yml
  gateway-service/src/test/resources/application-test.yml
  gateway-service/src/test/resources/application.yml
  onboarding-enabler-java-sample-app/src/main/resources/service-configuration.yml
  onboarding-enabler-java/src/main/java/org/zowe/apiml/eurekaservice/client/config/Ssl.java
  onboarding-enabler-java/src/test/java/org/zowe/apiml/eurekaservice/client/impl/ApiMediationClientImplTest.java
  onboarding-enabler-java/src/test/java/org/zowe/apiml/eurekaservice/client/util/ApiMediationServiceConfigReaderTest.java
  onboarding-enabler-java/src/test/resources/additional-service-configuration.yml
  onboarding-enabler-java/src/test/resources/additional-service-configuration_serviceid-ssl-ciphers-only.yml
  onboarding-enabler-java/src/test/resources/bad-protocol-baseurl-service-configuration.yml
  onboarding-enabler-java/src/test/resources/https-disabled-service-configuration.yml
  onboarding-enabler-java/src/test/resources/https-service-configuration.yml
  onboarding-enabler-java/src/test/resources/service-configuration-prefer-ip.yml
  onboarding-enabler-java/src/test/resources/service-configuration-wildcard.yml
  onboarding-enabler-java/src/test/resources/service-configuration.yml
  onboarding-enabler-java/src/test/resources/wrong-routes-service-configuration.yml
  onboarding-enabler-spring/src/test/resources/application.yml
Labels: passed CA tests

#756 Private/ac/retry demo
  config/local/api-defs/staticclient.yml
  discoverable-client/src/main/java/org/zowe/apiml/client/api/StatusCodeController.java
  gateway-service/src/main/resources/application.yml
Labels: failed CA tests

#760 Configuration validator enhancement
  onboarding-enabler-java/src/main/java/org/zowe/apiml/eurekaservice/client/util/EurekaInstanceConfigValidator.java
  onboarding-enabler-java/src/test/java/org/zowe/apiml/eurekaservice/client/util/EurekaInstanceConfigValidatorTest.java
  onboarding-enabler-java/src/test/resources/keyring-ssl-configuration.yml
  onboarding-enabler-java/src/test/resources/missing-ssl-configuration.yml
Labels: passed CA tests

#764 Remove E2E Tests run from the PR run on the Wash
  build.gradle
Labels: passed CA tests, size/XS

#765 Install PNPM dependencies before run
  docker/README.md
  docker/development/README.md
  docker/development/_run
Labels: passed CA tests, size/S

#747 Enhance Gateway logging
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/post/DebugHeaderFilter.java
Labels: under CA testing

#768 community edition java run configurations
  .run/java-Catalog.run.xml
  .run/java-DiscoverableClient.run.xml
  .run/java-Discovery.run.xml
  .run/java-Gateway.run.xml
  .run/spring-ApiCatalogApplication.run.xml
  .run/spring-DiscoverableClientSampleApplication.run.xml
  .run/spring-DiscoveryServiceApplication.run.xml
  .run/spring-EnablerV1SampleApplication.run.xml
  .run/spring-GatewayApplication.run.xml
Labels: size/M, under CA testing

#766 describe branch naming strategy
  CONTRIBUTING.md
Labels: ready for CA testing, size/S, under CA testing

#767 If service has no instances don't return null routes
  gateway-service/src/main/java/org/zowe/apiml/gateway/routing/ApimlRouteLocator.java
Labels: under CA testing
