Repository zowe/api-layer, pull requests merged in 2020-10, with the labels that each got.

#875 decouple internal pipelines
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/authentication/ZosmfAuthenticationLoginIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/startup/CheckEnvironment.java
Labels: passed CA tests

#878 Add changelog notes for v1.16.0
  CHANGELOG.md
Labels: size/S, under CA testing

#876 Fix fulfill JWT in request on ZaasClient.logout
  discoverable-client/src/main/java/org/zowe/apiml/client/api/ZaasClientTestController.java
  discoverable-client/src/test/java/org/zowe/apiml/client/api/ZaasClientTestControllerTest.java
  integration-tests/src/test/java/org/zowe/apiml/discoverableclient/IntegratedZaasClientTest.java
  integration-tests/src/test/java/org/zowe/apiml/zaasclient/ZaasClientIntegrationTest.java
  zaas-client/src/main/java/org/zowe/apiml/zaasclient/service/internal/ZaasJwtService.java
  zaas-client/src/test/java/org/zowe/apiml/zaasclient/service/internal/ZaasJwtServiceTest.java
Labels: passed CA tests

#880 Call ZSS with valid JWT token
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/x509/X509AuthenticationMapper.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/x509/X509AuthenticationProvider.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/x509/X509ExternalMapper.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/TokenCreationService.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/login/x509/X509AuthenticationProviderTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/login/x509/X509ExternalMapperTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/TokenCreationServiceTest.java
  gateway-service/src/test/resources/application.yml
Labels: passed CA tests

#874 Improve Gateway logout endpoint error handling
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/config/JWTLogoutHandler.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/AuthenticationService.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/config/JWTLogoutHandlerTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/AuthenticationServiceTest.java
  integration-tests/src/test/java/org/zowe/apiml/discoverableclient/IntegratedZaasClientTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/authentication/DummyLogoutTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/authentication/LogoutTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/authentication/SafLogoutTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/authentication/ZosmfAuthenticationLoginIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/authentication/ZosmfLogoutTest.java
  zaas-client/src/main/java/org/zowe/apiml/zaasclient/service/internal/ZaasJwtService.java
  zaas-client/src/test/java/org/zowe/apiml/zaasclient/service/internal/ZaasClientImplHttpsTests.java
Labels: passed CA tests

#881 Add guidelines around planning and sizing.
  CONTRIBUTING.md
Labels: failed CA tests, size/S

#882 Update CONTRIBUTING.md - small adjustments around the estimation process
  CONTRIBUTING.md
Labels: failed CA tests, size/S

#884 Consistent path pattern in API Catalog
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/SubstituteSwaggerGenerator.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/api/AbstractApiDocService.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/api/ApiDocV2Service.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/api/ApiDocV3Service.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/api/OpenApiUtil.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/services/status/LocalApiDocServiceTest.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/swagger/SubstituteSwaggerGeneratorTest.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/swagger/api/AbstractApiDocServiceTest.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/swagger/api/ApiDocV2ServiceTest.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/swagger/api/ApiDocV3ServiceTest.java
  api-catalog-ui/frontend/cypress/integration/e2e/detail-page/detail-page.test.js
  gateway-service/src/main/java/org/zowe/apiml/gateway/controllers/GatewayHomepageController.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/controllers/GatewayHomepageControllerTest.java
  integration-tests/src/test/java/org/zowe/apiml/apicatalog/ApiCatalogEndpointIntegrationTest.java
Labels: under CA testing

#885 Use the names actually provided by ZSS
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/x509/model/CertMapperResponse.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/login/x509/X509ExternalMapperTest.java
Labels: failed CA tests

#887 Create Mock of zOSMF to be used on the Wash CICD
  Jenkinsfile
  config/local/api-defs/mock-zosmf.yml
  config/local/gateway-service.yml
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/saf/MockPlatformUser.java
  gradle/license.gradle
  gradle/sonar.gradle
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/PublicKeyIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/SecurityUtils.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/ZosmfSsoIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/authentication/SafAuthenticationLoginIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/authentication/SafLogoutTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/authentication/ZosmfAuthenticationLoginIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/authentication/ZosmfLogoutTest.java
  integration-tests/src/test/java/org/zowe/apiml/penetration/JwtPenTest.java
  integration-tests/src/test/java/org/zowe/apiml/startup/CheckEnvironment.java
  mock-zosmf/README.md
  mock-zosmf/build.gradle
  mock-zosmf/src/main/java/org/zowe/apiml/client/MockZosmfApplication.java
  mock-zosmf/src/main/java/org/zowe/apiml/client/api/AuthenticationController.java
  mock-zosmf/src/main/java/org/zowe/apiml/client/api/FilesController.java
  mock-zosmf/src/main/java/org/zowe/apiml/client/api/InfoController.java
  mock-zosmf/src/main/resources/application.yml
  package.json
  settings.gradle
Labels: under CA testing

#883 GH704: default zowe parameters
  zowe-install/src/main/resources/component-scripts/start.sh
Labels: failed CA tests, size/XS

#893 Disable unstable tests on internal pipeline
  Jenkinsfile
  config/local/api-defs/mock-zosmf.yml
  config/local/gateway-service.yml
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/config/ComponentsConfiguration.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/Providers.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/x509/X509ExternalMapper.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/login/ProvidersTest.java
  integration-tests/src/test/java/org/zowe/apiml/discoverableclient/IntegratedZaasClientTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/SecurityUtils.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/authentication/DummyAuthenticationLoginIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/authentication/Login.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/authentication/SafAuthenticationLoginIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/authentication/ZosmfAuthenticationLoginIntegrationTest.java
Labels: passed CA tests

#894 Propagate config from the instance.env to the start.sh
  zowe-install/src/main/resources/component-scripts/start.sh
Labels: passed CA tests, size/S

#898 Update multiple instances setup
  config/local-multi/api-catalog-service.yml
  config/local-multi/discoverable-client.yml
  config/local-multi/discovery-service-1.yml
  config/local-multi/discovery-service-2.yml
  config/local-multi/gateway-service.yml
  keystore/local_ca/localca.cer
  keystore/local_ca/localca.keystore.p12
  keystore/localhost/localhost-multi.keystore.p12
  keystore/localhost/localhost-multi.truststore.p12
  package.json
Labels: passed CA tests

#902 Implement Caching API Controller
  caching-service/README.md
  caching-service/build.gradle
  caching-service/src/main/java/org/zowe/apiml/caching/api/CachingController.java
  caching-service/src/main/java/org/zowe/apiml/caching/config/MessageConfiguration.java
  caching-service/src/main/java/org/zowe/apiml/caching/config/StorageConfiguration.java
  caching-service/src/main/java/org/zowe/apiml/caching/config/SwaggerConfig.java
  caching-service/src/main/java/org/zowe/apiml/caching/exceptions/CachingPayloadException.java
  caching-service/src/main/java/org/zowe/apiml/caching/service/Storage.java
  caching-service/src/main/java/org/zowe/apiml/caching/service/inmemory/InMemoryStorage.java
  caching-service/src/main/resources/application.yml
  caching-service/src/main/resources/caching-log-messages.yml
  caching-service/src/test/java/org/zowe/apiml/caching/api/CachingControllerTest.java
  caching-service/src/test/java/org/zowe/apiml/caching/service/inmemory/InMemoryStorageTest.java
  discoverable-client/src/main/java/org/zowe/apiml/client/api/ZaasClientTestController.java
  docs/local-configuration.md
  integration-tests/build.gradle
  integration-tests/src/test/java/org/zowe/apiml/cachingservice/CachingApiIntegrationTest.java
  zaas-client/README.md
  zaas-client/build.gradle
  zaas-client/src/main/java/org/zowe/apiml/zaasclient/config/DefaultZaasClientConfiguration.java
Labels: failed CA tests

#904 In Memory implementation of the Caching API
  caching-service/README.md
  caching-service/build.gradle
  caching-service/cachingServiceStructure.png
  caching-service/src/main/java/org/zowe/apiml/caching/CachingService.java
  caching-service/src/main/java/org/zowe/apiml/caching/api/CachingController.java
  caching-service/src/main/java/org/zowe/apiml/caching/config/MessageConfiguration.java
  caching-service/src/main/java/org/zowe/apiml/caching/config/StorageConfiguration.java
  caching-service/src/main/java/org/zowe/apiml/caching/config/SwaggerConfig.java
  caching-service/src/main/java/org/zowe/apiml/caching/exceptions/CachingPayloadException.java
  caching-service/src/main/java/org/zowe/apiml/caching/model/KeyValue.java
  caching-service/src/main/java/org/zowe/apiml/caching/service/Storage.java
  caching-service/src/main/java/org/zowe/apiml/caching/service/inmemory/InMemoryStorage.java
  caching-service/src/main/resources/application.yml
  caching-service/src/main/resources/banner.txt
  caching-service/src/main/resources/caching-log-messages.yml
  caching-service/src/test/java/org/zowe/apiml/caching/api/CachingControllerTest.java
  caching-service/src/test/java/org/zowe/apiml/caching/service/inmemory/InMemoryStorageTest.java
  caching-service/src/test/resources/application.yml
  discoverable-client/src/main/java/org/zowe/apiml/client/api/ZaasClientTestController.java
  docs/local-configuration.md
  gradle/coverage.gradle
  gradle/license.gradle
  gradle/publish.gradle
  integration-tests/build.gradle
  integration-tests/src/test/java/org/zowe/apiml/cachingservice/CachingApiIntegrationTest.java
  package.json
  settings.gradle
  zaas-client/README.md
  zaas-client/build.gradle
  zaas-client/src/main/java/org/zowe/apiml/zaasclient/config/DefaultZaasClientConfiguration.java
  zowe-install/src/main/resources/component-scripts/start.sh
Labels: passed CA tests

#905 Update start scripts to use new discovery services parameter
  zowe-install/src/main/resources/component-scripts/start.sh
Labels: passed CA tests, size/XS

#907 Publish build of Caching Service
  Jenkinsfile
Labels: size/XS, under CA testing
