Repository zowe/api-layer, pull requests merged in 2020-12, with the labels that each got.

#966 Private/ac/catalog cache
  api-catalog-services/src/main/resources/application.yml
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/GatewayConfig.java
  integration-tests/src/test/java/org/zowe/apiml/startup/impl/ApiMediationLayerStartupChecker.java
Labels: under CA testing

#969 Invalidate JWT with multiple GW instances
  gateway-service/src/main/java/org/zowe/apiml/gateway/controllers/AuthController.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/AuthenticationService.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/AuthenticationServiceTest.java
  integration-tests/src/test/java/org/zowe/apiml/discoverableclient/IntegratedZaasClientTest.java
Labels: under CA testing

#975 Update endpoints to match the names of tests.
  integration-tests/src/test/java/org/zowe/apiml/apicatalog/ApiCatalogSecurityIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/discoveryservice/EurekaInstancesIntegrationTest.java
Labels: under CA testing

#978 Fix bash errors about returning numeric arguments
  api-catalog-package/src/main/resources/bin/validate.sh
  caching-service-package/src/main/resources/bin/validate.sh
  discovery-package/src/main/resources/bin/validate.sh
  gateway-package/src/main/resources/bin/validate.sh
Labels: size/XS, under CA testing

#973 Add check to verify VSAM file existence
  caching-service/src/main/java/org/zowe/apiml/caching/service/vsam/VsamFile.java
  caching-service/src/test/java/org/zowe/apiml/caching/service/vsam/VsamFileTest.java
  caching-service/src/test/java/org/zowe/apiml/caching/service/vsam/VsamKeyTest.java
Labels: under CA testing

#986 update build agent
  Jenkinsfile
  api-catalog-ui/frontend/package.json
  api-catalog-ui/frontend/src/components/ErrorBoundary/BigShield/BigShield.test.jsx
Labels: size/S

#981 Update changelog
  CHANGELOG.md
Labels: size/S

#1006 Remove previous thin jar impl
  api-catalog-services/build.gradle
  caching-service/build.gradle
  discoverable-client/build.gradle
  discovery-service/build.gradle
  gateway-service/build.gradle
  integration-tests/build.gradle
  integration-tests/src/test/java/org/zowe/apiml/cachingservice/CachingApiIntegrationTest.java
  mock-zosmf/build.gradle
Labels: size/M

#1010 Remove usage of -cp from launch scripts
  api-catalog-services/gradle/lite.gradle
  build.gradle
  discovery-service/gradle/lite.gradle
  gateway-package/src/main/resources/bin/start.sh
  gateway-service/gradle/lite.gradle
  package.json
  zowe-install/src/main/resources/component-scripts/start-gateway.sh
Labels: size/M

#1016 Repair publish tasks
  api-catalog-package/build.gradle
  api-catalog-services/build.gradle
  caching-service-package/build.gradle
  caching-service/build.gradle
  discoverable-client/build.gradle
  discovery-package/build.gradle
  discovery-service/build.gradle
  gateway-package/build.gradle
  gateway-service/build.gradle
Labels: size/M

#1019 Publish lite JARs
  api-catalog-package/build.gradle
  api-catalog-services/gradle/lite.gradle
  common-lib-package/build.gradle
  common-lib-package/src/main/resources/manifest.yaml
  discovery-package/build.gradle
  discovery-service/gradle/lite.gradle
  gateway-package/build.gradle
  gateway-service/gradle/lite.gradle
  gradle/publish.gradle
  gradle/sonar.gradle
  settings.gradle
Labels: size/L

#1021 Alter start scripts for the lite packaging
  api-catalog-package/src/main/resources/bin/start.sh
  discovery-package/src/main/resources/bin/start.sh
  gateway-package/src/main/resources/bin/start.sh
Labels: size/S

#1002 let zowe launch script to handle configure
  api-catalog-package/src/main/resources/bin/configure.sh
  api-catalog-package/src/main/resources/manifest.yaml
  caching-service-package/src/main/resources/bin/configure.sh
  caching-service-package/src/main/resources/manifest.yaml
  discovery-package/build.gradle
  discovery-package/src/main/resources/manifest.yaml
  discovery-package/src/main/resources/zosmf-static-definition.yaml.template
  gateway-package/src/main/resources/bin/configure.sh
  gateway-package/src/main/resources/manifest.yaml
Labels: size/L

#1031 Correct location of common lib in start scripts
  api-catalog-package/src/main/resources/bin/start.sh
  discovery-package/src/main/resources/bin/start.sh
  gateway-package/src/main/resources/bin/start.sh
Labels: size/XS

#1033 Use relative path with common-lib jar
  api-catalog-package/src/main/resources/bin/start.sh
  apiml-common-lib-package/build.gradle
  apiml-common-lib-package/src/main/resources/manifest.yaml
  discovery-package/src/main/resources/bin/start.sh
  gateway-package/src/main/resources/bin/start.sh
  gradle/publish.gradle
  gradle/sonar.gradle
  settings.gradle
Labels: size/S

#1037 Enhance connection limit log messages
  apiml-common/src/main/resources/common-log-messages.yml
Labels: size/XS
