Repository zowe/api-layer, pull requests merged in 2020-05, with the labels that each got.

#631 Run the integration tests on the external CI Jenkins server
  Jenkinsfile
  build.gradle
  integration-tests/build.gradle
  integration-tests/src/test/java/org/zowe/apiml/discoveryservice/EurekaInstancesIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/util/categories/Flaky.java
Labels: passed CA tests

#636 Tag those tests that will fail for Zowe RC
  integration-tests/build.gradle
  integration-tests/src/test/java/org/zowe/apiml/discoverableclient/RequestInfoIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/discoveryservice/EurekaInstancesIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/GatewaySecurityTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/GatewayTimeoutTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/LogoutTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/PublicKeyIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/VersionEndpointTest.java
  integration-tests/src/test/java/org/zowe/apiml/penetration/JwtPenTest.java
  integration-tests/src/test/java/org/zowe/apiml/ws/WebSocketProxyTest.java
Labels: passed CA tests

#639 Store the logs from integration tests on the Jenkins to be able to explore them
  Jenkinsfile
Labels: size/XS, under CA testing

#638 add dummy file to avoid warn log
  onboarding-enabler-java/src/main/resources/config.properties
Labels: size/XS, under CA testing

#617 switch to sso-auth instead of apiml-auth
  zlux-api-catalog/README.md
  zlux-api-catalog/web/index.html
  zowe-install/src/main/resources/component-scripts/configure.sh
Labels: passed CA tests, size/S

#640 Added logout api doc to swagger
  gateway-service/src/main/resources/gateway-api-doc.json
Labels: passed CA tests, size/S

#644 Move all tests under gradle
  Jenkinsfile
  build.gradle
  integration-tests/src/test/java/org/zowe/apiml/discoveryservice/EurekaInstancesIntegrationTest.java
Labels: passed CA tests

#651 replace codecov for sonar coverage badge
  README.md
Labels: size/XS

#652 Improve the CI CD Pipeline structure
  Jenkinsfile
  api-catalog-ui/build.gradle
  build.gradle
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/AuthenticationOnDeploymentTest.java
Labels: passed CA tests

#653 Improve Cypress Runs
  api-catalog-ui/frontend/cypress.json
  api-catalog-ui/frontend/package.json
  api-catalog-ui/frontend/pnpm-lock.yaml
Labels: passed CA tests, size/XL

#654 Move setup code outside of assertThrows
  integration-tests/src/test/java/org/zowe/apiml/zaasclient/ZaasClientIntegrationTest.java
  zaas-client/src/test/java/org/zowe/apiml/zaasclient/service/internal/CloseableClientProviderTest.java
Labels: passed CA tests

#655 Make jjwt only a test dependency in ZAAS Client
  zaas-client/build.gradle
Labels: passed CA tests, size/XS

#657 Run E2E tests on the external CI server
  api-catalog-ui/build.gradle
  build.gradle
  gradle.properties
Labels: passed CA tests, size/S

#658 fix PR artifact publish
  Jenkinsfile
Labels: passed CA tests, size/XS

#659 Api catalog backend refresh endpoint
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/security/SecurityConfiguration.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/staticapi/StaticAPIRefreshController.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/staticapi/StaticAPIRefreshControllerExceptionHandler.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/staticapi/StaticAPIResponse.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/staticapi/StaticAPIService.java
  api-catalog-services/src/main/resources/apicatalog-log-messages.yml
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/staticapi/StaticAPIRefreshControllerTest.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/staticapi/StaticAPIServiceTest.java
  discovery-service/src/main/resources/application.yml
  integration-tests/README.md
  integration-tests/src/test/java/org/zowe/apiml/apicatalog/ApiCatalogEndpointIntegrationTest.java
Labels: passed CA tests

#660 Add actions, envs and reducers for the refresh functionality
  api-catalog-ui/frontend/.env.test
  api-catalog-ui/frontend/src/actions/refresh-static-apis-actions.jsx
  api-catalog-ui/frontend/src/actions/refresh-static-apis-actions.test.jsx
  api-catalog-ui/frontend/src/constants/refresh-static-apis-constants.jsx
  api-catalog-ui/frontend/src/error-messages.json
  api-catalog-ui/frontend/src/reducers/fetch-tile-reducer.test.jsx
  api-catalog-ui/frontend/src/reducers/index.jsx
  api-catalog-ui/frontend/src/reducers/refresh-static-apis-reducer.jsx
  api-catalog-ui/frontend/src/reducers/refresh-static-apis-reducer.test.jsx
Labels: passed CA tests, ready for CA testing, size/L

#662 Add remaining react components for the refresh func
  api-catalog-ui/frontend/README.md
  api-catalog-ui/frontend/cypress/integration/e2e/dashboard/dashboard.test.js
  api-catalog-ui/frontend/src/components/Dashboard/Dashboard.css
  api-catalog-ui/frontend/src/components/Dashboard/Dashboard.jsx
  api-catalog-ui/frontend/src/components/Dashboard/DashboardContainer.jsx
Labels: passed CA tests, size/M

#661 fix order of fetching JWT from request
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/AuthenticationService.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/AuthenticationServiceTest.java
Labels: passed CA tests

#663 UI refactoring
  api-catalog-ui/frontend/src/components/Dashboard/Dashboard.jsx
  api-catalog-ui/frontend/src/components/Error/ErrorDialog.jsx
  api-catalog-ui/frontend/src/components/Error/ErrorDialog.test.jsx
Labels: passed CA tests, size/L

#667 Rip/us644826/revisit zowe apiml contrib guideline
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
  CONTRIBUTING.md
  README.md
  apiml-security-common/README.md
  config/local/api-defs/README.md
  discoverable-client/README.md
  docker/README.md
  docs/architecture/decisions/0001-record-architecture-decisions.md
  docs/architecture/decisions/0002-target-platform-and-supported-runtimes.md
  docs/architecture/decisions/0003-discovery-of-externally-accessible-url-of-api-gateway.md
  docs/architecture/decisions/0004-configuration-of-LatencyUtils-to-reduce-cpu-time-used
  docs/architecture/decisions/README.md
  docs/ciphers.md
  docs/conformance.md
  docs/manual_tests.md
  docs/release.md
  docs/static-apis.md
  docs/vscode-setup.md
  docs/websockets.md
  integration-enabler-spring-v1-sample-app/README.md
  onboarding-enabler-java-sample-app/README.md
  package.json
  scripts/README.md
  scripts/apiml_cm.test.js
  security-service-client-spring/README.md
Labels: passed CA tests, size/XL

#670 rip/US644826/contributing.md update
  CONTRIBUTING.md
Labels: size/L

#671 US644826/readme.md update
  README.md
Labels: passed CA tests, size/L

#678 Hotfixes for the 1.12 release
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/staticapi/StaticAPIService.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/staticapi/StaticAPIServiceTest.java
  gateway-service/src/main/resources/application.yml
Labels: passed CA tests
