Repository zowe/api-layer, pull requests merged in 2020-11, with the labels that each got.

#908 trap int signal in start script
  zowe-install/src/main/resources/component-scripts/start.sh
Labels: passed CA tests, size/S

#911 Add another configurable SSL port
  config/local/gateway-service.yml
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/TomcatConfiguration.java
  gateway-service/src/main/resources/application.yml
  gateway-service/src/test/resources/application-test.yml
  gateway-service/src/test/resources/application.yml
  integration-tests/src/test/java/org/zowe/apiml/apicatalog/ApiCatalogEndpointIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/PageRedirectionTest.java
  integration-tests/src/test/java/org/zowe/apiml/util/config/ConfigReader.java
  integration-tests/src/test/java/org/zowe/apiml/util/config/GatewayServiceConfiguration.java
  integration-tests/src/test/resources/environment-configuration.yml
Labels: passed CA tests

#913 Internal connector integration tests
  Jenkinsfile
  build.gradle
  integration-tests/build.gradle
Labels: size/S, under CA testing

#914 Add system property for spring profiles
  zowe-install/src/main/resources/component-scripts/start.sh
Labels: passed CA tests, size/XS

#916 revert the zowe variable for enabling x509
  zowe-install/src/main/resources/component-scripts/start.sh
Labels: size/XS, under CA testing

#920 Apiml/gh844/catalog versions ui coverage update
  api-catalog-ui/frontend/src/components/ServiceTab/ServiceTab.jsx
  api-catalog-ui/frontend/src/components/ServiceTab/ServiceTab.test.jsx
Labels: passed CA tests, size/M

#917 Mention the key changes in the 1.17 release
  CHANGELOG.md
Labels: passed CA tests, size/XS

#921 x509 zowe resilient feature flag
  zowe-install/src/main/resources/component-scripts/start.sh
Labels: size/XS

#919 Remove the script pushing the labels
  Jenkinsfile
Labels: size/S, under CA testing

#922 refactor 1.17 changelog feature description
  CHANGELOG.md
Labels: size/XS, under CA testing

#924 Correct zowe debug flag
  zowe-install/src/main/resources/component-scripts/start.sh
Labels: size/XS

#918 Allow storing the logs within the log files.
  apiml-common/src/main/resources/logback.xml
  apiml-utility/src/main/java/org/zowe/apiml/product/logging/ApimlRollingFileAppender.java
  apiml-utility/src/test/java/org/zowe/apiml/product/logging/ApimlRollingFileAppenderTest.java
  zowe-install/src/main/resources/component-scripts/start.sh
Labels: under CA testing

#926 Run Caching Service integration tests on MF
  integration-tests/src/test/java/org/zowe/apiml/cachingservice/CachingApiIntegrationTest.java
Labels: under CA testing

#927 Carsoncook/gh862/componentize start
  zowe-install/src/main/resources/component-scripts/setup.sh
  zowe-install/src/main/resources/component-scripts/start-cache.sh
  zowe-install/src/main/resources/component-scripts/start-catalog.sh
  zowe-install/src/main/resources/component-scripts/start-discovery.sh
  zowe-install/src/main/resources/component-scripts/start-gateway.sh
  zowe-install/src/main/resources/component-scripts/start.sh
Labels: size/L, under CA testing

#928 Fix componentized start
  zowe-install/build.gradle
Labels: size/S, under CA testing

#929 publish discoverable-client for performance test
  gradle/publish.gradle
Labels: size/XS, under CA testing

#930 caching api concurrent integration test
  caching-service/src/main/java/org/zowe/apiml/caching/service/inmemory/InMemoryStorage.java
  integration-tests/src/test/java/org/zowe/apiml/cachingservice/CachingApiIntegrationTest.java
Labels: under CA testing

#932 As an internal port I want to present myself with internal key.
  config/local/gateway-service.yml
  keystore/localhost/localhost-multi.truststore.p12
  keystore/localhost/localhost.truststore.p12
Labels: under CA testing

#936 Update the default username and password in the documentation
  README.md
Labels: size/XS

#937 Clean potential resource leaks
  mock-zosmf/src/main/java/org/zowe/apiml/client/api/AuthenticationController.java
  zaas-client/src/main/java/org/zowe/apiml/zaasclient/service/internal/ZaasHttpsClientProvider.java
Labels: under CA testing

#938 Replace master in the name of key with primary
  common-service-core/src/test/java/org/zowe/apiml/util/MapUtilsTest.java
Labels: under CA testing

#940 Dependencies update for jdk11 compatibility
  gradle/versions.gradle
  onboarding-enabler-java/build.gradle
  zaas-client/build.gradle
Labels: size/S, under CA testing

#941 Remove risk around the concurrent access to Map created after constructor
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/auth/AuthenticationScheme.java
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/auth/AuthenticationSchemes.java
  apiml-security-common/src/test/java/org/zowe/apiml/security/common/auth/AuthenticationSchemesTest.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/ServiceAuthenticationServiceImpl.java
Labels: under CA testing

#942 eureka client configuration
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/GatewayConfig.java
  gateway-service/src/main/resources/application.yml
  gateway-service/src/test/java/org/zowe/apiml/acceptance/common/AcceptanceTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/config/GatewayConfigTest.java
Labels: under CA testing

#935 Zaas client enhancements
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/config/AuthConfigurationProperties.java
  caching-service/src/main/java/org/zowe/apiml/caching/api/CachingController.java
  caching-service/src/test/java/org/zowe/apiml/caching/api/CachingControllerTest.java
  common-service-core/src/main/java/org/zowe/apiml/constants/ApimlConstants.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/AuthenticationService.java
  zaas-client/README.md
  zaas-client/build.gradle
  zaas-client/src/main/java/org/zowe/apiml/zaasclient/service/ZaasClient.java
  zaas-client/src/main/java/org/zowe/apiml/zaasclient/service/internal/TokenService.java
  zaas-client/src/main/java/org/zowe/apiml/zaasclient/service/internal/ZaasClientImpl.java
  zaas-client/src/main/java/org/zowe/apiml/zaasclient/service/internal/ZaasJwtService.java
  zaas-client/src/test/java/org/zowe/apiml/zaasclient/service/internal/ZaasJwtServiceTest.java
Labels: under CA testing

#945 Rip/ac/connector address
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/TomcatConfiguration.java
Labels: under CA testing

#946 Rip/ac/connector default conf
  config/local/gateway-service.yml
  gateway-service/src/main/resources/application.yml
Labels: size/S, under CA testing

#949 Proxy mechanism enhancements
  common-service-core/src/main/java/org/zowe/apiml/util/ClassOrDefaultProxyUtils.java
  common-service-core/src/test/java/org/zowe/apiml/util/ClassOrDefaultProxyUtilsTest.java
Labels: under CA testing

#948 Improve readability of the startup checker
  integration-tests/src/test/java/org/zowe/apiml/startup/impl/ApiMediationLayerStartupChecker.java
  integration-tests/src/test/java/org/zowe/apiml/util/config/ConfigReader.java
  integration-tests/src/test/java/org/zowe/apiml/util/config/GatewayServiceConfiguration.java
  integration-tests/src/test/java/org/zowe/apiml/util/http/HttpRequestUtils.java
  integration-tests/src/test/resources/environment-configuration.yml
  integration-tests/src/test/resources/logback.xml
Labels: under CA testing

#953 Upgrade dependencies
  api-catalog-services/build.gradle
  apiml-common/src/main/java/org/zowe/apiml/product/web/HttpConfig.java
  discovery-service/build.gradle
  gateway-service/build.gradle
  gateway-service/src/main/java/org/zowe/apiml/gateway/ws/ServletSslContextFactoryProvider.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/ws/SslContextFactoryProvider.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/ws/WebSocketProxyServerHandler.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/ws/WebSocketRoutedSession.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/ws/WebSocketRoutedSessionFactory.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/ws/WebSocketRoutedSessionFactoryImpl.java
  gradle/versions.gradle
  integration-tests/src/test/java/org/zowe/apiml/ws/WebSocketProxyTest.java
Labels: under CA testing

#925 Enable Caching service deployment
  zowe-install/build.gradle
  zowe-install/src/main/resources/component-scripts/start-cache.sh
  zowe-install/src/main/resources/component-scripts/start.sh
Labels: size/S, under CA testing

#951 Vsam config and helpers
  caching-service/build.gradle
  caching-service/src/main/java/org/zowe/apiml/caching/config/VsamConfig.java
  caching-service/src/main/java/org/zowe/apiml/caching/model/KeyValue.java
  caching-service/src/main/java/org/zowe/apiml/caching/service/vsam/VsamKey.java
  caching-service/src/main/java/org/zowe/apiml/caching/service/vsam/VsamRecord.java
  caching-service/src/main/java/org/zowe/apiml/caching/service/vsam/VsamRecordException.java
  caching-service/src/test/java/org/zowe/apiml/caching/service/vsam/VsamKeyTest.java
  caching-service/src/test/java/org/zowe/apiml/caching/service/vsam/VsamRecordTest.java
Labels: under CA testing

#954 Enhance versioning shown in API Catalog
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/services/status/APIDocRetrievalService.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/services/status/LocalApiDocServiceTest.java
  api-catalog-ui/frontend/src/components/ServiceTab/ServiceTab.jsx
Labels: under CA testing

#939 PoC packing
  .gitignore
  api-catalog-package/build.gradle
  api-catalog-package/src/main/resources/assets/api-catalog.png
  api-catalog-package/src/main/resources/bin/configure.sh
  api-catalog-package/src/main/resources/bin/start.sh
  api-catalog-package/src/main/resources/bin/validate.sh
  api-catalog-package/src/main/resources/manifest.yaml
  caching-service-package/build.gradle
  caching-service-package/src/main/resources/bin/configure.sh
  caching-service-package/src/main/resources/bin/start.sh
  caching-service-package/src/main/resources/bin/validate.sh
  caching-service-package/src/main/resources/manifest.yaml
  discovery-package/build.gradle
  discovery-package/src/main/resources/bin/configure.sh
  discovery-package/src/main/resources/bin/start.sh
  discovery-package/src/main/resources/bin/validate.sh
  discovery-package/src/main/resources/manifest.yaml
  gateway-package/build.gradle
  gateway-package/src/main/resources/bin/configure.sh
  gateway-package/src/main/resources/bin/start.sh
  gateway-package/src/main/resources/bin/validate.sh
  gateway-package/src/main/resources/manifest.yaml
  gradle/license.gradle
  gradle/publish.gradle
  gradle/sonar.gradle
  settings.gradle
  zowe-install/src/main/resources/component-scripts/start.sh
Labels: size/L, under CA testing

#956 Vsam storage implementation
  caching-service/src/main/java/org/zowe/apiml/caching/config/StorageConfiguration.java
  caching-service/src/main/java/org/zowe/apiml/caching/service/vsam/VsamFile.java
  caching-service/src/main/java/org/zowe/apiml/caching/service/vsam/VsamStorage.java
Labels: under CA testing

#957 Jordan cain/gh923/api version comparing
  api-catalog-services/build.gradle
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/controllers/api/CatalogApiDocController.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/services/status/APIServiceStatusService.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/services/status/OpenApiCompareProducer.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/services/status/model/ApiDiffNotAvailableException.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/controllers/api/CatalogApiDocControllerTest.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/services/status/ApiServiceStatusServiceTest.java
  api-catalog-ui/frontend/cypress/integration/e2e/detail-page/detail-page.test.js
  api-catalog-ui/frontend/cypress/integration/e2e/detail-page/service-version-compare.test.js
  api-catalog-ui/frontend/cypress/integration/e2e/detail-page/service-version-switch.test.js
  api-catalog-ui/frontend/src/actions/service-version-diff-actions.jsx
  api-catalog-ui/frontend/src/components/ServiceTab/ServiceTab.jsx
  api-catalog-ui/frontend/src/components/ServiceTab/ServiceTab.test.jsx
  api-catalog-ui/frontend/src/components/ServiceVersionDiff/ServiceVersionDiff.css
  api-catalog-ui/frontend/src/components/ServiceVersionDiff/ServiceVersionDiff.jsx
  api-catalog-ui/frontend/src/components/ServiceVersionDiff/ServiceVersionDiff.test.jsx
  api-catalog-ui/frontend/src/components/ServiceVersionDiff/ServiceVersionDiffContainer.jsx
  api-catalog-ui/frontend/src/reducers/index.jsx
  api-catalog-ui/frontend/src/reducers/service-version-diff-reducer.jsx
  api-catalog-ui/frontend/src/reducers/service-version-diff-reducer.test.jsx
  gradle/versions.gradle
  integration-tests/src/test/java/org/zowe/apiml/apicatalog/ApiCatalogEndpointIntegrationTest.java
Labels: under CA testing

#962 assert content of span
  api-catalog-ui/frontend/cypress/integration/e2e/detail-page/service-version-compare.test.js
Labels: size/XS
