Repository zowe/api-layer, pull requests merged in 2021-05, with the labels that each got.

#1431 chore: Remove feature which will be available in 1.22
  CHANGELOG.md
Labels: size/XS

#1433 refactor: Move web starter to compile only dependencies.
  apiml-utility/build.gradle
Labels: size/XS

#1436 refactor: Identify and mark security related PRs
  .github/workflows/security-analysis.yml
  scripts/security_sensitive/index.js
  scripts/security_sensitive/package.json
Labels: Sensitive, size/M

#1437 chore: Remove unused code
  scripts/README.md
  scripts/publish_and_release.sh
Labels: size/S

#1438 chore: Automate docgen generation
  .github/workflows/docs.yml
  docs/docgen/Docgen-1.0.jar
  gateway-service/src/main/resources/gateway-log-messages.yml
  scripts/docs/index.js
  scripts/docs/package.json
  zaas-client/src/main/resources/zaas-client-log-messages.yml
Labels: docs

#1443 chore: Calculate GH related stats
  .github/workflows/statistics.yml
  scripts/statistics/ci.js
  scripts/statistics/index.js
  scripts/statistics/issues.js
  scripts/statistics/package.json
  scripts/statistics/pullRequests.js
Labels: size/L

#1442 fix: configurable jwt alias at startup
  gateway-package/src/main/resources/bin/start.sh
Labels: size/XS

#1445 fix: change name of main class
  certificate-analyser/build.gradle
Labels: size/XS

#1448 refactor error code messages
  api-catalog-services/src/main/resources/apicatalog-log-messages.yml
  apiml-security-common/src/main/resources/security-common-log-messages.yml
  common-service-core/src/main/resources/core-log-messages.yml
  gateway-service/src/test/resources/gateway-messages.yml
  scripts/docs/index.js
  zaas-client/src/main/resources/zaas-client-log-messages.yml
Labels: Sensitive, docs, size/M

#1456 chore: Adjust testing guidelines
  CONTRIBUTING.md
Labels: size/XS

#1463 Allow customised SSO in Catalog
  api-catalog-ui/frontend/src/actions/user-actions.jsx
  api-catalog-ui/frontend/src/epics/fetch-tiles.jsx
  api-catalog-ui/frontend/src/services/user.service.jsx
Labels: size/XS

#1466 fix: Fix npm vulnerabilities
  api-catalog-ui/frontend/package-lock.json
  api-catalog-ui/frontend/package.json
  package-lock.json
Labels: size/XS

#1473 Change the registration to use the correct hostname in instanceId
  api-catalog-services/src/main/resources/application.yml
  discovery-service/src/main/resources/application.yml
Labels: size/XS

#1472 Remove the need to release from master branch
  build.gradle
  docs/release.md
Labels: size/M

#1471 feat: change pass via saf
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/login/LoginFilter.java
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/login/LoginRequest.java
  apiml-security-common/src/test/java/org/zowe/apiml/security/common/login/LoginFilterTest.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/saf/MockPlatformUser.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/saf/PlatformUser.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/saf/SafPlatformUser.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/saf/ZosAuthenticationProvider.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/zosmf/AbstractZosmfService.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/login/saf/MockPlatformUserTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/login/saf/SafPlatformUserTests.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/login/saf/ZosAuthenticationProviderTests.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/zosmf/ZosmfServiceTest.java
  security-service-client-spring/src/main/java/org/zowe/apiml/security/client/login/GatewayLoginProvider.java
  security-service-client-spring/src/test/java/org/zowe/apiml/security/client/login/GatewayLoginProviderTest.java
Labels: Sensitive

#1474 chore: reflect changes from start.sh
  config/zowe-api-dev/alternative_start.sh
  config/zowe-api-dev/run-wrapper.sh
Labels: size/M

#1475 Use the apiml.service.id the same way as in other services.
  api-catalog-services/src/main/resources/application.yml
Labels: size/XS

#1487 fix: npm multi startup
  config/local-multi/discovery-service-1.yml
  config/local-multi/discovery-service-2.yml
  config/local-multi/gateway-service-1.yml
  config/local-multi/gateway-service-2.yml
  package.json
Labels: size/S

#1499 chore: Add license header to jsx/js files
  api-catalog-ui/frontend/src/actions/catalog-tile-actions.jsx
  api-catalog-ui/frontend/src/actions/catalog-tile-actions.test.jsx
  api-catalog-ui/frontend/src/actions/error-actions.jsx
  api-catalog-ui/frontend/src/actions/error-actions.test.jsx
  api-catalog-ui/frontend/src/actions/filter-actions.jsx
  api-catalog-ui/frontend/src/actions/filter-actions.test.jsx
  api-catalog-ui/frontend/src/actions/refresh-static-apis-actions.jsx
  api-catalog-ui/frontend/src/actions/refresh-static-apis-actions.test.jsx
  api-catalog-ui/frontend/src/actions/selected-service-actions.jsx
  api-catalog-ui/frontend/src/actions/selected-service-actions.test.jsx
  api-catalog-ui/frontend/src/actions/service-version-diff-actions.jsx
  api-catalog-ui/frontend/src/actions/user-actions.jsx
  api-catalog-ui/frontend/src/constants/catalog-tile-constants.jsx
  api-catalog-ui/frontend/src/constants/error-constants.jsx
  api-catalog-ui/frontend/src/constants/filter-constants.jsx
  api-catalog-ui/frontend/src/constants/refresh-static-apis-constants.jsx
  api-catalog-ui/frontend/src/constants/selected-service-constants.jsx
  api-catalog-ui/frontend/src/constants/user-constants.jsx
  api-catalog-ui/frontend/src/epics/fetch-tiles-epic.test.jsx
  api-catalog-ui/frontend/src/epics/fetch-tiles.jsx
  api-catalog-ui/frontend/src/epics/index.jsx
  api-catalog-ui/frontend/src/helpers/history.jsx
  api-catalog-ui/frontend/src/index.js
  api-catalog-ui/frontend/src/reducers/authentication-reducer.jsx
  api-catalog-ui/frontend/src/reducers/authentication-reducer.test.jsx
  api-catalog-ui/frontend/src/reducers/error-reducer.jsx
  api-catalog-ui/frontend/src/reducers/error-reducer.test.jsx
  api-catalog-ui/frontend/src/reducers/fetch-tile-reducer.jsx
  api-catalog-ui/frontend/src/reducers/fetch-tile-reducer.test.jsx
  api-catalog-ui/frontend/src/reducers/filter-reducer.jsx
  api-catalog-ui/frontend/src/reducers/filter-reducer.test.jsx
  api-catalog-ui/frontend/src/reducers/index.jsx
  api-catalog-ui/frontend/src/reducers/loading-reducer.jsx
  api-catalog-ui/frontend/src/reducers/loading-reducer.test.jsx
  api-catalog-ui/frontend/src/reducers/refresh-static-apis-reducer.jsx
  api-catalog-ui/frontend/src/reducers/refresh-static-apis-reducer.test.jsx
  api-catalog-ui/frontend/src/reducers/selected-service-reducer.jsx
  api-catalog-ui/frontend/src/reducers/selected-service-reducer.test.jsx
  api-catalog-ui/frontend/src/reducers/service-version-diff-reducer.jsx
  api-catalog-ui/frontend/src/reducers/service-version-diff-reducer.test.jsx
  api-catalog-ui/frontend/src/selectors/selectors.jsx
  api-catalog-ui/frontend/src/selectors/selectors.test.jsx
  api-catalog-ui/frontend/src/services/index.jsx
  api-catalog-ui/frontend/src/services/user.service.jsx
  api-catalog-ui/frontend/src/services/user.service.test.jsx
  api-catalog-ui/frontend/src/setupTests.js
Labels: size/L
