Repository zowe/api-layer, pull requests merged in 2021-08, with the labels that each got.

#1657 feat: Wizard categories allow multiple configs
  api-catalog-ui/frontend/src/actions/wizard-actions.jsx
  api-catalog-ui/frontend/src/actions/wizard-actions.test.jsx
  api-catalog-ui/frontend/src/components/Wizard/WizardDialog.jsx
  api-catalog-ui/frontend/src/components/Wizard/WizardInputs.jsx
  api-catalog-ui/frontend/src/components/Wizard/WizardInputs.test.jsx
  api-catalog-ui/frontend/src/components/Wizard/WizardInputsContainer.jsx
  api-catalog-ui/frontend/src/components/Wizard/wizard.css
  api-catalog-ui/frontend/src/components/Wizard/wizard_config.jsx
  api-catalog-ui/frontend/src/constants/wizard-constants.jsx
  api-catalog-ui/frontend/src/reducers/wizard-reducer.jsx
  api-catalog-ui/frontend/src/reducers/wizard-reducer.test.jsx
Labels: size/XL

#1672 fix: configure WebSocket cipher suites
  apiml-common/src/main/java/org/zowe/apiml/product/web/HttpConfig.java
Labels: size/S

#1676 fix: Accommodating keystore parameters with spaces
  api-catalog-package/src/main/resources/bin/start.sh
  caching-service-package/src/main/resources/bin/start.sh
  config/zowe-api-dev/alternative_start.sh
  discovery-package/src/main/resources/bin/start.sh
  gateway-package/src/main/resources/bin/start.sh
  metrics-service-package/src/main/resources/bin/start.sh
Labels: size/L

#1662 feat: Conditional full debug logging for apiml common
  apiml-common/build.gradle
  apiml-common/src/main/resources/logback.xml
  gradle/versions.gradle
Labels: size/S

#1677 feat: path to a native java library
  api-catalog-package/src/main/resources/bin/start.sh
  caching-service-package/src/main/resources/bin/start.sh
  discovery-package/src/main/resources/bin/start.sh
  gateway-package/src/main/resources/bin/start.sh
Labels: size/S

#1678 do not include ciphers
  apiml-common/src/main/java/org/zowe/apiml/product/web/HttpConfig.java
Labels: size/S

#1687 refactor: Cleanup before actual implementation
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/AbstractAuthenticationScheme.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/DeterministicUserBasedRoutingTest.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/common/AcceptanceTestWithBasePath.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/corsTests/GatewaySpecificEndpointsCorsDisabledTest.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/requests/SecurityRequests.java
Labels: size/M, Sensitive

#1688 feat: Support SAF IDT as authentication scheme
  common-service-core/src/main/java/org/zowe/apiml/auth/Authentication.java
  common-service-core/src/main/java/org/zowe/apiml/auth/AuthenticationScheme.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/SafAuthenticationService.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/SafIdtScheme.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/DeterministicUserBasedRoutingTest.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/SafIdtSchemeTest.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/netflix/ApplicationRegistry.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/SafIdtSchemeTest.java
Labels: size/L, Sensitive

#1680 feat: Spring Enabler configuration
  api-catalog-ui/frontend/.eslintrc
  api-catalog-ui/frontend/src/components/Wizard/WizardDialog.jsx
  api-catalog-ui/frontend/src/components/Wizard/wizard_config.jsx
  api-catalog-ui/frontend/src/components/Wizard/wizard_defaults.jsx
  api-catalog-ui/frontend/src/reducers/wizard-reducer.jsx
  api-catalog-ui/frontend/src/reducers/wizard-reducer.test.jsx
Labels: size/L

#1686 feat: Wizard Static Onboarding
  api-catalog-ui/frontend/src/actions/wizard-actions.jsx
  api-catalog-ui/frontend/src/actions/wizard-actions.test.jsx
  api-catalog-ui/frontend/src/components/Wizard/YAMLVisualizer.jsx
  api-catalog-ui/frontend/src/components/Wizard/YAMLVisualizer.test.jsx
  api-catalog-ui/frontend/src/components/Wizard/wizard_config.jsx
Labels: size/L

#1689 fix: prevent API ML run with unsecure connection
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/security/SecurityConfiguration.java
  apiml-tomcat-common/src/main/java/org/zowe/apiml/filter/AttlsFilter.java
  apiml-tomcat-common/src/main/java/org/zowe/apiml/filter/SecureConnectionFilter.java
  apiml-tomcat-common/src/test/java/org/zowe/apiml/filter/AttlsFilterTest.java
  apiml-tomcat-common/src/test/java/org/zowe/apiml/filter/SecureConnectionFilterTest.java
  caching-service/src/main/java/org/zowe/apiml/caching/config/SpringSecurityConfig.java
  discovery-service/src/main/java/org/zowe/apiml/discovery/config/HttpsWebSecurityConfig.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/config/NewSecurityConfiguration.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/config/SecurityConfiguration.java
  gradle/versions.gradle
Labels: size/L, Sensitive

#1693 chore: Fix npm vulnerabilities
  api-catalog-ui/frontend/package-lock.json
  api-catalog-ui/frontend/package.json
  package-lock.json
Labels: size/XS

#1692 feat: introduce error codes for saf authentication
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/error/AuthExceptionHandler.java
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/error/PlatformPwdErrno.java
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/error/ZosAuthenticationException.java
  apiml-security-common/src/main/resources/security-common-log-messages.yml
  apiml-security-common/src/test/java/org/zowe/apiml/security/common/error/AuthExceptionHandlerTest.java
  apiml-security-common/src/test/java/org/zowe/apiml/security/common/error/ZosAuthenticationExceptionTest.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/saf/MockPlatformUser.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/saf/ZosAuthenticationException.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/saf/ZosAuthenticationProvider.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/login/saf/MockPlatformUserTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/login/saf/ZosAuthenticationProviderTests.java
Labels: size/L, Sensitive

#1697 fix: add stomp v1.2 as supported protocol
  apiml-common/src/main/java/org/zowe/apiml/product/web/HttpConfig.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/ws/ServletSslContextFactoryProvider.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/ws/SslContextFactoryProvider.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/ws/WebSocketClientFactory.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/ws/WebSocketProxyServerHandler.java
  gateway-service/src/main/resources/application.yml
  gateway-service/src/test/java/org/zowe/apiml/gateway/ws/WebSocketProxyServerHandlerTest.java
Labels: size/L

#1699 fix: udpate npm in actions
  .github/workflows/release.yml
  .github/workflows/snapshot-release.yml
  .github/workflows/specific-release.yml
  gradle.properties
  onboarding-enabler-nodejs/package.json
Labels: size/XS

#1694 refactor: Wizard refactoring
  api-catalog-ui/frontend/src/actions/wizard-actions.jsx
  api-catalog-ui/frontend/src/actions/wizard-actions.test.jsx
  api-catalog-ui/frontend/src/components/Dashboard/Dashboard.jsx
  api-catalog-ui/frontend/src/components/Dashboard/Dashboard.test.jsx
  api-catalog-ui/frontend/src/components/Wizard/WizardComponents/WizardInputs.jsx
  api-catalog-ui/frontend/src/components/Wizard/WizardComponents/WizardInputs.test.jsx
  api-catalog-ui/frontend/src/components/Wizard/WizardComponents/WizardInputsContainer.jsx
  api-catalog-ui/frontend/src/components/Wizard/WizardComponents/WizardNavigation.jsx
  api-catalog-ui/frontend/src/components/Wizard/WizardComponents/WizardNavigation.test.jsx
  api-catalog-ui/frontend/src/components/Wizard/WizardComponents/WizardNavigationContainer.jsx
  api-catalog-ui/frontend/src/components/Wizard/WizardContainer.jsx
  api-catalog-ui/frontend/src/components/Wizard/WizardDialog.jsx
  api-catalog-ui/frontend/src/components/Wizard/WizardDialog.test.jsx
  api-catalog-ui/frontend/src/components/Wizard/WizardNavigation.jsx
  api-catalog-ui/frontend/src/components/Wizard/YAML/YAMLVisualizer.jsx
  api-catalog-ui/frontend/src/components/Wizard/YAML/YAMLVisualizer.test.jsx
  api-catalog-ui/frontend/src/components/Wizard/YAML/YAMLVisualizerContainer.jsx
  api-catalog-ui/frontend/src/components/Wizard/configs/wizard_categories.jsx
  api-catalog-ui/frontend/src/components/Wizard/configs/wizard_defaults.jsx
  api-catalog-ui/frontend/src/components/Wizard/configs/wizard_onboarding_methods.jsx
  api-catalog-ui/frontend/src/constants/wizard-constants.jsx
  api-catalog-ui/frontend/src/reducers/wizard-reducer.jsx
  api-catalog-ui/frontend/src/reducers/wizard-reducer.test.jsx
Labels: size/XL

#1701 fix: Correctly handle ws connections for new path pattern
  gateway-service/src/main/java/org/zowe/apiml/gateway/ws/GatewayWebSocketConfigurer.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/ws/WebSocketProxyServerHandler.java
  gateway-service/src/main/resources/application.yml
  gateway-service/src/test/java/org/zowe/apiml/gateway/ws/WebSocketProxyServerHandlerTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/proxy/WebSocketProxyTest.java
Labels: size/L

#1703 chore: zowe-api-dev update
  config/zowe-api-dev/alternative_start.sh
  config/zowe-api-dev/run-wrapper.sh
Labels: size/L

#1706 chore: Create HA tests for API Catalog
  .github/workflows/containers.yml
  docker/nginx/conf/load-balancer.conf
  integration-tests/src/test/java/org/zowe/apiml/integration/ha/ApiCatalogMultipleInstancesTest.java
  integration-tests/src/test/java/org/zowe/apiml/util/config/ApiCatalogServiceConfiguration.java
  integration-tests/src/test/java/org/zowe/apiml/util/config/ConfigReader.java
  integration-tests/src/test/java/org/zowe/apiml/util/config/DiscoverableClientConfiguration.java
  integration-tests/src/test/java/org/zowe/apiml/util/requests/ApiCatalogRequests.java
  integration-tests/src/test/java/org/zowe/apiml/util/requests/Apps.java
  integration-tests/src/test/java/org/zowe/apiml/util/requests/ha/HAApiCatalogRequests.java
  integration-tests/src/test/resources/environment-configuration-attls.yml
  integration-tests/src/test/resources/environment-configuration-docker.yml
  integration-tests/src/test/resources/environment-configuration-ha.yml
  integration-tests/src/test/resources/environment-configuration.yml
Labels: size/L

#1714 feat: Introduce rest provider for SAF tokens
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/saf/SafIdtProvider.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/saf/SafProviderBeansConfig.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/saf/SafRestAuthenticationService.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/SafIdtScheme.java
  gateway-service/src/main/resources/application.yml
  gateway-service/src/test/java/org/zowe/apiml/acceptance/DeterministicUserBasedRoutingTest.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/SafIdtSchemeTest.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/netflix/ApplicationRegistry.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/saf/SafRestAuthenticationServiceTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/SafIdtSchemeTest.java
  gateway-service/src/test/resources/application-test.yml
  gateway-service/src/test/resources/application.yml
  mock-zosmf/README.md
  mock-zosmf/src/main/java/org/zowe/apiml/MockServicesApplication.java
  mock-zosmf/src/main/java/org/zowe/apiml/zss/api/SafIdtController.java
  mock-zosmf/src/main/java/org/zowe/apiml/zss/model/Authentication.java
  mock-zosmf/src/main/java/org/zowe/apiml/zss/model/Token.java
  mock-zosmf/src/main/java/org/zowe/apiml/zss/services/SafIdtProvider.java
  mock-zosmf/src/test/java/org/zowe/apiml/zss/api/SafIdtControllerTest.java
  mock-zosmf/src/test/java/org/zowe/apiml/zss/services/SafIdtProviderTest.java
Labels: size/XL, Sensitive

#1715 fix: Add remove null from packaged service files
  api-catalog-package/build.gradle
  apiml-common-lib-package/build.gradle
  caching-service-package/build.gradle
  discovery-package/build.gradle
  gateway-package/build.gradle
  metrics-service-package/build.gradle
Labels: size/S

#1719 feat: Refresh endpoint for prolonging valid JWT token
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/config/AuthConfigurationProperties.java
  config/docker/gateway-service.yml
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/config/NewSecurityConfiguration.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/refresh/SuccessfulRefreshHandler.java
  gateway-service/src/main/resources/application.yml
  gateway-service/src/main/resources/gateway-api-doc.json
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/refresh/SuccessfulRefreshHandlerTest.java
  gateway-service/src/test/resources/application-test.yml
  gateway-service/src/test/resources/application.yml
  integration-tests/src/test/java/org/zowe/apiml/integration/authentication/providers/RefreshTest.java
Labels: size/L, Sensitive

#1721 chore: Add Integration test for SAF IDT scheme
  config/docker/api-defs/staticclient.yml
  config/docker/gateway-service.yml
  config/local/api-defs-http/staticclient.yml
  config/local/api-defs/staticclient.yml
  config/local/gateway-service.yml
  integration-tests/src/test/java/org/zowe/apiml/integration/authentication/schemes/SafIdtSchemeTest.java
  integration-tests/src/test/java/org/zowe/apiml/util/requests/GatewayRequests.java
  integration-tests/src/test/java/org/zowe/apiml/util/requests/Requests.java
Labels: size/L

#1711 chore: Add Chaotic tests for southbound service + Websocket tests
  .github/workflows/containers.yml
  discoverable-client/src/main/resources/application.yml
  integration-tests/src/test/java/org/zowe/apiml/integration/ha/SouthboundServiceChaoticTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/ha/SouthboundServiceMultipleInstancesTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/ha/WebSocketChaoticTest.java
  integration-tests/src/test/java/org/zowe/apiml/util/config/ConfigReader.java
  integration-tests/src/test/java/org/zowe/apiml/util/config/DiscoverableClientConfiguration.java
  integration-tests/src/test/java/org/zowe/apiml/util/requests/DiscoverableClientRequests.java
  integration-tests/src/test/java/org/zowe/apiml/util/requests/GatewayRequests.java
  integration-tests/src/test/java/org/zowe/apiml/util/requests/ha/HADiscoverableClientRequests.java
  integration-tests/src/test/java/org/zowe/apiml/util/requests/ha/HAGatewayRequests.java
  integration-tests/src/test/resources/environment-configuration-attls.yml
  integration-tests/src/test/resources/environment-configuration-docker.yml
  integration-tests/src/test/resources/environment-configuration-ha.yml
  integration-tests/src/test/resources/environment-configuration.yml
Labels: size/XL

#1708 feat: Wizard data validation
  api-catalog-ui/frontend/src/actions/wizard-actions.jsx
  api-catalog-ui/frontend/src/actions/wizard-actions.test.jsx
  api-catalog-ui/frontend/src/components/Wizard/WizardComponents/WizardInputs.jsx
  api-catalog-ui/frontend/src/components/Wizard/WizardComponents/WizardInputs.test.jsx
  api-catalog-ui/frontend/src/components/Wizard/WizardComponents/WizardInputsContainer.jsx
  api-catalog-ui/frontend/src/components/Wizard/WizardComponents/WizardNavigation.jsx
  api-catalog-ui/frontend/src/components/Wizard/WizardComponents/WizardNavigation.test.jsx
  api-catalog-ui/frontend/src/components/Wizard/WizardComponents/WizardNavigationContainer.jsx
  api-catalog-ui/frontend/src/components/Wizard/WizardContainer.jsx
  api-catalog-ui/frontend/src/components/Wizard/WizardDialog.jsx
  api-catalog-ui/frontend/src/components/Wizard/WizardDialog.test.jsx
  api-catalog-ui/frontend/src/components/Wizard/configs/wizard_categories.jsx
  api-catalog-ui/frontend/src/components/Wizard/wizard.css
  api-catalog-ui/frontend/src/constants/wizard-constants.jsx
  api-catalog-ui/frontend/src/reducers/wizard-reducer.jsx
  api-catalog-ui/frontend/src/reducers/wizard-reducer.test.jsx
Labels: size/XXL

#1720 refactor: Streamline category's content - Wizard Dialog
  api-catalog-ui/frontend/src/actions/wizard-actions.jsx
  api-catalog-ui/frontend/src/actions/wizard-actions.test.jsx
  api-catalog-ui/frontend/src/components/Wizard/WizardComponents/WizardInputs.jsx
  api-catalog-ui/frontend/src/components/Wizard/WizardComponents/WizardInputs.test.jsx
  api-catalog-ui/frontend/src/reducers/wizard-reducer.jsx
  api-catalog-ui/frontend/src/reducers/wizard-reducer.test.jsx
Labels: size/XL

#1727 refactor: GH1625 integration test refactor
  gateway-service/src/test/java/org/zowe/apiml/acceptance/RefreshEndpointTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/authentication/providers/RefreshTest.java
  integration-tests/src/test/java/org/zowe/apiml/util/requests/GatewayRequests.java
  integration-tests/src/test/java/org/zowe/apiml/util/requests/JsonResponse.java
  integration-tests/src/test/java/org/zowe/apiml/util/requests/Requests.java
Labels: size/L

#1728 feat: compress response if service wants to
  apiml-tomcat-common/src/main/java/org/zowe/apiml/gzip/GZipResponseException.java
  apiml-tomcat-common/src/main/java/org/zowe/apiml/gzip/GZipResponseUtils.java
  apiml-tomcat-common/src/main/java/org/zowe/apiml/gzip/GZipResponseWrapper.java
  apiml-tomcat-common/src/main/java/org/zowe/apiml/gzip/GZipServletOutputStream.java
  apiml-tomcat-common/src/test/java/org/zowe/apiml/gzip/GZipResponseUtilsTest.java
  apiml-tomcat-common/src/test/java/org/zowe/apiml/gzip/GZipResponseWrapperTest.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/pre/PerServiceGZipFilter.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/CompressPerServiceTest.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/DeterministicUserBasedRoutingTest.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/RequestInstanceTest.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/SafIdtSchemeTest.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/common/AcceptanceTestWithTwoServices.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/netflix/ApplicationRegistry.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/filters/pre/PerServiceGZipFilterTest.java
Labels: size/XL

#1736 chore: Upgrade dependencies for 1.24 release
  .github/workflows/conformant-containers.yml
  .github/workflows/containers.yml
  api-catalog-services/build.gradle
  apiml-common/build.gradle
  apiml-security-common/build.gradle
  apiml-tomcat-common/build.gradle
  apiml-utility/build.gradle
  build.gradle
  caching-service/build.gradle
  common-service-core/build.gradle
  discoverable-client/build.gradle
  discovery-service/build.gradle
  gateway-service/build.gradle
  gradle/versions.gradle
  metrics-service/build.gradle
  mock-zosmf/build.gradle
  onboarding-enabler-micronaut-sample-app/build.gradle
  onboarding-enabler-micronaut/build.gradle
  onboarding-enabler-spring-sample-app/build.gradle
  onboarding-enabler-spring/build.gradle
  security-service-client-spring/build.gradle
  zaas-client/build.gradle
Labels: size/L, Sensitive

#1739 chore: explain override to startup timeout
  gateway-service/src/main/resources/gateway-log-messages.yml
Labels: size/XS

#1731 chore: Zowe Conformant images for all services
  .github/workflows/conformant-containers.yml
  .github/workflows/release.yml
  .github/workflows/snapshot-release.yml
  .github/workflows/specific-release.yml
  api-catalog-package/src/main/resources/bin/start.sh
  caching-service-package/src/main/resources/bin/start.sh
  containers/README.md
  containers/api-catalog-services/Dockerfile
  containers/api-catalog-services/prepare.sh
  containers/caching-service/Dockerfile
  containers/caching-service/prepare.sh
  containers/discovery-service/Dockerfile
  containers/discovery-service/prepare.sh
  containers/gateway-service/Dockerfile
  containers/gateway-service/prepare.sh
  containers/prepare-utils.sh
  containers/prepare.sh
  discovery-package/src/main/resources/bin/start.sh
Labels: size/XL

#1740 refactor: Combine amd64 and s390x image jobs
  .github/workflows/release.yml
  .github/workflows/snapshot-release.yml
  .github/workflows/specific-release.yml
Labels: size/L
