Repository zowe/api-layer, pull requests merged in 2021-11, with the labels that each got.

#1831 Embedded Metrics Dashboard leveraging Netflix Hystrix, Turbine
  gradle/versions.gradle
  metrics-service-ui/frontend/package-lock.json
  metrics-service-ui/frontend/public/hystrix-dashboard/LICENSE-2.0.txt
  metrics-service-ui/frontend/public/hystrix-dashboard/components/hystrixCommand/hystrixCommand.css
  metrics-service-ui/frontend/public/hystrix-dashboard/components/hystrixCommand/hystrixCommand.js
  metrics-service-ui/frontend/public/hystrix-dashboard/components/hystrixCommand/magnifying-glass-icon-20.png
  metrics-service-ui/frontend/public/hystrix-dashboard/components/hystrixCommand/magnifying-glass-icon.png
  metrics-service-ui/frontend/public/hystrix-dashboard/components/hystrixCommand/templates/hystrixCircuit.html
  metrics-service-ui/frontend/public/hystrix-dashboard/components/hystrixCommand/templates/hystrixCircuitContainer.html
  metrics-service-ui/frontend/public/hystrix-dashboard/components/hystrixCommand/templates/hystrixCircuitProperties.html
  metrics-service-ui/frontend/public/hystrix-dashboard/components/hystrixThreadPool/hystrixThreadPool.css
  metrics-service-ui/frontend/public/hystrix-dashboard/components/hystrixThreadPool/hystrixThreadPool.js
  metrics-service-ui/frontend/public/hystrix-dashboard/components/hystrixThreadPool/templates/hystrixThreadPool.html
  metrics-service-ui/frontend/public/hystrix-dashboard/components/hystrixThreadPool/templates/hystrixThreadPoolContainer.html
  metrics-service-ui/frontend/public/hystrix-dashboard/css/global.css
  metrics-service-ui/frontend/public/hystrix-dashboard/css/resets.css
  metrics-service-ui/frontend/public/hystrix-dashboard/css/simplegrid/1236_grid.css
  metrics-service-ui/frontend/public/hystrix-dashboard/css/simplegrid/720_grid.css
  metrics-service-ui/frontend/public/hystrix-dashboard/css/simplegrid/986_grid.css
  metrics-service-ui/frontend/public/hystrix-dashboard/css/simplegrid/LICENSE.txt
  metrics-service-ui/frontend/public/hystrix-dashboard/css/simplegrid/README.txt
  metrics-service-ui/frontend/public/hystrix-dashboard/css/simplegrid/percentage_grid.css
  metrics-service-ui/frontend/public/hystrix-dashboard/images/hystrix-logo-tagline-tiny.png
  metrics-service-ui/frontend/public/hystrix-dashboard/images/hystrix-logo.png
  metrics-service-ui/frontend/public/hystrix-dashboard/js/LICENSE
  metrics-service-ui/frontend/public/hystrix-dashboard/js/d3.v2.min.js
  metrics-service-ui/frontend/public/hystrix-dashboard/js/jquery.min.js
  metrics-service-ui/frontend/public/hystrix-dashboard/js/jquery.tinysort.min.js
  metrics-service-ui/frontend/public/hystrix-dashboard/js/tmpl.js
  metrics-service-ui/frontend/public/hystrix-dashboard/monitor/monitor.css
  metrics-service-ui/frontend/public/hystrix-dashboard/monitor/monitor.html
  metrics-service-ui/frontend/public/hystrix-dashboard/monitor/monitor.js
  metrics-service-ui/frontend/public/index.html
  metrics-service-ui/frontend/src/components/Dashboard/Dashboard.jsx
  metrics-service-ui/frontend/src/components/Header/Header.jsx
  metrics-service-ui/frontend/src/components/Login/LoginWebflow.css
  metrics-service/build.gradle
  metrics-service/src/main/java/org/zowe/apiml/metrics/MetricsServiceApplication.java
  metrics-service/src/main/resources/application.yml
Labels: size/XXL

#1867 docs: Improve internal documentation for Metrics Service
  metrics-service/README.md
  metrics-service/metrics-service-structure.png
Labels: size/M

#1868 fix: Metrics Service verifies certificates
  metrics-service/README.md
  metrics-service/src/main/resources/application.yml
Labels: size/S

#1872 chore: Update SAF IDT provider and add GW sharedlibs props
  gateway-package/src/main/resources/bin/start.sh
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/saf/SafProviderBeansConfig.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/saf/SafRestAuthenticationService.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/saf/SafRestAuthenticationServiceTest.java
Labels: size/M, Sensitive

#1874 refactor: cert analyser
  certificate-analyser/src/main/java/org/zowe/apiml/Analyser.java
  certificate-analyser/src/main/java/org/zowe/apiml/ApimlConf.java
  certificate-analyser/src/main/java/org/zowe/apiml/Config.java
  certificate-analyser/src/main/java/org/zowe/apiml/LocalHandshake.java
  certificate-analyser/src/main/java/org/zowe/apiml/LocalVerifier.java
  certificate-analyser/src/main/java/org/zowe/apiml/RemoteHandshake.java
  certificate-analyser/src/main/java/org/zowe/apiml/SSLContextFactory.java
  certificate-analyser/src/main/java/org/zowe/apiml/Stores.java
  certificate-analyser/src/test/java/org/zowe/apiml/LocalHandshakeTest.java
  certificate-analyser/src/test/java/org/zowe/apiml/RemoteHandshakeTest.java
Labels: size/L

#1837 Mock of JWT token validation
  mock-zosmf/build.gradle
  mock-zosmf/src/main/java/org/zowe/apiml/client/api/FilesController.java
  mock-zosmf/src/main/java/org/zowe/apiml/client/api/InfoController.java
  mock-zosmf/src/main/java/org/zowe/apiml/client/services/JwtTokenService.java
  mock-zosmf/src/main/java/org/zowe/apiml/client/services/apars/FunctionalApar.java
  mock-zosmf/src/main/java/org/zowe/apiml/client/services/apars/JwtKeys.java
  mock-zosmf/src/main/java/org/zowe/apiml/client/services/apars/PH34201.java
  mock-zosmf/src/main/java/org/zowe/apiml/client/services/apars/PHBase.java
  mock-zosmf/src/main/java/org/zowe/apiml/client/services/apars/RSU2012.java
  mock-zosmf/src/main/resources/application.yml
  mock-zosmf/src/test/java/org/zowe/apiml/client/api/RealJwtTokenEndpointTest.java
  mock-zosmf/src/test/java/org/zowe/apiml/client/services/apars/PHBaseTest.java
Labels: size/L

#1878 Gateway Log Messages language refactor
  gateway-service/src/main/resources/gateway-log-messages.yml
Labels: size/S

#1880 chore: Upgrade Netty to latest version
  gateway-service/build.gradle
  gateway-service/src/test/java/org/zowe/apiml/gateway/filters/pre/HeaderSanitizerFilterTest.java
  gradle/versions.gradle
  mock-zosmf/src/test/java/org/zowe/apiml/client/services/versions/AvailableAparsTest.java
Labels: size/S

#1881 chore: Version updates
  api-catalog-services/build.gradle
  apiml-common/build.gradle
  apiml-security-common/build.gradle
  apiml-utility/build.gradle
  build.gradle
  caching-service/build.gradle
  discovery-service/build.gradle
  gateway-service/build.gradle
  gradle/versions.gradle
  metrics-service/build.gradle
Labels: size/L, Sensitive

#1899 Feat: Enable hystrix metrics stream for core APIML services
  api-catalog-services/build.gradle
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/ApiCatalogApplication.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/controllers/api/ApiCatalogController.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/controllers/api/CatalogApiDocController.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/controllers/handlers/NotFoundErrorController.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/security/SecurityConfiguration.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/staticapi/StaticAPIRefreshController.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/staticapi/StaticDefinitionController.java
  api-catalog-services/src/main/resources/application.yml
  caching-service/build.gradle
  caching-service/src/main/java/org/zowe/apiml/caching/CachingService.java
  caching-service/src/main/java/org/zowe/apiml/caching/api/CachingController.java
  caching-service/src/main/java/org/zowe/apiml/caching/config/SpringSecurityConfig.java
  caching-service/src/main/resources/application.yml
  discovery-service/build.gradle
  discovery-service/src/main/java/org/zowe/apiml/discovery/DiscoveryServiceApplication.java
  discovery-service/src/main/java/org/zowe/apiml/discovery/EurekaInstanceCanceledListener.java
  discovery-service/src/main/java/org/zowe/apiml/discovery/EurekaInstanceRegisteredListener.java
  discovery-service/src/main/java/org/zowe/apiml/discovery/config/HttpWebSecurityConfig.java
  discovery-service/src/main/java/org/zowe/apiml/discovery/config/HttpsWebSecurityConfig.java
  discovery-service/src/main/java/org/zowe/apiml/discovery/staticdef/StaticApiRestController.java
  discovery-service/src/main/resources/application.yml
  gateway-service/build.gradle
  gateway-service/src/main/java/org/zowe/apiml/gateway/GatewayApplication.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/apidoc/reader/ApiDocController.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/controllers/AuthController.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/controllers/AuthProviderController.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/controllers/CacheServiceController.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/controllers/GatewayHomepageController.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/controllers/SafResourceAccessController.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/controllers/VersionController.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/error/NotFoundErrorController.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/config/NewSecurityConfiguration.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/services/ServicesInfoController.java
  gateway-service/src/main/resources/application.yml
  metrics-service/src/main/resources/application.yml
Labels: size/L, Sensitive

#1902 fix: remove hardcoded values from metrics service ui
  metrics-service-ui/frontend/package.json
  metrics-service-ui/frontend/public/hystrix-dashboard/monitor/monitor.js
  metrics-service-ui/frontend/src/components/Dashboard/Dashboard.jsx
  metrics-service-ui/frontend/src/components/Error/Error.jsx
  metrics-service-ui/frontend/src/components/Header/Header.jsx
Labels: size/L

#1898 fix: Fix GW script
  api-catalog-package/src/main/resources/bin/start.sh
  caching-service-package/src/main/resources/bin/start.sh
  config/zowe-api-dev/alternative_start.sh
  discovery-package/src/main/resources/bin/start.sh
  gateway-package/src/main/resources/bin/start.sh
  metrics-service-package/src/main/resources/bin/start.sh
Labels: size/S

#1904 chore: update tomcat to 9.0.54 in zaas client
  zaas-client/build.gradle
Labels: size/XS

#1906 fix: Disable hystrix timeout
  api-catalog-services/src/main/resources/application.yml
  caching-service/src/main/resources/application.yml
  discovery-service/src/main/resources/application.yml
Labels: size/XS

#1896 refactor: security remapping
  gateway-service/src/main/java/org/zowe/apiml/gateway/ribbon/GatewayRibbonConfig.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/ribbon/http/BeanConfig.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/ribbon/http/HttpClientProxyConfig.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/ribbon/http/ServiceAuthenticationDecorator.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/ServiceAuthenticationServiceImpl.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/AuthenticationCommand.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/ByPassScheme.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/HttpBasicPassTicketScheme.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/ZosmfScheme.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/ribbon/http/HttpClientProxyConfigTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/ribbon/http/ServiceAuthenticationDecoratorTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/ServiceAuthenticationServiceImplTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/ByPassSchemeTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/HttpBasicPassTicketSchemeTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/ZosmfSchemeTest.java
Labels: size/XL, Sensitive

#1908 chore: ERROR level for jetty ssl logs
  apiml-utility/src/main/java/org/zowe/apiml/product/logging/ApimlDependencyLogHider.java
  gateway-service/src/main/resources/application.yml
Labels: size/XS

#1909 chore: Fix dependency vulnerabilities in the Caching Service
  caching-service/build.gradle
  gradle/versions.gradle
  zaas-client/build.gradle
Labels: size/S

#1911 chore: Distinguish Core and SDK publishing
  api-catalog-services/build.gradle
  discoverable-client/build.gradle
  discovery-service/build.gradle
  gateway-service/build.gradle
  gradle/publish.gradle
  metrics-service/build.gradle
Labels: size/L

#1912 fix: Add proper icons to Metrics Service
  metrics-service-ui/frontend/public/favicon.ico
  metrics-service-ui/frontend/public/index.html
  metrics-service-ui/frontend/src/components/Header/Header.jsx
  metrics-service-ui/frontend/src/components/Icons/MetricsIconButton.jsx
  metrics-service-ui/frontend/src/components/Icons/MetricsIconButton.test.jsx
  metrics-service-ui/frontend/src/components/Login/Login.jsx
  metrics-service-ui/frontend/src/helpers/theme.jsx
Labels: size/M

#1913 chore: Add feature flag to metrics service
  metrics-service-package/src/main/resources/bin/start.sh
Labels: size/XS

#1914 chore: Add functional tests for the metrics service
  metrics-service/build.gradle
  metrics-service/src/test/java/org/zowe/apiml/metrics/functional/MetricsFunctionalTest.java
  metrics-service/src/test/java/org/zowe/apiml/metrics/functional/PrototypeFunctionalTest.java
Labels: size/M

#1910 chore: metrics tests
  gradle/sonar.gradle
  metrics-service-ui/frontend/package-lock.json
  metrics-service-ui/frontend/package.json
  metrics-service-ui/frontend/src/actions/user-actions.test.jsx
  metrics-service-ui/frontend/src/components/Dashboard/Dashboard.test.jsx
Labels: size/L

#1917 chore: run metrics service as a part of IT
  .github/workflows/containers.yml
  config/docker/api-catalog-services.yml
  config/docker/discovery-service.yml
  config/docker/gateway-service.yml
  integration-tests/build.gradle
  integration-tests/src/test/java/org/zowe/apiml/integration/external/MetricServiceTest.java
  integration-tests/src/test/java/org/zowe/apiml/util/categories/MetricsServiceTest.java
Labels: size/M

#1918 chore: remove spring boot web
  zaas-client/build.gradle
  zaas-client/src/main/java/org/zowe/apiml/zaasclient/config/DefaultZaasClientConfiguration.java
Labels: size/S

#1919 chore: Provide basic documentation on the VSAM
  caching-service/README.md
  mock-zosmf/README.md
Labels: size/M

#1920 chore: Configure the timeout for JWT token in mock zOSMF
  config/local/mock-zosmf.yml
  mock-zosmf/src/main/java/org/zowe/apiml/client/services/apars/AuthenticateApar.java
  mock-zosmf/src/main/java/org/zowe/apiml/client/services/apars/FunctionalApar.java
  mock-zosmf/src/main/java/org/zowe/apiml/client/services/apars/PH12143.java
  mock-zosmf/src/main/java/org/zowe/apiml/client/services/apars/PH34201.java
  mock-zosmf/src/main/java/org/zowe/apiml/client/services/apars/RSU2012.java
  mock-zosmf/src/main/java/org/zowe/apiml/client/services/versions/AvailableApars.java
  mock-zosmf/src/main/java/org/zowe/apiml/client/services/versions/Versions.java
  mock-zosmf/src/main/resources/application.yml
  mock-zosmf/src/test/java/org/zowe/apiml/client/services/apars/AuthenticationAparTest.java
  mock-zosmf/src/test/java/org/zowe/apiml/client/services/apars/PH12143Test.java
  mock-zosmf/src/test/java/org/zowe/apiml/client/services/apars/PH34201Test.java
  mock-zosmf/src/test/java/org/zowe/apiml/client/services/apars/RSU2012Test.java
  mock-zosmf/src/test/java/org/zowe/apiml/client/services/versions/AvailableAparsTest.java
  mock-zosmf/src/test/java/org/zowe/apiml/client/services/versions/VersionsTest.java
  package.json
Labels: size/M

#1915 Fix: Proper authentication flow for Metrics Service
  metrics-service-ui/frontend/src/components/App/App.jsx
  metrics-service-ui/frontend/src/components/AuthRoute/AuthRoute.jsx
  metrics-service-ui/frontend/src/components/AuthRoute/AuthRoute.test.jsx
  metrics-service-ui/frontend/src/components/AuthRoute/AuthRouteContainer.jsx
  metrics-service-ui/frontend/src/components/Login/LoginContainer.jsx
  metrics-service-ui/frontend/src/index.js
  metrics-service-ui/frontend/src/services/user-service.jsx
  metrics-service/src/main/java/org/zowe/apiml/metrics/security/SpringSecurityConfiguration.java
Labels: size/L, Sensitive

#1925 Chore: Publish Metrics Service Zowe conformant containers
  .github/workflows/create-image-without-release.yml
  .github/workflows/release.yml
  .github/workflows/snapshot-release.yml
  .github/workflows/specific-release.yml
  containers/README.md
  containers/metrics-service/Dockerfile
  containers/metrics-service/prepare.sh
  metrics-service-package/build.gradle
  metrics-service-package/src/main/resources/bin/start.sh
  metrics-service-package/src/main/resources/bin/validate.sh
Labels: size/L

#1924 fix: Remove duplicated hystrix streams in Metrics Service dashboard
  metrics-service-ui/frontend/public/hystrix-dashboard/monitor/monitor.js
Labels: size/S

#1930 chore: Upgrade dependencies
  api-catalog-ui/frontend/package-lock.json
  api-catalog-ui/frontend/package.json
  onboarding-enabler-micronaut/build.gradle
Labels: size/XS

#1931 Fix: Release Metrics Service connection when change stream
  metrics-service-ui/frontend/public/hystrix-dashboard/monitor/monitor.js
Labels: size/XS

#1934 Fix: Swagger server url transform
  api-catalog-ui/frontend/src/components/Swagger/Swagger.jsx
  api-catalog-ui/frontend/src/components/Swagger/Swagger.test.jsx
Labels: size/M

#1935 fix: specify jgit dependency for gradle plugin
  api-catalog-services/build.gradle
  caching-service/build.gradle
  discoverable-client/build.gradle
  discovery-service/build.gradle
  gateway-service/build.gradle
  metrics-service/build.gradle
  mock-zosmf/build.gradle
Labels: size/S

#1939 fix: choose correct key by alias
  common-service-core/src/main/java/org/zowe/apiml/security/HttpsFactory.java
  common-service-core/src/test/java/org/zowe/apiml/security/SecurityTestUtils.java
Labels: size/S, Sensitive
