Repository zowe/api-layer, pull requests merged in 2021-03, with the labels that each got.

#1196 JS enabler integration into build
  Jenkinsfile
  README.md
  api-catalog-ui/build.gradle
  api-catalog-ui/frontend/README.md
  api-catalog-ui/frontend/package-lock.json
  api-catalog-ui/frontend/package.json
  api-catalog-ui/frontend/pnpm-lock.yaml
  api-catalog-ui/frontend/pnpmfile.js
  build.gradle
  docs/local-configuration.md
  gradle.properties
  gradle/coverage.gradle
  onboarding-enabler-nodejs-sample-app/build.gradle
  onboarding-enabler-nodejs-sample-app/config/service-configuration.yml
  onboarding-enabler-nodejs-sample-app/package.json
  onboarding-enabler-nodejs/build.gradle
  package.json
Labels: size/L

#1209 Disable javascript enabler publish
  scripts/publish_and_release.sh
Labels: size/XS

#1214 Add unregistration method to Node.js enabler
  onboarding-enabler-nodejs-sample-app/src/index.js
  onboarding-enabler-nodejs/README.md
  onboarding-enabler-nodejs/src/index.js
Labels: size/M

#1220 chore: Dont test while releasing
  scripts/publish_and_release.sh
Labels: size/XS

#1221 chore: Try removing buildTasks
  build.gradle
Labels: size/XS

#1226 Update sonar plugin
  build.gradle
Labels: size/XS

#1225 chore: Try Actions
  .github/pull_request_template.md
  .github/workflows/ci-internal-tests.yml
  .github/workflows/ci-tests-with-rsu2012.yml
  .github/workflows/ci-tests-without-jwt.yml
  .github/workflows/ci-tests.yml
  Jenkinsfile
  api-catalog-ui/frontend/src/components/App/AsyncModules.jsx
  api-catalog-ui/frontend/src/components/ServiceVersionDiff/ServiceVersionDiff.jsx
  build.gradle
  gradle/lite.gradle
  gradle/versions.gradle
  integration-tests/README.md
  integration-tests/build.gradle
  integration-tests/src/test/java/org/zowe/apiml/apicatalog/ApiCatalogEndpointIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/apicatalog/ApiCatalogHttpHeadersIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/apicatalog/ApiCatalogLoginIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/apicatalog/ApiCatalogSecurityIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/cachingservice/CachingApiIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/cachingservice/RejectEvictionTest.java
  integration-tests/src/test/java/org/zowe/apiml/cachingservice/RemoveOldestTest.java
  integration-tests/src/test/java/org/zowe/apiml/discoverableclient/DownloadApiIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/discoverableclient/GreetingApiIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/discoverableclient/GreetingV2ApiIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/discoverableclient/IntegratedApiMediationClientTest.java
  integration-tests/src/test/java/org/zowe/apiml/discoverableclient/IntegratedZaasClientTest.java
  integration-tests/src/test/java/org/zowe/apiml/discoverableclient/MultipartPutIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/discoverableclient/RequestInfoIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/discoverableclient/UiIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/discoveryservice/EurekaInstancesIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/discoveryservice/staticdef/StaticClientRoutingEndpointsTest.java
  integration-tests/src/test/java/org/zowe/apiml/enablejavasampleapp/EnablerJavaSampleAppEndpointTest.java
  integration-tests/src/test/java/org/zowe/apiml/enablenodejssampleapp/EnablerNodejsSampleAppEndpointTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/AuthenticationOnDeploymentTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/EncodedCharactersTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/GatewayConcurrentRequestsTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/GatewaySecurityTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/GatewayTimeoutTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/PageRedirectionTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/PassTicketTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/PublicKeyIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/QueryIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/ServiceHaModeTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/ServicesInfoTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/VersionEndpointTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/ZosmfAuthenticationTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/ZosmfSsoIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/authentication/LoginTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/authentication/LogoutTest.java
  integration-tests/src/test/java/org/zowe/apiml/penetration/JwtPenTest.java
  integration-tests/src/test/java/org/zowe/apiml/util/StartAndCleanApplications.java
  integration-tests/src/test/java/org/zowe/apiml/util/TestWithStartedInstances.java
  integration-tests/src/test/java/org/zowe/apiml/util/service/CachingService.java
  integration-tests/src/test/java/org/zowe/apiml/util/service/FullApiMediationLayer.java
  integration-tests/src/test/java/org/zowe/apiml/util/service/RunningService.java
  integration-tests/src/test/java/org/zowe/apiml/ws/WebSocketProxyTest.java
  integration-tests/src/test/java/org/zowe/apiml/zaasclient/ZaasClientIntegrationTest.java
  integration-tests/src/test/resources/META-INF/services/org.junit.platform.launcher.TestExecutionListener
Labels: size/L

#1245 Fix Gateway start script
  gateway-package/src/main/resources/bin/start.sh
Labels: size/XS

#1246 Gitignore api-layer/onboarding-enabler-nodejs-sample-app/tools
  .gitignore
Labels: size/XS

#1251 Add notes to release process
  docs/release.md
Labels: size/XS

#1252 Fix gateway start script
  gateway-package/src/main/resources/bin/start.sh
Labels: size/XS

#1250 changelog 1.20
  CHANGELOG.md
  docs/release.md
  integration-tests/src/test/java/org/zowe/apiml/apicatalog/ApiCatalogEndpointIntegrationTest.java
Labels: size/M

#1254 changelog edit
  CHANGELOG.md
Labels: size/S

#1267 chore: Add Github Token needed for master branch run
  .github/workflows/sonarqube.yml
Labels: size/XS

#1266 chore: Always store test results and logs
  .github/workflows/ci-internal-tests.yml
  .github/workflows/ci-tests-with-rsu2012.yml
  .github/workflows/ci-tests-without-jwt-with-authenticate.yml
  .github/workflows/ci-tests-without-jwt.yml
  .github/workflows/ci-tests.yml
  integration-tests/src/test/java/org/zowe/apiml/apicatalog/ApiCatalogEndpointIntegrationTest.java
Labels: size/S

#1271 chore: Move Snapshot release to GH Actions
  .github/workflows/snapshot-release.yml
  Jenkinsfile
Labels: size/M

#1272 chore: GH actions for non snapshot releases.
  .github/workflows/release.yml
  build.gradle
Labels: size/M

#1279 chore: GH Actions authenticate as different user
  .github/workflows/release.yml
  .github/workflows/specific-release.yml
Labels: size/S

#1282 chore: Add PAT
  .github/workflows/release.yml
  .github/workflows/specific-release.yml
Labels: size/S

#1280 chore: Add Code QL to get the security inputs
  .github/workflows/codeql.yml
Labels: size/M

#1284 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: size/XS

#1286 chore: Add timeouts to the GH Actions
  .github/workflows/ci-internal-tests.yml
  .github/workflows/ci-tests-with-rsu2012.yml
  .github/workflows/ci-tests-without-jwt-with-authenticate.yml
  .github/workflows/ci-tests-without-jwt.yml
  .github/workflows/ci-tests.yml
  .github/workflows/codeql.yml
  .github/workflows/release.yml
  .github/workflows/snapshot-release.yml
  .github/workflows/sonarqube.yml
  .github/workflows/specific-release.yml
Labels: size/S

#1288 chore: Release the NPM libraries as part of the release process.
  .github/workflows/release.yml
  .github/workflows/specific-release.yml
Labels: size/S

#1289 chore: commit before release
  .github/workflows/release.yml
  .github/workflows/specific-release.yml
Labels: size/XS

#1290 chore: Updated release procedure
  .github/workflows/release.yml
  .github/workflows/specific-release.yml
  onboarding-enabler-nodejs/package.json
Labels: size/XS

#1293 fix: Provide default values
  gateway-package/src/main/resources/bin/start.sh
Labels: size/XS

#1295 chore: faster eureka registration
  config/local/discoverable-client.yml
  integration-tests/src/test/resources/environment-configuration.yml
Labels: size/XS

#1299 fix: enable vsam
  caching-service-package/src/main/resources/bin/start.sh
Labels: size/XS

#1303 more specific template
  .github/pull_request_template.md
  CONTRIBUTING.md
Labels: size/S

#1307 chore: https zss
  gateway-package/src/main/resources/bin/start.sh
Labels: size/XS

#1311 Fix apiml-multi startup
  config/local-multi/discovery-service-1.yml
  config/local-multi/discovery-service-2.yml
  config/local-multi/gateway-service-1.yml
  config/local-multi/gateway-service-2.yml
  config/local-multi/mock-zosmf.yml
  package.json
Labels: size/M

#1316 chore: do not override external mapper url in script
  gateway-package/src/main/resources/bin/start.sh
  zss-sample-service/server.js
Labels: size/S

#1319 fix: ipaddress conf
  caching-service/src/test/java/org/zowe/apiml/caching/api/CachingControllerTest.java
  gateway-package/src/main/resources/bin/start.sh
Labels: size/XS
