Repository zowe/api-layer, pull requests merged in 2021-01, with the labels that each got.

#1042 Update the commons library for Gateway
  gateway-service/build.gradle
Labels: size/XS

#1044 GH999 zowe-api-dev thin jars update
  config/zowe-api-dev/alternative_start.sh
  config/zowe-api-dev/run-wrapper.sh
  docs/ad-hoc-mainframe-deployment.md
  zowe-api.json
Labels: size/M

#1043 Developer documentation of SAF resource checking via annotation
  docs/saf-authorized-endpoints.md
Labels: size/L

#1055 Fix running local integration tests for zOSMF related tests
  integration-tests/README.md
  integration-tests/src/test/resources/environment-configuration.yml
Labels: size/S

#1005 Add /api/v1/gateway/services/{serviceId} endpoint that provides information about a service in API ML for API clients
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/auth/Authentication.java
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/config/AuthConfigurationProperties.java
  apiml-security-common/src/test/java/org/zowe/apiml/security/common/auth/AuthenticationTest.java
  common-service-core/src/main/java/org/zowe/apiml/auth/Authentication.java
  common-service-core/src/main/java/org/zowe/apiml/auth/AuthenticationScheme.java
  common-service-core/src/main/java/org/zowe/apiml/auth/AuthenticationSchemes.java
  common-service-core/src/main/java/org/zowe/apiml/config/ApiInfo.java
  common-service-core/src/main/java/org/zowe/apiml/constants/EurekaMetadataDefinition.java
  common-service-core/src/main/java/org/zowe/apiml/eurekaservice/client/util/EurekaMetadataParser.java
  common-service-core/src/test/java/org/zowe/apiml/auth/AuthenticationSchemesTest.java
  common-service-core/src/test/java/org/zowe/apiml/auth/AuthenticationTest.java
  common-service-core/src/test/java/org/zowe/apiml/eurekaservice/client/util/EurekaMetadataParserTest.java
  config/local/gateway-service.yml
  discovery-service/src/main/java/org/zowe/apiml/discovery/metadata/MetadataTranslationService.java
  discovery-service/src/main/java/org/zowe/apiml/discovery/staticdef/Service.java
  discovery-service/src/main/java/org/zowe/apiml/discovery/staticdef/ServiceDefinitionProcessor.java
  discovery-service/src/test/java/org/zowe/apiml/discovery/metadata/MetadataTranslationServiceTest.java
  docs/ad-hoc-mainframe-deployment.md
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/GatewayConfig.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/post/PageRedirectionFilter.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/ribbon/http/ServiceAuthenticationDecorator.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/routing/ApimlRoutingConfig.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/config/SecurityConfiguration.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/ServiceAuthenticationServiceImpl.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/AbstractAuthenticationScheme.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/AuthenticationSchemeFactory.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/ByPassScheme.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/HttpBasicPassTicketScheme.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/ServiceAuthenticationService.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/ZosmfScheme.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/ZoweJwtScheme.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/services/ServerInfoConfig.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/services/ServiceInfo.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/services/ServicesInfoController.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/services/ServicesInfoService.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/config/ApimlRoutingConfig.java
  gateway-service/src/test/java/org/zowe/apiml/config/service/security/MockedSecurityContext.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/filters/post/PageRedirectionFilterTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/ribbon/http/ServiceAuthenticationDecoratorTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/ServiceAuthenticationServiceImplTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/AuthenticationSchemeFactoryTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/ByPassSchemeTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/HttpBasicPassTicketSchemeTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/ZosmfSchemeTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/ZoweJwtSchemeTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/services/ServicesInfoControllerTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/services/ServicesInfoServiceTest.java
  integration-tests/README.md
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/AuthenticationOnDeploymentTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/ServicesInfoTest.java
  integration-tests/src/test/java/org/zowe/apiml/gatewayservice/ZosmfSsoIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/util/service/VirtualService.java
  package.json
Labels: size/XXL

#1081 rollout parameters apiml.security.authorization.* in each place
  config/zowe-api-dev/alternative_start.sh
  gateway-package/src/main/resources/bin/start.sh
  zowe-install/src/main/resources/component-scripts/start-gateway.sh
Labels: size/S

#1085 Gateway start script Docker support
  gateway-package/src/main/resources/bin/start.sh
Labels: size/S

#1102 Bump version down to correct 1.20.0-SNAPSHOT
  gradle.properties
Labels: size/XS

#1104 Disable repeated test on publish artifacts
  Jenkinsfile
Labels: size/XS

#1109 We using npm but document pnpm
  README.md
Labels: size/S

#1124 1.19 changelog
  CHANGELOG.md
Labels: docs, size/S

#1079 Change agent to use test docker jdk11 image
  Jenkinsfile
  gateway-service/src/test/java/org/zowe/apiml/acceptance/common/AcceptanceTest.java
Labels: size/S

#1137 use latest version of gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: size/XS
