Repository zowe/api-layer, pull requests merged in 2021-04, with the labels that each got.

#1329 fix: Remove zss http default for authorization endpoint api
  gateway-package/src/main/resources/bin/start.sh
Labels: size/XS

#1335 Remove wait from start.sh to reduce address spaces
  api-catalog-package/src/main/resources/bin/start.sh
  api-catalog-package/src/main/resources/bin/validate.sh
  caching-service-package/src/main/resources/bin/start.sh
  caching-service-package/src/main/resources/bin/validate.sh
  discovery-package/src/main/resources/bin/start.sh
  discovery-package/src/main/resources/bin/validate.sh
  gateway-package/src/main/resources/bin/start.sh
  gateway-package/src/main/resources/bin/validate.sh
Labels: size/M

#1336 API Catalog UI fix critical issues from Sonar report
  api-catalog-ui/frontend/src/components/Error/ErrorFormatter.jsx
  api-catalog-ui/frontend/src/components/ErrorBoundary/BigShield/BigShield._test.jsx
  api-catalog-ui/frontend/src/components/ServiceTab/ServiceTab.jsx
Labels: size/L

#1340 fix: bump node to LTS
  .github/workflows/release.yml
  .github/workflows/snapshot-release.yml
  .github/workflows/specific-release.yml
  gradle.properties
Labels: size/S

#1344 feature: Starting for different Redis related setups
  redis/docker-compose-replica.yml
  redis/docker-compose-sentinel.yml
  redis/master/redis.conf
  redis/replica/redis.conf
  redis/sentinel-1/sentinel.conf
  redis/sentinel-2/sentinel.conf
  redis/sentinel-3/sentinel.conf
Labels: size/L

#1351 Fix major issues from Sonar in Catalog UI
  api-catalog-ui/frontend/src/actions/service-version-diff-actions.jsx
  api-catalog-ui/frontend/src/components/App/App.jsx
  api-catalog-ui/frontend/src/components/Swagger/Swagger.jsx
  api-catalog-ui/frontend/src/reducers/authentication-reducer.jsx
  api-catalog-ui/frontend/src/reducers/fetch-tile-reducer.jsx
  api-catalog-ui/frontend/src/reducers/filter-reducer.jsx
  api-catalog-ui/frontend/src/reducers/loading-reducer.jsx
  api-catalog-ui/frontend/src/reducers/refresh-static-apis-reducer.jsx
  api-catalog-ui/frontend/src/reducers/selected-service-reducer.jsx
  api-catalog-ui/frontend/src/reducers/service-version-diff-reducer.jsx
  api-catalog-ui/frontend/src/setupTests.js
Labels: size/M

#1354 Fix major issues from Sonar in Catalog UI
  api-catalog-ui/frontend/src/reducers/authentication-reducer.jsx
  api-catalog-ui/frontend/src/reducers/authentication-reducer.test.jsx
  api-catalog-ui/frontend/src/reducers/error-reducer.jsx
Labels: size/M

#1356 chore: Upgrade jetty to the latest versions
  api-catalog-services/build.gradle
  discovery-service/build.gradle
  gateway-service/build.gradle
  gradle/versions.gradle
Labels: size/S

#1365 chore: Create SECURITY.md
  SECURITY.md
Labels: size/S

#1385 Remove discoveryServiceUrls inconsistency in API Catalog Service
  api-catalog-package/src/main/resources/bin/start.sh
  api-catalog-services/src/main/resources/application.yml
  api-catalog-services/src/main/resources/parmlib.sh
  api-catalog-ui/frontend/package-lock.json
  caching-service-package/src/main/resources/bin/start.sh
  config/local-multi/api-catalog-service.yml
  config/local/api-catalog-service.yml
  config/zowe-api-dev/alternative_start.sh
Labels: size/L

#1393 chore: Improve onboarding development for Redis
  .github/workflows/ci-tests.yml
  caching-service/README.md
Labels: size/M

#1404 Improve security risk situation
  api-catalog-services/build.gradle
  apiml-common/build.gradle
  apiml-utility/build.gradle
  gradle/versions.gradle
Labels: size/S

#1402 chore: Add key features and bug fixes to the changelog.
  CHANGELOG.md
Labels: size/S

#1427 docs: Explain how to run API ML with starting services outside of the IT
  integration-tests/README.md
Labels: size/M

#1428 Script to update apiml
  README.md
  apiml-common-lib-package/build.gradle
  apiml-common-lib-package/src/main/update_apiml.sh
  scripts/README.md
Labels: size/L
