Repository zowe/api-layer, pull requests merged in 2021-10, with the labels that each got.

#1806 feat: Per service configuration to ignore certain headers
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/pre/PerServiceGZipFilter.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/pre/PerServiceIgnoreHeaderFilter.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/IgnoreHeadersPerServiceTest.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/netflix/MetadataBuilder.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/filters/pre/PerServiceIgnoreHeaderFilterTest.java
Labels: size/L

#1813 starting the gateway-url with slash / to make it look consistent with other URLs
  caching-service/src/main/resources/application.yml
  caching-service/src/test/resources/application.yml
  discoverable-client/src/main/resources/application.yml
  discoverable-client/src/test/resources/application.yml
  metrics-service/src/main/resources/application.yml
  onboarding-enabler-spring-sample-app/src/main/resources/application.yml
Labels: size/M

#1816 updating the documentation to reflect the change in #1813
  docs/websockets.md
  onboarding-enabler-nodejs/README.md
Labels: size/XS

#1814 fix: define appfwPlugins instead of desktopIframePlugins for API Catalog
  api-catalog-package/src/main/resources/manifest.yaml
  api-catalog-package/src/main/resources/pluginDefinition.json
Labels: size/S

#1811 feat: Ignore Origin header for z/OSMF
  discovery-package/src/main/resources/zosmf-static-definition.yaml.template
Labels: size/XS

#1812 feat: Per service configuration to direct the APIML to add headers
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/post/PerServiceAddResponseHeadersFilter.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/AddHeadersPerServiceTest.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/netflix/MetadataBuilder.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/filters/post/PerServiceAddResponseHeadersFilterTest.java
Labels: size/L

#1819 fix: pje enabler sample and password validation
  gradle/lite.gradle
  gradle/sonar.gradle
  onboarding-enabler-java-sample-app-plain-java/build.gradle
  onboarding-enabler-java-sample-app-plain-java/config/service-configuration.yml
  onboarding-enabler-java-sample-app-plain-java/readme.md
  onboarding-enabler-java-sample-app-plain-java/src/main/java/org/zowe/apiml/sample/PlainJavaEnablerApp.java
  onboarding-enabler-java-sample-app/build.gradle
  onboarding-enabler-java/src/main/java/org/zowe/apiml/eurekaservice/client/util/EurekaInstanceConfigValidator.java
  onboarding-enabler-java/src/test/java/org/zowe/apiml/eurekaservice/client/util/EurekaInstanceConfigValidatorTest.java
  onboarding-enabler-java/src/test/resources/service-configuration-keyring.yml
  settings.gradle
Labels: size/L

#1822 fix: add pluginDefinition.json to package
  api-catalog-package/build.gradle
  api-catalog-package/src/main/resources/manifest.yaml
  api-catalog-package/src/main/resources/plugin/pluginDefinition.json
  api-catalog-package/src/main/resources/plugin/web/assets/api-catalog.png
Labels: size/S
