Repository zowe/api-layer, pull requests merged in 2021-02, with the labels that each got.

#1139 Move to the newer Zowe wide env variables names.
  caching-service-package/src/main/resources/bin/start.sh
Labels: size/XS

#1142 Introduce token validation providers
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/AuthenticationService.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/zosmf/AuthenticateEndpointStrategy.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/zosmf/TokenValidationStrategy.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/zosmf/ZosmfBeans.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/zosmf/ZosmfService.java
  gateway-service/src/test/java/org/zowe/apiml/config/service/security/MockedAuthenticationServiceContext.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/login/zosmf/ZosmfAuthenticationProviderTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/query/SuccessfulQueryHandlerTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/AuthenticationServiceTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/zosmf/AuthenticateEndpointStrategyTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/zosmf/ZosmfServiceTest.java
Labels: Sensitive

#1143 Token generic validator
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/zosmf/AuthenticateEndpointStrategy.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/zosmf/AuthenticatedEndpointStrategy.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/zosmf/TokenValidationConfigRsu2012.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/zosmf/TokenValidationRequest.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/zosmf/TokenValidationStrategy.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/zosmf/ZosmfBeans.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/zosmf/ZosmfService.java
  gateway-service/src/main/resources/application.yml
  gateway-service/src/test/java/org/zowe/apiml/config/service/security/MockedAuthenticationServiceContext.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/login/zosmf/ZosmfAuthenticationProviderTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/query/SuccessfulQueryHandlerTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/AuthenticationServiceTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/zosmf/AuthenticateEndpointStrategyTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/zosmf/AuthenticatedEndpointStrategyTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/zosmf/ZosmfServiceTest.java
  integration-tests/src/test/java/org/zowe/apiml/enablenodejssampleapp/EnablerNodejsSampleAppEndpointTest.java
Labels: Sensitive

#1151 Disable invasive debug logs in Nodejs enabler
  onboarding-enabler-nodejs-sample-app/package.json
  onboarding-enabler-nodejs/package.json
  onboarding-enabler-nodejs/src/index.js
Labels: size/S

#1153 Configure another service instead of Catalog
  gateway-package/src/main/resources/bin/start.sh
Labels: size/S

#1154 Improve the Contributing with info about the mock zOSMF
  CONTRIBUTING.md
Labels: size/XS

#1157 Publish Node.js enabler as part of the API ML release
  onboarding-enabler-nodejs-sample-app/README.md
  onboarding-enabler-nodejs-sample-app/package.json
  onboarding-enabler-nodejs-sample-app/src/index.js
  onboarding-enabler-nodejs/README.md
  onboarding-enabler-nodejs/package.json
  scripts/publish_and_release.sh
Labels: size/M

#1158 Add missing slash
  gateway-package/src/main/resources/bin/start.sh
Labels: size/XS

#1179 Rip/ac/enabler readme
  onboarding-enabler-micronaut-sample-app/README.md
Labels: size/S

#1183 Update README.md
  onboarding-enabler-micronaut-sample-app/README.md
Labels: size/XS

#1194 Introduce commit message template
  .github/pull_request_template.md
  CONTRIBUTING.md
Labels: size/M

#1198 temporally remove broken release types
  scripts/publish_and_release.sh
Labels: size/S
