Repository zowe/api-layer, pull requests merged in 2021-06, with the labels that each got.

#1500 Fix: metrics service publishing
  metrics-service/build.gradle
Labels: size/S

#1496 feat: determnistic routing
  gateway-service/src/main/java/org/zowe/apiml/gateway/error/InternalServerErrorController.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/error/check/LoadBalancerErrorCheck.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/ribbon/AbortingRetryListener.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/ribbon/ApimlLoadBalancer.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/ribbon/ApimlRetryableClient.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/ribbon/GatewayRibbonConfig.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/ribbon/loadbalancer/InstanceInfoExtractor.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/ribbon/loadbalancer/LoadBalancerRuleAdapter.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/ribbon/loadbalancer/LoadBalancingContext.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/ribbon/loadbalancer/LoadBalancingPredicatesConfig.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/ribbon/loadbalancer/PredicateFactory.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/ribbon/loadbalancer/RequestAwarePredicate.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/ribbon/loadbalancer/predicate/RequestHeaderPredicate.java
  gateway-service/src/main/resources/gateway-log-messages.yml
  gateway-service/src/test/java/org/zowe/apiml/gateway/error/check/LoadBalancerErrorCheckTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/error/check/SecurityErrorCheckTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/ribbon/ApimlRetryableClientTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/ribbon/loadbalancer/InstanceInfoExtractorTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/ribbon/loadbalancer/LoadBalancerRuleAdapterTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/ribbon/loadbalancer/predicate/RequestHeaderPredicateTest.java
  gateway-service/src/test/resources/gateway-messages.yml
Labels: docs

#1502 chore: Remove unused apiml updater script
  README.md
  apiml-common-lib-package/build.gradle
  apiml-common-lib-package/src/main/update_apiml.sh
Labels: docs, size/L

#1505 chore: se any branch
  build.gradle
Labels: docs, size/XS

#1507 fix: dummy auth
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/dummy/DummyAuthenticationProvider.java
Labels: Sensitive, docs

#1508 fix: hide metrics from gw homepage
  gateway-service/src/main/resources/application.yml
Labels: docs, size/XS

#1518 Automate generation of Changelog via GH action
  .github/workflows/changelog.yml
  scripts/release_docs/index.js
  scripts/release_docs/package.json
Labels: docs, size/L

#1525 fix: integration tests fails
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/login/LoginRequest.java
  apiml-security-common/src/test/java/org/zowe/apiml/security/common/login/LoginRequestTest.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/saf/ZosAuthenticationProvider.java
  integration-tests/src/test/java/org/zowe/apiml/integration/authentication/schemes/PassticketSchemeTest.java
  integration-tests/src/test/java/org/zowe/apiml/util/config/ConfigReader.java
Labels: Sensitive

#1522 Add release 1.22 changelog
  CHANGELOG.md
Labels: docs, size/S

#1529 fix: key cache on commit hash
  .github/workflows/ci-tests.yml
Labels: size/M

#1514 Fix wrong using of certificates in ZAAS client
  zaas-client/src/main/java/org/zowe/apiml/zaasclient/config/ConfigProperties.java
  zaas-client/src/main/java/org/zowe/apiml/zaasclient/service/internal/ZaasClientImpl.java
  zaas-client/src/main/java/org/zowe/apiml/zaasclient/service/internal/ZaasHttpsClientProvider.java
  zaas-client/src/test/java/org/zowe/apiml/zaasclient/service/internal/ZaasClientImplHttpTests.java
  zaas-client/src/test/java/org/zowe/apiml/zaasclient/service/internal/ZaasClientTest.java
  zaas-client/src/test/java/org/zowe/apiml/zaasclient/service/internal/ZaasHttpsClientProviderTests.java
Labels: docs

#1534 chore: Run once a week th script for error messages
  .github/workflows/docs.yml
  scripts/docs/index.js
Labels: size/M

#1539 Fix for failing build due to Linux/IOS/Windows endofline differnces.
  metrics-service-ui/frontend/.eslintrc
Labels: size/XS

#1540 Update README.md
  README.md
Labels: size/XS

#1543 chore: Working automation of the changelog generation
  .github/workflows/changelog.yml
Labels: size/XS

#1526 fix: change order of authentication filters on Login endpoint
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/security/SecurityConfiguration.java
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/login/LoginFilter.java
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/login/NonCompulsoryAuthenticationProcessingFilter.java
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/login/ShouldBeAlreadyAuthenticatedFilter.java
  apiml-security-common/src/test/java/org/zowe/apiml/security/common/login/LoginFilterTest.java
  apiml-security-common/src/test/java/org/zowe/apiml/security/common/login/NonCompulsoryAuthenticationProcessingFilterTest.java
  apiml-security-common/src/test/java/org/zowe/apiml/security/common/login/ShouldBeAlreadyAuthenticatedFilterTest.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/config/SecurityConfiguration.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/config/X509AuthenticationFilter.java
  integration-tests/src/test/java/org/zowe/apiml/integration/authentication/providers/LoginTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/authentication/services/ZaasClientIntegrationTest.java
  metrics-service/src/main/java/org/zowe/apiml/metrics/security/SpringSecurityConfiguration.java
Labels: Sensitive

#1551 Don't use PR in master build
  .github/workflows/containers.yml
Labels: size/XS

#1553 Upgrade Eureka version
  common-service-core/build.gradle
  gradle/versions.gradle
  onboarding-enabler-java/build.gradle
Labels: size/XS

#1545 feat: Make cookie samesite configurable
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/config/AuthConfigurationProperties.java
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/login/SuccessfulLoginHandler.java
  apiml-security-common/src/test/java/org/zowe/apiml/security/common/config/AuthConfigurationPropertiesTest.java
  apiml-security-common/src/test/java/org/zowe/apiml/security/common/login/SuccessfulLoginHandlerTest.java
  common-service-core/src/main/java/org/zowe/apiml/util/CookieUtil.java
  common-service-core/src/test/java/org/zowe/apiml/util/CookieUtilTest.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/post/ConvertAuthTokenInUriToCookieFilter.java
  integration-tests/src/test/java/org/zowe/apiml/integration/authentication/providers/LoginTest.java
Labels: Sensitive

#1568 feat: Authenticate with client certificate for /apidoc/** routes
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/security/SecurityConfiguration.java
  api-catalog-services/src/main/resources/application.yml
  config/docker/api-catalog-services.yml
  integration-tests/src/test/java/org/zowe/apiml/functional/apicatalog/ApiCatalogAuthenticationTest.java
Labels: Sensitive
