Repository zowe/api-layer, pull requests merged in 2021-12, with the labels that each got.

#1940 chore: Update dependencies versions
  api-catalog-ui/frontend/package-lock.json
  api-catalog-ui/frontend/package.json
  gradle/versions.gradle
Labels: size/XS

#1900 feat: Migrate Login panel to Material UI
  api-catalog-ui/frontend/cypress/integration/e2e/login/login-bad.test.js
  api-catalog-ui/frontend/cypress/integration/mocked-e2e/login/login-bad.test.js
  api-catalog-ui/frontend/package-lock.json
  api-catalog-ui/frontend/package.json
  api-catalog-ui/frontend/src/assets/css/APIMReactToastify.css
  api-catalog-ui/frontend/src/components/App/App.test.js
  api-catalog-ui/frontend/src/components/Error/Error.test.jsx
  api-catalog-ui/frontend/src/components/ErrorBoundary/Shield/Shield.test.jsx
  api-catalog-ui/frontend/src/components/Login/Login.css
  api-catalog-ui/frontend/src/components/Login/Login.jsx
  api-catalog-ui/frontend/src/components/Login/Login.test.jsx
  api-catalog-ui/frontend/src/components/Search/SearchCriteria.test.jsx
  api-catalog-ui/frontend/src/components/Tile/Tile.test.jsx
Labels: size/L, Sensitive

#1942 chore: set node and npm
  .github/workflows/ci-tests.yml
  .github/workflows/containers.yml
  .github/workflows/create-image-without-release.yml
  .github/workflows/release.yml
  .github/workflows/snapshot-release.yml
  .github/workflows/specific-release.yml
  api-catalog-ui/build.gradle
  gradle.properties
  onboarding-enabler-nodejs/package.json
Labels: size/S

#1946 chore: use correct node cache
  .github/workflows/ci-tests.yml
  .github/workflows/containers.yml
  .github/workflows/create-image-without-release.yml
  .github/workflows/release.yml
  .github/workflows/snapshot-release.yml
  .github/workflows/specific-release.yml
  gradle.properties
  onboarding-enabler-nodejs/package.json
Labels: size/L

#1943 feat: Migrate header and footer to Material UI
  api-catalog-ui/frontend/src/components/Footer/Footer.jsx
  api-catalog-ui/frontend/src/components/Footer/Footer.test.jsx
  api-catalog-ui/frontend/src/components/Header/Header.css
  api-catalog-ui/frontend/src/components/Header/Header.jsx
  api-catalog-ui/frontend/src/components/Header/Header.test.jsx
Labels: size/M

#1949 feat: Migrate detail page to Material
  api-catalog-ui/frontend/src/components/DetailPage/DetailPage.css
  api-catalog-ui/frontend/src/components/DetailPage/DetailPage.jsx
  api-catalog-ui/frontend/src/components/ServiceTab/ServiceTab.css
  api-catalog-ui/frontend/src/components/ServiceTab/ServiceTab.jsx
  api-catalog-ui/frontend/src/components/ServiceTab/ServiceTab.test.jsx
Labels: size/L

#1953 chore: Update Servlet Version
  gradle/versions.gradle
Labels: size/XS

#1955 accept homepage without context path
  common-service-core/src/main/java/org/zowe/apiml/product/routing/RoutedServices.java
  common-service-core/src/test/java/org/zowe/apiml/product/routing/RoutedServicesTest.java
Labels: size/S

#1956 chore: merge main branch
  .github/workflows/ci-tests.yml
  .github/workflows/containers.yml
  .github/workflows/create-image-without-release.yml
  .github/workflows/release.yml
  .github/workflows/snapshot-release.yml
  .github/workflows/specific-release.yml
  api-catalog-ui/build.gradle
  api-catalog-ui/frontend/package-lock.json
  api-catalog-ui/frontend/package.json
  common-service-core/src/main/java/org/zowe/apiml/security/HttpsFactory.java
  common-service-core/src/test/java/org/zowe/apiml/security/SecurityTestUtils.java
  gradle/versions.gradle
Labels: size/L, Sensitive

#1957 feat: Migrate Error components to Material
  api-catalog-ui/frontend/src/components/Error/Error.jsx
  api-catalog-ui/frontend/src/components/Error/Error.test.jsx
  api-catalog-ui/frontend/src/components/Error/ErrorDialog.jsx
  api-catalog-ui/frontend/src/components/Error/ErrorDialog.test.jsx
  api-catalog-ui/frontend/src/components/Error/ErrorFormatter.jsx
  api-catalog-ui/frontend/src/components/ErrorBoundary/BigShield/BigShield.jsx
  api-catalog-ui/frontend/src/components/ErrorBoundary/Shield/Shield.jsx
  api-catalog-ui/frontend/src/components/ServiceTab/InstanceInfo.jsx
Labels: size/L

#1959 feat: Migrate dashboard to Material
  api-catalog-ui/frontend/src/components/Dashboard/Dashboard.css
  api-catalog-ui/frontend/src/components/Dashboard/Dashboard.jsx
  api-catalog-ui/frontend/src/components/Dashboard/Dashboard.test.jsx
  api-catalog-ui/frontend/src/components/Login/Login.css
  api-catalog-ui/frontend/src/components/Login/Login.jsx
  api-catalog-ui/frontend/src/components/PageNotFound/PageNotFound.css
  api-catalog-ui/frontend/src/components/PageNotFound/PageNotFound.jsx
  api-catalog-ui/frontend/src/components/Search/SearchCriteria.jsx
  api-catalog-ui/frontend/src/components/Search/SearchCriteria.test.jsx
  api-catalog-ui/frontend/src/components/Tile/Tile.css
  api-catalog-ui/frontend/src/components/Tile/Tile.jsx
  api-catalog-ui/frontend/src/components/Tile/Tile.test.jsx
Labels: size/L

#1963 chore: Add github action to publish PR snapshot
  .github/workflows/pull-request-snapshot-release.yml
  docs/release.md
Labels: size/M

#1960 Chore: Change mock-zosmf docker host to mock-services
  .github/workflows/containers.yml
  config/docker/api-defs/mock-services.yml
  config/docker/gateway-service.yml
  docker/ha-local/docker-compose.yml
  docker/local-single/docker-compose.yml
  integration-tests/src/test/resources/environment-configuration-docker.yml
  integration-tests/src/test/resources/environment-configuration-ha.yml
  keystore/docker/all-services.keystore.cer
  keystore/docker/all-services.keystore.csr
  keystore/docker/all-services.keystore.p12
  keystore/docker/all-services.keystore_signed.cer
  keystore/docker/all-services.truststore.p12
Labels: size/L

#1970 feat: infinispan storage
  .github/workflows/containers.yml
  caching-service/build.gradle
  caching-service/src/main/java/org/zowe/apiml/caching/CachingService.java
  caching-service/src/main/java/org/zowe/apiml/caching/config/GeneralConfig.java
  caching-service/src/main/java/org/zowe/apiml/caching/model/KeyValue.java
  caching-service/src/main/java/org/zowe/apiml/caching/service/infinispan/config/InfinispanConfig.java
  caching-service/src/main/java/org/zowe/apiml/caching/service/infinispan/exception/InfinispanConfigException.java
  caching-service/src/main/java/org/zowe/apiml/caching/service/infinispan/storage/InfinispanStorage.java
  caching-service/src/main/resources/application.yml
  caching-service/src/main/resources/infinispan.xml
  caching-service/src/test/java/org/zowe/apiml/caching/service/infinispan/storage/InfinispanStartupTest.java
  caching-service/src/test/java/org/zowe/apiml/caching/service/infinispan/storage/InfinispanStorageTest.java
  caching-service/src/test/resources/application.yml
  config/zowe-api-dev/alternative_start.sh
  config/zowe-api-dev/run-wrapper.sh
  gradle/versions.gradle
Labels: size/XL

#1964 Users/jack/test v2
  api-catalog-package/src/main/resources/bin/start.sh
  api-catalog-package/src/main/resources/bin/validate.sh
  api-catalog-package/src/main/resources/manifest.yaml
  caching-service-package/src/main/resources/bin/start.sh
  caching-service-package/src/main/resources/bin/validate.sh
  caching-service-package/src/main/resources/manifest.yaml
  discovery-package/src/main/resources/bin/start.sh
  discovery-package/src/main/resources/bin/validate.sh
  discovery-package/src/main/resources/manifest.yaml
  gateway-package/src/main/resources/bin/start.sh
  gateway-package/src/main/resources/bin/validate.sh
  gateway-package/src/main/resources/manifest.yaml
  gradle.properties
  integration-tests/src/test/java/org/zowe/apiml/util/service/FullApiMediationLayer.java
  integration-tests/src/test/java/org/zowe/apiml/util/service/RunningService.java
  integration-tests/src/test/resources/environment-configuration.yml
  metrics-service-package/src/main/resources/bin/start.sh
  metrics-service-package/src/main/resources/bin/validate.sh
  metrics-service-package/src/main/resources/manifest.yaml
  onboarding-enabler-nodejs/package.json
Labels: size/XL
