Repository zowe/api-layer, pull requests merged in 2021-09, with the labels that each got.

#1722 feat: Wizard configuration
  api-catalog-ui/frontend/src/actions/wizard-actions.jsx
  api-catalog-ui/frontend/src/actions/wizard-actions.test.jsx
  api-catalog-ui/frontend/src/components/Wizard/WizardDialog.jsx
  api-catalog-ui/frontend/src/components/Wizard/WizardDialog.test.jsx
  api-catalog-ui/frontend/src/components/Wizard/configs/wizard_categories.jsx
  api-catalog-ui/frontend/src/components/Wizard/configs/wizard_onboarding_methods.jsx
  api-catalog-ui/frontend/src/reducers/wizard-reducer.jsx
  api-catalog-ui/frontend/src/reducers/wizard-reducer.test.jsx
Labels: size/L

#1741 refactor: Remove required LAUNCH_COMPONENT from conformant containers environment variables
  api-catalog-package/src/main/resources/bin/start.sh
  caching-service-package/src/main/resources/bin/start.sh
  containers/README.md
  discovery-package/src/main/resources/bin/start.sh
  gateway-package/src/main/resources/bin/start.sh
Labels: size/M

#1744 fix: hide log messages with no value
  apiml-utility/src/main/java/org/zowe/apiml/product/logging/ApimlDependencyLogHider.java
Labels: size/XS

#1733 feat: Wizard NodeJS & Micronaut enablers' configurations
  api-catalog-ui/frontend/src/actions/wizard-actions.jsx
  api-catalog-ui/frontend/src/actions/wizard-actions.test.jsx
  api-catalog-ui/frontend/src/components/Wizard/WizardComponents/WizardInputs.jsx
  api-catalog-ui/frontend/src/components/Wizard/WizardComponents/WizardInputs.test.jsx
  api-catalog-ui/frontend/src/components/Wizard/configs/wizard_base_categories.jsx
  api-catalog-ui/frontend/src/components/Wizard/configs/wizard_categories.jsx
  api-catalog-ui/frontend/src/components/Wizard/configs/wizard_defaults.jsx
  api-catalog-ui/frontend/src/components/Wizard/configs/wizard_micronaut_categories.jsx
  api-catalog-ui/frontend/src/components/Wizard/configs/wizard_node_categories.jsx
  api-catalog-ui/frontend/src/components/Wizard/configs/wizard_onboarding_methods.jsx
  api-catalog-ui/frontend/src/components/Wizard/configs/wizard_spring_categories.jsx
  api-catalog-ui/frontend/src/components/Wizard/configs/wizard_static_categories.jsx
  api-catalog-ui/frontend/src/reducers/wizard-reducer.jsx
  api-catalog-ui/frontend/src/reducers/wizard-reducer.test.jsx
  onboarding-enabler-nodejs-sample-app/config/service-configuration.yml
Labels: size/XXL

#1749 refactor: Discovery service functional test infrastructure
  .run/spring-ApiCatalogApplication.run.xml
  config/docker/discovery-service.yml
  config/local/gateway-service.yml
  discovery-service/build.gradle
  discovery-service/src/main/resources/application.yml
  discovery-service/src/test/java/org/zowe/apiml/discovery/functional/DiscoveryFunctionalTest.java
  discovery-service/src/test/java/org/zowe/apiml/discovery/functional/HttpSecuredEndpointTest.java
  discovery-service/src/test/java/org/zowe/apiml/discovery/functional/HttpsSecuredEndpointsTest.java
  discovery-service/src/test/resources/application.yml
  integration-tests/build.gradle
  integration-tests/src/test/java/org/zowe/apiml/functional/apicatalog/ApiCatalogAuthenticationTest.java
  integration-tests/src/test/java/org/zowe/apiml/functional/caching/CachingAuthenticationTest.java
  integration-tests/src/test/java/org/zowe/apiml/functional/discovery/EurekaInstancesIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/functional/gateway/StaticClientRoutingEndpointsTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/authentication/providers/LoginTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/authentication/providers/RefreshTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/authentication/providers/ZosmfLoginTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/authentication/schemes/X509SchemeTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/discovery/DiscoveryAuthIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/external/CachingStorageTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/zos/ServicesInfoTest.java
  integration-tests/src/test/java/org/zowe/apiml/util/config/ItSslConfigFactory.java
  integration-tests/src/testFixtures/java/org/zowe/apiml/util/config/SslContext.java
  integration-tests/src/testFixtures/java/org/zowe/apiml/util/config/SslContextConfigurer.java
Labels: size/XL

#1752 feat: Wizard UX tweaks
  api-catalog-ui/frontend/src/components/Wizard/WizardComponents/WizardInputs.jsx
  api-catalog-ui/frontend/src/components/Wizard/WizardComponents/WizardNavigation.jsx
  api-catalog-ui/frontend/src/components/Wizard/WizardComponents/WizardNavigation.test.jsx
  api-catalog-ui/frontend/src/components/Wizard/WizardDialog.jsx
  api-catalog-ui/frontend/src/components/Wizard/wizard.css
Labels: size/S

#1759 feat: possibility to delete static def
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/staticapi/StaticDefinitionController.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/staticapi/StaticDefinitionGenerator.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/staticapi/StaticDefinitionControllerTest.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/staticapi/StaticDefinitionGeneratorTest.java
  integration-tests/src/test/java/org/zowe/apiml/functional/apicatalog/ApiCatalogEndpointIntegrationTest.java
Labels: size/L

#1761 fix: static definition generation tweaks
  api-catalog-package/src/main/resources/bin/start.sh
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/staticapi/StaticDefinitionGenerator.java
  integration-tests/src/test/java/org/zowe/apiml/functional/apicatalog/ApiCatalogEndpointIntegrationTest.java
Labels: size/L

#1764 feat: static api enpoints protected by SAF check
  api-catalog-package/src/main/resources/bin/start.sh
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/staticapi/StaticDefinitionController.java
  integration-tests/src/test/java/org/zowe/apiml/functional/apicatalog/ApiCatalogEndpointIntegrationTest.java
Labels: size/M

#1755 feat: Provide compression for specific paths only.
  .github/workflows/ci-tests.yml
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/pre/PerServiceGZipFilter.java
  gateway-service/src/main/resources/application.yml
  gateway-service/src/test/java/org/zowe/apiml/acceptance/CompressPerServiceTest.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/DeterministicUserBasedRoutingTest.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/RefreshEndpointTest.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/RequestInstanceTest.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/SafIdtSchemeTest.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/common/AcceptanceTestWithTwoServices.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/netflix/ApplicationRegistry.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/netflix/MetadataBuilder.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/filters/pre/PerServiceGZipFilterTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/login/zosmf/SaveZosmfPublicKeyConsoleApplicationTest.java
Labels: size/XL, Sensitive

#1763 Fix Zaas client to not send a certificate during authentication
  zaas-client/src/main/java/org/zowe/apiml/zaasclient/service/internal/ZaasHttpsClientProvider.java
  zaas-client/src/test/java/org/zowe/apiml/zaasclient/service/internal/ZaasHttpsClientProviderTests.java
Labels: size/M

#1765 chore: share filesystem for static definitions
  .github/workflows/containers.yml
  config/docker/api-catalog-services.yml
  config/docker/discovery-service.yml
  config/local/api-catalog-service.yml
  docker/ha-local/docker-compose.yml
  docker/local-single/docker-compose.yml
Labels: size/L

#1723 Server Sent Events Handler - Access Turbine SSE events through Gateway
  discoverable-client/build.gradle
  discoverable-client/src/main/java/org/zowe/apiml/client/sse/ServerSentEventController.java
  discoverable-client/src/main/resources/application.yml
  discoverable-client/src/test/java/org/zowe/apiml/client/sse/ServerSentEventControllerTest.java
  gateway-service/build.gradle
  gateway-service/src/main/java/org/zowe/apiml/gateway/sse/ServerSentEventProxyHandler.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/sse/SseErrorMessages.java
  gateway-service/src/main/resources/application.yml
  gateway-service/src/main/resources/gateway-log-messages.yml
  gateway-service/src/test/java/org/zowe/apiml/gateway/sse/ServerSentEventProxyHandlerTest.java
  gateway-service/src/test/resources/application-test.yml
  gateway-service/src/test/resources/application.yml
  gradle/versions.gradle
  integration-tests/build.gradle
  integration-tests/src/test/java/org/zowe/apiml/integration/proxy/ServerSentEventsProxyTest.java
Labels: size/XL

#1771 fix: Fix flaky unit test
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/AuthenticationServiceTest.java
Labels: size/S, Sensitive

#1775 V2 preparation
  .github/workflows/ci-tests.yml
  .github/workflows/codeql.yml
  .github/workflows/containers.yml
  .github/workflows/security-analysis.yml
  .github/workflows/snapshot-release.yml
  .github/workflows/statistics.yml
  scripts/statistics/ci.js
  scripts/statistics/index.js
  scripts/statistics/issues.js
  scripts/statistics/package.json
  scripts/statistics/pullRequests.js
Labels: size/L, Sensitive

#1772 feat: Wizard improvements
  api-catalog-ui/frontend/src/actions/wizard-actions.jsx
  api-catalog-ui/frontend/src/actions/wizard-actions.test.jsx
  api-catalog-ui/frontend/src/components/Dashboard/Dashboard.jsx
  api-catalog-ui/frontend/src/components/Dashboard/DashboardContainer.jsx
  api-catalog-ui/frontend/src/components/Wizard/DialogDropdown.jsx
  api-catalog-ui/frontend/src/components/Wizard/WizardComponents/WizardInputs.jsx
  api-catalog-ui/frontend/src/components/Wizard/WizardComponents/WizardInputs.test.jsx
  api-catalog-ui/frontend/src/components/Wizard/WizardComponents/WizardInputsContainer.jsx
  api-catalog-ui/frontend/src/components/Wizard/WizardComponents/WizardNavigation.jsx
  api-catalog-ui/frontend/src/components/Wizard/WizardComponents/WizardNavigation.test.jsx
  api-catalog-ui/frontend/src/components/Wizard/WizardComponents/WizardNavigationContainer.jsx
  api-catalog-ui/frontend/src/components/Wizard/WizardContainer.jsx
  api-catalog-ui/frontend/src/components/Wizard/WizardDialog.jsx
  api-catalog-ui/frontend/src/components/Wizard/WizardDialog.test.jsx
  api-catalog-ui/frontend/src/components/Wizard/configs/wizard_base_categories.jsx
  api-catalog-ui/frontend/src/components/Wizard/configs/wizard_defaults.jsx
  api-catalog-ui/frontend/src/components/Wizard/configs/wizard_micronaut_categories.jsx
  api-catalog-ui/frontend/src/components/Wizard/configs/wizard_node_categories.jsx
  api-catalog-ui/frontend/src/components/Wizard/configs/wizard_onboarding_methods.jsx
  api-catalog-ui/frontend/src/components/Wizard/configs/wizard_regex_restrictions.jsx
  api-catalog-ui/frontend/src/components/Wizard/configs/wizard_static_categories.jsx
  api-catalog-ui/frontend/src/components/Wizard/wizard.css
  api-catalog-ui/frontend/src/reducers/wizard-reducer.jsx
  api-catalog-ui/frontend/src/reducers/wizard-reducer.test.jsx
Labels: size/XXL

#1778 Add action to merge major version
  .github/workflows/merge-major-version.yml
Labels: size/S

#1781 Fix: Zuul semaphore concurrency configuration
  gateway-service/src/main/resources/application.yml
Labels: size/XS

#1785 Workflow no release
  .github/workflows/create-image-without-release.yml
Labels: size/L

#1782 feat: Certificate authentication for static refresh endpoint
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/security/SecurityConfiguration.java
  integration-tests/src/test/java/org/zowe/apiml/functional/apicatalog/ApiCatalogAuthenticationTest.java
Labels: size/L, Sensitive

#1789 chore: Github actions workflow name typo
  .github/workflows/release.yml
  .github/workflows/snapshot-release.yml
  .github/workflows/specific-release.yml
Labels: size/XS

#1788 Handle errors in apiversions and wrong URLs
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/services/cached/CachedProductFamilyService.java
  apiml-common/src/main/java/org/zowe/apiml/product/routing/transform/TransformService.java
Labels: size/S

#1792 chore: Option for creating specific service test image
  .github/workflows/create-image-without-release.yml
Labels: size/L

#1793 chore: create redis config beans conditionally
  caching-service/src/main/java/org/zowe/apiml/caching/service/redis/config/RedisConfig.java
  caching-service/src/main/java/org/zowe/apiml/caching/service/redis/config/RedisConfiguration.java
Labels: size/XS

#1794 chore: caching functional tests
  caching-service/build.gradle
  caching-service/src/test/java/org/zowe/apiml/caching/functional/InMemoryFunctionalTest.java
Labels: size/L

#1798 chore: security fixes guideline
  CONTRIBUTING.md
Labels: size/XS

#1803 chore: Api catalog functional tests infrastructure
  api-catalog-package/src/main/resources/bin/start.sh
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/ApiCatalogApplication.java
  api-catalog-services/src/main/resources/application.yml
  api-catalog-services/src/main/resources/parmlib.sh
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/controllers/api/ApiCatalogControllerContainerRetrievalTest.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/controllers/api/ApiCatalogControllerContainerRetrievalTestContextConfiguration.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/controllers/api/CatalogApiDocControllerApiDocNotFoundTest.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/controllers/api/CatalogApiDocControllerApiDocNotFoundTestContextConfiguration.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/controllers/api/CatalogApiDocControllerServiceNotFoundTest.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/controllers/api/CatalogApiDocControllerServiceNotFoundTestContextConfiguration.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/functional/ApiCatalogFunctionalTest.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/functional/PrototypeFunctionalTest.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/instance/InstanceRetrievalServiceTest.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/instance/InstanceServicesContextConfiguration.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/staticapi/StaticAPIRefreshControllerTest.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/staticapi/StaticApiContextConfiguration.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/staticapi/StaticDefinitionControllerTest.java
  api-catalog-services/src/test/resources/application.yml
  config/docker/api-catalog-services.yml
  config/local-multi/api-catalog-service-1.yml
  config/local-multi/api-catalog-service-2.yml
  config/local/api-catalog-service.yml
  config/zowe-api-dev/alternative_start.sh
  docs/local-configuration.md
Labels: size/XL

#1800 fix: Display multiple APIs with multiple different versions.
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/controllers/api/CatalogApiDocController.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/model/APIService.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/services/cached/CachedProductFamilyService.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/services/status/APIDocRetrievalService.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/services/status/APIServiceStatusService.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/controllers/api/CatalogApiDocControllerApiDocNotFoundTest.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/controllers/api/CatalogApiDocControllerApiDocNotFoundTestContextConfiguration.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/services/cached/CachedProductFamilyServiceTest.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/services/status/LocalApiDocServiceTest.java
  api-catalog-ui/frontend/src/components/ServiceTab/ServiceTab.jsx
  api-catalog-ui/frontend/src/components/ServiceTab/ServiceTab.test.jsx
  common-service-core/src/main/java/org/zowe/apiml/config/ApiInfo.java
  common-service-core/src/test/java/org/zowe/apiml/config/ApiInfoTest.java
  discoverable-client/src/main/java/org/zowe/apiml/client/api/GreetingGraphController.java
  discoverable-client/src/main/java/org/zowe/apiml/client/configuration/SwaggerConfiguration.java
  discoverable-client/src/main/resources/application.yml
  integration-tests/src/test/java/org/zowe/apiml/functional/apicatalog/ApiCatalogEndpointIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/discovery/ApiCatalogDiscoverableClientIntegrationTest.java
Labels: size/L
