Repository zowe/api-layer, pull requests merged in 2022-01, with the labels that each got.

#1974 Fix: Make ZWEAM511E message more accurate
  common-service-core/src/main/resources/core-log-messages.yml
Labels: size/S

#1947 feat: Create API ML sample extension
  .github/workflows/pull-request-snapshot-release.yml
  apiml-sample-extension-package/build.gradle
  apiml-sample-extension-package/src/main/resources/manifest.yaml
  apiml-sample-extension/README.md
  apiml-sample-extension/build.gradle
  apiml-sample-extension/src/main/java/org/zowe/apiml/gateway/api/GreetingController.java
  build.gradle
  gradle/license.gradle
  gradle/publish.gradle
  gradle/sonar.gradle
  settings.gradle
Labels: size/L

#1976 feat: remove jwtsecret from usage
  .github/workflows/snapshot-release.yml
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/config/AuthConfigurationProperties.java
  common-service-core/src/main/java/org/zowe/apiml/security/SecurityUtils.java
  common-service-core/src/test/java/org/zowe/apiml/security/SecurityUtilsTest.java
  common-service-core/src/test/resources/jwt-public-key.pub
  config/zowe-api-dev/alternative_start.sh
  config/zowe-api-dev/run-wrapper.sh
  gateway-package/src/main/resources/bin/start.sh
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/zosmf/JwkConversionError.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/zosmf/JwkToPublicKeyConverter.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/zosmf/SaveZosmfPublicKeyConsoleApplication.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/zosmf/ZosmfJwkToPublicKey.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/JwtSecurity.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/zosmf/ZosmfService.java
  gateway-service/src/main/resources/application.yml
  gateway-service/src/main/resources/gateway-log-messages.yml
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/login/zosmf/JwkToPublicKeyConverterTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/login/zosmf/SaveZosmfPublicKeyConsoleApplicationTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/login/zosmf/ZosmfJwkToPublicKeyTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/JwtSecurityTest.java
  gateway-service/src/test/resources/application-test.yml
  gateway-service/src/test/resources/application.yml
  gateway-service/src/test/resources/gateway-messages.yml
  integration-tests/src/test/java/org/zowe/apiml/integration/authentication/services/ZaasClientIntegrationTest.java
  keystore/docker/all-services.keystore.p12
  keystore/localhost/localhost-multi.keystore.p12
  keystore/localhost/localhost.keystore.p12
  zaas-client/src/test/java/org/zowe/apiml/zaasclient/service/internal/ZaasClientImplHttpsTests.java
Labels: size/XL, Sensitive

#1980 chore: higher timeouts
  .github/workflows/ci-tests.yml
  .github/workflows/create-image-without-release.yml
  .github/workflows/pull-request-snapshot-release.yml
  .github/workflows/release.yml
  .github/workflows/snapshot-release.yml
  .github/workflows/specific-release.yml
  gradle.properties
  onboarding-enabler-nodejs/package.json
Labels: size/M

#1983 Chore: Add performance test script for the Caching Service
  config/profiling/.gitignore
  config/profiling/README.md
  config/profiling/caching-profiling-parametrized.jmx
  config/profiling/mock_csv.csv
  config/profiling/mock_csv_small.csv
  config/profiling/run-profiling.sh
Labels: size/XXL

#1984 chore: test one thing at a time
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/AuthenticationService.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/AuthenticationServiceTest.java
Labels: size/S, Sensitive

#1989 Chore: Removed unnecessary exception signature
  metrics-service/src/test/java/org/zowe/apiml/metrics/functional/MetricsFunctionalTest.java
Labels: size/XS

#1991 Add Zaas methods for password change support
  zaas-client/src/main/java/org/zowe/apiml/zaasclient/service/ZaasClient.java
  zaas-client/src/main/java/org/zowe/apiml/zaasclient/service/internal/TokenService.java
  zaas-client/src/main/java/org/zowe/apiml/zaasclient/service/internal/ZaasClientImpl.java
  zaas-client/src/main/java/org/zowe/apiml/zaasclient/service/internal/ZaasJwtService.java
  zaas-client/src/test/java/org/zowe/apiml/zaasclient/service/internal/ZaasClientTest.java
Labels: size/M

#1997 Chore: Avoid jcenter respository
  api-catalog-services/gradle/lite.gradle
  discovery-service/gradle/lite.gradle
  gateway-service/gradle/lite.gradle
  gradle/coverage.gradle
  gradle/license.gradle
  gradle/publish.gradle
  metrics-service/gradle/lite.gradle
  onboarding-enabler-micronaut/build.gradle
  settings.gradle
Labels: size/S

#1998 minor grammar fix in docs/release.md
  docs/release.md
Labels: size/XS

#1993 Chore: Lower concurrency of s390x builds
  .github/workflows/build-conformant-images.yml
  .github/workflows/create-image-without-release.yml
  .github/workflows/release.yml
  .github/workflows/snapshot-release.yml
  .github/workflows/specific-release.yml
Labels: size/S

#2002 Chore: Increase build time
  .github/workflows/release.yml
  .github/workflows/snapshot-release.yml
  .github/workflows/specific-release.yml
Labels: size/XS

#2003 Fix: Add log masking class for sensitive logs
  apiml-common/src/main/resources/logback.xml
  apiml-utility/src/main/java/org/zowe/apiml/product/logging/MaskingLogPatternLayout.java
  apiml-utility/src/test/java/org/zowe/apiml/product/logging/MaskingLogPatternLayoutTest.java
  caching-service/src/main/resources/logback.xml
  metrics-service/src/main/resources/logback.xml
Labels: size/L

#2004 feat: use material in wizard
  api-catalog-ui/frontend/package-lock.json
  api-catalog-ui/frontend/package.json
  api-catalog-ui/frontend/src/components/Dashboard/Dashboard.css
  api-catalog-ui/frontend/src/components/Login/Login.css
  api-catalog-ui/frontend/src/components/Wizard/ConfirmDialog.jsx
  api-catalog-ui/frontend/src/components/Wizard/DialogDropdown.jsx
  api-catalog-ui/frontend/src/components/Wizard/DialogDropdown.test.jsx
  api-catalog-ui/frontend/src/components/Wizard/WizardComponents/WizardInputs.jsx
  api-catalog-ui/frontend/src/components/Wizard/WizardComponents/WizardInputs.test.jsx
  api-catalog-ui/frontend/src/components/Wizard/WizardComponents/WizardNavigation.jsx
  api-catalog-ui/frontend/src/components/Wizard/WizardComponents/WizardNavigation.test.jsx
  api-catalog-ui/frontend/src/components/Wizard/WizardDialog.jsx
  api-catalog-ui/frontend/src/components/Wizard/WizardDialog.test.jsx
  api-catalog-ui/frontend/src/components/Wizard/YAML/YAMLVisualizer.jsx
  api-catalog-ui/frontend/src/components/Wizard/wizard.css
Labels: size/XL

#1987 feat: Enable Discovery Service class path extensions and Gateway native library extensions
  discovery-package/src/main/resources/bin/start.sh
  gateway-package/src/main/resources/bin/start.sh
Labels: size/S

#2005 chore: Clean up Github workflows
  .github/actions/setup/action.yml
  .github/actions/teardown/action.yml
  .github/workflows/build-conformant-images.yml
  .github/workflows/ci-tests.yml
  .github/workflows/containers.yml
  .github/workflows/pull-request-snapshot-release.yml
  .github/workflows/release.yml
  .github/workflows/snapshot-release.yml
  .github/workflows/specific-release.yml
Labels: size/XL

#2009 fix: Build conformant images properly
  .github/actions/image-publish-setup/action.yml
  .github/workflows/build-conformant-images.yml
  .github/workflows/create-image-without-release.yml
  .github/workflows/release.yml
  .github/workflows/snapshot-release.yml
  .github/workflows/specific-release.yml
Labels: size/L

#2012 chore: Reduce ci duplication when releasing
  .github/workflows/release.yml
  .github/workflows/specific-release.yml
  build.gradle
Labels: size/XS

#2015 chore: Increase image build timeout
  .github/workflows/build-conformant-images.yml
Labels: size/XS

#2019 fix: Change homepage label to be consistent
  api-catalog-ui/frontend/src/components/ServiceTab/ServiceTab.jsx
Labels: size/XS

#2022 Fix: Updated URL for api catalog desktop app
  api-catalog-package/src/main/resources/plugin/pluginDefinition.json
Labels: size/XS

#2024 chore: Provide correct license for .json utilities
  scripts/docs/package.json
  scripts/release_docs/package.json
  scripts/security_sensitive/package.json
Labels: size/XS, Sensitive

#2035 feat: UI pass change
  api-catalog-ui/frontend/mocked-backend/assets/services/new-pass-not-valid.json
  api-catalog-ui/frontend/mocked-backend/assets/services/password-expired.json
  api-catalog-ui/frontend/mocked-backend/assets/services/user-suspended.json
  api-catalog-ui/frontend/mocked-backend/routes/routes.js
  api-catalog-ui/frontend/package-lock.json
  api-catalog-ui/frontend/package.json
  api-catalog-ui/frontend/src/actions/user-actions.jsx
  api-catalog-ui/frontend/src/assets/images/zowe-background.jpg
  api-catalog-ui/frontend/src/components/App/App.css
  api-catalog-ui/frontend/src/components/Login/Login.css
  api-catalog-ui/frontend/src/components/Login/Login.jsx
  api-catalog-ui/frontend/src/components/Login/Login.test.jsx
  api-catalog-ui/frontend/src/components/Login/LoginContainer.jsx
  api-catalog-ui/frontend/src/components/Spinner/Spinner.jsx
  api-catalog-ui/frontend/src/constants/user-constants.jsx
  api-catalog-ui/frontend/src/error-messages.json
  api-catalog-ui/frontend/src/reducers/authentication-reducer.jsx
  api-catalog-ui/frontend/src/reducers/authentication-reducer.test.jsx
  api-catalog-ui/frontend/src/reducers/loading-reducer.jsx
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/error/ErrorType.java
  apiml-security-common/src/main/resources/security-common-log-messages.yml
  security-service-client-spring/src/main/java/org/zowe/apiml/security/client/handler/RestResponseHandler.java
  security-service-client-spring/src/main/java/org/zowe/apiml/security/client/login/GatewayLoginProvider.java
  security-service-client-spring/src/main/java/org/zowe/apiml/security/client/service/GatewaySecurityService.java
  security-service-client-spring/src/test/java/org/zowe/apiml/security/client/handler/RestResponseHandlerTest.java
  security-service-client-spring/src/test/java/org/zowe/apiml/security/client/login/GatewayLoginProviderTest.java
  security-service-client-spring/src/test/java/org/zowe/apiml/security/client/service/GatewaySecurityServiceTest.java
Labels: size/XL, Sensitive

#2031 chore: Enable e2e in GitHub Actions
  .github/workflows/containers.yml
  api-catalog-ui/frontend/cypress/integration/e2e/dashboard/dashboard.test.js
  api-catalog-ui/frontend/cypress/integration/e2e/detail-page/detail-page.test.js
  api-catalog-ui/frontend/cypress/integration/e2e/detail-page/service-version-compare.test.js
  api-catalog-ui/frontend/package.json
  api-catalog-ui/frontend/src/components/ErrorBoundary/BigShield/BigShield.test.jsx
  api-catalog-ui/frontend/src/components/ErrorBoundary/Shield/Shield.test.jsx
Labels: size/L

#2050 fix: Enable password autofill for API Catalog
  api-catalog-ui/frontend/src/components/Login/Login.jsx
Labels: size/XL

#2051 chore: Remove micronaut enabler from projects to publish
  gradle/publish.gradle
Labels: size/XS

#2052 fix: publish images to appropriate Artifactory location
  .github/actions/image-publish-setup/action.yml
  .github/workflows/build-conformant-images.yml
  .github/workflows/create-image-without-release.yml
  .github/workflows/release.yml
  .github/workflows/snapshot-release.yml
  .github/workflows/specific-release.yml
Labels: size/M

#2055 chore: fix Sonar issue in tests
  common-service-core/src/test/java/org/zowe/apiml/config/ApiInfoTest.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/CompressPerServiceTest.java
Labels: size/XS
