Repository zowe/api-layer, pull requests merged in 2022-09, with the labels that each got.

#2565 fix: enable hsts
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/config/NewSecurityConfiguration.java
Labels: size/XS, Sensitive

#2567 fix: additionalProperties must be outside of properties attribute
  schemas/caching-schema.json
  schemas/catalog-schema.json
  schemas/discovery-schema.json
  schemas/gateway-schema.json
  schemas/metrics-schema.json
Labels: size/S

#2569 Fix tests in Windows
  apiml-extension-loader/src/test/java/org/zowe/apiml/extension/ExtensionConfigReaderTest.java
  common-service-core/src/test/java/org/zowe/apiml/security/SecurityUtilsTest.java
Labels: size/S, Sensitive

#2571 fix: Fix bug in the swagger
  api-catalog-ui/frontend/src/components/Swagger/SwaggerUI.jsx
  api-catalog-ui/frontend/src/components/Swagger/SwaggerUI.test.jsx
  api-catalog-ui/frontend/src/utils/generateSnippets.js
Labels: size/M

#2574 chore: update manifest id according to description
  api-catalog-package/src/main/resources/manifest.yaml
  apiml-common-lib-package/src/main/resources/manifest.yaml
  apiml-sample-extension-package/src/main/resources/manifest.yaml
  caching-service-package/src/main/resources/manifest.yaml
  discovery-package/src/main/resources/manifest.yaml
  gateway-package/src/main/resources/manifest.yaml
  metrics-service-package/src/main/resources/manifest.yaml
Labels: size/S

#2573 fix: Add build info to the manifest.yaml
  .github/workflows/automated-release.yml
  .github/workflows/binary-snapshot-release.yml
  .github/workflows/binary-specific-release.yml
  .github/workflows/pull-request-snapshot-release.yml
  api-catalog-package/build.gradle
  api-catalog-package/src/main/resources/manifest.yaml
  apiml-common-lib-package/build.gradle
  apiml-common-lib-package/src/main/resources/manifest.yaml
  apiml-sample-extension-package/build.gradle
  apiml-sample-extension-package/src/main/resources/manifest.yaml
  caching-service-package/build.gradle
  caching-service-package/src/main/resources/manifest.yaml
  containers/prepare-utils.sh
  discovery-package/build.gradle
  discovery-package/src/main/resources/manifest.yaml
  gateway-package/build.gradle
  gateway-package/src/main/resources/manifest.yaml
  metrics-service-package/build.gradle
  metrics-service-package/src/main/resources/manifest.yaml
Labels: size/L

#2577 fix: snakeyml update, scheme validation fix
  api-catalog-package/src/main/resources/manifest.yaml
  apiml-common-lib-package/src/main/resources/manifest.yaml
  apiml-extension-loader/build.gradle
  apiml-sample-extension-package/src/main/resources/manifest.yaml
  apiml-tomcat-common/build.gradle
  caching-service-package/src/main/resources/manifest.yaml
  common-service-core/build.gradle
  discovery-package/src/main/resources/manifest.yaml
  discovery-service/build.gradle
  gateway-package/src/main/resources/manifest.yaml
  gateway-service/build.gradle
  gradle/versions.gradle
  metrics-service-package/src/main/resources/manifest.yaml
  metrics-service/build.gradle
  onboarding-enabler-java-sample-app/build.gradle
  onboarding-enabler-java/build.gradle
Labels: size/M

#2575 fix: enable hsts (#2565)
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/config/NewSecurityConfiguration.java
Labels: size/XS, Sensitive

#2576 feat: new cloud gateway service
  .gitignore
  build.gradle
  cloud-gateway-package/build.gradle
  cloud-gateway-package/src/main/resources/bin/start.sh
  cloud-gateway-package/src/main/resources/bin/validate.sh
  cloud-gateway-package/src/main/resources/manifest.yaml
  cloud-gateway-package/src/test/java/.gitkeep
  cloud-gateway-service/.gitignore
  cloud-gateway-service/build.gradle
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/CloudGatewayServiceApplication.java
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/config/HttpConfig.java
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/service/RouteLocator.java
  cloud-gateway-service/src/main/resources/application.yml
  cloud-gateway-service/src/main/resources/cloud-gateway-log-messages.yml
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/config/HttpConfigTest.java
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/service/RouteLocatorTest.java
  cloud-gateway-service/src/test/resources/application.yml
  config/local/gateway-service.yml
  gradle/coverage.gradle
  gradle/license.gradle
  gradle/publish.gradle
  gradle/sonar.gradle
  gradle/versions.gradle
  integration-tests/src/test/java/org/zowe/apiml/startup/impl/ApiMediationLayerStartupChecker.java
  integration-tests/src/test/java/org/zowe/apiml/util/service/FullApiMediationLayer.java
  schemas/cloud-gateway-schema.json
  settings.gradle
Labels: size/XXL

#2581 chore: exclude snakeyaml
  api-catalog-services/build.gradle
  api-catalog-ui/build.gradle
  apiml-common/build.gradle
  apiml-sample-extension/build.gradle
  apiml-security-common/build.gradle
  caching-service/build.gradle
  cloud-gateway-service/build.gradle
  discoverable-client/build.gradle
  discovery-service/build.gradle
  gateway-service/build.gradle
  mock-services/build.gradle
  onboarding-enabler-spring/build.gradle
  security-service-client-spring/build.gradle
Labels: size/M, Sensitive

#2582 chore: do not include jars in package
  apiml-sample-extension/build.gradle
Labels: size/XS

#2587 replace script call with shared action
  .github/workflows/security-analysis.yml
  scripts/security_sensitive/index.js
  scripts/security_sensitive/package.json
Labels: size/M, Sensitive

#2589 chore: remove unused broken tests
  api-catalog-ui/frontend/cypress/integration/mocked-e2e/dashboard/dashboard.test.js
  api-catalog-ui/frontend/cypress/integration/mocked-e2e/detail/detail.test.js
  api-catalog-ui/frontend/cypress/integration/mocked-e2e/login/login-bad.test.js
  api-catalog-ui/frontend/cypress/integration/mocked-e2e/login/login-ok.test.js
  api-catalog-ui/frontend/package.json
Labels: size/L

#2592 fix: caching service references non-existent schema
  caching-service-package/src/main/resources/manifest.yaml
Labels: size/XS

#2595 fix: do not require clientAuth extension
  cloud-gateway-service/src/test/resources/application.yml
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/config/ComponentsConfiguration.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/x509/X509AbstractMapper.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/x509/X509CommonNameUserMapper.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/x509/X509ExternalMapper.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/source/X509AuthSourceService.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/SafIdtSchemeTest.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/X509SchemeTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/login/x509/X509CommonNameUserMapperTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/source/X509AuthSourceServiceTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/source/X509CNAuthSourceServiceTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/authentication/schemes/X509SchemeTest.java
  integration-tests/src/testFixtures/java/org/zowe/apiml/util/config/SslContext.java
Labels: size/L, Sensitive

#2599 chore: update checkout action
  .github/workflows/automated-release.yml
  .github/workflows/binary-snapshot-release.yml
  .github/workflows/binary-specific-release.yml
  .github/workflows/build-conformant-images.yml
  .github/workflows/changelog.yml
  .github/workflows/ci-tests.yml
  .github/workflows/codeql.yml
  .github/workflows/containers.yml
  .github/workflows/docs.yml
  .github/workflows/image-publish-branch.yml
  .github/workflows/image-snapshot-release.yml
  .github/workflows/image-specific-release.yml
  .github/workflows/pull-request-snapshot-release.yml
Labels: size/M

#2600 feat: route to service based on header
  .github/workflows/containers.yml
  build.gradle
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/config/HttpConfig.java
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/service/ProxyRouteLocator.java
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/service/RouteLocator.java
  cloud-gateway-service/src/main/resources/application.yml
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/config/HttpConfigTest.java
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/service/RouteLocatorTest.java
  cloud-gateway-service/src/test/resources/application.yml
  config/docker/cloud-gateway-service.yml
  integration-tests/build.gradle
  integration-tests/src/test/java/org/zowe/apiml/integration/proxy/CloudGatewayProxyTest.java
  integration-tests/src/test/java/org/zowe/apiml/util/config/CloudGatewayConfiguration.java
  integration-tests/src/test/java/org/zowe/apiml/util/config/ConfigReader.java
  integration-tests/src/test/java/org/zowe/apiml/util/config/EnvironmentConfiguration.java
  integration-tests/src/test/resources/environment-configuration-attls.yml
  integration-tests/src/test/resources/environment-configuration-docker.yml
  integration-tests/src/test/resources/environment-configuration-ha.yml
  integration-tests/src/test/resources/environment-configuration.yml
Labels: size/L

#2602 chore: patch updates of spring libraries
  discovery-service/build.gradle
  gradle/versions.gradle
Labels: size/S
