Repository zowe/api-layer, pull requests merged in 2022-07, with the labels that each got.

#2477 fix: Add missing function for building images
  containers/prepare-utils.sh
Labels: size/XS

#2476 feat: revoke PAT by admin
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/config/AccessTokenProviderConfig.java
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/config/AuthConfigurationProperties.java
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/error/ErrorType.java
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/login/BasicAuthFilter.java
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/login/LoginFilter.java
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/login/X509AuthAwareFilter.java
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/login/X509AuthenticationFilter.java
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/token/AccessTokenProvider.java
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/token/QueryResponse.java
  apiml-security-common/src/main/resources/security-common-log-messages.yml
  apiml-security-common/src/test/java/org/zowe/apiml/security/common/token/QueryResponseTest.java
  apiml-security-common/src/test/resources/security-service-messages.yml
  gateway-service/src/main/java/org/zowe/apiml/gateway/cache/CachingServiceClient.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/cache/CachingServiceClientException.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/controllers/AuthController.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/config/NewSecurityConfiguration.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/AuthenticationService.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/token/ApimlAccessTokenProvider.java
  gateway-service/src/main/resources/gateway-log-messages.yml
  gateway-service/src/test/java/org/zowe/apiml/gateway/controllers/AuthControllerTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/config/X509AuthenticationFilterTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/RequestAuthenticationServiceTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/source/JwtAuthSourceServiceTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/token/ApimlAccessTokenProviderTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/authentication/pat/AccessTokenServiceTest.java
  integration-tests/src/test/java/org/zowe/apiml/util/SecurityUtils.java
  integration-tests/src/test/java/org/zowe/apiml/util/requests/Endpoints.java
  security-service-client-spring/src/test/java/org/zowe/apiml/security/client/service/GatewaySecurityServiceTest.java
  security-service-client-spring/src/test/java/org/zowe/apiml/security/client/token/GatewayTokenProviderTest.java
Labels: size/XL, Sensitive

#2479 chore: npm and Node upgrades
  .babelrc.json
  .eslintrc.json
  api-catalog-ui/build.gradle
  api-catalog-ui/frontend/.babelrc.js
  api-catalog-ui/frontend/package-lock.json
  api-catalog-ui/frontend/package.json
  api-catalog-ui/frontend/src/actions/error-actions.jsx
  api-catalog-ui/frontend/src/actions/refresh-static-apis-actions.jsx
  api-catalog-ui/frontend/src/components/App/App.jsx
  api-catalog-ui/frontend/src/components/App/AppContainer.jsx
  api-catalog-ui/frontend/src/components/App/AsyncModules.jsx
  api-catalog-ui/frontend/src/components/Dashboard/Dashboard.test.jsx
  api-catalog-ui/frontend/src/components/DetailPage/DetailPage.jsx
  api-catalog-ui/frontend/src/components/Error/ErrorFormatter.jsx
  api-catalog-ui/frontend/src/components/ErrorBoundary/BigShield/BigShield.test.jsx
  api-catalog-ui/frontend/src/components/Header/Header.jsx
  api-catalog-ui/frontend/src/components/Login/Login.jsx
  api-catalog-ui/frontend/src/components/ServiceTab/ServiceTab.jsx
  api-catalog-ui/frontend/src/components/Swagger/SwaggerUI.jsx
  api-catalog-ui/frontend/src/components/Wizard/WizardComponents/WizardNavigation.jsx
  api-catalog-ui/frontend/src/components/Wizard/WizardComponents/WizardNavigation.test.jsx
  api-catalog-ui/frontend/src/components/Wizard/WizardDialog.test.jsx
  api-catalog-ui/frontend/src/constants/error-constants.jsx
  api-catalog-ui/frontend/src/epics/fetch-tiles-epic.test.jsx
  api-catalog-ui/frontend/src/epics/fetch-tiles.jsx
  api-catalog-ui/frontend/src/setupTests.js
  gradle/versions.gradle
  metrics-service-ui/build.gradle
  metrics-service-ui/frontend/.babelrc.js
  metrics-service-ui/frontend/package-lock.json
  metrics-service-ui/frontend/package.json
  metrics-service-ui/frontend/src/components/App/App.jsx
  metrics-service-ui/frontend/src/components/App/AppContainer.jsx
  metrics-service-ui/frontend/src/components/App/AsyncModules.jsx
  metrics-service-ui/frontend/src/components/AuthRoute/AuthRoute.test.jsx
  metrics-service-ui/frontend/src/components/Dashboard/Dashboard.jsx
  metrics-service-ui/frontend/src/components/Error/Error.jsx
  metrics-service-ui/frontend/src/components/Header/Header.jsx
  metrics-service-ui/frontend/src/components/Icons/MetricsIconButton.jsx
  metrics-service-ui/frontend/src/components/Login/Login.jsx
  metrics-service-ui/frontend/src/constants/error-constants.jsx
  onboarding-enabler-nodejs-sample-app/build.gradle
Labels: size/XL

#2492 chore: Upgrade jetty version
  gradle/versions.gradle
Labels: size/XS

#2494 chore: npm and Node upgrades
  api-catalog-ui/build.gradle
  api-catalog-ui/frontend/package-lock.json
  api-catalog-ui/frontend/package.json
  gradle/versions.gradle
  metrics-service-ui/build.gradle
  metrics-service-ui/frontend/package-lock.json
  metrics-service-ui/frontend/package.json
  onboarding-enabler-nodejs-sample-app/build.gradle
Labels: size/M

#2496 fix: immediately expires passticket command
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/config/AuthConfigurationProperties.java
  config/docker/gateway-service.yml
  config/local-multi/gateway-service-1.yml
  config/local-multi/gateway-service-2.yml
  config/local/gateway-service.yml
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/HttpBasicPassTicketScheme.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/HttpBasicPassTicketSchemeTest.java
  gateway-service/src/test/resources/application-test.yml
  gateway-service/src/test/resources/application.yml
Labels: size/M, Sensitive

#2500 fix: retrieve swagger api docs with or without certificate config enabled
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/services/status/APIDocRetrievalService.java
Labels: size/XS

#2514 fix: remove multiple tokens from cookies
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/HttpBasicPassTicketScheme.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/JwtCommand.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/SafIdtScheme.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/ZosmfScheme.java
Labels: size/M, Sensitive

#2520 Add octokit.request to push updates into open changelog PR
  scripts/release_docs/index.js
Labels: size/M

#2522 fix: enable redis storage mode in tests
  .github/workflows/containers.yml
  caching-service/src/main/resources/application.yml
  docker/redis/docker-compose-replica-tls.yml
Labels: size/M

#2509 feat: Code snippet configuration
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/model/APIService.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/services/cached/CachedProductFamilyService.java
  api-catalog-services/src/main/resources/application.yml
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/controllers/api/ApiCatalogControllerTests.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/services/cached/CachedProductFamilyServiceTest.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/services/status/ApiServiceStatusServiceTest.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/util/ContainerServiceMockUtil.java
  api-catalog-ui/frontend/src/components/ServiceTab/InstanceInfo.jsx
  api-catalog-ui/frontend/src/components/ServiceTab/InstanceInfo.test.jsx
  api-catalog-ui/frontend/src/components/Swagger/SwaggerUI.test.jsx
  common-service-core/src/main/java/org/zowe/apiml/config/ApiInfo.java
  common-service-core/src/main/java/org/zowe/apiml/config/CodeSnippet.java
  common-service-core/src/main/java/org/zowe/apiml/constants/EurekaMetadataDefinition.java
  common-service-core/src/main/java/org/zowe/apiml/eurekaservice/client/util/EurekaMetadataParser.java
  common-service-core/src/test/java/org/zowe/apiml/eurekaservice/client/util/EurekaMetadataParserTest.java
  config/local/api-defs/staticclient.yml
  discoverable-client/src/main/resources/application.yml
  discovery-service/src/main/java/org/zowe/apiml/discovery/staticdef/ServiceDefinitionProcessor.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/services/ServicesInfoService.java
  integration-tests/src/test/java/org/zowe/apiml/integration/discovery/ApiCatalogDiscoverableClientIntegrationTest.java
Labels: size/L

#2513 chore: Upgrade gradle to 7.5
  .github/workflows/ci-tests.yml
  .github/workflows/containers.yml
  api-catalog-package/build.gradle
  api-catalog-services/build.gradle
  api-catalog-services/gradle/lite.gradle
  apiml-common-lib-package/build.gradle
  apiml-common/build.gradle
  apiml-extension-loader/build.gradle
  apiml-sample-extension-package/build.gradle
  apiml-sample-extension/build.gradle
  apiml-security-common/build.gradle
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/config/AccessTokenProviderConfig.java
  apiml-tomcat-common/build.gradle
  apiml-utility/build.gradle
  build.gradle
  caching-service-package/build.gradle
  caching-service/build.gradle
  certificate-analyser/build.gradle
  common-service-core/build.gradle
  discoverable-client/build.gradle
  discovery-package/build.gradle
  discovery-service/build.gradle
  discovery-service/gradle/lite.gradle
  gateway-package/build.gradle
  gateway-service/build.gradle
  gateway-service/gradle/lite.gradle
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/HttpBasicPassTicketSchemeTest.java
  gradle/coverage.gradle
  gradle/generate-pom.gradle
  gradle/lite-project.gradle
  gradle/lite.gradle
  gradle/publish.gradle
  gradle/versions.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  integration-tests/build.gradle
  metrics-service-package/build.gradle
  metrics-service/build.gradle
  metrics-service/gradle/lite.gradle
  mock-services/build.gradle
  onboarding-enabler-java-sample-app-plain-java/build.gradle
  onboarding-enabler-java-sample-app/build.gradle
  onboarding-enabler-java/build.gradle
  onboarding-enabler-micronaut-sample-app/build.gradle
  onboarding-enabler-micronaut/build.gradle
  onboarding-enabler-spring-sample-app/build.gradle
  onboarding-enabler-spring/build.gradle
  package-lock.json
  security-service-client-spring/build.gradle
  zaas-client/build.gradle
  zaas-client/src/test/java/org/zowe/apiml/zaasclient/service/internal/ZaasJwtServiceTest.java
Labels: size/XXL, Sensitive

#2528 fix: gradle publish after update
  caching-service/build.gradle
  gradle/publish.gradle
Labels: size/S

#2536 chore: Remove new label from release issue template
  .github/ISSUE_TEMPLATE/release_support.md
Labels: size/XS
