Repository zowe/api-layer, pull requests merged in 2022-03, with the labels that each got.

#2128 fix: Properly remove services when instances are removed from Discovery Service
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/config/CachingConfig.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/instance/InstanceRefreshService.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/model/APIService.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/services/cached/CachedProductFamilyService.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/instance/InstanceRefreshServiceTest.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/services/cached/CachedProductFamilyServiceTest.java
Labels: size/L

#2137 chore: Upgrade dependency versions
  apiml-tomcat-common/build.gradle
  apiml-tomcat-common/src/test/java/org/zowe/apiml/product/web/ApimlTomcatCustomizerTest.java
  onboarding-enabler-micronaut-sample-app/build.gradle
  onboarding-enabler-micronaut-sample-app/src/test/java/org/zowe/apiml/HealthControllerTest.java
  onboarding-enabler-micronaut/build.gradle
Labels: size/S

#2142 fix: Document x509 auth in GW API doc
  gateway-service/src/main/resources/gateway-api-doc.json
  gateway-service/src/test/resources/api-doc.json
Labels: size/XS

#2141 fix: Show tooltips properly
  api-catalog-ui/frontend/src/components/ServiceTab/InstanceInfo.jsx
Labels: size/XS

#2149 chore: Cherry pick instead of merge
  .github/workflows/merge-major-version.yml
  scripts/create_pull_request/index.js
  scripts/create_pull_request/package-lock.json
  scripts/create_pull_request/package.json
Labels: size/M

#2154 fix: configure southbound timeout with APIML_GATEWAY_TIMEOUT_MILLIS
  gateway-service/src/main/resources/application.yml
  integration-tests/src/test/java/org/zowe/apiml/functional/gateway/GatewayTimeoutTest.java
Labels: size/S

#2162 chore: Update permissions after HA run
  .github/actions/setup/action.yml
  .github/workflows/containers.yml
Labels: size/S

#2159 fix: Versioning in image publishing workflow
  .github/actions/image-publish-setup/action.yml
  .github/workflows/image-publish-branch.yml
Labels: size/XS

#2163 refactor: introduce dedicated origin of the authentication source
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/ZosmfScheme.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/source/AuthSource.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/source/AuthSourceServiceImpl.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/source/JwtAuthSource.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/ServiceAuthenticationServiceImplTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/AuthenticationSchemeFactoryTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/HttpBasicPassTicketSchemeTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/SafIdtSchemeTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/ZosmfSchemeTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/source/AuthSourceServiceImplTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/source/AuthSourceTest.java
Labels: size/L, Sensitive

#2146 feat: Add ApimlX509Filter to default filterchain.
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/security/SecurityConfiguration.java
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/filter/CategorizeCertsFilter.java
  apiml-security-common/src/test/java/org/zowe/apiml/security/common/filter/ApimlX509FilterTest.java
  apiml-security-common/src/test/java/org/zowe/apiml/security/common/filter/CategorizeCertsFilterTest.java
  gateway-service/build.gradle
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/config/NewSecurityConfiguration.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/config/SecurityConfiguration.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/X509SchemeTest.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/netflix/MetadataBuilder.java
Labels: size/XL, Sensitive

#2170 chore: Mocked backend for Metrics Service
  metrics-service-ui/frontend/mocked-backend/assets/invalid-credentials.json
  metrics-service-ui/frontend/mocked-backend/assets/login-success.json
  metrics-service-ui/frontend/mocked-backend/assets/services/clusters.json
  metrics-service-ui/frontend/mocked-backend/assets/services/metrics.txt
  metrics-service-ui/frontend/mocked-backend/assets/timeout-error.json
  metrics-service-ui/frontend/mocked-backend/routes.js
  metrics-service-ui/frontend/mocked-backend/server.js
  metrics-service-ui/frontend/package-lock.json
  metrics-service-ui/frontend/package.json
  metrics-service-ui/frontend/src/components/Dashboard/Dashboard.jsx
Labels: size/L

#2156 fix: update data model for infinispan
  caching-service/src/main/java/org/zowe/apiml/caching/service/infinispan/storage/InfinispanStorage.java
  caching-service/src/test/java/org/zowe/apiml/caching/service/infinispan/storage/InfinispanStorageTest.java
  config/profiling/run-profiling.sh
Labels: size/L

#2168 refactor: Refactored PostStoreLoadBalancerCacheFilter and LocationFilter
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/post/PostStoreLoadBalancerCacheFilter.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/pre/LocationFilter.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/filters/post/PostStoreLoadBalancerCacheFilterTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/filters/pre/LocationFilterTest.java
Labels: size/L

#2178 fix: Improve error handling for API diff endpoint
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/services/status/APIServiceStatusService.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/services/status/ApiServiceStatusServiceTest.java
Labels: size/M

#2181 fix: Use tr instead of upper_case
  api-catalog-package/src/main/resources/bin/start.sh
  caching-service-package/src/main/resources/bin/start.sh
  discovery-package/src/main/resources/bin/start.sh
  gateway-package/src/main/resources/bin/start.sh
  metrics-service-package/src/main/resources/bin/start.sh
Labels: size/S

#2180 chore: Cherry pick commits from master
  .github/actions/image-publish-setup/action.yml
  .github/actions/setup/action.yml
  .github/workflows/containers.yml
  .github/workflows/image-publish-branch.yml
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/services/status/APIServiceStatusService.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/services/status/ApiServiceStatusServiceTest.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/post/ConvertAuthTokenInUriToCookieFilter.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/post/DebugHeaderFilter.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/post/PageRedirectionFilter.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/post/PerServiceAddResponseHeadersFilter.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/post/PostStoreLoadBalancerCacheFilter.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/post/PostZuulFilter.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/post/RoutedInstanceIdFilter.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/pre/EncodedCharactersFilter.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/pre/HeaderSanitizerFilter.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/pre/LocationFilter.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/pre/PerServiceIgnoreHeaderFilter.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/pre/PreZuulFilter.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/pre/ServiceAuthenticationFilter.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/pre/ServiceNotFoundFilter.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/pre/SlashFilter.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/routing/FilterConfig.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/services/ServiceInstancesUtils.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/filters/post/ConvertAuthTokenInUriToCookieFilterTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/filters/post/PerServiceAddResponseHeadersFilterTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/filters/post/PostStoreLoadBalancerCacheFilterTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/filters/pre/LocationFilterTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/filters/pre/PerServiceIgnoreHeaderFilterTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/filters/pre/ServiceNotFoundFilterTest.java
  metrics-service-ui/frontend/mocked-backend/assets/invalid-credentials.json
  metrics-service-ui/frontend/mocked-backend/assets/login-success.json
  metrics-service-ui/frontend/mocked-backend/assets/services/clusters.json
  metrics-service-ui/frontend/mocked-backend/assets/services/metrics.txt
  metrics-service-ui/frontend/mocked-backend/assets/timeout-error.json
  metrics-service-ui/frontend/mocked-backend/routes.js
  metrics-service-ui/frontend/mocked-backend/server.js
  metrics-service-ui/frontend/package-lock.json
  metrics-service-ui/frontend/package.json
  metrics-service-ui/frontend/src/components/Dashboard/Dashboard.jsx
Labels: size/XXL

#2183 fix: Image publish with proper input name
  .github/actions/image-publish-setup/action.yml
Labels: size/XS

#2184 fix: Typo in image setup input name
  .github/actions/image-publish-setup/action.yml
Labels: size/XS

#2177 feat: publish jacococ results
  .github/actions/dump-jacoco/action.yml
  .github/workflows/ci-tests.yml
  .github/workflows/containers.yml
  gradle/coverage.gradle
  gradle/jib.gradle
  gradle/sonar.gradle
  package.json
  scripts/jacocoagent.jar
  scripts/jacococli.jar
Labels: size/L

#2192 fix: use unique artifacts for gha
  .github/workflows/ci-tests.yml
  .github/workflows/containers.yml
  .github/workflows/docs.yml
Labels: size/M

#2190 chore: Return classes that extenders depend on
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/pre/RequestContextProvider.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/pre/RequestContextProviderThreadLocal.java
Labels: size/M

#2188 feat: Add Cluster Option to HTTP Metric Data Source Plugin
  metrics-service-ui/data-source-plugin/README.md
  metrics-service-ui/data-source-plugin/config/default.json
  metrics-service-ui/data-source-plugin/src/ConfigEditor.tsx
  metrics-service-ui/data-source-plugin/src/QueryEditor.tsx
  metrics-service-ui/data-source-plugin/src/datasource.ts
  metrics-service-ui/data-source-plugin/src/module.ts
  metrics-service-ui/data-source-plugin/src/types.ts
Labels: size/L

#2197 fix: Add BearerContent filter to enable bearer auth
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/security/SecurityConfiguration.java
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/content/BearerContentFilter.java
  apiml-security-common/src/test/java/org/zowe/apiml/security/common/content/BasicContentFilterTest.java
  apiml-security-common/src/test/java/org/zowe/apiml/security/common/content/BearerContentFilterTest.java
  discovery-service/src/main/java/org/zowe/apiml/discovery/config/HttpsWebSecurityConfig.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/config/NewSecurityConfiguration.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/config/SecurityConfiguration.java
  integration-tests/src/test/java/org/zowe/apiml/functional/apicatalog/ApiCatalogAuthenticationTest.java
  integration-tests/src/test/java/org/zowe/apiml/functional/discovery/DiscoveryServiceAuthenticationTest.java
  integration-tests/src/test/java/org/zowe/apiml/functional/gateway/GatewayAuthenticationTest.java
Labels: size/XXL, Sensitive

#2214 chore: Upgrade dependencies
  apiml-tomcat-common/build.gradle
  common-service-core/build.gradle
  gradle/versions.gradle
  mock-services/build.gradle
Labels: size/XS

#2216 refactor: Update the mock functionality
  README.md
  mock-services/build.gradle
  mock-services/src/main/java/org/zowe/apiml/zss/api/SafIdtController.java
  mock-services/src/main/java/org/zowe/apiml/zss/model/Authentication.java
  mock-services/src/main/java/org/zowe/apiml/zss/model/Token.java
  mock-services/src/main/java/org/zowe/apiml/zss/services/SafIdtProvider.java
  mock-services/src/test/java/org/zowe/apiml/zss/api/SafIdtControllerTest.java
  mock-services/src/test/java/org/zowe/apiml/zss/services/SafIdtProviderTest.java
Labels: size/M

#2219 refactor: Introduce applid to the SafIdtProvider
  config/docker/api-defs/staticclient.yml
  config/local/api-defs-http/staticclient.yml
  config/local/api-defs/staticclient.yml
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/saf/SafIdtProvider.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/saf/SafRestAuthenticationService.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/SafIdtScheme.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/SafIdtSchemeTest.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/netflix/MetadataBuilder.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/saf/SafRestAuthenticationServiceTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/SafIdtSchemeTest.java
Labels: size/L, Sensitive

#2222 fix: caching service logging
  caching-service-package/src/main/resources/bin/start.sh
  caching-service/build.gradle
  caching-service/src/main/resources/application.yml
  caching-service/src/main/resources/logback.xml
Labels: size/S

#2221 fix: caching service logging
  caching-service-package/src/main/resources/bin/start.sh
  caching-service/build.gradle
  caching-service/src/main/resources/application.yml
  caching-service/src/main/resources/logback.xml
Labels: size/S

#2207 feat: Enhance zosmf authentication scheme to support client certificates
  gateway-service/build.gradle
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/config/ComponentsConfiguration.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/AuthenticationService.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/AuthenticationSchemeNotSupportedException.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/ZosmfScheme.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/source/AuthSourceService.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/source/DefaultAuthSourceService.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/source/JwtAuthSourceService.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/source/X509AuthSourceService.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/ZosmfSchemeTest.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/common/AcceptanceTestWithTwoServices.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/config/GatewayOverrideConfig.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/AuthenticationServiceTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/ZosmfSchemeTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/source/X509AuthSourceServiceTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/utils/JWTUtils.java
  gateway-service/src/test/resources/application.yml
  gradle/versions.gradle
  integration-tests/src/test/java/org/zowe/apiml/integration/authentication/providers/ZosmfLoginTest.java
Labels: size/XL, Sensitive

#2225 chore: Allow integration tests to be run manually
  .github/workflows/ci-tests.yml
  .github/workflows/containers.yml
Labels: size/XS

#2226 chore: allow tests to be run manually
  .github/workflows/ci-tests.yml
  .github/workflows/containers.yml
Labels: size/XS

#2232 chore: update release template
  .github/ISSUE_TEMPLATE/release_support.md
Labels: size/XS

#2234 chore: Upgrade Jackson
  api-catalog-services/build.gradle
  caching-service/build.gradle
  discovery-service/build.gradle
  gateway-service/build.gradle
  gradle/versions.gradle
  integration-tests/build.gradle
  zaas-client/build.gradle
Labels: size/S

#2194 feat: Add missing tooltips to all onboarding options
  api-catalog-ui/frontend/src/components/Wizard/configs/wizard_base_categories.jsx
  api-catalog-ui/frontend/src/components/Wizard/configs/wizard_micronaut_categories.jsx
  api-catalog-ui/frontend/src/components/Wizard/configs/wizard_node_categories.jsx
  api-catalog-ui/frontend/src/components/Wizard/configs/wizard_spring_categories.jsx
  api-catalog-ui/frontend/src/components/Wizard/configs/wizard_static_categories.jsx
Labels: size/L

#2227 fix: zaas client supports v2 compatibility with both gateway endpoint base Url paths
  zaas-client/src/main/java/org/zowe/apiml/zaasclient/config/ConfigProperties.java
  zaas-client/src/test/java/org/zowe/apiml/zaasclient/service/internal/ZaasClientApimlBaseUrlTest.java
Labels: size/M

#2237 refactor: Move passticket related code to mockzos
  .github/workflows/ci-tests.yml
  build.gradle
  common-service-core/build.gradle
  common-service-core/src/main/java/org/zowe/apiml/passticket/AbstractIRRPassTicketException.java
  common-service-core/src/main/java/org/zowe/apiml/passticket/IRRPassTicket.java
  common-service-core/src/main/java/org/zowe/apiml/passticket/PassTicketService.java
  common-service-core/src/test/java/org/zowe/apiml/passticket/AbstractIRRPassTicketExceptionTest.java
  common-service-core/src/test/java/org/zowe/apiml/passticket/IRRPassTicketEvaluationExceptionTest.java
  common-service-core/src/test/java/org/zowe/apiml/passticket/IRRPassTicketGenerationExceptionTest.java
  common-service-core/src/test/java/org/zowe/apiml/passticket/PassTicketServiceTest.java
  discoverable-client/build.gradle
  discoverable-client/src/main/java/org/zowe/apiml/client/api/PassTicketTestController.java
  gateway-package/src/main/resources/bin/start.sh
  gateway-service/build.gradle
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/TokenCreationService.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/saf/SafRestAuthenticationService.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/HttpBasicPassTicketScheme.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/SafIdtScheme.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/ticket/SuccessfulTicketHandler.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/TokenCreationServiceTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/saf/SafRestAuthenticationServiceTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/HttpBasicPassTicketSchemeTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/SafIdtSchemeTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/ticket/SuccessfulTicketHandlerTest.java
  gradle/jib.gradle
  gradle/publish.gradle
  integration-tests/build.gradle
  integration-tests/src/test/java/org/zowe/apiml/integration/zos/PassTicketTest.java
  integration-tests/src/test/java/org/zowe/apiml/util/service/FullApiMediationLayer.java
  mock-zos/build.gradle
  mock-zos/src/main/java/com/ibm/eserver/zos/racf/AbstractIRRPassTicketException.java
  mock-zos/src/main/java/com/ibm/eserver/zos/racf/IRRPassTicket.java
  mock-zos/src/main/java/com/ibm/eserver/zos/racf/IRRPassTicketEvaluationException.java
  mock-zos/src/main/java/com/ibm/eserver/zos/racf/IRRPassTicketGenerationException.java
  mock-zos/src/main/java/com/ibm/eserver/zos/racf/ObjectUtil.java
  mock-zos/src/test/java/com/ibm/eserver/zos/racf/IRRPassTicketTest.java
  package.json
  runIT
  settings.gradle
Labels: size/XXL

#2236 refactor: Refactor ZUtil from eureka-service to mock-zos
  .gitignore
  discoverable-client/build.gradle
  mock-zos/build.gradle
  mock-zos/src/main/java/com/ibm/jzos/ZUtil.java
  onboarding-enabler-java/build.gradle
  onboarding-enabler-java/src/main/java/org/zowe/apiml/eurekaservice/client/impl/DefaultCustomMetadataHelper.java
  onboarding-enabler-java/src/main/java/org/zowe/apiml/eurekaservice/client/impl/ZUtil.java
  onboarding-enabler-java/src/test/java/org/zowe/apiml/eurekaservice/client/impl/ApiMediationClientImplTest.java
  settings.gradle
Labels: size/L

#2239 chore: Improved integration and unit tests for v1 and v2 base urls
  integration-tests/src/test/java/org/zowe/apiml/util/config/ConfigReaderZaasClient.java
  zaas-client/src/test/java/org/zowe/apiml/zaasclient/service/internal/ZaasClientImplHttpTests.java
Labels: size/S

#2244 feat: Enhance x509 authentication scheme to support client certificates (part 1)
  common-service-core/src/main/java/org/zowe/apiml/auth/Authentication.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/pre/ServiceAuthenticationFilter.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/ribbon/http/ServiceAuthenticationDecorator.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/ServiceAuthenticationServiceImpl.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/AbstractAuthenticationScheme.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/HttpBasicPassTicketScheme.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/SafIdtScheme.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/ServiceAuthenticationService.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/ZosmfScheme.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/filters/pre/ServiceAuthenticationFilterTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/ribbon/http/ServiceAuthenticationDecoratorTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/ServiceAuthenticationServiceImplTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/HttpBasicPassTicketSchemeTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/SafIdtSchemeTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/ZosmfSchemeTest.java
Labels: size/L, Sensitive
