Repository zowe/api-layer, pull requests merged in 2022-02, with the labels that each got.

#2060 chore: fix Sonar issue in UI
  api-catalog-ui/frontend/src/reducers/filters-reducer.jsx
  api-catalog-ui/frontend/src/reducers/filters-reducer.test.jsx
  api-catalog-ui/frontend/src/reducers/index.jsx
  api-catalog-ui/frontend/src/reducers/tiles-reducer.jsx
  api-catalog-ui/frontend/src/reducers/tiles-reducer.test.jsx
Labels: size/S

#2061 fix: UI bug polishing in v2
  api-catalog-ui/frontend/src/actions/refresh-static-apis-actions.jsx
  api-catalog-ui/frontend/src/actions/wizard-fetch-actions.jsx
  api-catalog-ui/frontend/src/assets/css/APIMReactToastify.css
  api-catalog-ui/frontend/src/components/Header/Header.css
  api-catalog-ui/frontend/src/components/Header/Header.jsx
  api-catalog-ui/frontend/src/components/Login/Login.jsx
  api-catalog-ui/frontend/src/components/Login/Login.test.jsx
  api-catalog-ui/frontend/src/components/Wizard/wizard.css
Labels: size/L

#2066 chore: fix Sonar issue in UI
  api-catalog-ui/frontend/src/components/Swagger/Swagger.test.jsx
  api-catalog-ui/frontend/src/components/Swagger/SwaggerContainer.jsx
  api-catalog-ui/frontend/src/components/Swagger/SwaggerUI.jsx
  api-catalog-ui/frontend/src/components/Swagger/SwaggerUI.test.jsx
Labels: size/L

#2075 chore: separate snapshot release of images and binaries
  .github/workflows/binary-snapshot-release.yml
  .github/workflows/build-conformant-images.yml
  .github/workflows/image-snapshot-release.yml
Labels: size/M

#2068 fix: login page styles
  api-catalog-ui/frontend/cypress/integration/e2e/login/login-bad.test.js
  api-catalog-ui/frontend/cypress/integration/mocked-e2e/login/login-bad.test.js
  api-catalog-ui/frontend/mocked-backend/assets/services/user-name-invalid.json
  api-catalog-ui/frontend/mocked-backend/routes/routes.js
  api-catalog-ui/frontend/src/actions/user-actions.jsx
  api-catalog-ui/frontend/src/components/Dashboard/Dashboard.jsx
  api-catalog-ui/frontend/src/components/Dashboard/Dashboard.test.jsx
  api-catalog-ui/frontend/src/components/Dashboard/DashboardContainer.jsx
  api-catalog-ui/frontend/src/components/Login/Login.css
  api-catalog-ui/frontend/src/components/Login/Login.jsx
  api-catalog-ui/frontend/src/components/Login/Login.test.jsx
  api-catalog-ui/frontend/src/components/Wizard/DialogDropdown.jsx
  api-catalog-ui/frontend/src/constants/user-constants.jsx
  api-catalog-ui/frontend/src/error-messages.json
  api-catalog-ui/frontend/src/reducers/authentication-reducer.jsx
  api-catalog-ui/frontend/src/reducers/authentication-reducer.test.jsx
  api-catalog-ui/frontend/src/reducers/loading-reducer.jsx
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/error/ErrorType.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/dummy/DummyAuthenticationProvider.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/zosmf/ZosmfAuthenticationProvider.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/zosmf/AbstractZosmfService.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/login/dummy/DummyAuthenticationProviderTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/login/zosmf/ZosmfAuthenticationProviderTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/AuthenticationServiceTest.java
  metrics-service-ui/frontend/src/components/Login/Login.test.jsx
  security-service-client-spring/src/main/java/org/zowe/apiml/security/client/login/GatewayLoginProvider.java
  security-service-client-spring/src/test/java/org/zowe/apiml/security/client/service/GatewaySecurityServiceTest.java
Labels: size/XL, Sensitive

#2077 chore: Update micronaut to the working version
  gradle/coverage.gradle
  gradle/license.gradle
  gradle/publish.gradle
  onboarding-enabler-micronaut-sample-app/build.gradle
  onboarding-enabler-micronaut/build.gradle
  settings.gradle
Labels: size/S

#2069 fix: Reflect different options for the calls to the catalog's backend
  api-catalog-ui/frontend/cypress/integration/e2e/dashboard/dashboard.test.js
  api-catalog-ui/frontend/cypress/integration/e2e/detail-page/detail-page.test.js
  api-catalog-ui/frontend/cypress/integration/e2e/detail-page/service-version-compare.test.js
  api-catalog-ui/frontend/cypress/integration/e2e/detail-page/service-version-switch.test.js
  api-catalog-ui/frontend/cypress/integration/e2e/detail-page/swagger-try-out.test.js
  api-catalog-ui/frontend/cypress/integration/e2e/login/login-bad.test.js
  api-catalog-ui/frontend/cypress/integration/e2e/login/login-ok.test.js
  api-catalog-ui/frontend/package.json
  api-catalog-ui/frontend/src/actions/refresh-static-apis-actions.jsx
  api-catalog-ui/frontend/src/actions/service-version-diff-actions.jsx
  api-catalog-ui/frontend/src/actions/user-actions.jsx
  api-catalog-ui/frontend/src/actions/wizard-fetch-actions.jsx
  api-catalog-ui/frontend/src/components/Swagger/Swagger.jsx
  api-catalog-ui/frontend/src/epics/fetch-tiles.jsx
  api-catalog-ui/frontend/src/helpers/urls.jsx
  api-catalog-ui/frontend/src/helpers/urls.test.jsx
  api-catalog-ui/frontend/src/services/user.service.jsx
  package-lock.json
Labels: size/L

#2079 chore: Upgrade spring, spring-cloud-netflix, tomcat, xstream
  gradle/versions.gradle
Labels: size/S

#2086 fix: change ws and sse pattern
  .github/workflows/pull-request-snapshot-release.yml
  discoverable-client/src/main/java/org/zowe/apiml/client/api/WebServiceController.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/sse/ServerSentEventProxyHandler.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/ws/GatewayWebSocketConfigurer.java
  gateway-service/src/main/resources/application.yml
  integration-tests/src/test/java/org/zowe/apiml/integration/discovery/ApiCatalogDiscoverableClientIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/proxy/ServerSentEventsProxyTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/proxy/WebSocketProxyTest.java
Labels: size/L

#2094 chore: Clean and refactor tests
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/instance/InstanceInitializeService.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/services/cached/CachedProductFamilyService.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/instance/InstanceInitializeServiceTest.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/services/cached/CachedProductFamilyServiceTest.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/util/ServicesBuilder.java
Labels: size/XXL

#2096 refactor: Zosmf tests refactoring
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/login/zosmf/ZosmfAuthenticationProviderTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/zosmf/ZosmfServiceTest.java
Labels: size/XXL, Sensitive

#2097 fix: cross platform support for npm lint
  api-catalog-ui/frontend/package.json
  metrics-service-ui/frontend/package.json
Labels: size/XS, Sensitive

#2095 feat: Add support to change password via zOSMF
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/login/ChangePasswordRequest.java
  apiml-security-common/src/test/java/org/zowe/apiml/security/common/login/ChangePasswordRequestTest.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/zosmf/ZosmfAuthenticationProvider.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/zosmf/ZosmfService.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/login/zosmf/ZosmfAuthenticationProviderTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/zosmf/AuthenticatedEndpointStrategyTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/zosmf/ZosmfServiceTest.java
Labels: size/L, Sensitive

#2098 chore: Refactor and clean ApiCatalogControllerTest
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/controllers/api/ApiCatalogControllerTests.java
Labels: size/L

#2100 chore: increase sonar scan timeout
  .github/workflows/ci-tests.yml
Labels: size/XS

#2099 chore: add gitignore for caching-service/index
  caching-service/.gitignore
Labels: size/XS

#2107 apiml.security.authorization.provider default value should be empty i…
  gateway-package/src/main/resources/bin/start.sh
  gateway-package/src/main/resources/manifest.yaml
Labels: size/XS

#2102 feat: redesign logout panel
  api-catalog-ui/frontend/cypress/integration/e2e/login/login-ok.test.js
  api-catalog-ui/frontend/mocked-backend/assets/services/timeout-error.json
  api-catalog-ui/frontend/src/components/Dashboard/Dashboard.css
  api-catalog-ui/frontend/src/components/Header/Header.css
  api-catalog-ui/frontend/src/components/Header/Header.jsx
  api-catalog-ui/frontend/src/components/Header/Header.test.jsx
  api-catalog-ui/frontend/src/components/Login/Login.jsx
Labels: size/L

#2106 chore: Add password change to mock zosmf
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/zosmf/ZosmfService.java
  mock-services/README.md
  mock-services/src/main/java/org/zowe/apiml/client/api/AuthenticationController.java
  mock-services/src/main/java/org/zowe/apiml/client/model/LoginBody.java
  mock-services/src/main/java/org/zowe/apiml/client/services/AparBasedService.java
  mock-services/src/main/java/org/zowe/apiml/client/services/apars/FunctionalApar.java
  mock-services/src/main/java/org/zowe/apiml/client/services/apars/PH34912.java
  mock-services/src/main/java/org/zowe/apiml/client/services/versions/AvailableApars.java
  mock-services/src/test/java/org/zowe/apiml/client/services/apars/PH34912Test.java
Labels: size/L, Sensitive

#2110 fix: do not require keyAlias
  common-service-core/src/main/java/org/zowe/apiml/security/SecurityUtils.java
  discoverable-client/src/main/java/org/zowe/apiml/client/model/DiscoverableClientConfig.java
  onboarding-enabler-java/src/main/java/org/zowe/apiml/eurekaservice/client/util/EurekaInstanceConfigValidator.java
  onboarding-enabler-java/src/test/java/org/zowe/apiml/eurekaservice/client/util/EurekaInstanceConfigValidatorTest.java
  zaas-client/src/main/java/org/zowe/apiml/zaasclient/service/internal/ZaasHttpsClientProvider.java
Labels: size/S, Sensitive

#2116 chore: Remove image release from automated release workflow
  .github/workflows/automated-release.yml
  docs/release.md
Labels: size/M

#2081 feat: loader for extensions in custom base packages
  apiml-extension-loader/build.gradle
  apiml-extension-loader/src/main/java/org/zowe/apiml/extension/ExtensionConfigReader.java
  apiml-extension-loader/src/main/java/org/zowe/apiml/extension/ExtensionDefinition.java
  apiml-extension-loader/src/main/java/org/zowe/apiml/extension/ExtensionsLoader.java
  apiml-extension-loader/src/main/java/org/zowe/apiml/extension/ZoweRuntimeEnvironment.java
  apiml-extension-loader/src/test/java/org/zowe/CustomBean.java
  apiml-extension-loader/src/test/java/org/zowe/apiml/extension/ExtensionConfigReaderTest.java
  apiml-extension-loader/src/test/java/org/zowe/apiml/extension/ExtensionsLoaderTest.java
  apiml-extension-loader/src/test/java/org/zowe/apiml/extension/ZoweRuntimeEnvironmentTest.java
  apiml-extension-loader/src/test/resources/apimlextension/manifest.json
  apiml-extension-loader/src/test/resources/apimlextension/manifest.yaml
  gateway-service/build.gradle
  gateway-service/src/main/java/org/zowe/apiml/gateway/GatewayApplication.java
  gradle/coverage.gradle
  gradle/lite.gradle
  settings.gradle
Labels: size/XL

#2118 fix: Add missing fields in error response
  common-service-core/src/main/java/org/zowe/apiml/message/api/ApiMessage.java
  common-service-core/src/main/java/org/zowe/apiml/message/core/Message.java
  common-service-core/src/test/java/org/zowe/apiml/message/core/MessageTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/error/check/SecurityErrorCheckTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/error/check/ServiceErrorCheckTest.java
Labels: size/S

#2117 chore: remove unlikely to be customized values from manifest.yaml
  api-catalog-package/src/main/resources/manifest.yaml
  caching-service-package/src/main/resources/bin/start.sh
  caching-service-package/src/main/resources/manifest.yaml
  discovery-package/src/main/resources/manifest.yaml
  gateway-package/src/main/resources/manifest.yaml
  metrics-service-package/src/main/resources/manifest.yaml
Labels: size/S

#2122 docs: update IntelliJ setup to include all services that need to be run
  docs/ide-setup.md
Labels: size/XS

#2123 chore: Update dependencies
  api-catalog-services/build.gradle
  apiml-common/build.gradle
  apiml-sample-extension/build.gradle
  apiml-tomcat-common/build.gradle
  caching-service/build.gradle
  common-service-core/build.gradle
  gateway-service/build.gradle
  gradle/versions.gradle
  onboarding-enabler-spring/build.gradle
Labels: size/M

#2126 fix: API Catalog icon links to dashboard
  api-catalog-ui/frontend/src/components/Header/Header.jsx
  api-catalog-ui/frontend/src/components/Header/Header.test.jsx
Labels: size/XS

#2127 chore: Upgrade thymeleaf
  api-catalog-services/build.gradle
  gateway-service/build.gradle
  gradle/versions.gradle
Labels: size/XS
