Repository zowe/api-layer, pull requests merged in 2022-11, with the labels that each got.

#2646 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: size/XS

#2659 fix: disable x509
  .github/workflows/pull-request-snapshot-release.yml
  discovery-service/build.gradle
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/source/DefaultAuthSourceService.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/source/DefaultAuthSourceServiceTest.java
  gateway-service/src/test/resources/application.yml
  gradle.properties
Labels: size/M, Sensitive

#2670 chore: spring boot and jackson update
  api-catalog-services/build.gradle
  apiml-sample-extension/build.gradle
  caching-service/build.gradle
  discoverable-client/build.gradle
  gradle/versions.gradle
  metrics-service/build.gradle
Labels: size/S

#2664 chore: Upgrade jettison, snakeyaml and commons-text
  api-catalog-services/build.gradle
  apiml-common/build.gradle
  apiml-sample-extension/build.gradle
  apiml-security-common/build.gradle
  apiml-tomcat-common/build.gradle
  apiml-utility/build.gradle
  caching-service/build.gradle
  common-service-core/build.gradle
  discoverable-client/build.gradle
  discovery-service/build.gradle
  gateway-service/build.gradle
  gradle/versions.gradle
  metrics-service/build.gradle
  mock-services/build.gradle
  onboarding-enabler-java-sample-app/build.gradle
  onboarding-enabler-java/build.gradle
  onboarding-enabler-spring-sample-app/build.gradle
  onboarding-enabler-spring/build.gradle
  security-service-client-spring/build.gradle
Labels: size/L, Sensitive

#2671 chore: Upgrade springframework, spring-boot-starter-aop libraries and minimatch, unset-value node libraries
  api-catalog-services/build.gradle
  apiml-common/build.gradle
  apiml-security-common/build.gradle
  apiml-tomcat-common/build.gradle
  apiml-utility/build.gradle
  caching-service/build.gradle
  common-service-core/build.gradle
  discoverable-client/build.gradle
  discovery-service/build.gradle
  gateway-service/build.gradle
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/refresh/SuccessfulRefreshHandlerTest.java
  gradle/versions.gradle
  metrics-service/build.gradle
  mock-services/build.gradle
  onboarding-enabler-spring-sample-app/build.gradle
  onboarding-enabler-spring/build.gradle
  security-service-client-spring/build.gradle
  zaas-client/build.gradle
Labels: size/L, Sensitive

#2679 feat: CGW circuit breaker
  .github/workflows/containers.yml
  cloud-gateway-service/build.gradle
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/config/HttpConfig.java
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/service/ProxyRouteLocator.java
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/service/RouteLocator.java
  cloud-gateway-service/src/main/resources/application.yml
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/config/HttpConfigTest.java
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/service/RouteLocatorTest.java
  gradle/versions.gradle
  integration-tests/src/test/java/org/zowe/apiml/integration/proxy/CloudGatewayProxyTest.java
Labels: size/L

#2680 fix: update libraries
  cloud-gateway-service/build.gradle
  gradle/versions.gradle
Labels: size/M

#2682 fi: set content type header when calling caching service
  gateway-service/src/main/java/org/zowe/apiml/gateway/cache/CachingServiceClient.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/cache/CachingServiceClientTest.java
Labels: size/M

#2681 chore: remaining updates from report
  api-catalog-services/build.gradle
  apiml-common/build.gradle
  apiml-security-common/build.gradle
  apiml-tomcat-common/build.gradle
  caching-service/build.gradle
  cloud-gateway-service/build.gradle
  common-service-core/build.gradle
  discoverable-client/build.gradle
  discovery-service/build.gradle
  gateway-service/build.gradle
  metrics-service/build.gradle
  mock-services/build.gradle
  onboarding-enabler-spring/build.gradle
  security-service-client-spring/build.gradle
Labels: size/L, Sensitive

#2684 fix: allow to set key password separately
  api-catalog-package/src/main/resources/bin/start.sh
  caching-service-package/src/main/resources/bin/start.sh
  cloud-gateway-package/src/main/resources/bin/start.sh
  discovery-package/src/main/resources/bin/start.sh
  gateway-package/src/main/resources/bin/start.sh
  metrics-service-package/src/main/resources/bin/start.sh
Labels: size/M

#2685 chore: Upgrade npm dependencies
  api-catalog-ui/frontend/package-lock.json
  api-catalog-ui/frontend/package.json
  metrics-service-ui/frontend/package-lock.json
  metrics-service-ui/frontend/package.json
Labels: size/XS
