Repository zowe/api-layer, pull requests merged in 2022-08, with the labels that each got.

#2507 feat:Validate service is onboarded to the API Mediation Layer
  gateway-service/src/main/java/org/zowe/apiml/gateway/conformance/ValidateAPIController.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/conformance/VerificationOnboardService.java
  gateway-service/src/main/resources/gateway-log-messages.yml
  gateway-service/src/test/java/org/zowe/apiml/gateway/conformance/ValidateAPIControllerTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/conformance/VerificationOnboardServiceTest.java
  integration-tests/src/test/java/org/zowe/apiml/functional/gateway/ValidateAPITest.java
Labels: size/L

#2526 feat: Add customized code snippets to API Catalog
  api-catalog-services/src/main/resources/application.yml
  api-catalog-ui/frontend/mocked-backend/assets/containers.json
  api-catalog-ui/frontend/mocked-backend/assets/services/cademoapps.json
  api-catalog-ui/frontend/src/components/ServiceTab/ServiceTab.jsx
  api-catalog-ui/frontend/src/components/Swagger/SwaggerUI.jsx
  api-catalog-ui/frontend/src/components/Swagger/SwaggerUI.test.jsx
  api-catalog-ui/frontend/src/utils/generateSnippets.js
  api-catalog-ui/frontend/src/utils/generateSnippets.test.js
  discoverable-client/src/main/resources/application.yml
Labels: size/XXL

#2543 chore: update tomcat, eureka core and aws sdk
  discovery-service/build.gradle
  gradle/versions.gradle
Labels: size/S

#2544 chore: jwt lib update
  gateway-service/src/main/java/org/zowe/apiml/gateway/controllers/AuthController.java
  gradle/versions.gradle
Labels: size/XS

#2545 chore: Upgrade tomcat to 9.0.65
  gradle/versions.gradle
Labels: size/XS

#2548 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: size/S

#2546 feat: Redis sentinel enabled field
  caching-service/src/main/java/org/zowe/apiml/caching/service/redis/RedisOperator.java
  caching-service/src/main/java/org/zowe/apiml/caching/service/redis/config/RedisConfig.java
  caching-service/src/main/resources/application.yml
  caching-service/src/test/java/org/zowe/apiml/caching/service/redis/config/RedisConfigTest.java
Labels: size/S

#2550 chore: Use job id as jib tag
  .github/workflows/containers.yml
Labels: size/L

#2551 chore: Use job id as jib tag
  .github/workflows/containers.yml
Labels: size/L

#2555 feat: PoC protect rest endpoint with okta
  .github/workflows/containers.yml
  build.gradle
  discoverable-client/build.gradle
  discoverable-client/src/main/java/org/zowe/apiml/client/api/Oauth2Controller.java
  discoverable-client/src/main/java/org/zowe/apiml/client/configuration/SecurityConfiguration.java
  gradle/versions.gradle
  integration-tests/build.gradle
  integration-tests/src/test/java/org/zowe/apiml/integration/authentication/oauth2/OktaOauth2Test.java
  keystore/docker/all-services.truststore.p12
  keystore/localhost/localhost.truststore.p12
Labels: size/L

#2549 chore: security update tomcat el
  api-catalog-services/build.gradle
  apiml-common/build.gradle
  apiml-security-common/build.gradle
  apiml-tomcat-common/build.gradle
  apiml-utility/build.gradle
  caching-service/build.gradle
  discoverable-client/build.gradle
  discovery-service/build.gradle
  gateway-service/build.gradle
  gradle/versions.gradle
  metrics-service/build.gradle
  mock-services/build.gradle
  onboarding-enabler-spring/build.gradle
  security-service-client-spring/build.gradle
Labels: size/M, Sensitive

#2558 chore: Improve Caching Service Redis integration tests
  .github/actions/validate-apiml-healthy/action.yml
  .github/workflows/containers.yml
  caching-service/src/main/java/org/zowe/apiml/caching/service/redis/RedisOperator.java
  config/docker/discovery-service.yml
  docker/redis/.gitignore
  docker/redis/README.md
  docker/redis/compose/apiml.env.template
  docker/redis/compose/mock-services.yml.template
  docker/redis/compose/redis.yml.template
  docker/redis/config/master-tls.conf
  docker/redis/config/master.conf
  docker/redis/config/master.conf.template
  docker/redis/config/replica-tls.conf
  docker/redis/config/replica.conf
  docker/redis/config/replica.conf.template
  docker/redis/config/sentinel-1-tls.conf
  docker/redis/config/sentinel-1.conf
  docker/redis/config/sentinel-2-tls.conf
  docker/redis/config/sentinel-2.conf
  docker/redis/config/sentinel-3-tls.conf
  docker/redis/config/sentinel-3.conf
  docker/redis/config/sentinel.conf.template
  docker/redis/docker-compose-replica-tls.yml
  docker/redis/docker-compose-replica.yml
  docker/redis/docker-compose-sentinel-tls.yml
  docker/redis/docker-compose-sentinel.yml
  docker/redis/run-redis.sh
  integration-tests/src/test/java/org/zowe/apiml/util/config/ConfigReader.java
Labels: size/XXL

#2554 feat: Evict non relevant tokens and rules
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/config/AccessTokenProviderConfig.java
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/config/AuthConfigurationProperties.java
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/token/AccessTokenProvider.java
  caching-service/src/main/java/org/zowe/apiml/caching/api/CachingController.java
  caching-service/src/main/java/org/zowe/apiml/caching/service/Storage.java
  caching-service/src/main/java/org/zowe/apiml/caching/service/infinispan/storage/InfinispanStorage.java
  caching-service/src/main/java/org/zowe/apiml/caching/service/inmemory/InMemoryStorage.java
  caching-service/src/main/java/org/zowe/apiml/caching/service/redis/RedisStorage.java
  caching-service/src/main/java/org/zowe/apiml/caching/service/vsam/VsamStorage.java
  caching-service/src/test/java/org/zowe/apiml/caching/api/CachingControllerTest.java
  caching-service/src/test/java/org/zowe/apiml/caching/service/infinispan/storage/InfinispanStorageTest.java
  caching-service/src/test/java/org/zowe/apiml/caching/service/inmemory/InMemoryStorageTest.java
  caching-service/src/test/java/org/zowe/apiml/caching/service/redis/RedisStorageTest.java
  caching-service/src/test/java/org/zowe/apiml/caching/service/vsam/VsamStorageTest.java
  common-service-core/src/main/java/org/zowe/apiml/models/AccessTokenContainer.java
  config/saf.yml
  gateway-service/saf.yml
  gateway-service/src/main/java/org/zowe/apiml/gateway/cache/CachingServiceClient.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/controllers/AuthController.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/config/NewSecurityConfiguration.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/token/ApimlAccessTokenProvider.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/cache/CachingServiceClientTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/controllers/AuthControllerTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/token/ApimlAccessTokenProviderTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/authentication/pat/AccessTokenServiceTest.java
  integration-tests/src/test/java/org/zowe/apiml/util/requests/Endpoints.java
Labels: size/XL, Sensitive

#2564 fix: Fix code snippets bug
  api-catalog-ui/frontend/src/components/Swagger/SwaggerUI.jsx
  api-catalog-ui/frontend/src/components/Swagger/SwaggerUI.test.jsx
  config/local/api-defs/staticclient.yml
Labels: size/M
