Repository zowe/api-layer, pull requests merged in 2022-04, with the labels that each got.

#2251 chore: Upgrade Spring to version without vulnerability
  api-catalog-services/build.gradle
  caching-service/build.gradle
  discovery-service/build.gradle
  gateway-service/build.gradle
  gradle/versions.gradle
  metrics-service/build.gradle
Labels: size/XS

#2252 chore: Upgrade Spring to version without vulnerability
  api-catalog-services/build.gradle
  caching-service/build.gradle
  discovery-service/build.gradle
  gateway-service/build.gradle
  gradle/versions.gradle
  metrics-service/build.gradle
Labels: size/XS

#2247 chore: rename AbstractAuthenticationScheme interface
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/ServiceAuthenticationServiceImpl.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/AuthenticationSchemeFactory.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/ByPassScheme.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/HttpBasicPassTicketScheme.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/IAuthenticationScheme.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/SafIdtScheme.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/X509Scheme.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/ZosmfScheme.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/ZoweJwtScheme.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/ServiceAuthenticationServiceImplTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/AuthenticationSchemeFactoryTest.java
Labels: size/M, Sensitive

#2248 created grafana-http-dashboard directory under metrics-service-ui which includes the http dashboard json and a readme
  metrics-service-ui/grafana-http-dashboard/APIML-Metrics-Service-HTTP-1648659430036.json
  metrics-service-ui/grafana-http-dashboard/README
Labels: size/XXL, mentee

#2245 feat: zowe jwt from x509
  .github/workflows/containers.yml
  config/docker/api-defs/staticclient.yml
  config/local/api-defs/staticclient.yml
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/ServiceAuthenticationServiceImpl.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/AuthenticationCommand.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/JwtCommand.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/ServiceAuthenticationService.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/ZosmfScheme.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/ZoweJwtScheme.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/source/UserNotMappedException.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/source/X509AuthSourceService.java
  gateway-service/src/main/resources/gateway-log-messages.yml
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/ZoweJwtSchemeTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/source/X509AuthSourceServiceTest.java
  gateway-service/src/test/resources/gateway-messages.yml
  integration-tests/src/test/java/org/zowe/apiml/integration/authentication/schemes/ZoweJwtSchemeTest.java
Labels: size/XL, Sensitive

#2263 fix: API Catalog heading changed #1555
  api-catalog-ui/frontend/src/components/Header/Header.jsx
Labels: size/XS

#2269 chore: more generic changlog action
  .github/workflows/changelog.yml
  scripts/release_docs/index.js
Labels: size/S

#2271 chore: more generic changlog action (#2269)
  .github/workflows/changelog.yml
  scripts/release_docs/index.js
Labels: size/S

#2260 feat: Enhance x509 authentication scheme to support client certificates (part 2)
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/config/ComponentsConfiguration.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/AuthenticationSchemeFactory.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/X509Scheme.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/source/X509AuthSourceService.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/source/X509CNAuthSourceService.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/SafIdtSchemeTest.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/X509SchemeTest.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/ZosmfSchemeTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/AuthenticationSchemeFactoryTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/X509SchemeTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/source/DefaultAuthSourceServiceTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/source/X509AuthSourceServiceTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/source/X509CNAuthSourceServiceTest.java
Labels: size/XL, Sensitive

#2241 chore: Provide old path pattern support for auth related endpoints for zaas client
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/config/AuthConfigurationProperties.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/config/NewSecurityConfiguration.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/config/SecurityConfiguration.java
  integration-tests/src/test/java/org/zowe/apiml/integration/authentication/providers/LoginTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/authentication/providers/LogoutTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/authentication/providers/QueryTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/authentication/providers/SafLoginTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/authentication/providers/SafLogoutTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/authentication/providers/ZosmfLoginTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/authentication/providers/ZosmfLogoutTest.java
  integration-tests/src/test/java/org/zowe/apiml/util/SecurityUtils.java
  integration-tests/src/test/java/org/zowe/apiml/util/config/ConfigReaderZaasClient.java
  integration-tests/src/test/java/org/zowe/apiml/util/requests/Endpoints.java
  zaas-client/src/main/java/org/zowe/apiml/zaasclient/config/ConfigProperties.java
  zaas-client/src/test/java/org/zowe/apiml/zaasclient/service/internal/ZaasClientApimlBaseUrlTest.java
  zaas-client/src/test/java/org/zowe/apiml/zaasclient/service/internal/ZaasClientImplHttpTests.java
Labels: size/L, Sensitive

#2274 fix: Improve metrics in mocked-backend for metrics service
  metrics-service-ui/frontend/mocked-backend/assets/services/metrics.json
  metrics-service-ui/frontend/mocked-backend/assets/services/metrics.txt
  metrics-service-ui/frontend/mocked-backend/routes.js
Labels: size/M

#2272 fix: Add support for regex
  .github/workflows/containers.yml
  discovery-service/src/main/java/org/zowe/apiml/discovery/ApimlInstanceRegistry.java
  discovery-service/src/test/java/org/zowe/apiml/discovery/ApimlInstanceRegistryTest.java
Labels: size/M

#2275 chore: Upgrade vulnerable dependencies
  apiml-security-common/build.gradle
  apiml-tomcat-common/build.gradle
  gradle/versions.gradle
  mock-services/build.gradle
  onboarding-enabler-spring/build.gradle
  zaas-client/build.gradle
Labels: size/S, Sensitive

#2284 fix: variable references converted to v2 format
  gateway-package/src/main/resources/bin/start.sh
  gateway-service/src/main/resources/gateway-log-messages.yml
Labels: size/XS

#2270 chore: automated changelog update
  CHANGELOG.md
Labels: docs, size/S

#2285 feat: Enhance x509 authentication scheme to support client certificates (part 3)
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/config/ComponentsConfiguration.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/X509Scheme.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/source/AuthSourceService.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/source/X509AuthSourceService.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/source/X509CNAuthSourceService.java
  gateway-service/src/main/resources/gateway-log-messages.yml
  gateway-service/src/test/java/org/zowe/apiml/acceptance/X509SchemeTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/X509SchemeTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/source/X509AuthSourceServiceTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/source/X509CNAuthSourceServiceTest.java
  gateway-service/src/test/resources/gateway-messages.yml
  integration-tests/src/test/java/org/zowe/apiml/integration/authentication/schemes/X509SchemeTest.java
Labels: size/XL, Sensitive

#2292 feat: zowe jwt from x509 (update)
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/config/AuthConfigurationProperties.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/X509Scheme.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/ZoweJwtScheme.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/source/AuthSourceService.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/X509SchemeTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/ZoweJwtSchemeTest.java
Labels: size/L, Sensitive

#2201 feat: yaml upload to prefill wizard inputs
  api-catalog-ui/frontend/cypress/fixtures/enabler-test-files/testEnabler1.yaml
  api-catalog-ui/frontend/cypress/fixtures/enabler-test-files/testEnabler2.yaml
  api-catalog-ui/frontend/cypress/fixtures/enabler-test-files/testEnabler3.yaml
  api-catalog-ui/frontend/cypress/fixtures/enabler-test-files/testEnabler4.yaml
  api-catalog-ui/frontend/cypress/fixtures/enabler-test-files/testEnabler5.yaml
  api-catalog-ui/frontend/cypress/fixtures/enabler-test-files/testEnabler6.yaml
  api-catalog-ui/frontend/cypress/integration/e2e/dashboard/wizard-dialog.test.js
  api-catalog-ui/frontend/cypress/support/commands.js
  api-catalog-ui/frontend/package-lock.json
  api-catalog-ui/frontend/package.json
  api-catalog-ui/frontend/src/actions/wizard-actions.jsx
  api-catalog-ui/frontend/src/actions/wizard-actions.test.jsx
  api-catalog-ui/frontend/src/actions/wizard-fetch-actions.jsx
  api-catalog-ui/frontend/src/actions/wizard-fetch-actions.test.jsx
  api-catalog-ui/frontend/src/components/Wizard/WizardContainer.jsx
  api-catalog-ui/frontend/src/components/Wizard/WizardDialog.jsx
  api-catalog-ui/frontend/src/components/Wizard/WizardDialog.test.jsx
  api-catalog-ui/frontend/src/components/Wizard/configs/wizard_base_categories.jsx
  api-catalog-ui/frontend/src/components/Wizard/wizard.css
  api-catalog-ui/frontend/src/constants/wizard-constants.jsx
  api-catalog-ui/frontend/src/reducers/wizard-reducer.jsx
  api-catalog-ui/frontend/src/reducers/wizard-reducer.test.jsx
Labels: size/XXL, mentee

#2294 refactor: move ZOSMF transformation logic into createCommand()
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/ZosmfScheme.java
  gateway-service/src/main/resources/gateway-log-messages.yml
  gateway-service/src/test/java/org/zowe/apiml/acceptance/ZosmfSchemeTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/ZosmfSchemeTest.java
  gateway-service/src/test/resources/gateway-messages.yml
Labels: size/L, Sensitive

#2283 feat: json schema
  api-catalog-package/build.gradle
  api-catalog-package/src/main/resources/manifest.yaml
  caching-service-package/build.gradle
  caching-service-package/src/main/resources/manifest.yaml
  discovery-package/build.gradle
  discovery-package/src/main/resources/manifest.yaml
  gateway-package/build.gradle
  gateway-package/src/main/resources/manifest.yaml
  metrics-service-package/build.gradle
  metrics-service-package/src/main/resources/manifest.yaml
  schemas/caching-schema.json
  schemas/catalog-schema.json
  schemas/discovery-schema.json
  schemas/gateway-schema.json
  schemas/metrics-schema.json
Labels: size/L

#2297 feat: zebra metrics persistent data rest endpoint POC
  metrics-service-ui/grafana-zebra-dashboard/RPRT - CPC Metrics-1649876869207.json
  metrics-service/src/main/java/org/zowe/apiml/metrics/controllers/MetricServiceController.java
  metrics-service/src/main/java/org/zowe/apiml/metrics/services/zebra/RmfData.java
  metrics-service/src/main/java/org/zowe/apiml/metrics/services/zebra/ZebraMetricsService.java
  metrics-service/src/main/java/org/zowe/apiml/metrics/services/zebra/config/ZebraBeanConfiguration.java
  metrics-service/src/main/java/org/zowe/apiml/metrics/services/zebra/config/ZebraConfiguration.java
  metrics-service/src/main/resources/application.yml
  metrics-service/src/test/java/org/zowe/apiml/metrics/services/ZebraMetricsServiceTest.java
Labels: size/XXL

#2298 feat: use default expiration time in Zosmf scheme
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/ZosmfScheme.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/ZosmfSchemeTest.java
Labels: size/XS, Sensitive

#2304 chore: Upgrade Spring Framework
  build.gradle
  gradle/versions.gradle
  metrics-service/build.gradle
Labels: size/S

#2307 chore: dep upgrade
  build.gradle
  gradle/versions.gradle
  metrics-service/build.gradle
Labels: size/S

#2301 feat: functionality for error message in HttpBasicPassTicketScheme
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/HttpBasicPassTicketScheme.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/HttpBasicPassTicketSchemeTest.java
Labels: size/L, Sensitive

#2308 fix: replication of data for infinispan nodes
  caching-service/src/main/java/org/zowe/apiml/caching/service/infinispan/config/InfinispanConfig.java
  config/docker/caching-service.yml
Labels: size/XS

#2312 feat: Discovery service health check
  discovery-service/src/main/java/org/zowe/apiml/discovery/health/DiscoveryServiceHealthIndicator.java
  discovery-service/src/main/resources/application.yml
  discovery-service/src/test/java/org/zowe/apiml/discovery/health/DiscoveryServiceHealthIndicatorTest.java
  discovery-service/src/test/resources/application.yml
Labels: size/L

#2314 feat: TLSv1.3 configuration
  api-catalog-services/src/main/resources/application.yml
  caching-service/src/main/resources/application.yml
  discoverable-client/src/main/resources/application.yml
  discovery-service/src/main/resources/application.yml
  gateway-service/src/main/resources/application.yml
  metrics-service/src/main/resources/application.yml
  mock-services/src/main/resources/application.yml
  onboarding-enabler-spring-sample-app/src/main/resources/application.yml
Labels: size/M

#2302 Fix: Build and Grafana Errors
  metrics-service-ui/README.md
  metrics-service-ui/frontend/src/components/Dashboard/Dashboard.jsx
  metrics-service-ui/frontend/src/components/Dashboard/Dashboard.test.jsx
  metrics-service-ui/frontend/src/components/Default_Dashboard/DefaultDashboard.jsx
  metrics-service-ui/frontend/src/components/grafana-iframes/Gateway-http-dashboard.jsx
  metrics-service-ui/frontend/src/components/grafana-iframes/Gateway-zebra-dashboard.jsx
  metrics-service-ui/grafana-plugins/data-source-plugin/.github/workflows/ci.yml
  metrics-service-ui/grafana-plugins/data-source-plugin/.github/workflows/release.yml
  metrics-service-ui/grafana-plugins/data-source-plugin/.gitignore
  metrics-service-ui/grafana-plugins/data-source-plugin/.prettierrc.js
  metrics-service-ui/grafana-plugins/data-source-plugin/CHANGELOG.md
  metrics-service-ui/grafana-plugins/data-source-plugin/LICENSE
  metrics-service-ui/grafana-plugins/data-source-plugin/README.md
  metrics-service-ui/grafana-plugins/data-source-plugin/config/default.json
  metrics-service-ui/grafana-plugins/data-source-plugin/package-lock.json
  metrics-service-ui/grafana-plugins/data-source-plugin/package.json
  metrics-service-ui/grafana-plugins/data-source-plugin/src/ConfigEditor.tsx
  metrics-service-ui/grafana-plugins/data-source-plugin/src/QueryEditor.tsx
  metrics-service-ui/grafana-plugins/data-source-plugin/src/datasource.ts
  metrics-service-ui/grafana-plugins/data-source-plugin/src/img/logo.svg
  metrics-service-ui/grafana-plugins/data-source-plugin/src/module.ts
  metrics-service-ui/grafana-plugins/data-source-plugin/src/plugin.json
  metrics-service-ui/grafana-plugins/data-source-plugin/src/types.ts
  metrics-service-ui/grafana-plugins/data-source-plugin/tsconfig.json
  metrics-service-ui/grafana-plugins/marcusolsson-json-datasource/CHANGELOG.md
  metrics-service-ui/grafana-plugins/marcusolsson-json-datasource/LICENSE
  metrics-service-ui/grafana-plugins/marcusolsson-json-datasource/MANIFEST.txt
  metrics-service-ui/grafana-plugins/marcusolsson-json-datasource/README.md
  metrics-service-ui/grafana-plugins/marcusolsson-json-datasource/img/dark.png
  metrics-service-ui/grafana-plugins/marcusolsson-json-datasource/img/light.png
  metrics-service-ui/grafana-plugins/marcusolsson-json-datasource/img/logo.svg
  metrics-service-ui/grafana-plugins/marcusolsson-json-datasource/module.js
  metrics-service-ui/grafana-plugins/marcusolsson-json-datasource/module.js.LICENSE.txt
  metrics-service-ui/grafana-plugins/marcusolsson-json-datasource/module.js.map
  metrics-service-ui/grafana-plugins/marcusolsson-json-datasource/plugin.json
  metrics-service/src/main/java/org/zowe/apiml/metrics/controllers/MetricServiceController.java
  metrics-service/src/main/java/org/zowe/apiml/metrics/services/zebra/RmfData.java
  metrics-service/src/main/java/org/zowe/apiml/metrics/services/zebra/ZebraMetricsService.java
  metrics-service/src/main/java/org/zowe/apiml/metrics/services/zebra/config/ZebraBeanConfiguration.java
  metrics-service/src/main/java/org/zowe/apiml/metrics/services/zebra/config/ZebraConfiguration.java
  metrics-service/src/test/java/org/zowe/apiml/metrics/services/ZebraMetricsServiceTest.java
Labels: size/XL

#2317 Refactor: authentication schemes exception handling
  discoverable-client/src/main/java/org/zowe/apiml/client/api/PassTicketTestController.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/pre/ServiceAuthenticationFilter.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/config/ComponentsConfiguration.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/HttpBasicPassTicketScheme.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/JwtCommand.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/X509Scheme.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/ZosmfScheme.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/ZoweJwtScheme.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/source/AuthSchemeException.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/source/X509AuthSourceService.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/source/X509CNAuthSourceService.java
  gateway-service/src/main/resources/gateway-log-messages.yml
  gateway-service/src/test/java/org/zowe/apiml/acceptance/X509SchemeTest.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/ZosmfSchemeTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/filters/pre/ServiceAuthenticationFilterTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/HttpBasicPassTicketSchemeTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/X509SchemeTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/ZosmfSchemeTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/ZoweJwtSchemeTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/source/X509AuthSourceServiceTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/source/X509CNAuthSourceServiceTest.java
  gateway-service/src/test/resources/gateway-messages.yml
  integration-tests/src/test/java/org/zowe/apiml/integration/authentication/schemes/PassticketSchemeTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/authentication/schemes/X509SchemeTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/penetration/JwtPenTest.java
Labels: size/XXL, Sensitive

#2319 feat: minor update in authentication schemes
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/pre/ServiceAuthenticationFilter.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/ribbon/http/BeanConfig.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/ribbon/http/ServiceAuthenticationDecorator.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/ServiceAuthenticationServiceImpl.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/X509Scheme.java
  gateway-service/src/main/resources/gateway-log-messages.yml
  gateway-service/src/test/java/org/zowe/apiml/acceptance/X509SchemeTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/ribbon/http/ServiceAuthenticationDecoratorTest.java
  gateway-service/src/test/resources/gateway-messages.yml
  integration-tests/src/test/java/org/zowe/apiml/integration/authentication/schemes/X509SchemeTest.java
Labels: size/M, Sensitive

#2327 feat: Create endpoint to retrieve default API doc for service
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/controllers/api/CatalogApiDocController.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/controllers/handlers/CatalogApiDocControllerExceptionHandler.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/services/status/APIServiceStatusService.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/controllers/api/CatalogApiDocControllerApiDocNotFoundTest.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/controllers/api/CatalogApiDocControllerTest.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/services/status/ApiServiceStatusServiceTest.java
  integration-tests/src/test/java/org/zowe/apiml/functional/apicatalog/ApiCatalogAuthenticationTest.java
  integration-tests/src/test/java/org/zowe/apiml/functional/apicatalog/ApiCatalogEndpointIntegrationTest.java
Labels: size/L

#2328 fix: Add server side logging for swagger handling code
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/services/cached/CachedApiDocService.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/services/status/APIDocRetrievalService.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/services/status/APIServiceStatusService.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/SubstituteSwaggerGenerator.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/api/ApiDocV3Service.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/services/cached/CachedApiDocServiceTest.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/services/status/ApiServiceStatusServiceTest.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/services/status/LocalApiDocServiceTest.java
Labels: size/XL

#2330 fix: verify ssl certs takes precedence over nonstrict verify
  common-service-core/src/main/java/org/zowe/apiml/security/HttpsFactory.java
Labels: size/XS, Sensitive

#2333 chore: merge master into v2
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/controllers/api/CatalogApiDocController.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/controllers/handlers/CatalogApiDocControllerExceptionHandler.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/services/cached/CachedApiDocService.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/services/status/APIDocRetrievalService.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/services/status/APIServiceStatusService.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/SubstituteSwaggerGenerator.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/api/AbstractApiDocService.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/api/ApiDocV3Service.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/controllers/api/CatalogApiDocControllerApiDocNotFoundTest.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/controllers/api/CatalogApiDocControllerTest.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/services/cached/CachedApiDocServiceTest.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/services/status/ApiServiceStatusServiceTest.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/services/status/LocalApiDocServiceTest.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/swagger/api/AbstractApiDocServiceTest.java
  common-service-core/src/main/java/org/zowe/apiml/security/HttpsFactory.java
  integration-tests/src/test/java/org/zowe/apiml/functional/apicatalog/ApiCatalogAuthenticationTest.java
  integration-tests/src/test/java/org/zowe/apiml/functional/apicatalog/ApiCatalogEndpointIntegrationTest.java
Labels: size/XXL, Sensitive
