Repository zowe/api-layer, pull requests merged in 2022-05, with the labels that each got.

#2334 chore: use defaults for eureka credentials
  api-catalog-package/src/main/resources/bin/start.sh
  config/zowe-api-dev/alternative_start.sh
Labels: size/XS

#2335 chore: use defaults for eureka credentials
  api-catalog-package/src/main/resources/bin/start.sh
  config/zowe-api-dev/alternative_start.sh
Labels: size/XS

#2329 chore: bump snapshot version
  gradle.properties
  onboarding-enabler-nodejs/package.json
Labels: size/XS

#2340 fix: use same key and record lengths as jcl
  caching-service/src/main/java/org/zowe/apiml/caching/service/vsam/config/VsamConfig.java
Labels: size/XS

#2341 fix: use same key and record lengths as jcl
  caching-service/src/main/java/org/zowe/apiml/caching/service/vsam/config/VsamConfig.java
Labels: size/XS

#2345 fix: API Catalog swagger link
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/api/ApiDocV2Service.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/api/ApiDocV3Service.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/api/OpenApiUtil.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/swagger/api/ApiDocV2ServiceTest.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/swagger/api/ApiDocV3ServiceTest.java
  gateway-service/src/main/resources/application.yml
Labels: size/XL

#2344 fix: API Catalog swagger link
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/api/ApiDocV2Service.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/api/ApiDocV3Service.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/api/OpenApiUtil.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/swagger/api/ApiDocV2ServiceTest.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/swagger/api/ApiDocV3ServiceTest.java
  gateway-service/src/main/resources/application.yml
Labels: size/XL

#2223 feat: Fix SAF IDT scheme and service
  gateway-package/src/main/resources/bin/start.sh
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/saf/SafProviderBeansConfig.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/saf/SafRestAuthenticationService.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/SafIdtSchemeTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/saf/SafRestAuthenticationServiceTest.java
  mock-services/src/main/java/org/zowe/apiml/zss/api/SafIdtController.java
  mock-services/src/test/java/org/zowe/apiml/zss/api/SafIdtControllerTest.java
Labels: size/L, Sensitive, blocked

#2343 chore: authentication schemes tweaks
  apiml-common/src/main/java/org/zowe/apiml/product/gateway/GatewayInstanceInitializer.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/pre/ServiceAuthenticationFilter.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/HttpBasicPassTicketScheme.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/X509Scheme.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/ZosmfScheme.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/ZoweJwtScheme.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/source/JwtAuthSourceService.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/source/X509AuthSourceService.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/source/X509CNAuthSourceService.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/SafIdtSchemeTest.java
Labels: size/L, Sensitive

#2352 chore: Update patch version of Spring
  gradle/versions.gradle
Labels: size/XS

#2354 chore: Upgrade gson
  gradle/versions.gradle
Labels: size/XS

#2339 improve shell if checks
  api-catalog-package/src/main/resources/bin/start.sh
  caching-service-package/src/main/resources/bin/start.sh
  discovery-package/src/main/resources/bin/start.sh
  gateway-package/src/main/resources/bin/start.sh
  metrics-service-package/src/main/resources/bin/start.sh
Labels: size/M

#2362 chore: spring upgrade
  gateway-service/src/main/java/org/zowe/apiml/gateway/metadata/service/CorsMetadataProcessor.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/config/CorsBeans.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/netflix/ApplicationRegistry.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/metadata/service/CorsMetadataProcessorTest.java
  gradle/versions.gradle
Labels: size/S, Sensitive

#2361 feat: Generate SAF ID token based on x509
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/SafIdtScheme.java
  gateway-service/src/main/resources/gateway-log-messages.yml
  gateway-service/src/test/java/org/zowe/apiml/acceptance/SafIdtSchemeTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/SafIdtSchemeTest.java
  gateway-service/src/test/resources/gateway-messages.yml
Labels: size/L, Sensitive

#2367 chore: Upgrade logback, tomcat, netty
  api-catalog-services/build.gradle
  caching-service/build.gradle
  common-service-core/build.gradle
  discovery-service/build.gradle
  gateway-service/build.gradle
  gradle/versions.gradle
  metrics-service/build.gradle
Labels: size/S

#2368 chore: gson security update
  api-catalog-services/build.gradle
  common-service-core/build.gradle
  discovery-service/build.gradle
  gateway-service/build.gradle
  gradle/versions.gradle
  metrics-service/build.gradle
  onboarding-enabler-java/build.gradle
Labels: size/S

#2360 chore: 1.28 change log
  CHANGELOG.md
Labels: size/S

#2374 fix: Externalize index location to work with zowe env
  caching-service/src/main/java/org/zowe/apiml/caching/service/infinispan/config/InfinispanConfig.java
Labels: size/XS

#2375 Upgrade patch version of servers
  gradle/versions.gradle
Labels: size/XS

#2381 chore: Upgrade patch versions of servers
  gradle/versions.gradle
Labels: size/XS

#2383 chore: Upgrade versions
  gradle/versions.gradle
  metrics-service/build.gradle
Labels: size/XS

#2386 chore: Upgrade Spring Boot to 2.5
  api-catalog-services/build.gradle
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/ApiCatalogApplication.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/controllers/handlers/NotFoundErrorController.java
  api-catalog-services/src/main/resources/application.yml
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/functional/ApiCatalogFunctionalTest.java
  api-catalog-services/src/test/resources/application.yml
  apiml-common/build.gradle
  apiml-common/src/main/java/org/zowe/apiml/product/compatibility/ApimlDiscoveryCompositeHealthContributor.java
  apiml-common/src/main/java/org/zowe/apiml/product/compatibility/ApimlErrorController.java
  apiml-common/src/main/java/org/zowe/apiml/product/compatibility/ApimlHealthCheckHandler.java
  apiml-common/src/test/java/org/zowe/apiml/product/compatibility/ApimlDiscoveryCompositeHealthContributorTest.java
  apiml-common/src/test/java/org/zowe/apiml/product/compatibility/ApimlHealthCheckHandlerTest.java
  apiml-extension-loader/src/test/java/org/zowe/apiml/extension/ExtensionsLoaderTest.java
  apiml-extension-loader/src/test/java/org/zowe/apiml/extension/ZoweRuntimeEnvironmentTest.java
  build.gradle
  caching-service/build.gradle
  caching-service/src/main/resources/application.yml
  caching-service/src/test/resources/application.yml
  config/local/api-catalog-service.yml
  config/local/discovery-service.yml
  config/local/gateway-service.yml
  discoverable-client/build.gradle
  discoverable-client/src/main/resources/application.yml
  discoverable-client/src/test/resources/application.yml
  discovery-service/build.gradle
  discovery-service/src/main/resources/application.yml
  discovery-service/src/test/resources/application.yml
  gateway-service/build.gradle
  gateway-service/src/main/java/org/zowe/apiml/gateway/error/controllers/InternalServerErrorController.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/error/controllers/NotFoundErrorController.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/routing/ZuulErrorControllerHandler.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/config/NewSecurityConfiguration.java
  gateway-service/src/main/resources/application.yml
  gateway-service/src/test/java/org/zowe/apiml/acceptance/AddHeadersPerServiceTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/context/ConfigurableNamedContextFactoryTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/error/InternalServerErrorControllerTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/error/check/LoadBalancerErrorCheckTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/error/check/RibbonRetryErrorCheckTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/error/check/TimeoutErrorCheckTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/error/check/TlsErrorCheckTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/routing/ZuulErrorControllerHandlerTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/SafIdtSchemeTest.java
  gateway-service/src/test/resources/application-test.yml
  gateway-service/src/test/resources/application.yml
  gradle/versions.gradle
  metrics-service/build.gradle
  metrics-service/src/main/java/org/zowe/apiml/metrics/MetricsServiceApplication.java
  metrics-service/src/main/resources/application.yml
  metrics-service/src/test/java/org/zowe/apiml/metrics/functional/PrototypeFunctionalTest.java
Labels: size/XXL, Sensitive

#2391 chore: Upgrade spring boot to 2.5
  api-catalog-services/build.gradle
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/ApiCatalogApplication.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/controllers/handlers/NotFoundErrorController.java
  api-catalog-services/src/main/resources/application.yml
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/functional/ApiCatalogFunctionalTest.java
  api-catalog-services/src/test/resources/application.yml
  apiml-common-lib-package/src/main/resources/manifest.yaml
  apiml-common/build.gradle
  apiml-common/src/main/java/org/zowe/apiml/product/compatibility/ApimlDiscoveryCompositeHealthContributor.java
  apiml-common/src/main/java/org/zowe/apiml/product/compatibility/ApimlErrorController.java
  apiml-common/src/main/java/org/zowe/apiml/product/compatibility/ApimlHealthCheckHandler.java
  apiml-common/src/test/java/org/zowe/apiml/product/compatibility/ApimlDiscoveryCompositeHealthContributorTest.java
  apiml-common/src/test/java/org/zowe/apiml/product/compatibility/ApimlHealthCheckHandlerTest.java
  apiml-sample-extension-package/src/main/resources/manifest.yaml
  build.gradle
  caching-service/build.gradle
  caching-service/src/main/resources/application.yml
  caching-service/src/test/resources/application.yml
  config/local/api-catalog-service.yml
  config/local/discovery-service.yml
  config/local/gateway-service.yml
  discoverable-client/build.gradle
  discoverable-client/src/main/resources/application.yml
  discoverable-client/src/test/resources/application.yml
  discovery-service/build.gradle
  discovery-service/src/main/resources/application.yml
  discovery-service/src/test/resources/application.yml
  gateway-service/build.gradle
  gateway-service/src/main/java/org/zowe/apiml/gateway/error/controllers/InternalServerErrorController.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/error/controllers/NotFoundErrorController.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/routing/ZuulErrorControllerHandler.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/config/NewSecurityConfiguration.java
  gateway-service/src/main/resources/application.yml
  gateway-service/src/test/java/org/zowe/apiml/acceptance/AddHeadersPerServiceTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/context/ConfigurableNamedContextFactoryTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/error/InternalServerErrorControllerTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/error/check/LoadBalancerErrorCheckTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/error/check/RibbonRetryErrorCheckTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/error/check/TimeoutErrorCheckTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/error/check/TlsErrorCheckTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/routing/ZuulErrorControllerHandlerTest.java
  gateway-service/src/test/resources/application-test.yml
  gateway-service/src/test/resources/application.yml
  gradle/versions.gradle
  metrics-service/build.gradle
  metrics-service/src/main/java/org/zowe/apiml/metrics/MetricsServiceApplication.java
  metrics-service/src/main/resources/application.yml
  metrics-service/src/test/java/org/zowe/apiml/metrics/functional/PrototypeFunctionalTest.java
Labels: size/XXL

#2392 chore: Remove merge workflow
  .github/workflows/merge-major-version.yml
Labels: size/M

#2393 chore: Remove merge workflow
  .github/workflows/merge-major-version.yml
Labels: size/M

#2387 feat: Generate basic code snippets
  api-catalog-ui/frontend/cypress/integration/e2e/detail-page/detail-page.test.js
  api-catalog-ui/frontend/cypress/integration/e2e/detail-page/service-version-compare.test.js
  api-catalog-ui/frontend/cypress/integration/e2e/detail-page/swagger-try-out-and-code-snippets.test.js
  api-catalog-ui/frontend/package-lock.json
  api-catalog-ui/frontend/package.json
  api-catalog-ui/frontend/src/components/ServiceTab/ServiceTab.jsx
  api-catalog-ui/frontend/src/components/Swagger/Swagger.css
  api-catalog-ui/frontend/src/components/Swagger/SwaggerUI.jsx
  api-catalog-ui/frontend/src/utils/generateSnippets.js
  api-catalog-ui/frontend/src/utils/generateSnippets.test.js
Labels: size/L

#2395 chore: Add infinispan config for v2
  caching-service-package/src/main/resources/bin/start.sh
  caching-service-package/src/main/resources/manifest.yaml
  caching-service/src/main/java/org/zowe/apiml/caching/service/infinispan/config/InfinispanConfig.java
Labels: size/M

#2397 feat: Extend API operation filter in the Swagger UI
  api-catalog-ui/frontend/src/components/Swagger/SwaggerUI.jsx
  api-catalog-ui/frontend/src/utils/filterApis.js
  api-catalog-ui/frontend/src/utils/filterApis.test.js
Labels: size/L
