Repository zowe/api-layer, pull requests merged in 2023-04, with the labels that each got.

#2859 chore: spring update
  .github/workflows/containers.yml
  gradle/versions.gradle
Labels: size/XS

#2854 fix: read response from http client
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/instance/InstanceRetrievalService.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/staticapi/StaticAPIService.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/staticapi/StaticAPIServiceTest.java
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/filter/CategorizeCertsFilter.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/mapping/ExternalMapper.java
  zss-sample-service/server.js
Labels: size/L, Sensitive

#2860 chore: adding npm version to zowe plugin yml file
  .github/workflows/automated-release.yml
  .github/workflows/binary-specific-release.yml
  .github/workflows/zowe-cli-plugin.yml
  onboarding-enabler-nodejs/package.json
  zowe-cli-id-federation-plugin/package.json
Labels: size/S

#2866 chore: Update jettison and netty to latest versions.
  gradle/versions.gradle
Labels: size/XS

#2869 chore: Remove broken publishing of Zowe identity federation plugin.
  .github/workflows/automated-release.yml
  .github/workflows/binary-specific-release.yml
Labels: size/XS

#2871 docs: Sync the messages with the docs-site
  gateway-service/src/main/resources/gateway-log-messages.yml
Labels: size/M

#2872 chore: Update spring-security and spring-framework libraries
  cloud-gateway-service/build.gradle
  gradle/versions.gradle
Labels: size/XS

#2855 chore: run configuration
  .run/GatewayApplication.run.xml
  .run/spring-GatewayApplication.run.xml
Labels: size/M

#2876 fix: Fix parsing swagger2 by API Catalog
  .run/spring-ApiCatalogApplication.run.xml
  .run/spring-DiscoveryServiceApplication.run.xml
  api-catalog-services/build.gradle
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/services/cached/CachedApiDocService.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/swagger/api/ApiDocV2ServiceTest.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/swagger/api/ApiDocV3ServiceTest.java
  api-catalog-services/src/test/resources/swagger/openapi3.json
  api-catalog-services/src/test/resources/swagger/swagger2.json
  gradle/versions.gradle
Labels: size/L

#2879 Update zowe-cli-deploy-component.yml
  .github/workflows/zowe-cli-deploy-component.yml
Labels: size/XS

#2893 Update README.md
  zowe-cli-id-federation-plugin/README.md
Labels: size/XS
