Repository zowe/api-layer, pull requests merged in 2023-08, with the labels that each got.

#3014 Reboot/gh647/improved conformance testing
  gateway-service/src/main/java/org/zowe/apiml/gateway/conformance/ConformanceProblemsContainer.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/conformance/ValidateAPIController.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/conformance/VerificationOnboardService.java
  gateway-service/src/main/resources/gateway-log-messages.yml
  gateway-service/src/test/java/org/zowe/apiml/gateway/conformance/ConformanceProblemsContainerTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/conformance/ValidateAPIControllerTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/conformance/VerificationOnboardServiceTest.java
Labels: size/XL

#3013 feat: fix z/OSMF not available logging before validation
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/error/AuthExceptionHandler.java
  apiml-security-common/src/test/java/org/zowe/apiml/security/common/error/AuthExceptionHandlerTest.java
  apiml-utility/src/main/java/org/zowe/apiml/product/service/ServiceStartupEventHandler.java
  build.gradle
  discovery-package/src/main/resources/bin/start.sh
  gateway-service/src/main/java/org/zowe/apiml/gateway/GatewayApplication.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/GatewayStartupListener.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/zosmf/AbstractZosmfService.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/zosmf/ZosmfService.java
  gateway-service/src/main/resources/gateway-log-messages.yml
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/zosmf/ZosmfServiceTest.java
Labels: size/L, Sensitive

#3022 fix: [: FSUM7766 unbalanced [] startup message
  discovery-package/src/main/resources/bin/start.sh
Labels: size/XS

#3024 fix: newlines and ssl error message in z/OSMF validation
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/zosmf/AbstractZosmfService.java
  gateway-service/src/main/resources/gateway-log-messages.yml
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/zosmf/ZosmfServiceTest.java
Labels: size/M, Sensitive

#3023 chore: Improve conformance validation
  gateway-service/src/main/java/org/zowe/apiml/gateway/conformance/ConformanceProblemsContainer.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/conformance/ValidateAPIController.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/conformance/VerificationOnboardService.java
  gateway-service/src/main/resources/gateway-log-messages.yml
  gateway-service/src/test/java/org/zowe/apiml/gateway/conformance/ConformanceProblemsContainerTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/conformance/ValidateAPIControllerTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/conformance/VerificationOnboardServiceTest.java
  integration-tests/src/test/java/org/zowe/apiml/functional/gateway/ValidateAPITest.java
Labels: size/XL

#3019 Remove stacktrace from Catalog log when service is down
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/instance/EurekaServiceInstanceRequest.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/instance/InstanceRetrievalService.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/services/status/APIDocRetrievalService.java
  api-catalog-services/src/main/resources/apicatalog-log-messages.yml
Labels: size/L

#3029 fix: setting default value of nonStrictVerifySslCertificatesOfServices to …
  api-catalog-package/src/main/resources/bin/start.sh
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/security/SecurityConfiguration.java
  caching-service-package/src/main/resources/bin/start.sh
  caching-service/src/main/java/org/zowe/apiml/caching/config/SpringSecurityConfig.java
  common-service-core/src/main/java/org/zowe/apiml/security/HttpsFactory.java
  discovery-package/src/main/resources/bin/start.sh
  discovery-service/src/main/java/org/zowe/apiml/discovery/config/HttpsWebSecurityConfig.java
  gateway-package/src/main/resources/bin/start.sh
  integration-tests/src/test/java/org/zowe/apiml/util/config/ConfigReaderZaasClient.java
  metrics-service-package/src/main/resources/bin/start.sh
  onboarding-enabler-java/src/main/java/org/zowe/apiml/eurekaservice/client/impl/ApiMediationClientImpl.java
Labels: size/M, Sensitive

#3032 fix: update messages after docs review
  gateway-service/src/main/resources/gateway-log-messages.yml
  gateway-service/src/test/resources/gateway-messages.yml
Labels: size/S

#3040 fix: Fix processing of Open API docs by API Catalog (JavaTimeModule)
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/api/ApiDocV2Service.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/api/ApiDocV3Service.java
Labels: size/S

#3031 feat: Spring cloud gateway routing
  .github/workflows/containers.yml
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/config/RoutingConfig.java
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/filters/HeaderRouteStepFilterFactory.java
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/service/ProxyRouteLocator.java
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/service/RouteLocator.java
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/service/routing/ByBasePath.java
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/service/routing/ByHeader.java
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/service/routing/RouteDefinitionProducer.java
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/service/scheme/HttpBasicPassticket.java
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/service/scheme/SchemeHandler.java
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/service/scheme/X509.java
  cloud-gateway-service/src/main/resources/application.yml
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/acceptance/CorsPerServiceTest.java
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/acceptance/PassticketTest.java
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/acceptance/RequestInstanceTest.java
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/acceptance/RetryPerServiceTest.java
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/acceptance/common/MetadataBuilder.java
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/acceptance/config/DiscoveryClientTestConfig.java
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/acceptance/netflix/ApimlDiscoveryClientStub.java
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/config/ConnectionsConfigTest.java
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/filters/HeaderRouteStepFilterFactoryTest.java
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/service/RouteLocatorTest.java
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/service/routing/ByBasePathTest.java
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/service/routing/ByHeaderTest.java
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/service/routing/RouteDefinitionProducerTest.java
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/service/scheme/HttpBasicPassticketTest.java
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/service/scheme/X509Test.java
  cloud-gateway-service/src/test/resources/application-test.yml
  cloud-gateway-service/src/test/resources/application.yml
  common-service-core/src/main/java/org/zowe/apiml/constants/EurekaMetadataDefinition.java
  common-service-core/src/main/java/org/zowe/apiml/util/StringUtils.java
  common-service-core/src/test/java/org/zowe/apiml/util/StringUtilsTest.java
  config/docker/gateway-service.yml
  config/local/gateway-service.yml
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/GatewayConfig.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/routing/ApimlRouteLocator.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/routing/NewApimlRouteLocator.java
  integration-tests/src/test/java/org/zowe/apiml/integration/proxy/CloudGatewayProxyTest.java
Labels: size/XXL

#3039 feat: swagger validation in gateway
  gateway-service/build.gradle
  gateway-service/src/main/java/org/zowe/apiml/gateway/conformance/AbstractSwaggerValidator.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/conformance/ConformanceProblemsContainer.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/conformance/Endpoint.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/conformance/OpenApiV2Validator.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/conformance/OpenApiV3Validator.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/conformance/ValidateAPIController.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/conformance/ValidationException.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/conformance/ValidatorFactory.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/conformance/VerificationOnboardService.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/conformance/ConformanceProblemsContainerTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/conformance/ValidateAPIControllerTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/conformance/ValidatorFactoryTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/conformance/VerificationOnboardServiceTest.java
  gateway-service/src/test/resources/api-doc-v2.json
  integration-tests/src/test/java/org/zowe/apiml/functional/gateway/ValidateAPITest.java
Labels: size/XXL

#3044 fix: Integration tests for new Cloud Gateway routing
  .github/workflows/containers.yml
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/filters/MissingHeaderRoutePredicateFactory.java
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/service/routing/ByBasePath.java
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/filters/MissingHeaderRoutePredicateFactoryTest.java
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/service/routing/ByBasePathTest.java
  config/local/cloud-gateway-service.yml
  config/local/gateway-service.yml
  gateway-package/src/main/resources/bin/start.sh
  gateway-package/src/main/resources/manifest.yaml
  integration-tests/src/test/java/org/zowe/apiml/functional/gateway/CloudGatewayRoutingTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/authentication/schemes/X509SchemeTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/proxy/CloudGatewayProxyTest.java
Labels: size/L

#3048 chore: update dependencies
  api-catalog-ui/frontend/config-overrides.js
  api-catalog-ui/frontend/package-lock.json
  api-catalog-ui/frontend/package.json
  gradle/versions.gradle
  metrics-service-ui/frontend/package-lock.json
  metrics-service-ui/frontend/package.json
  zowe-cli-id-federation-plugin/npm-shrinkwrap.json
  zowe-cli-id-federation-plugin/package.json
Labels: size/M

#3053 chore: Update UI per suggestions from UX + add keyboard shortcuts - Mike
  api-catalog-ui/frontend/config-overrides.js
  api-catalog-ui/frontend/package.json
  api-catalog-ui/frontend/src/assets/images/linkedin-red.png
  api-catalog-ui/frontend/src/assets/images/square-envelope.png
  api-catalog-ui/frontend/src/assets/images/swagger.png
  api-catalog-ui/frontend/src/assets/images/twitter-square.png
  api-catalog-ui/frontend/src/assets/images/youtube-square.png
  api-catalog-ui/frontend/src/assets/scss/_theme_default.scss
  api-catalog-ui/frontend/src/components/App/_app.scss
  api-catalog-ui/frontend/src/components/Dashboard/Dashboard.css
  api-catalog-ui/frontend/src/components/Dashboard/Dashboard.jsx
  api-catalog-ui/frontend/src/components/Dashboard/Dashboard.test.jsx
  api-catalog-ui/frontend/src/components/Dashboard/_dashboard.scss
  api-catalog-ui/frontend/src/components/Footer/Footer.jsx
  api-catalog-ui/frontend/src/components/Header/Header.jsx
  api-catalog-ui/frontend/src/components/Header/_header.scss
  api-catalog-ui/frontend/src/components/Search/SearchCriteria.jsx
  api-catalog-ui/frontend/src/components/Search/_search.scss
  api-catalog-ui/frontend/src/components/ServicesNavigationBar/_serviceNavigationBar.scss
  api-catalog-ui/frontend/src/components/Spinner/_spinner.scss
  api-catalog-ui/frontend/src/components/Tile/Tile.css
  api-catalog-ui/frontend/src/components/Tile/Tile.jsx
  api-catalog-ui/frontend/src/components/Tile/Tile.test.jsx
  api-catalog-ui/frontend/src/components/Tile/_tile.scss
  api-catalog-ui/frontend/src/utils/utilFunctions.js
  api-catalog-ui/frontend/src/utils/utilFunctions.test.js
Labels: size/L

#3054 Reboot/gh647/verify sso
  gateway-service/src/main/java/org/zowe/apiml/gateway/conformance/AbstractSwaggerValidator.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/conformance/ConformanceProblemsContainer.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/conformance/Endpoint.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/conformance/OpenApiV2Validator.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/conformance/OpenApiV3Validator.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/conformance/ValidateAPIController.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/conformance/VerificationOnboardService.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/conformance/ConformanceProblemsContainerTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/conformance/ValidateAPIControllerTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/conformance/ValidatorFactoryTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/conformance/VerificationOnboardServiceTest.java
  integration-tests/src/test/java/org/zowe/apiml/functional/gateway/ValidateAPITest.java
Labels: size/L

#3046 feat: Forward client certificate from central gateway to domain gateway in request header
  .github/workflows/containers.yml
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/security/SecurityConfiguration.java
  apiml-security-common/build.gradle
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/filter/CategorizeCertsFilter.java
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/verify/CertificateValidator.java
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/verify/TrustedCertificatesProvider.java
  apiml-security-common/src/main/resources/security-common-log-messages.yml
  apiml-security-common/src/test/java/org/zowe/apiml/security/common/auth/SafMethodSecurityExpressionControllerTest.java
  apiml-security-common/src/test/java/org/zowe/apiml/security/common/filter/CategorizeCertsFilterTest.java
  apiml-security-common/src/test/java/org/zowe/apiml/security/common/verify/CertificateValidatorTest.java
  apiml-security-common/src/test/java/org/zowe/apiml/security/common/verify/TrustedCertificatesProviderTest.java
  apiml-security-common/src/test/resources/security-service-messages.yml
  cloud-gateway-package/src/main/resources/bin/start.sh
  cloud-gateway-package/src/main/resources/manifest.yaml
  cloud-gateway-service/build.gradle
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/config/RoutingConfig.java
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/controller/CertificatesRestController.java
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/filters/ClientCertFilterFactory.java
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/service/CertificateChainService.java
  cloud-gateway-service/src/main/resources/application.yml
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/controller/CertificatesRestControllerTest.java
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/filters/ClientCertFilterFactoryTest.java
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/service/CertificateChainServiceTest.java
  cloud-gateway-service/src/test/resources/application.yml
  common-service-core/src/main/java/org/zowe/apiml/security/SecurityUtils.java
  config/local/gateway-service.yml
  gateway-package/src/main/resources/bin/start.sh
  gateway-package/src/main/resources/manifest.yaml
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/config/NewSecurityConfiguration.java
  gateway-service/src/main/resources/application.yml
  gateway-service/src/main/resources/ehcache.xml
  integration-tests/src/test/java/org/zowe/apiml/integration/authentication/schemes/PassticketSchemeTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/authentication/schemes/X509SchemeTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/proxy/CloudGatewayProxyTest.java
  integration-tests/src/test/java/org/zowe/apiml/util/requests/Endpoints.java
  keystore/docker/all-services.ext
  keystore/docker/all-services.keystore.p12
Labels: size/XXL, Sensitive
