Repository zowe/api-layer, pull requests merged in 2023-01, with the labels that each got.

#2718 feat: support passticket auth scheme in cloud gateway service
  .github/workflows/containers.yml
  build.gradle
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/config/HttpConfig.java
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/filters/PassticketFilterFactory.java
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/service/InstanceInfoService.java
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/service/RouteLocator.java
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/acceptance/CorsPerServiceTest.java
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/acceptance/PassticketTest.java
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/acceptance/RequestInstanceTest.java
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/acceptance/RetryPerServiceTest.java
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/acceptance/common/AcceptanceTestWithTwoServices.java
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/acceptance/common/MetadataBuilder.java
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/acceptance/config/DiscoveryClientTestConfig.java
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/acceptance/netflix/ApplicationRegistry.java
  common-service-core/src/main/java/org/zowe/apiml/ticket/TicketRequest.java
  common-service-core/src/main/java/org/zowe/apiml/ticket/TicketResponse.java
  common-service-core/src/main/resources/core-log-messages.yml
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/ticket/SuccessfulTicketHandler.java
  gateway-service/src/main/resources/gateway-log-messages.yml
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/ticket/SuccessfulTicketHandlerTest.java
  integration-tests/build.gradle
  integration-tests/src/test/java/org/zowe/apiml/integration/authentication/schemes/PassticketSchemeTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/penetration/JwtPenTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/zos/PassTicketTest.java
Labels: size/XL, Sensitive

#2723 chore: passticket error test
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/filters/PassticketFilterFactory.java
  integration-tests/src/test/java/org/zowe/apiml/integration/authentication/schemes/PassticketSchemeTest.java
Labels: size/M

#2725 chore: clean build when release
  .github/workflows/binary-snapshot-release.yml
  .github/workflows/pull-request-snapshot-release.yml
Labels: size/XS

#2727 chore: clean build for remaining jobs
  .github/workflows/automated-release.yml
  .github/workflows/binary-specific-release.yml
  .github/workflows/ci-tests.yml
  .github/workflows/image-publish-branch.yml
  .github/workflows/image-snapshot-release.yml
  .github/workflows/image-specific-release.yml
Labels: size/S

#2724 Fix missing z/OS related metadata
  common-service-core/src/main/java/org/zowe/apiml/util/ClassOrDefaultProxyUtils.java
  common-service-core/src/test/java/org/zowe/apiml/util/ClassOrDefaultProxyUtilsTest.java
  onboarding-enabler-java/src/main/java/org/zowe/apiml/eurekaservice/client/impl/ApiMediationClientImpl.java
  onboarding-enabler-java/src/test/java/org/zowe/apiml/eurekaservice/client/impl/ApiMediationClientImplTest.java
Labels: size/L

#2721 Update debug log message
  apiml-extension-loader/src/main/java/org/zowe/apiml/extension/ExtensionConfigReader.java
Labels: size/XS

#2726 Add API Catalog standalone mode - only remove authentication
  api-catalog-services/README.md
  api-catalog-services/build.gradle
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/security/SecurityConfiguration.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/services/status/listeners/GatewayLookupEventListener.java
  api-catalog-services/src/main/resources/META-INF/additional-spring-configuration-metadata.json
Labels: size/M, Sensitive

#2734 chore: update netty
  cloud-gateway-service/build.gradle
  gradle/versions.gradle
  onboarding-enabler-micronaut/build.gradle
Labels: size/S

#2729 feat: remap client cert
  cloud-gateway-service/build.gradle
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/config/HttpConfig.java
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/config/WebSecurity.java
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/filters/PassticketFilterFactory.java
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/filters/X509FilterFactory.java
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/service/RouteLocator.java
  cloud-gateway-service/src/main/resources/application.yml
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/filters/X509FilterFactoryTest.java
  cloud-gateway-service/src/test/resources/application.yml
  cloud-gateway-service/src/test/resources/cloud-gateway-log-messages.yml
  common-service-core/src/main/java/org/zowe/apiml/constants/ApimlConstants.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/pre/ServiceAuthenticationFilter.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/SafIdtSchemeTest.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/X509SchemeTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/filters/pre/ServiceAuthenticationFilterTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/SafIdtSchemeTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/authentication/schemes/PassticketSchemeTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/authentication/schemes/X509SchemeTest.java
Labels: size/XL, Sensitive

#2736 Chore: Upgrade vulnerable libraries
  api-catalog-services/build.gradle
  discoverable-client/build.gradle
  discovery-service/build.gradle
  gateway-service/build.gradle
  gradle/versions.gradle
  metrics-service/build.gradle
Labels: size/S

#2737 chore(deps): Update XStream
  apiml-common/build.gradle
  cloud-gateway-service/build.gradle
  gradle/versions.gradle
  onboarding-enabler-java/build.gradle
  onboarding-enabler-spring/build.gradle
  security-service-client-spring/build.gradle
Labels: size/S, Sensitive

#2739 chore(deps): Move eslint to devDependencies
  api-catalog-ui/frontend/package-lock.json
  api-catalog-ui/frontend/package.json
  metrics-service-ui/frontend/package-lock.json
  metrics-service-ui/frontend/package.json
Labels: size/XS

#2744 fix: improve handling of SSL errors
  api-catalog-services/src/main/resources/application.yml
  apiml-common/src/main/java/org/zowe/apiml/product/eureka/client/ApimlPeerEurekaNode.java
  apiml-common/src/main/java/org/zowe/apiml/product/eureka/client/AsgReplicationTask.java
  apiml-common/src/main/java/org/zowe/apiml/product/eureka/client/InstanceReplicationTask.java
  apiml-common/src/main/java/org/zowe/apiml/product/eureka/client/ReplicationTask.java
  apiml-common/src/test/java/org/zowe/apiml/product/eureka/client/ApimlPeerEurekaNodeTest.java
  apiml-common/src/test/java/org/zowe/apiml/product/eureka/client/ReplicationTaskProcessorTest.java
  apiml-common/src/test/java/org/zowe/apiml/product/eureka/client/TestableHttpReplicationClient.java
  apiml-common/src/test/java/org/zowe/apiml/product/eureka/client/TestableInstanceReplicationTask.java
  caching-service/src/main/resources/application.yml
  discovery-service/src/main/java/org/zowe/apiml/discovery/config/EurekaConfig.java
  discovery-service/src/main/java/org/zowe/apiml/discovery/eureka/RefreshablePeerEurekaNodes.java
  discovery-service/src/main/resources/application.yml
  discovery-service/src/test/java/org/zowe/apiml/discovery/eureka/RefreshablePeerEurekaNodesTest.java
  gateway-service/src/main/resources/application.yml
Labels: size/XXL

#2750 chore: Change structure of configuration to hide service info
  api-catalog-package/src/main/resources/bin/start.sh
  api-catalog-package/src/main/resources/manifest.yaml
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/services/cached/CachedProductFamilyService.java
Labels: size/XS

#2757 feat: provide OIDC info via webfinger
  config/local/gateway-service.yml
  config/local/webfinger.yml
  gateway-service/src/main/java/org/zowe/apiml/gateway/controllers/AuthController.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/webfinger/StaticWebFingerProvider.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/webfinger/WebFingerProperties.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/webfinger/WebFingerProvider.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/webfinger/WebFingerResponse.java
  gateway-service/src/main/resources/gateway-log-messages.yml
  gateway-service/src/test/java/org/zowe/apiml/gateway/controllers/AuthControllerTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/webfinger/StaticWebFingerProviderTest.java
  gateway-service/src/test/resources/gateway-messages.yml
Labels: size/L, Sensitive

#2768 refactor: Restructured unit test classes
  discovery-service/src/test/java/org/zowe/apiml/discovery/EurekaInstanceRegisteredListenerTest.java
  discovery-service/src/test/java/org/zowe/apiml/discovery/EurekaSecuredEndpointsTest.java
  discovery-service/src/test/java/org/zowe/apiml/discovery/functional/HttpSecuredEndpointTest.java
  discovery-service/src/test/java/org/zowe/apiml/discovery/functional/HttpsSecuredEndpointsTest.java
  discovery-service/src/test/java/org/zowe/apiml/discovery/health/DiscoveryServiceHealthIndicatorTest.java
  discovery-service/src/test/java/org/zowe/apiml/discovery/metadata/MetadataDefaultsServiceTest.java
  discovery-service/src/test/java/org/zowe/apiml/discovery/metadata/MetadataTranslationServiceTest.java
  discovery-service/src/test/java/org/zowe/apiml/discovery/staticdef/ServiceDefinitionProcessorTest.java
Labels: size/L

#2746 Mock implementation for try out in standalone API catalog
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/controllers/api/MockController.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/standalone/ApiDocTransformForMock.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/standalone/StandaloneLoaderService.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/standalone/StandaloneSecurityConfig.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/controllers/api/MockControllerTest.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/standalone/ApiDocTransformForMockTest.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/standalone/StandaloneLoaderServiceTest.java
  api-catalog-services/src/test/resources/standalone/services/apps/service1.json
  api-catalog-services/src/test/resources/standalone/services/apps/service2.json
  config/local/catalog-standalone-defs/apps/service1.json
  config/local/catalog-standalone-defs/apps/service2.json
Labels: size/L, Sensitive

#2758 Using examples by mock endpoint in API Catalog from API doc files
  api-catalog-services/build.gradle
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/controllers/api/MockController.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/standalone/ExampleService.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/standalone/StandaloneLoaderService.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/api/AbstractApiDocService.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/api/ApiDocV2Service.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/api/ApiDocV3Service.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/controllers/api/MockControllerTest.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/standalone/ExampleServiceTest.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/standalone/StandaloneLoaderServiceTest.java
  gradle/versions.gradle
Labels: size/L

#2769 Allow environment variable override of tmp in java
  api-catalog-package/src/main/resources/bin/start.sh
  caching-service-package/src/main/resources/bin/start.sh
  cloud-gateway-package/src/main/resources/bin/start.sh
  config/zowe-api-dev/alternative_start.sh
  discovery-package/src/main/resources/bin/start.sh
  gateway-package/src/main/resources/bin/start.sh
  metrics-service-package/src/main/resources/bin/start.sh
Labels: size/S

#2772 Fix media type in mock controller
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/standalone/ExampleService.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/controllers/api/MockControllerTest.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/standalone/ExampleServiceTest.java
Labels: size/S

#2773 fix: Fix bug in Wizard static onboarding method
  api-catalog-ui/frontend/src/components/Wizard/configs/wizard_static_categories.jsx
Labels: size/XS

#2767 Improve API catalog documentation for command to build standalone
  api-catalog-services/README.md
  api-catalog-ui/frontend/README.md
Labels: size/S
