Repository zowe/api-layer, pull requests merged in 2023-02, with the labels that each got.

#2751 feat: add standalone catalog integration tests
  .github/workflows/containers.yml
  api-catalog-services/README.md
  api-catalog-services/build.gradle
  config/docker/api-catalog-services-standalone.yml
  config/docker/catalog-standalone-defs/apiDocs/service1-instance1_org.zowe v1.0.0_default.json
  config/docker/catalog-standalone-defs/apiDocs/service1-instance2_org.zowe v1.0.0_default.json
  config/docker/catalog-standalone-defs/apiDocs/service2_org.zowe v1.0.0_default.json
  config/docker/catalog-standalone-defs/apiDocs/service2_org.zowe v2.0.0.json
  config/docker/catalog-standalone-defs/apiDocs/service3_instance1_org.zowe v1.0.0_default.json
  config/docker/catalog-standalone-defs/apps/service1.json
  config/docker/catalog-standalone-defs/apps/service2.json
  config/docker/catalog-standalone-defs/apps/service3.json
  docker/local-single/docker-compose.yml
  gradle/versions.gradle
  integration-tests/build.gradle
  integration-tests/src/test/java/org/zowe/apiml/functional/apicatalog/ApiCatalogEndpointIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/functional/apicatalog/ApiCatalogStandaloneTest.java
  integration-tests/src/test/java/org/zowe/apiml/util/StartAndCleanApplications.java
  integration-tests/src/test/java/org/zowe/apiml/util/config/ConfigReader.java
  integration-tests/src/test/java/org/zowe/apiml/util/config/EnvironmentConfiguration.java
  integration-tests/src/test/resources/environment-configuration-docker.yml
  integration-tests/src/test/resources/environment-configuration.yml
Labels: size/XXL

#2782 chore: Improve error handling for Wizard Static Onboarding
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/staticapi/StaticDefinitionControllerExceptionHandler.java
  api-catalog-ui/frontend/src/actions/wizard-fetch-actions.jsx
  api-catalog-ui/frontend/src/assets/css/APIMReactToastify.css
Labels: size/S

#2775 fix: Eureka peer connections loop
  apiml-common/src/main/java/org/zowe/apiml/product/eureka/client/ApimlPeerEurekaNode.java
  apiml-common/src/test/java/org/zowe/apiml/product/eureka/client/ApimlPeerEurekaNodeTest.java
  apiml-common/src/test/java/org/zowe/apiml/product/eureka/client/ReplicationTaskProcessorTest.java
  discovery-service/src/main/java/org/zowe/apiml/discovery/config/EurekaConfig.java
  discovery-service/src/main/java/org/zowe/apiml/discovery/eureka/RefreshablePeerEurekaNodes.java
  discovery-service/src/test/java/org/zowe/apiml/discovery/eureka/RefreshablePeerEurekaNodesTest.java
Labels: size/L

#2784 chore: Upgrade Node.js and npm
  .github/actions/setup/action.yml
  .github/workflows/changelog.yml
  .github/workflows/docs.yml
  .github/workflows/release_and_update_manifest_json.yml
  api-catalog-ui/frontend/package-lock.json
  api-catalog-ui/frontend/package.json
  gradle/versions.gradle
  metrics-service-ui/frontend/package-lock.json
  metrics-service-ui/frontend/package.json
  onboarding-enabler-nodejs-sample-app/package-lock.json
  onboarding-enabler-nodejs-sample-app/package.json
  onboarding-enabler-nodejs/package.json
Labels: size/M

#2787 fix: Catalog image build
  containers/prepare-utils.sh
Labels: size/XS

#2788 fix: remove diff script
  api-catalog-ui/build.gradle
  containers/prepare-utils.sh
Labels: size/M

#2785 chore: Increase coverage of statements
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/model/ServiceUpdateResult.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/model/SemanticVersionTest.java
  discoverable-client/src/test/java/org/zowe/apiml/client/api/GreetingGraphControllerTest.java
  discoverable-client/src/test/java/org/zowe/apiml/client/api/RequestInfoControllerTest.java
  discoverable-client/src/test/java/org/zowe/apiml/client/api/StatusCodeControllerTest.java
  discoverable-client/src/test/java/org/zowe/apiml/client/api/WebServiceControllerTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/controllers/AuthProviderControllerTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/error/controllers/NotFoundErrorControllerTest.java
  onboarding-enabler-spring-sample-app/src/test/java/org/zowe/apiml/sample/enable/controller/SampleControllerTest.java
Labels: size/L

#2789 fix: recognize profile settings
  config/local/api-catalog-service.yml
Labels: size/XS

#2790 feat: Skeleton of Zowe CLI plugin for identity federation ESM mapping
  zowe-cli-id-federation-plugin/.eslintrc.js
  zowe-cli-id-federation-plugin/.gitignore
  zowe-cli-id-federation-plugin/.husky/commit-msg
  zowe-cli-id-federation-plugin/.npmignore
  zowe-cli-id-federation-plugin/.npmrc
  zowe-cli-id-federation-plugin/LICENSE_HEADER
  zowe-cli-id-federation-plugin/README.md
  zowe-cli-id-federation-plugin/__tests__/__integration__/cli/map/__resources__/zowe.config.json
  zowe-cli-id-federation-plugin/__tests__/__integration__/cli/map/__scripts__/map_error_handler.sh
  zowe-cli-id-federation-plugin/__tests__/__integration__/cli/map/__scripts__/map_old_profiles.sh
  zowe-cli-id-federation-plugin/__tests__/__integration__/cli/map/__scripts__/map_team_config.sh
  zowe-cli-id-federation-plugin/__tests__/__integration__/cli/map/__snapshots__/cli.map.integration.test.ts.snap
  zowe-cli-id-federation-plugin/__tests__/__integration__/cli/map/cli.map.integration.test.ts
  zowe-cli-id-federation-plugin/__tests__/__resources__/env/integration.env
  zowe-cli-id-federation-plugin/__tests__/__resources__/env/system.env
  zowe-cli-id-federation-plugin/__tests__/__resources__/env/unit.env
  zowe-cli-id-federation-plugin/__tests__/__resources__/properties/custom_properties.yaml
  zowe-cli-id-federation-plugin/__tests__/__snapshots__/main.failure.test.ts.snap
  zowe-cli-id-federation-plugin/__tests__/__snapshots__/main.success.test.ts.snap
  zowe-cli-id-federation-plugin/__tests__/__src__/environment/doc/ITestPropertiesSchema.ts
  zowe-cli-id-federation-plugin/__tests__/__system__/cli/map/__scripts__/map.sh
  zowe-cli-id-federation-plugin/__tests__/__system__/cli/map/__scripts__/map_help.sh
  zowe-cli-id-federation-plugin/__tests__/__system__/cli/map/__snapshots__/cli.map.system.test.ts.snap
  zowe-cli-id-federation-plugin/__tests__/__system__/cli/map/cli.map.system.test.ts
  zowe-cli-id-federation-plugin/__tests__/api/Mapper.test.ts
  zowe-cli-id-federation-plugin/__tests__/cli/map/Map.definition.test.ts
  zowe-cli-id-federation-plugin/__tests__/cli/map/Map.handler.test.ts
  zowe-cli-id-federation-plugin/__tests__/cli/map/__snapshots__/Map.definition.test.ts.snap
  zowe-cli-id-federation-plugin/__tests__/cli/map/__snapshots__/Map.handler.test.ts.snap
  zowe-cli-id-federation-plugin/__tests__/imperative.test.ts
  zowe-cli-id-federation-plugin/__tests__/test-tsconfig.json
  zowe-cli-id-federation-plugin/npm-shrinkwrap.json
  zowe-cli-id-federation-plugin/package.json
  zowe-cli-id-federation-plugin/release.config.js
  zowe-cli-id-federation-plugin/src/api/Mapper.ts
  zowe-cli-id-federation-plugin/src/api/ProfileConstants.ts
  zowe-cli-id-federation-plugin/src/cli/map/Map.definition.ts
  zowe-cli-id-federation-plugin/src/cli/map/Map.handler.ts
  zowe-cli-id-federation-plugin/src/healthCheck.Handler.ts
  zowe-cli-id-federation-plugin/src/imperative.ts
  zowe-cli-id-federation-plugin/src/index.ts
  zowe-cli-id-federation-plugin/tsconfig.json
Labels: size/XXL

#2791 chore: Increase statement coverage
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/services/status/model/ApiDiffNotAvailableExceptionTest.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/swagger/ApiDocTransformationExceptionTest.java
  api-catalog-ui/frontend/src/actions/service-version-diff-actions.test.jsx
  api-catalog-ui/frontend/src/actions/user-actions.test.jsx
  api-catalog-ui/frontend/src/components/Error/ErrorFormatter.test.jsx
  api-catalog-ui/frontend/src/services/user.service.test.jsx
  apiml-common/src/test/java/org/zowe/apiml/product/gateway/GatewayNotAvailableExceptionTest.java
  apiml-common/src/test/java/org/zowe/apiml/product/instance/lookup/RetryExceptionTest.java
  apiml-common/src/test/java/org/zowe/apiml/product/registry/CannotRegisterServiceExceptionTest.java
  apiml-security-common/src/test/java/org/zowe/apiml/security/common/error/AuthenticationTokenExceptionTest.java
  apiml-security-common/src/test/java/org/zowe/apiml/security/common/login/X509AuthAwareFilterTest.java
  apiml-tomcat-common/src/test/java/org/zowe/apiml/exception/AttlsHandlerExceptionTest.java
  apiml-tomcat-common/src/test/java/org/zowe/apiml/exception/InboundAttlsExceptionTest.java
  apiml-utility/src/test/java/org/zowe/apiml/product/logging/UseridFilterTest.java
  caching-service/src/test/java/org/zowe/apiml/caching/exceptions/CachingPayloadExceptionTest.java
  caching-service/src/test/java/org/zowe/apiml/caching/service/infinispan/exception/InfinispanConfigExceptionTest.java
  certificate-analyser/src/test/java/org/zowe/apiml/StoresTest.java
  common-service-core/src/test/java/org/zowe/apiml/exception/ServiceDefinitionExceptionTest.java
  common-service-core/src/test/java/org/zowe/apiml/security/SecurityUtilsTest.java
  common-service-core/src/test/java/org/zowe/apiml/zfile/EnqueueExceptionTest.java
  common-service-core/src/test/java/org/zowe/apiml/zfile/RcExceptionTest.java
  common-service-core/src/test/java/org/zowe/apiml/zfile/ZFileExceptionTest.java
  discoverable-client/src/test/java/org/zowe/apiml/client/ws/HeaderSocketServerHandlerTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/AuthenticationSchemeNotSupportedExceptionTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/ws/WebSocketRoutedSessionTest.java
  gradle/sonar.gradle
Labels: size/XXL, Sensitive

#2796 chore: Suppress eslint warnings
  api-catalog-ui/frontend/src/components/Dashboard/DashboardContainer.test.jsx
  metrics-service-ui/frontend/src/components/Header/HeaderContainer.test.jsx
  metrics-service-ui/frontend/src/components/Login/Login.test.jsx
  metrics-service-ui/frontend/src/components/Login/LoginContainer.test.jsx
Labels: size/XS

#2799 feat: Support of other keyring types
  api-catalog-ui/frontend/src/components/Wizard/configs/wizard_base_categories.jsx
  certificate-analyser/src/test/java/org/zowe/apiml/StoresTest.java
  onboarding-enabler-java/src/main/java/org/zowe/apiml/eurekaservice/client/util/EurekaInstanceConfigValidator.java
Labels: size/S

#2797 fix: periodically clean connection pool
  .run/spring-GatewayApplication.run.xml
  apiml-common/src/main/java/org/zowe/apiml/product/web/HttpConfig.java
  common-service-core/src/main/java/org/zowe/apiml/security/HttpsFactory.java
  common-service-core/src/test/java/org/zowe/apiml/security/HttpsFactoryTest.java
  common-service-core/src/test/java/org/zowe/apiml/tomcat/TomcatHttpsTest.java
  common-service-core/src/test/java/org/zowe/apiml/tomcat/TomcatServerFactory.java
  config/local/gateway-service.yml
Labels: size/L, Sensitive

#2805 fix: handle WebSocket connection failure
  gateway-service/src/main/java/org/zowe/apiml/gateway/ws/WebSocketProxyServerHandler.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/ws/WebSocketRoutedSessionFactory.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/ws/WebSocketProxyServerHandlerTest.java
Labels: size/L

#2809 Space missing
  certificate-analyser/README.md
Labels: size/XS

#2807 fix:run gateway instances with own cache storage
  gateway-package/src/main/resources/bin/start.sh
  package.json
Labels: size/XS

#2808 feat: zowe-cli-id-federation-plugin included as gradle module
  gradle/coverage.gradle
  gradle/sonar.gradle
  settings.gradle
  zowe-cli-id-federation-plugin/build.gradle
  zowe-cli-id-federation-plugin/package.json
Labels: size/M
