Repository zowe/api-layer, pull requests merged in 2023-09, with the labels that each got.

#3057 chore: add media icon and change link color
  api-catalog-ui/frontend/package-lock.json
  api-catalog-ui/frontend/src/assets/images/youtube2.png
  api-catalog-ui/frontend/src/components/App/_app.scss
  api-catalog-ui/frontend/src/components/Footer/_footer.scss
  api-catalog-ui/frontend/src/components/Header/_header.scss
Labels: size/S

#3050 fix: Fixes for API Catalog standalone mode
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/services/cached/CachedApiDocService.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/services/status/listeners/AppReadyListener.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/standalone/StandaloneInitializer.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/standalone/StandaloneLoaderService.java
  api-catalog-ui/frontend/src/components/App/_app.scss
  api-catalog-ui/frontend/src/selectors/selectors.jsx
Labels: size/S

#3059 fix: fix header in api portal
  api-catalog-ui/frontend/src/components/Header/_header.scss
  api-catalog-ui/frontend/src/utils/utilFunctions.js
Labels: size/XS

#3066 Remove invalid information from internal documentation
  README.md
  docs/diagnostics.md
Labels: size/S

#3072 Update run api-layer readme
  README.md
Labels: size/S

#3070 chore: Update dependencies to avoid vulnerabilities V1
  build.gradle
  gradle/versions.gradle
  onboarding-enabler-micronaut-sample-app/src/test/resources/application.yml
Labels: size/S

#3069 feat: Add centralRegistryUrls config parameter to zowe.yaml
  .github/workflows/containers.yml
  gateway-package/src/main/resources/bin/start.sh
  gateway-service/src/main/resources/application.yml
  gateway-service/src/test/resources/application.yml
  schemas/cloud-gateway-schema.json
  schemas/gateway-schema.json
Labels: size/M

#3074 chore: Update dependencies to avoid vulnerabilities V2
  build.gradle
  gradle/versions.gradle
Labels: size/S

#3073 chore: Add html-loader in webpack config
  api-catalog-ui/frontend/config-overrides.js
  api-catalog-ui/frontend/package-lock.json
  api-catalog-ui/frontend/package.json
  api-catalog-ui/frontend/src/utils/utilFunctions.js
Labels: size/S

#3078 chore: Update Tomcat to version 9.0.80 in V2
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/post/CustomSendErrorFilter.java
  gradle/versions.gradle
Labels: size/XS

#3087 fix: heap configuration from zowe.yaml
  api-catalog-package/src/main/resources/bin/start.sh
  caching-service-package/src/main/resources/bin/start.sh
  cloud-gateway-package/src/main/resources/bin/start.sh
  discovery-package/src/main/resources/bin/start.sh
  gateway-package/src/main/resources/bin/start.sh
  metrics-service-package/src/main/resources/bin/start.sh
  schemas/caching-schema.json
  schemas/catalog-schema.json
  schemas/cloud-gateway-schema.json
  schemas/discovery-schema.json
  schemas/gateway-schema.json
  schemas/metrics-schema.json
Labels: size/L

#3089 Private/ms895784/more UI fixes
  api-catalog-ui/frontend/src/components/Dashboard/Dashboard.css
  api-catalog-ui/frontend/src/components/Dashboard/_dashboard.scss
  api-catalog-ui/frontend/src/components/FeedbackButton/FeedbackButton.jsx
  api-catalog-ui/frontend/src/components/FeedbackForm/FeedbackForm.jsx
  api-catalog-ui/frontend/src/feedbackServices/feedback.service.jsx
  api-catalog-ui/frontend/src/feedbackServices/index.jsx
  api-catalog-ui/frontend/src/feedbackServices/user.service.test.jsx
  api-catalog-ui/frontend/src/services copy/index.jsx
Labels: size/L

#3075 chore: Update Tomcat to version 9.0.80 in V1
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/post/CustomSendErrorFilter.java
  gradle/versions.gradle
Labels: size/XS

#3099 chore: publish CGW images
  .github/workflows/build-conformant-images.yml
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/config/AuthConfigurationProperties.java
Labels: size/XS, Sensitive

#3100 chore: CGW dockerfile
  containers/cloud-gateway-service/Dockerfile
  containers/cloud-gateway-service/prepare.sh
Labels: size/M

#3101 chore: update dependencies in v1
  gradle/versions.gradle
Labels: size/XS

#3082 chore: Address UX comments and improve responsiveness
  api-catalog-ui/frontend/package-lock.json
  api-catalog-ui/frontend/package.json
  api-catalog-ui/frontend/src/assets/images/ExternalLink.svg
  api-catalog-ui/frontend/src/assets/images/hamburger.svg
  api-catalog-ui/frontend/src/assets/images/square-envelope.svg
  api-catalog-ui/frontend/src/assets/images/xmark.svg
  api-catalog-ui/frontend/src/assets/images/zowe.png
  api-catalog-ui/frontend/src/assets/scss/_components.scss
  api-catalog-ui/frontend/src/assets/scss/_media.scss
  api-catalog-ui/frontend/src/assets/scss/_mixin.scss
  api-catalog-ui/frontend/src/assets/scss/_theme_default.scss
  api-catalog-ui/frontend/src/assets/scss/_utility.scss
  api-catalog-ui/frontend/src/components/App/App.jsx
  api-catalog-ui/frontend/src/components/App/App.test.js
  api-catalog-ui/frontend/src/components/App/App.test.jsx
  api-catalog-ui/frontend/src/components/App/_app.scss
  api-catalog-ui/frontend/src/components/Dashboard/Dashboard.css
  api-catalog-ui/frontend/src/components/Dashboard/Dashboard.jsx
  api-catalog-ui/frontend/src/components/Dashboard/Dashboard.test.jsx
  api-catalog-ui/frontend/src/components/Dashboard/_dashboard.scss
  api-catalog-ui/frontend/src/components/DetailPage/DetailPage.jsx
  api-catalog-ui/frontend/src/components/DetailPage/DetailPage.test.jsx
  api-catalog-ui/frontend/src/components/DetailPage/_detailPage.scss
  api-catalog-ui/frontend/src/components/DetailPage/_models.scss
  api-catalog-ui/frontend/src/components/FeedbackButton/FeedbackButton.jsx
  api-catalog-ui/frontend/src/components/Footer/_footer.scss
  api-catalog-ui/frontend/src/components/Header/_header.scss
  api-catalog-ui/frontend/src/components/Login/_login.scss
  api-catalog-ui/frontend/src/components/ServiceTab/ServiceTab.jsx
  api-catalog-ui/frontend/src/components/ServicesNavigationBar/ServiceNavigationBar.test.jsx
  api-catalog-ui/frontend/src/components/ServicesNavigationBar/ServicesNavigationBar.jsx
  api-catalog-ui/frontend/src/components/ServicesNavigationBar/_serviceNavigationBar.scss
  api-catalog-ui/frontend/src/components/Swagger/SwaggerUI.jsx
  api-catalog-ui/frontend/src/components/Swagger/SwaggerUI.test.jsx
  api-catalog-ui/frontend/src/components/Swagger/_swagger.scss
  api-catalog-ui/frontend/src/components/Tile/Tile.jsx
  api-catalog-ui/frontend/src/components/Tile/Tile.test.jsx
  api-catalog-ui/frontend/src/components/Tile/_tile.scss
  api-catalog-ui/frontend/src/index.scss
  api-catalog-ui/frontend/src/utils/utilFunctions.js
  api-catalog-ui/frontend/src/utils/utilFunctions.test.js
Labels: size/XXL

#3116 chore: Support go back button for portal
  api-catalog-ui/frontend/src/components/Dashboard/Dashboard.jsx
  api-catalog-ui/frontend/src/components/Dashboard/Dashboard.test.jsx
  api-catalog-ui/frontend/src/components/DetailPage/DetailPage.jsx
  api-catalog-ui/frontend/src/components/DetailPage/DetailPage.test.jsx
  api-catalog-ui/frontend/src/components/Header/_header.scss
Labels: size/M
