Repository zowe/api-layer, pull requests merged in 2023-11, with the labels that each got.

#3176 chore: Set minimal version of org.w2.asm:asm component
  gradle/versions.gradle
Labels: size/XS

#3181 feat: Cloud Gateway - create additional registrations
  .github/workflows/integration-tests.yml
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/config/AdditionalEurekaClientsHolder.java
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/config/ConnectionsConfig.java
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/config/EurekaFactory.java
  cloud-gateway-service/src/main/resources/application.yml
  cloud-gateway-service/src/main/resources/banner.txt
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/config/AdditionalRegistrationTest.java
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/config/ConnectionsConfigTest.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/DiscoveryClientConfig.java
  gradle/versions.gradle
  integration-tests/build.gradle
  integration-tests/src/test/java/org/zowe/apiml/functional/cloudgateway/CentralRegistryTest.java
Labels: size/L

#3184 fix: change ehCache storage location
  gateway-package/src/main/resources/bin/start.sh
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/CacheConfig.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/NoOpCacheConfig.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/config/CacheConfigTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/config/NoOpCacheConfigTest.java
Labels: size/L

#3197 fix: update bean definitions for noop cache mode
  common-service-core/src/main/java/org/zowe/apiml/util/CacheUtils.java
  common-service-core/src/test/java/org/zowe/apiml/util/CacheUtilsTest.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/NoOpCacheConfig.java
Labels: size/M

#3201 Fixes for azure jwks reader
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/token/JwkKeys.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/token/OIDCConfig.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/token/OIDCTokenProvider.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/token/OIDCConfigTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/token/OIDCTokenProviderTest.java
  gateway-service/src/test/resources/test_samples/azure_jwks.json
  gateway-service/src/test/resources/test_samples/okta_jwks.json
Labels: size/L, Sensitive

#3212 fix: read public key from keyring
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/config/ConnectionsConfig.java
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/service/CertificateChainService.java
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/service/CertificateChainServiceTest.java
Labels: size/M

#3186 fix: AT-TLS support
  .gitignore
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/security/SecurityConfiguration.java
  apiml-tomcat-common/src/main/java/org/zowe/apiml/product/web/ApimlTomcatCustomizer.java
  apiml-tomcat-common/src/test/java/org/zowe/apiml/product/web/ApimlTomcatCustomizerTest.java
  caching-service/build.gradle
  caching-service/src/main/java/org/zowe/apiml/caching/config/SpringSecurityConfig.java
  common-service-core/src/test/java/org/zowe/apiml/util/CacheUtilsTest.java
  config/zowe-api-dev/alternative_start.sh
  config/zowe-api-dev/run-wrapper.sh
  config/zowe-api-dev/template-stc.jcl
  discovery-package/src/main/resources/zosmf-static-definition.yaml.template
  discovery-service/src/main/java/org/zowe/apiml/discovery/config/HttpsWebSecurityConfig.java
  docs/ad-hoc-mainframe-deployment.md
  gateway-service/build.gradle
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/GatewayConfig.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/TomcatConfiguration.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/routing/NewApimlRouteLocator.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/config/NewSecurityConfiguration.java
  gateway-service/src/main/resources/application.yml
  gateway-service/src/test/java/org/zowe/apiml/gateway/routing/ApimlRouteLocatorTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/routing/NewApimlRouteLocatorTest.java
  zowe-api.json
Labels: size/XL, Sensitive

#3210 chore: FIx NPM audit vulnerabilities in the API Catalog
  api-catalog-ui/frontend/cypress.config.js
  api-catalog-ui/frontend/cypress.json
  api-catalog-ui/frontend/cypress/e2e/dashboard/dashboard.cy.js
  api-catalog-ui/frontend/cypress/e2e/dashboard/wizard-dialog.cy.js
  api-catalog-ui/frontend/cypress/e2e/detail-page/detail-page.cy.js
  api-catalog-ui/frontend/cypress/e2e/detail-page/service-version-compare.cy.js
  api-catalog-ui/frontend/cypress/e2e/detail-page/service-version-switch.cy.js
  api-catalog-ui/frontend/cypress/e2e/detail-page/swagger-try-out-and-code-snippets.cy.js
  api-catalog-ui/frontend/cypress/e2e/login/login-bad.cy.js
  api-catalog-ui/frontend/cypress/e2e/login/login-ok.cy.js
  api-catalog-ui/frontend/cypress/support/e2e.js
  api-catalog-ui/frontend/package-lock.json
  api-catalog-ui/frontend/package.json
  api-catalog-ui/frontend/src/components/App/AppContainer.test.jsx
  api-catalog-ui/frontend/src/components/Dashboard/Dashboard.test.jsx
  api-catalog-ui/frontend/src/components/Dashboard/DashboardContainer.test.jsx
  api-catalog-ui/frontend/src/components/DetailPage/DetailPageContainer.test.jsx
  api-catalog-ui/frontend/src/components/Error/ErrorContainer.test.jsx
  api-catalog-ui/frontend/src/components/Error/ErrorDialog.test.jsx
  api-catalog-ui/frontend/src/components/Header/Header.test.jsx
  api-catalog-ui/frontend/src/components/Header/HeaderContainer.test.jsx
  api-catalog-ui/frontend/src/components/Login/Login.test.jsx
  api-catalog-ui/frontend/src/components/Login/LoginContainer.test.jsx
  api-catalog-ui/frontend/src/components/Search/SearchCriteriaContainer.test.jsx
  api-catalog-ui/frontend/src/components/ServiceTab/ServiceTabContainer.test.jsx
  api-catalog-ui/frontend/src/components/ServiceVersionDiff/ServiceVersionDiffContainer.test.jsx
  api-catalog-ui/frontend/src/components/ServicesNavigationBar/ServiceNavigationBarContainer.test.jsx
  api-catalog-ui/frontend/src/components/Swagger/SwaggerContainer.test.jsx
  api-catalog-ui/frontend/src/components/Wizard/ConfirmDialogContainer.test.jsx
  api-catalog-ui/frontend/src/components/Wizard/DialogDropdown.test.jsx
  api-catalog-ui/frontend/src/components/Wizard/WizardComponents/WizardInputs.test.jsx
  api-catalog-ui/frontend/src/components/Wizard/WizardComponents/WizardInputsContainer.test.jsx
  api-catalog-ui/frontend/src/components/Wizard/WizardComponents/WizardNavigation.test.jsx
  api-catalog-ui/frontend/src/components/Wizard/WizardComponents/WizardNavigationContainer.test.jsx
  api-catalog-ui/frontend/src/components/Wizard/WizardContainer.test.jsx
  api-catalog-ui/frontend/src/components/Wizard/WizardDialog.test.jsx
  api-catalog-ui/frontend/src/components/Wizard/YAML/YAMLVisualizerContainer.test.jsx
Labels: size/L

#3203 fix: Fix signing outgoing call from Cloud Gateway just if necessary
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/config/ConnectionsConfig.java
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/config/NettyRoutingFilterApiml.java
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/config/RoutingConfig.java
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/filters/AbstractAuthSchemeFactory.java
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/filters/ClientCertFilterFactory.java
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/filters/PassticketFilterFactory.java
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/filters/X509FilterFactory.java
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/filters/ZosmfFilterFactory.java
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/service/GatewayIndexService.java
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/service/RouteLocator.java
  cloud-gateway-service/src/main/resources/application.yml
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/acceptance/ZosmfSchemeTest.java
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/config/NettyRoutingFilterApimlTest.java
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/filters/ClientCertFilterFactoryTest.java
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/filters/X509FilterFactoryTest.java
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/service/GatewayIndexServiceTest.java
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/service/RouteLocatorTest.java
  common-service-core/src/main/java/org/zowe/apiml/constants/ApimlConstants.java
  common-service-core/src/main/java/org/zowe/apiml/constants/EurekaMetadataDefinition.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/GatewayConfig.java
  gateway-service/src/main/resources/application.yml
  integration-tests/src/test/java/org/zowe/apiml/functional/gateway/CloudGatewayRoutingTest.java
Labels: size/XL

#3213 chore: Fix NPM audit vulnerabilities in the ID Federation plugin
  zowe-cli-id-federation-plugin/npm-shrinkwrap.json
  zowe-cli-id-federation-plugin/package.json
Labels: size/S

#3211 chore: Fix NPM audit vulnerabilities in the Metrics service
  .github/workflows/integration-tests.yml
  api-catalog-ui/frontend/cypress/e2e/detail-page/service-version-compare.cy.js
  metrics-service-ui/frontend/cypress.config.js
  metrics-service-ui/frontend/cypress.json
  metrics-service-ui/frontend/cypress/e2e/login/login.cy.js
  metrics-service-ui/frontend/cypress/support/e2e.js
  metrics-service-ui/frontend/package-lock.json
  metrics-service-ui/frontend/package.json
  metrics-service-ui/frontend/src/components/App/AppContainer.test.jsx
  metrics-service-ui/frontend/src/components/AuthRoute/AuthRouteContainer.test.jsx
  metrics-service-ui/frontend/src/components/Dashboard/DashboardContainer.test.jsx
  metrics-service-ui/frontend/src/components/Header/HeaderContainer.test.jsx
  metrics-service-ui/frontend/src/components/Login/Login.test.jsx
  metrics-service-ui/frontend/src/components/Login/LoginContainer.test.jsx
  metrics-service-ui/frontend/src/services/user-service.test.jsx
Labels: size/L

#3219 fix: At-tls for outgoing calls and allow At-tls in discoverable client
  api-catalog-package/src/main/resources/bin/start.sh
  caching-service-package/src/main/resources/bin/start.sh
  cloud-gateway-package/src/main/resources/bin/start.sh
  config/zowe-api-dev/template-stc.jcl
  discoverable-client/build.gradle
  discoverable-client/src/main/java/org/zowe/apiml/client/configuration/SecurityConfiguration.java
  discovery-package/src/main/resources/bin/start.sh
  gateway-package/src/main/resources/bin/start.sh
  metrics-service-package/src/main/resources/bin/start.sh
Labels: size/M

#3216 chore: Update Java dependencies
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/auth/saf/SafMethodSecurityExpressionRoot.java
  build.gradle
  docs/ide-setup.md
  gradle.properties
  gradle/versions.gradle
  gradle/wrapper/gradle-wrapper.properties
  integration-tests/build.gradle
  onboarding-enabler-micronaut/build.gradle
Labels: size/L, Sensitive

#3217 refactor: passTicket integration tests
  integration-tests/src/test/java/org/zowe/apiml/integration/zaas/PassTicketTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/zaas/ZaasNegativeTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/zaas/ZosmfTokensTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/zaas/ZoweTokensTest.java
Labels: size/L
