Repository zowe/api-layer, pull requests merged in 2023-10, with the labels that each got.

#3118 chore: Fix configuration of EhCache 3
  gateway-service/src/main/resources/ehcache.xml
Labels: size/XS

#3117 fix: Fix using GitHub actions form v1.x.x for v1
  .github/workflows/image-publish-branch.yml
  .github/workflows/image-snapshot-release.yml
  .github/workflows/image-specific-release.yml
Labels: size/XS

#3120 chore: Set log level for EhCache (V1)
  api-catalog-services/src/main/resources/application.yml
  api-catalog-services/src/test/resources/application.yml
  caching-service/src/main/resources/application.yml
  discovery-service/src/main/resources/application.yml
  gateway-service/src/main/resources/application.yml
  gateway-service/src/test/resources/application-test.yml
  gateway-service/src/test/resources/application.yml
  metrics-service/src/main/resources/application.yml
Labels: size/S

#3102 chore: Update EhCache V2
  api-catalog-services/src/main/resources/application.yml
  api-catalog-services/src/test/resources/application.yml
  caching-service/src/main/resources/application.yml
  common-service-core/src/main/java/org/zowe/apiml/util/CacheUtils.java
  common-service-core/src/test/java/org/zowe/apiml/util/CacheUtilsTest.java
  config/local-multi/gateway-service-1.yml
  config/local-multi/gateway-service-2.yml
  config/local/gateway-service.yml
  discovery-service/src/main/resources/application.yml
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/CacheConfig.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/ServiceAuthenticationServiceImpl.java
  gateway-service/src/main/resources/application.yml
  gateway-service/src/main/resources/ehcache.xml
  gateway-service/src/test/java/org/zowe/apiml/config/service/security/MockedSecurityContext.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/ServiceAuthenticationServiceImplTest.java
  gateway-service/src/test/resources/application-test.yml
  gateway-service/src/test/resources/application.yml
  gradle/versions.gradle
  metrics-service/src/main/resources/application.yml
Labels: size/L, Sensitive

#3108 chore: changelog for zowe 1.28.5
  CHANGELOG.md
Labels: size/M

#3130 chore: Upgrade dependencies V2
  api-catalog-ui/frontend/package-lock.json
  api-catalog-ui/frontend/package.json
  build.gradle
  caching-service/build.gradle
  gradle/versions.gradle
  metrics-service-ui/frontend/package-lock.json
  metrics-service-ui/frontend/package.json
  onboarding-enabler-nodejs-sample-app/package-lock.json
  onboarding-enabler-nodejs-sample-app/package.json
Labels: size/M

#3128 chore: Upgrade dependencies V1
  api-catalog-ui/frontend/package-lock.json
  api-catalog-ui/frontend/package.json
  build.gradle
  caching-service/build.gradle
  gateway-service/build.gradle
  gradle/versions.gradle
  metrics-service-ui/frontend/package-lock.json
  metrics-service-ui/frontend/package.json
  onboarding-enabler-nodejs-sample-app/package-lock.json
  onboarding-enabler-nodejs-sample-app/package.json
Labels: size/M

#3134 Homepage UI
  api-catalog-ui/frontend/src/assets/images/broadcom_logo.svg
  api-catalog-ui/frontend/src/assets/images/code.svg
  api-catalog-ui/frontend/src/assets/images/enterprise.svg
  api-catalog-ui/frontend/src/assets/images/homepage_header.svg
  api-catalog-ui/frontend/src/assets/images/mainframe.svg
  api-catalog-ui/frontend/src/assets/images/payment.svg
  api-catalog-ui/frontend/src/assets/images/security.svg
  api-catalog-ui/frontend/src/assets/images/storage.svg
  api-catalog-ui/frontend/src/assets/images/zowe_logo.svg
  api-catalog-ui/frontend/src/assets/scss/_media.scss
  api-catalog-ui/frontend/src/assets/scss/_theme_default.scss
  api-catalog-ui/frontend/src/components/App/_app.scss
  api-catalog-ui/frontend/src/components/Dashboard/Dashboard.jsx
  api-catalog-ui/frontend/src/components/Dashboard/Homepage.jsx
  api-catalog-ui/frontend/src/components/Dashboard/_dashboard.scss
  api-catalog-ui/frontend/src/components/DetailPage/DetailPage.jsx
  api-catalog-ui/frontend/src/components/DetailPage/_detailPage.scss
  api-catalog-ui/frontend/src/components/Swagger/_swagger.scss
  api-catalog-ui/frontend/src/components/Tile/Tile.jsx
Labels: size/XL

#3125 feat: Passticket endpoint for ZAAS component
  gateway-service/src/main/java/org/zowe/apiml/gateway/controllers/ZaasController.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/pre/ExtractAuthSourceFilter.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/config/NewSecurityConfiguration.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/HttpBasicPassTicketScheme.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/SafIdtScheme.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/X509Scheme.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/ZosmfScheme.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/ZoweJwtScheme.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/source/AuthSourceService.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/source/DefaultAuthSourceService.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/source/JwtAuthSourceService.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/source/OIDCAuthSourceService.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/source/PATAuthSourceService.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/source/TokenAuthSourceService.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/source/X509AuthSourceService.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/source/X509CNAuthSourceService.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/controllers/ZaasControllerTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/filters/pre/ExtractAuthSourceFilterTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/HttpBasicPassTicketSchemeTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/SafIdtSchemeTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/X509SchemeTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/ZosmfSchemeTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/ZoweJwtSchemeTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/source/DefaultAuthSourceServiceTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/source/JwtAuthSourceServiceTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/source/OIDCAuthSourceServiceTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/source/PATAuthSourceServiceTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/source/X509AuthSourceServiceTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/source/X509CNAuthSourceServiceTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/zaas/PassTicketTest.java
Labels: size/XL, Sensitive

#3136 chore: Adjust css and add support code for customisation
  api-catalog-ui/frontend/package-lock.json
  api-catalog-ui/frontend/package.json
  api-catalog-ui/frontend/src/actions/user-actions.jsx
  api-catalog-ui/frontend/src/actions/user-actions.test.jsx
  api-catalog-ui/frontend/src/assets/scss/_media.scss
  api-catalog-ui/frontend/src/assets/scss/_theme_default.scss
  api-catalog-ui/frontend/src/components/App/App.jsx
  api-catalog-ui/frontend/src/components/App/App.test.jsx
  api-catalog-ui/frontend/src/components/App/_app.scss
  api-catalog-ui/frontend/src/components/Dashboard/Dashboard.jsx
  api-catalog-ui/frontend/src/components/Dashboard/_dashboard.scss
  api-catalog-ui/frontend/src/components/DetailPage/DetailPage.jsx
  api-catalog-ui/frontend/src/components/DetailPage/DetailPage.test.jsx
  api-catalog-ui/frontend/src/components/DetailPage/_detailPage.scss
  api-catalog-ui/frontend/src/components/ErrorBoundary/BigShield/BigShield.jsx
  api-catalog-ui/frontend/src/components/ErrorBoundary/BigShield/BigShield.test.jsx
  api-catalog-ui/frontend/src/components/Header/_header.scss
  api-catalog-ui/frontend/src/components/PageNotFound/PageNotFound.jsx
  api-catalog-ui/frontend/src/components/PageNotFound/PageNotFound.test.jsx
  api-catalog-ui/frontend/src/components/Swagger/_swagger.scss
  api-catalog-ui/frontend/src/components/Tile/Tile.css
  api-catalog-ui/frontend/src/components/Tile/Tile.jsx
Labels: size/XL

#3139 chore: Upgrade Tomcat to 9.0.81 (V1)
  gradle/versions.gradle
Labels: size/XS

#3140 chore: Upgrade Tomcat to 9.0.81 (V2)
  gradle/versions.gradle
Labels: size/XS

#3143 chore: revert back unused code in UI
  api-catalog-ui/frontend/src/actions/user-actions.jsx
  api-catalog-ui/frontend/src/actions/user-actions.test.jsx
  api-catalog-ui/frontend/src/components/App/App.jsx
  api-catalog-ui/frontend/src/components/DetailPage/DetailPage.jsx
  api-catalog-ui/frontend/src/components/ErrorBoundary/BigShield/BigShield.jsx
  api-catalog-ui/frontend/src/components/ErrorBoundary/BigShield/BigShield.test.jsx
  api-catalog-ui/frontend/src/components/PageNotFound/PageNotFound.jsx
  api-catalog-ui/frontend/src/components/PageNotFound/PageNotFound.test.jsx
Labels: size/M

#3146 fix: test in Federation plugin
  zowe-cli-id-federation-plugin/__tests__/api/JobUtil.test.ts
Labels: size/XS

#3145 fix: Fix navigation issue in Catalog when using browser back button
  api-catalog-ui/frontend/src/components/DetailPage/DetailPage.jsx
  api-catalog-ui/frontend/src/components/ServicesNavigationBar/ServiceNavigationBar.test.jsx
  api-catalog-ui/frontend/src/components/ServicesNavigationBar/ServicesNavigationBar.jsx
Labels: size/M

#3154 Enhancements for Tiles, Header, footer, dashboard, homepage
  api-catalog-ui/frontend/src/assets/images/swagger.svg
  api-catalog-ui/frontend/src/assets/images/tutorials.svg
  api-catalog-ui/frontend/src/assets/images/videos.svg
  api-catalog-ui/frontend/src/assets/scss/_media.scss
  api-catalog-ui/frontend/src/components/App/_app.scss
  api-catalog-ui/frontend/src/components/Dashboard/_dashboard.scss
  api-catalog-ui/frontend/src/components/Footer/_footer.scss
  api-catalog-ui/frontend/src/components/Header/_header.scss
  api-catalog-ui/frontend/src/components/Tile/Tile.jsx
  api-catalog-ui/frontend/src/components/Tile/_tile.scss
Labels: size/L

#3155 chore: fixes for vscode startup
  README.md
  apiml-security-common/src/test/java/org/zowe/apiml/security/common/auth/SafMethodSecurityExpressionControllerTest.java
  apiml-utility/src/test/java/org/zowe/apiml/product/logging/ApimlLogInjectorTest.java
  docs/ide-setup.md
Labels: size/L, Sensitive

#3137 feat: OIDC - Fetch JWK from providers
  .github/workflows/integration-tests.yml
  config/docker/gateway-service.yml
  config/local/gateway-service.yml
  gateway-package/src/main/resources/bin/start.sh
  gateway-package/src/main/resources/manifest.yaml
  gateway-service/src/main/java/org/zowe/apiml/gateway/cache/ServiceCacheEvictor.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/token/ApimlAccessTokenProvider.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/token/JwkKeys.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/token/OIDCConfig.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/token/OIDCTokenProvider.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/webfinger/StaticWebFingerProvider.java
  gateway-service/src/main/resources/application.yml
  gateway-service/src/test/java/org/zowe/apiml/acceptance/config/GatewayOverrideConfig.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/token/ApimlAccessTokenProviderTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/token/OIDCTokenProviderTest.java
  gateway-service/src/test/resources/application.yml
Labels: size/XL, Sensitive

#3157 Back button
  api-catalog-ui/frontend/src/assets/images/angles-left.svg
  api-catalog-ui/frontend/src/components/App/_app.scss
  api-catalog-ui/frontend/src/components/Header/_header.scss
Labels: size/S

#3127 feat: Gateway additional registrations HA
  .github/workflows/integration-tests.yml
  cloud-gateway-service/src/main/resources/application.yml
  cloud-gateway-service/src/main/resources/logback.xml
  config/local/gateway-service.yml
  gateway-package/src/main/resources/bin/start.sh
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/AdditionalRegistration.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/AdditionalRegistrationCondition.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/AdditionalRegistrationConfig.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/DiscoveryClientConfig.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/discovery/ApimlDiscoveryClientFactory.java
  gateway-service/src/main/resources/application.yml
  gateway-service/src/test/java/org/zowe/apiml/gateway/config/AdditionalRegistrationConditionTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/config/AdditionalRegistrationConfigTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/config/DiscoveryClientBeanTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/config/DiscoveryClientConfigTest.java
  gateway-service/src/test/resources/application.yml
  integration-tests/src/test/java/org/zowe/apiml/functional/cloudgateway/CentralRegistryTest.java
  schemas/gateway-schema.json
Labels: size/XL

#3156 chore: Add Brian work for the UI
  api-catalog-ui/frontend/src/assets/images/angles-left.svg
  api-catalog-ui/frontend/src/assets/images/swagger.svg
  api-catalog-ui/frontend/src/assets/images/tutorials.svg
  api-catalog-ui/frontend/src/assets/images/videos.svg
  api-catalog-ui/frontend/src/assets/scss/_media.scss
  api-catalog-ui/frontend/src/components/App/_app.scss
  api-catalog-ui/frontend/src/components/Dashboard/_dashboard.scss
  api-catalog-ui/frontend/src/components/Footer/_footer.scss
  api-catalog-ui/frontend/src/components/Header/_header.scss
  api-catalog-ui/frontend/src/components/Tile/_tile.scss
Labels: size/L

#3159 fix: Context path from application property in mock catalog controller
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/standalone/ApiDocTransformForMock.java
Labels: size/XS

#3160 UI enhancements per Jan
  api-catalog-ui/frontend/src/assets/images/square-envelope-mobile.svg
  api-catalog-ui/frontend/src/assets/images/square-envelope.svg
  api-catalog-ui/frontend/src/assets/scss/_media.scss
  api-catalog-ui/frontend/src/components/App/_app.scss
  api-catalog-ui/frontend/src/components/Dashboard/Dashboard.jsx
  api-catalog-ui/frontend/src/components/Dashboard/_dashboard.scss
  api-catalog-ui/frontend/src/components/DetailPage/DetailPage.jsx
  api-catalog-ui/frontend/src/components/DetailPage/_detailPage.scss
  api-catalog-ui/frontend/src/components/Header/_header.scss
  api-catalog-ui/frontend/src/components/ServiceTab/ServiceTab.jsx
  api-catalog-ui/frontend/src/components/ServiceTab/_serviceTab.scss
  api-catalog-ui/frontend/src/components/ServicesNavigationBar/ServicesNavigationBar.jsx
  api-catalog-ui/frontend/src/components/ServicesNavigationBar/_serviceNavigationBar.scss
  api-catalog-ui/frontend/src/components/Swagger/SwaggerUI.jsx
  api-catalog-ui/frontend/src/components/Swagger/_swagger.scss
Labels: size/L

#3158 fix: Enhance error handling in the UI
  api-catalog-ui/frontend/src/components/Error/ErrorDialog.jsx
  api-catalog-ui/frontend/src/components/Login/Login.jsx
  api-catalog-ui/frontend/src/components/Login/Login.test.jsx
Labels: size/S

#3162 chore: Brian work
  api-catalog-ui/frontend/src/assets/images/square-envelope-mobile.svg
  api-catalog-ui/frontend/src/assets/images/square-envelope.svg
  api-catalog-ui/frontend/src/assets/scss/_media.scss
  api-catalog-ui/frontend/src/components/App/_app.scss
  api-catalog-ui/frontend/src/components/Dashboard/Dashboard.jsx
  api-catalog-ui/frontend/src/components/Dashboard/_dashboard.scss
  api-catalog-ui/frontend/src/components/DetailPage/DetailPage.jsx
  api-catalog-ui/frontend/src/components/DetailPage/_detailPage.scss
  api-catalog-ui/frontend/src/components/Footer/_footer.scss
  api-catalog-ui/frontend/src/components/Header/_header.scss
  api-catalog-ui/frontend/src/components/ServiceTab/ServiceTab.jsx
  api-catalog-ui/frontend/src/components/ServiceTab/_serviceTab.scss
  api-catalog-ui/frontend/src/components/ServicesNavigationBar/ServicesNavigationBar.jsx
  api-catalog-ui/frontend/src/components/ServicesNavigationBar/_serviceNavigationBar.scss
  api-catalog-ui/frontend/src/components/Swagger/SwaggerUI.jsx
  api-catalog-ui/frontend/src/components/Swagger/_swagger.scss
Labels: size/L

#3166 Qualifier for clock to avoid conflict in extension
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/token/OIDCConfig.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/token/OIDCTokenProvider.java
Labels: size/XS, Sensitive

#3167 fix: Reasonable defaults in the cloud-gateway-service application.yml
  .github/workflows/integration-tests.yml
  cloud-gateway-service/src/main/resources/application.yml
  gateway-service/src/main/resources/application.yml
Labels: size/XS

#3172 fix: Gateway additional registration fixes
  .github/workflows/service-registration.yml
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/DiscoveryClientConfig.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/discovery/ApimlDiscoveryClientFactory.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/config/DiscoveryClientBeanTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/config/DiscoveryClientConfigTest.java
Labels: size/M

#3168 fix: style updates for Catalog UI and Caching Fix for static file distribution in API Catalog
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/config/WebConfig.java
  api-catalog-ui/frontend/src/components/DetailPage/_detailPage.scss
  api-catalog-ui/frontend/src/components/ServiceTab/ServiceTab.jsx
  api-catalog-ui/frontend/src/components/ServiceTab/ServiceTab.test.jsx
  api-catalog-ui/frontend/src/components/ServiceVersionDiff/ServiceVersionDiff.jsx
  api-catalog-ui/frontend/src/components/ServiceVersionDiff/ServiceVersionDiff.test.jsx
  api-catalog-ui/frontend/src/components/ServiceVersionDiff/ServiceVersionDiffContainer.test.jsx
  api-catalog-ui/frontend/src/components/Swagger/SwaggerUI.jsx
  api-catalog-ui/frontend/src/utils/utilFunctions.js
Labels: size/L

#3178 chore: minor UI fixes
  api-catalog-ui/frontend/src/components/ServiceTab/ServiceTab.jsx
  api-catalog-ui/frontend/src/components/ServicesNavigationBar/ServicesNavigationBar.jsx
  api-catalog-ui/frontend/src/components/Swagger/_swagger.scss
Labels: size/XS

#3171 chore: Ignore integration tests that could suspend account
  integration-tests/build.gradle
  integration-tests/src/test/java/org/zowe/apiml/integration/authentication/providers/SafLoginTest.java
Labels: size/XS

#3180 fix: JWT clock qualifier to avoid dependency conflict
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/token/OIDCConfig.java
Labels: size/XS, Sensitive

#3179 CGW: move additional registration parser to common place
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/config/ConnectionsConfig.java
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/config/ConnectionsConfigTest.java
  common-service-core/src/main/java/org/zowe/apiml/config/AdditionalRegistration.java
  common-service-core/src/main/java/org/zowe/apiml/config/AdditionalRegistrationCondition.java
  common-service-core/src/main/java/org/zowe/apiml/config/AdditionalRegistrationParser.java
  common-service-core/src/test/java/org/zowe/apiml/config/AdditionalRegistrationConditionTest.java
  common-service-core/src/test/java/org/zowe/apiml/config/AdditionalRegistrationParserTest.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/DiscoveryClientConfig.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/config/DiscoveryClientBeanTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/config/DiscoveryClientConfigTest.java
Labels: size/L
