Repository zowe/api-layer, pull requests merged in 2023-06, with the labels that each got.

#2950 chore: fix for micronaut sample plugins use
  gradle/versions.gradle
  onboarding-enabler-micronaut-sample-app/build.gradle
Labels: size/S

#2945 fix: broken link in readme
  README.md
Labels: size/XS

#2953 fix: eureka/status endpoint fix
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/config/HandlerInitializer.java
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/handler/FailedAuthenticationHandler.java
  discovery-service/src/main/resources/application.yml
Labels: size/S, Sensitive

#2956 Include Brian changes for the templating
  .github/workflows/containers.yml
  api-catalog-ui/frontend/package-lock.json
  api-catalog-ui/frontend/package.json
  api-catalog-ui/frontend/src/assets/css/APIMReactToastify.css
  api-catalog-ui/frontend/src/assets/scss/_components.scss
  api-catalog-ui/frontend/src/assets/scss/_media.scss
  api-catalog-ui/frontend/src/assets/scss/_theme_default.scss
  api-catalog-ui/frontend/src/assets/scss/_toastify.scss
  api-catalog-ui/frontend/src/components/App/App.jsx
  api-catalog-ui/frontend/src/components/App/_app.scss
  api-catalog-ui/frontend/src/components/Dashboard/Dashboard.jsx
  api-catalog-ui/frontend/src/components/Dashboard/_dashboard.scss
  api-catalog-ui/frontend/src/components/DetailPage/DetailPage.jsx
  api-catalog-ui/frontend/src/components/DetailPage/_detailPage.scss
  api-catalog-ui/frontend/src/components/DetailPage/_models.scss
  api-catalog-ui/frontend/src/components/DetailPage/_tabs.scss
  api-catalog-ui/frontend/src/components/ErrorBoundary/BigShield/BigShield.jsx
  api-catalog-ui/frontend/src/components/Footer/Footer.jsx
  api-catalog-ui/frontend/src/components/Footer/_footer.scss
  api-catalog-ui/frontend/src/components/Header/Header.jsx
  api-catalog-ui/frontend/src/components/Header/_header.scss
  api-catalog-ui/frontend/src/components/PageNotFound/PageNotFound.jsx
  api-catalog-ui/frontend/src/components/Search/SearchCriteria.jsx
  api-catalog-ui/frontend/src/components/Search/_search.scss
  api-catalog-ui/frontend/src/components/ServiceTab/ServiceTab.jsx
  api-catalog-ui/frontend/src/components/Spinner/Spinner.jsx
  api-catalog-ui/frontend/src/components/Spinner/_spinner.scss
  api-catalog-ui/frontend/src/components/Swagger/SwaggerUI.jsx
  api-catalog-ui/frontend/src/components/Swagger/_swagger.scss
  api-catalog-ui/frontend/src/components/Tile/Tile.jsx
  api-catalog-ui/frontend/src/components/Tile/_tile.scss
  api-catalog-ui/frontend/src/index.js
  api-catalog-ui/frontend/src/index.scss
  api-catalog-ui/frontend/yarn.lock
Labels: size/XXL

#2960 Set the host for the micronaut sample tests
  onboarding-enabler-micronaut-sample-app/src/test/resources/application.yml
Labels: size/XS
