Repository zowe/api-layer, pull requests merged in 2024-07, with the labels that each got.

#3622 chore: Upgrade dependencies (v1)
  api-catalog-ui/frontend/package-lock.json
  api-catalog-ui/frontend/package.json
  gradle/versions.gradle
  integration-tests/build.gradle
  metrics-service-ui/frontend/package-lock.json
  metrics-service-ui/frontend/package.json
Labels: size/M

#3626 chore: Fix link in Contributing
  CONTRIBUTING.md
Labels: size/XS

#3624 feat: add outofmemory flag
  api-catalog-package/src/main/resources/bin/start.sh
  caching-service-package/src/main/resources/bin/start.sh
  cloud-gateway-package/src/main/resources/bin/start.sh
  discovery-package/src/main/resources/bin/start.sh
  gateway-package/src/main/resources/bin/start.sh
  metrics-service-package/src/main/resources/bin/start.sh
Labels: size/XS

#3625 fix: optionaly protect health endpoint
  .github/workflows/integration-tests.yml
  apiml-common/src/main/java/org/zowe/apiml/product/compatibility/ApimlDiscoveryCompositeHealthContributor.java
  apiml-common/src/main/java/org/zowe/apiml/product/compatibility/ApimlHealthCheckHandler.java
  apiml-common/src/test/java/org/zowe/apiml/product/compatibility/ApimlDiscoveryCompositeHealthContributorTest.java
  apiml-common/src/test/java/org/zowe/apiml/product/compatibility/ApimlHealthCheckHandlerTest.java
  gateway-package/src/main/resources/bin/start.sh
  gateway-service/src/main/java/org/zowe/apiml/gateway/health/GatewayHealthIndicator.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/config/NewSecurityConfiguration.java
  gateway-service/src/main/resources/application.yml
  integration-tests/build.gradle
  integration-tests/src/test/java/org/zowe/apiml/functional/gateway/GatewayAuthenticationTest.java
  package.json
  schemas/gateway-schema.json
Labels: Sensitive, size/XL

#3628 chore: Upgrade of dependencies (v2)
  api-catalog-ui/frontend/package.json
  cloud-gateway-service/build.gradle
  gradle/versions.gradle
  metrics-service-ui/frontend/package-lock.json
  metrics-service-ui/frontend/package.json
  zowe-cli-id-federation-plugin/npm-shrinkwrap.json
  zowe-cli-id-federation-plugin/package.json
Labels: size/M

#3629 fix: Add requestConnectionTimeout as a zowe.yaml property
  gateway-package/src/main/resources/bin/start.sh
Labels: size/XS

#3633 chore: cherry pick from v2
  api-catalog-package/src/main/resources/bin/start.sh
  api-catalog-ui/frontend/cypress/e2e/detail-page/swagger-try-out-and-code-snippets.cy.js
  caching-service-package/src/main/resources/bin/start.sh
  cloud-gateway-package/src/main/resources/bin/start.sh
  discovery-package/src/main/resources/bin/start.sh
  gateway-package/src/main/resources/bin/start.sh
  integration-tests/src/test/java/org/zowe/apiml/integration/authentication/pat/AccessTokenServiceTest.java
Labels: size/L

#3635 fix: update attls icsf condition
  api-catalog-package/src/main/resources/bin/start.sh
  caching-service-package/src/main/resources/bin/start.sh
  cloud-gateway-package/src/main/resources/bin/start.sh
  discovery-package/src/main/resources/bin/start.sh
  gateway-package/src/main/resources/bin/start.sh
  metrics-service-package/src/main/resources/bin/start.sh
Labels: size/S

#3600 chore: update v1 changelog
  CHANGELOG.md
Labels: size/XS

#3620 chore: add missing configuration in the start script
  .github/workflows/integration-tests.yml
  .run/CachingService.run.xml
  apiml-common/src/main/java/org/zowe/apiml/product/web/HttpConfig.java
  common-service-core/src/main/java/org/zowe/apiml/message/api/ApiMessage.java
  common-service-core/src/main/java/org/zowe/apiml/message/api/ApiMessageView.java
  gateway-package/src/main/resources/bin/start.sh
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/ConnectionsConfig.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/NettyRoutingFilterApiml.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/RoutingConfig.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/ForbidEncodedSlashesFilterFactory.java
  gateway-service/src/main/resources/application.yml
  gateway-service/src/test/java/org/zowe/apiml/gateway/filters/ForbidEncodedSlashesFilterFactoryTest.java
  gateway-service/src/test/resources/application.yml
  integration-tests/src/test/java/org/zowe/apiml/integration/authentication/oauth2/OktaOauth2Test.java
  integration-tests/src/test/java/org/zowe/apiml/integration/proxy/GatewayProxyTest.java
  integration-tests/src/test/resources/environment-configuration-attls.yml
  integration-tests/src/test/resources/environment-configuration.yml
  zaas-package/src/main/resources/bin/start.sh
  zaas-service/src/main/java/org/zowe/apiml/zaas/controllers/AuthController.java
  zaas-service/src/main/resources/application.yml
  zaas-service/src/test/resources/application-test.yml
Labels: size/L

#3623 chore: [Gateway migration] Renaming ZAAS controller path
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/ConnectionsConfig.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/MessageServiceConfiguration.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/WebSecurity.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/conformance/VerificationOnboardService.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/AbstractAuthSchemeFactory.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/PassticketFilterFactory.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/SafIdtFilterFactory.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/ZosmfFilterFactory.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/ZoweFilterFactory.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/security/BasicAuthFilter.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/acceptance/PassticketTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/acceptance/SafIdtSchemeTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/acceptance/ZosmfSchemeTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/acceptance/ZoweSchemeTest.java
  gateway-service/src/test/resources/api-doc.json
  integration-tests/src/test/java/org/zowe/apiml/functional/gateway/ValidateAPITest.java
  integration-tests/src/test/java/org/zowe/apiml/startup/impl/ApiMediationLayerStartupChecker.java
  integration-tests/src/test/java/org/zowe/apiml/util/requests/Endpoints.java
  package.json
  zaas-service/src/main/java/org/zowe/apiml/zaas/security/config/NewSecurityConfiguration.java
  zaas-service/src/main/java/org/zowe/apiml/zaas/zaas/ZaasController.java
  zaas-service/src/test/java/org/zowe/apiml/acceptance/ZaasTest.java
  zaas-service/src/test/java/org/zowe/apiml/zaas/zaas/ZaasControllerTest.java
Labels: size/L

#3634 chore: Upgrade of dependencies (v3 - GW migration)
  api-catalog-ui/frontend/package-lock.json
  api-catalog-ui/frontend/package.json
  caching-service/build.gradle
  gradle/versions.gradle
  integration-tests/src/test/java/org/zowe/apiml/integration/ha/WebSocketChaoticTest.java
  onboarding-enabler-java/build.gradle
  zaas-service/src/main/java/org/zowe/apiml/zaas/controllers/AuthController.java
  zowe-cli-id-federation-plugin/npm-shrinkwrap.json
  zowe-cli-id-federation-plugin/package.json
Labels: size/M

#3639 chore: fix unit tests
  gateway-service/src/main/java/org/zowe/apiml/gateway/conformance/VerificationOnboardService.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/conformance/VerificationOnboardServiceTest.java
Labels: size/S

#3640 fix: re-enable integration tests
  gateway-service/src/main/java/org/zowe/apiml/gateway/controllers/VersionController.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/HeaderSanitizerFilterFactory.java
  gateway-service/src/main/resources/application.yml
  integration-tests/src/test/java/org/zowe/apiml/functional/gateway/VersionTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/authentication/schemes/X509SchemeTest.java
Labels: size/M

#3642 chore: update security filters for actuator and conformance endpoint
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/AuthEndpointConfig.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/WebSecurity.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/conformance/VerificationOnboardService.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/conformance/VerificationOnboardServiceTest.java
  zaas-service/src/main/java/org/zowe/apiml/zaas/zaas/SchemeController.java
  zaas-service/src/test/java/org/zowe/apiml/zaas/zaas/SchemeControllerTest.java
Labels: size/M

#3638 fix: return correct error message when WS auth fails
  api-catalog-ui/frontend/package.json
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/ApimlServerEndpointConfig.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/WebSocketConfig.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/websocket/ApimlRequestUpgradeStrategy.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/websocket/ApimlWebSocketClient.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/websocket/ApimlWebSocketSession.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/websocket/ApimlRequestUpgradeStrategyTest.java
  integration-tests/src/test/java/org/zowe/apiml/functional/gateway/VersionTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/authentication/schemes/X509SchemeTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/proxy/WebSocketProxyTest.java
Labels: size/L

#3647 fix: missing referer header in the UI requests
  api-catalog-ui/frontend/package-lock.json
  api-catalog-ui/frontend/package.json
  api-catalog-ui/frontend/public/index.html
Labels: size/XS

#3651 feat: add loading of extensions in gateway service
  gateway-package/src/main/resources/bin/start.sh
Labels: size/XS

#3650 fix: parameters in zaas start.sh
  .github/workflows/integration-tests.yml
  api-catalog-ui/frontend/cypress/e2e/detail-page/detail-page.cy.js
  api-catalog-ui/frontend/public/index.html
  common-service-core/src/main/java/org/zowe/apiml/product/routing/RoutedServices.java
  gateway-package/src/main/resources/bin/start.sh
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/ConnectionsConfig.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/NettyRoutingFilterApiml.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/RoutingConfig.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/controllers/GatewayHomepageController.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/service/routing/ByBasePath.java
  gateway-service/src/main/resources/application.yml
  gateway-service/src/test/java/org/zowe/apiml/gateway/config/NettyRoutingFilterApimlTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/controllers/GatewayHomepageControllerTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/service/routing/ByBasePathTest.java
  schemas/zaas-schema.json
  zaas-package/src/main/resources/bin/start.sh
Labels: size/L

#3649 chore: add comment, temporary disable flaky test
  integration-tests/src/test/java/org/zowe/apiml/functional/gateway/ServiceHaModeTest.java
  integration-tests/src/test/java/org/zowe/apiml/util/service/VirtualService.java
Labels: size/XS

#3648 chore: review GW messages
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/error/ErrorType.java
  apiml-security-common/src/main/resources/security-common-log-messages.yml
  gateway-service/src/main/resources/gateway-log-messages.yml
  gateway-service/src/test/resources/gateway-log-messages.yml
  zaas-service/src/main/resources/zaas-log-messages.yml
  zaas-service/src/test/resources/zaas-messages.yml
Labels: size/XL

#3656 fix flaky authconfig tests
  gateway-service/src/main/java/org/zowe/apiml/gateway/controllers/VersionController.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/acceptance/PassticketTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/acceptance/SafIdtSchemeTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/acceptance/TokenSchemeTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/acceptance/common/AcceptanceTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/config/AuthEndpointConfigTest.java
Labels: size/M

#3658 feat: Add deterministic routing and sticky session load balancing
  .github/workflows/integration-tests.yml
  common-service-core/src/main/java/org/zowe/apiml/constants/ApimlConstants.java
  common-service-core/src/main/java/org/zowe/apiml/services/BasicInfoService.java
  gateway-service/build.gradle
  gateway-service/src/main/java/org/zowe/apiml/gateway/caching/CachingServiceClient.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/caching/CachingServiceClientException.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/caching/LoadBalancerCache.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/caching/LoadBalancerCacheException.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/RegistryConfig.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/DeterministicRoutingResponseHeaderFilterFactory.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/PageRedirectionFilterFactory.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/loadbalancer/CustomLoadBalancerConfiguration.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/loadbalancer/DeterministicLoadBalancer.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/loadbalancer/DeterministicRoutingListSupplierBuilder.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/loadbalancer/LoadBalancerConfiguration.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/services/ServicesInfoService.java
  gateway-service/src/main/resources/application.yml
  gateway-service/src/test/java/org/zowe/apiml/gateway/caching/CachingServiceClientTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/caching/LoadBalancerCacheTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/config/AuthEndpointConfigTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/filters/PageRedirectionFilterFactoryTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/loadbalancer/DeterministicLoadBalancerTest.java
  integration-tests/build.gradle
  integration-tests/src/test/java/org/zowe/apiml/functional/gateway/PageRedirectionTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/ha/DeterministicLoadBalancingTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/ha/DistributedLoadBalancingTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/ha/StickySessionLoadBalancingTest.java
  integration-tests/src/test/java/org/zowe/apiml/util/categories/DeterministicLbHaTest.java
  integration-tests/src/test/java/org/zowe/apiml/util/categories/StickySessionLbHaTest.java
  integration-tests/src/test/java/org/zowe/apiml/util/service/FullApiMediationLayer.java
  integration-tests/src/test/java/org/zowe/apiml/util/service/RunningService.java
  integration-tests/src/test/resources/environment-configuration.yml
Labels: size/XXL

#3661 chore: store results of tests if they fail in release
  .github/workflows/automated-release.yml
  .github/workflows/binary-snapshot-release.yml
  .github/workflows/binary-specific-release.yml
  .github/workflows/branch-snapshot-release.yml
Labels: size/M

#3662 chore: add zaas for docker publishing
  .github/workflows/image-publish-branch.yml
  containers/api-catalog-services/Dockerfile
  containers/caching-service/Dockerfile
  containers/discovery-service/Dockerfile
  containers/gateway-service/Dockerfile
  containers/gateway-service/prepare.sh
  containers/zaas-service/Dockerfile
  containers/zaas-service/prepare.sh
Labels: size/S

#3663 fix: update task name for zaas package
  zaas-package/build.gradle
Labels: size/S

#3664 fix: cors enabled property in gateway
  api-catalog-package/src/main/resources/bin/start.sh
  caching-service-package/src/main/resources/bin/start.sh
  discovery-package/src/main/resources/bin/start.sh
  gateway-package/src/main/resources/bin/start.sh
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/ConnectionsConfig.java
  zaas-package/src/main/resources/bin/start.sh
Labels: size/M

#3666 fix: support customized code snippets in case of endpoint with query params
  api-catalog-ui/frontend/src/utils/generateSnippets.js
  api-catalog-ui/frontend/src/utils/generateSnippets.test.js
Labels: size/M

#3636 fix: enable optional authentication requirement for application/health endpoints
  .github/workflows/integration-tests.yml
  api-catalog-package/src/main/resources/bin/start.sh
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/security/SecurityConfiguration.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/functional/ApiCatalogProtectedEndpointTest.java
  discovery-package/src/main/resources/bin/start.sh
  discovery-service/src/main/java/org/zowe/apiml/discovery/config/HttpWebSecurityConfig.java
  discovery-service/src/main/java/org/zowe/apiml/discovery/config/HttpsWebSecurityConfig.java
  discovery-service/src/test/java/org/zowe/apiml/discovery/health/ProtectedHealthEndpointTest.java
  gateway-package/src/main/resources/bin/start.sh
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/config/NewSecurityConfiguration.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/config/ProtectedHealthEndpointTest.java
  integration-tests/src/test/java/org/zowe/apiml/functional/apicatalog/ApiCatalogAuthenticationTest.java
  integration-tests/src/test/java/org/zowe/apiml/functional/discovery/DiscoveryServiceAuthenticationTest.java
  metrics-service-package/src/main/resources/bin/start.sh
Labels: Sensitive, size/L

#3668 fix: update application config file for health parameter
  api-catalog-services/src/main/resources/application.yml
  discovery-service/src/main/resources/application.yml
  gateway-service/src/main/resources/application.yml
Labels: size/XS
