Repository zowe/api-layer, pull requests merged in 2024-03, with the labels that each got.

#3338 fix: zowe logo and trademark info
  api-catalog-ui/frontend/src/assets/images/zowe-horizontal-color.png
  api-catalog-ui/frontend/src/components/Dashboard/_dashboard.scss
  api-catalog-ui/frontend/src/components/DetailPage/DetailPage.jsx
  api-catalog-ui/frontend/src/components/DetailPage/_detailPage.scss
  api-catalog-ui/frontend/src/components/Footer/_footer.scss
  api-catalog-ui/frontend/src/components/Header/_header.scss
  api-catalog-ui/frontend/src/components/ServicesNavigationBar/ServicesNavigationBar.jsx
  api-catalog-ui/frontend/src/utils/utilFunctions.js
  api-catalog-ui/frontend/src/utils/utilFunctions.test.js
Labels: size/L

#3345 fix: header position
  api-catalog-ui/frontend/src/components/DetailPage/DetailPage.jsx
  api-catalog-ui/frontend/src/components/Header/_header.scss
Labels: size/S

#3344 chore: Change log levels for WS and Identity Mapper and add service info
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/mapping/ExternalMapper.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/source/DefaultAuthSourceService.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/ws/WebSocketProxyClientHandler.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/ws/WebSocketProxyServerHandler.java
  gateway-service/src/main/resources/gateway-log-messages.yml
Labels: Sensitive, size/M

#3346 fix: change scheme of service homepage when AT-TLS is enabled and fix bug in UI
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/services/cached/CachedProductFamilyService.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/services/cached/CachedProductFamilyServiceTest.java
  api-catalog-ui/frontend/src/components/DetailPage/DetailPage.jsx
  apiml-common/src/main/java/org/zowe/apiml/product/routing/transform/TransformService.java
  apiml-common/src/test/java/org/zowe/apiml/product/routing/transform/TransformServiceTest.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/post/PageRedirectionFilter.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/services/ServicesInfoService.java
Labels: size/L

#3317 chore: add cloud gateway to package.json
  config/local/cloud-gateway-service.yml
  package.json
Labels: size/XS

#3453 fix: allow key exchange port configuration
  caching-service-package/src/main/resources/bin/start.sh
  caching-service/src/main/java/org/zowe/apiml/caching/service/infinispan/config/InfinispanConfig.java
  caching-service/src/main/resources/infinispan.xml
Labels: size/XS

#3464 chore: add add-opens options in start scripts
  api-catalog-package/src/main/resources/bin/start.sh
  caching-service-package/src/main/resources/bin/start.sh
  cloud-gateway-package/src/main/resources/bin/start.sh
  discovery-package/src/main/resources/bin/start.sh
  gateway-package/src/main/resources/bin/start.sh
  metrics-service-package/src/main/resources/bin/start.sh
Labels: size/M

#3463 chore: Metrics service removal
  .github/workflows/image-publish-branch.yml
  .github/workflows/service-registration.yml
  .gitignore
  CONTRIBUTING.md
  README.md
  build.gradle
  caching-service/src/main/java/org/zowe/apiml/caching/config/SpringSecurityConfig.java
  config/docker/api-catalog-services-standalone.yml
  config/docker/api-catalog-services.yml
  config/docker/discovery-service.yml
  config/docker/gateway-service.yml
  config/docker/metrics-service.yml
  config/local/api-catalog-services-standalone.yml
  containers/README.md
  containers/metrics-service/Dockerfile
  containers/metrics-service/prepare.sh
  docs/ide-setup.md
  docs/local-configuration.md
  gateway-service/src/main/java/org/zowe/apiml/gateway/controllers/GatewayHomepageController.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/config/NewSecurityConfiguration.java
  gateway-service/src/main/resources/application.yml
  gateway-service/src/main/resources/templates/home.html
  gateway-service/src/test/java/org/zowe/apiml/gateway/controllers/GatewayHomepageControllerTest.java
  keystore/docker/all-services.ext
  package.json
  schemas/catalog-schema.json
  schemas/metrics-schema.json
Labels: Sensitive, size/L

#3403 fix: Fix updating of SSL configuration in the Tomcat
  apiml-tomcat-common/src/main/java/org/zowe/apiml/product/web/TomcatDefaultCertificate.java
  apiml-tomcat-common/src/main/java/org/zowe/apiml/product/web/TomcatKeyringFix.java
  apiml-tomcat-common/src/test/java/org/zowe/apiml/product/web/TomcatDefaultCertificateTest.java
  apiml-tomcat-common/src/test/java/org/zowe/apiml/product/web/TomcatKeyringFixTest.java
Labels: size/L

#3462 fix: More general exception handling to detect TCP Stack restart
  apiml-tomcat-common/src/main/java/org/zowe/apiml/product/web/TomcatAcceptFixConfig.java
  apiml-tomcat-common/src/test/java/org/zowe/apiml/product/web/TomcatAcceptFixConfigTest.java
Labels: size/M

#3466 fix: More general exception handling to detect TCP Stack restart
  apiml-tomcat-common/src/main/java/org/zowe/apiml/product/web/TomcatAcceptFixConfig.java
  apiml-tomcat-common/src/test/java/org/zowe/apiml/product/web/TomcatAcceptFixConfigTest.java
Labels: size/M

#3474 fix: Respect configuration enabling JWT Token Refresh Functionality #3468
  gateway-package/src/main/resources/bin/start.sh
Labels: size/XS

#3467 chore: updates java dependencies for v3
  build.gradle
  discoverable-client/src/main/resources/static/index.html
  gradle/versions.gradle
  gradle/wrapper/gradle-wrapper.properties
  integration-tests/src/test/java/org/zowe/apiml/integration/authentication/providers/LoginTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/zaas/ZaasNegativeTest.java
  integration-tests/src/test/java/org/zowe/apiml/util/SecurityUtils.java
  integration-tests/src/test/java/org/zowe/apiml/util/SecurityUtilsTest.java
  mock-services/src/main/java/org/zowe/apiml/client/services/JwtTokenService.java
  mock-services/src/main/java/org/zowe/apiml/zss/services/SafIdtProvider.java
  zowe-api.json
Labels: size/L

#3479 chore: fix pipeline for e2e tests
  .github/workflows/integration-tests.yml
  api-catalog-ui/frontend/package-lock.json
  api-catalog-ui/frontend/package.json
Labels: size/XS

#3480 chore: snippet patch update
  api-catalog-ui/frontend/package-lock.json
  api-catalog-ui/frontend/package.json
Labels: size/XS

#3481 chore: removed jaxb dependency.
  api-catalog-services/build.gradle
  gradle/versions.gradle
Labels: size/XS

#3478 fix: remove zosmf context-path from the instance base url
  discovery-package/src/main/resources/zosmf-static-definition.yaml.template
Labels: size/XS

#3486 fix: set correct protocol using start script
  api-catalog-package/src/main/resources/bin/start.sh
  caching-service-package/src/main/resources/bin/start.sh
  cloud-gateway-package/src/main/resources/bin/start.sh
  discovery-package/src/main/resources/bin/start.sh
  gateway-package/src/main/resources/bin/start.sh
Labels: size/M

#3483 fix: update dependencies
  .github/workflows/ci-tests.yml
  api-catalog-ui/frontend/package-lock.json
  api-catalog-ui/frontend/package.json
  build.gradle
  gradle/versions.gradle
  integration-tests/src/test/java/org/zowe/apiml/util/service/FullApiMediationLayer.java
  integration-tests/src/test/java/org/zowe/apiml/util/service/RunningService.java
  metrics-service-ui/frontend/package-lock.json
  metrics-service-ui/frontend/package.json
  onboarding-enabler-java-sample-app/build.gradle
  onboarding-enabler-nodejs-sample-app/package-lock.json
  onboarding-enabler-nodejs-sample-app/package.json
  onboarding-enabler-nodejs/package.json
  security-service-client-spring/build.gradle
Labels: Sensitive, size/M
