Repository zowe/api-layer, pull requests merged in 2024-09, with the labels that each got.

#3697 chore: Basic HTTP responses in the SCGW
  .github/workflows/security-analysis.yml
  apiml-common/src/main/resources/common-log-messages.yml
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/config/AuthConfigurationProperties.java
  ehcache/.lock
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/WebSecurity.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/controllers/GatewayExceptionHandler.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/AbstractAuthSchemeFactory.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/AbstractEncodedCharactersFilterFactory.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/ForbidCharacterException.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/ForbidEncodedCharactersFilterFactory.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/ForbidEncodedSlashesFilterFactory.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/ForbidSlashException.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/service/AbstractAuthProviderFilter.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/service/ZaasServiceIsNotAvailableException.java
  gateway-service/src/main/resources/gateway-log-messages.yml
  gateway-service/src/test/java/org/zowe/apiml/gateway/acceptance/TokenSchemeTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/acceptance/common/AcceptanceTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/acceptance/common/MockService.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/config/ProtectedHealthEndpointTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/config/WebSecurityTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/controllers/GatewayExceptionHandlerTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/filters/ForbidEncodedCharactersFilterFactoryTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/filters/ForbidEncodedSlashesFilterFactoryTest.java
  integration-tests/src/test/java/org/zowe/apiml/functional/gateway/GatewayAuthenticationTest.java
  integration-tests/src/test/java/org/zowe/apiml/functional/gateway/ServiceHaModeTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/proxy/ServerSentEventsProxyTest.java
  zaas-service/ehcache/.lock
Labels: Sensitive, size/XL

#3718 Update v2 container builds to use `<major>-<distro>`
  containers/api-catalog-services/Dockerfile
  containers/caching-service/Dockerfile
  containers/cloud-gateway-service/Dockerfile
  containers/discovery-service/Dockerfile
  containers/gateway-service/Dockerfile
  containers/metrics-service/Dockerfile
Labels: size/S

#3712 chore: fix Medium and High issues in SonarCloud report for branch v3.x.x
  common-service-core/src/main/java/org/zowe/apiml/message/core/AbstractMessageService.java
  common-service-core/src/main/java/org/zowe/apiml/message/core/Message.java
  common-service-core/src/main/java/org/zowe/apiml/message/log/ApimlLogger.java
  common-service-core/src/test/java/org/zowe/apiml/message/log/ApimlLoggerTest.java
  zaas-service/src/main/java/org/zowe/apiml/zaas/security/config/ComponentsConfiguration.java
Labels: Sensitive, size/L

#3719 Update v3 container builds to use `<major>-<distro>`
  containers/api-catalog-services/Dockerfile
  containers/caching-service/Dockerfile
  containers/discovery-service/Dockerfile
  containers/gateway-service/Dockerfile
  containers/zaas-service/Dockerfile
Labels: size/S

#3723 chore: fix new SonarCloud issues in v3.x.x
  apiml-common/src/main/java/org/zowe/apiml/product/web/HttpConfig.java
  caching-service/src/main/java/org/zowe/apiml/caching/api/CachingController.java
Labels: size/S

#3716 fix: update default javax.net.ssl log levels
  api-catalog-services/src/main/resources/application.yml
  caching-service/src/main/resources/application.yml
  discoverable-client/src/main/resources/application.yml
  discovery-service/src/main/resources/application.yml
  gateway-service/src/main/resources/application.yml
  zaas-service/src/main/resources/application.yml
Labels: size/S

#3721 chore: deprecate vsam storage option
  .github/workflows/docs.yml
  caching-service-package/src/main/resources/bin/start.sh
  caching-service/src/main/java/org/zowe/apiml/caching/service/vsam/config/VsamConfiguration.java
  caching-service/src/main/resources/caching-log-messages.yml
  schemas/caching-schema.json
  scripts/docs/index.js
Labels: size/M

#3736 fix: use jfrog registry in renovate bot
  renovate-config.js
  zowe-cli-id-federation-plugin/.npmrc
Labels: size/XS

#3724 chore: GH action to check PR title (V3)
  .github/workflows/pr-checker.yml
Labels: size/M

#3738 chore: GH action to check PR title (V2)
  .github/workflows/pr-checker.yml
Labels: size/M

#3740 chore: Remove build_arg overwriting image versions in workflow
  .github/workflows/build-conformant-images.yml
Labels: size/S

#3702 fix: Remove global setup of keystores
  .github/workflows/integration-tests.yml
  .github/workflows/security-analysis.yml
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/functional/ApiCatalogFunctionalTest.java
  apiml-common/src/main/java/org/zowe/apiml/product/web/HttpConfig.java
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/config/ConnectionsConfig.java
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/acceptance/common/AcceptanceTestWithBasePath.java
  common-service-core/src/main/java/org/zowe/apiml/security/HttpsFactory.java
  common-service-core/src/test/java/org/zowe/apiml/security/HttpsFactoryTest.java
  config/local/metrics-service.yml
  discovery-service/src/main/java/org/zowe/apiml/discovery/config/EurekaConfig.java
  discovery-service/src/main/java/org/zowe/apiml/discovery/eureka/RefreshablePeerEurekaNodes.java
  discovery-service/src/test/java/org/zowe/apiml/discovery/eureka/RefreshablePeerEurekaNodesTest.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/DiscoveryClientConfig.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/sse/ServerSentEventProxyHandler.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/RefreshEndpointTest.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/common/AcceptanceTestWithBasePath.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/config/DiscoveryClientBeanTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/config/DiscoveryClientConfigTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/sse/ServerSentEventProxyHandlerTest.java
  integration-tests/build.gradle
  integration-tests/src/test/java/org/zowe/apiml/integration/external/MetricServiceTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/ha/ApiCatalogMultipleInstancesTest.java
  integration-tests/src/test/java/org/zowe/apiml/startup/impl/ApiMediationLayerStartupChecker.java
  integration-tests/src/test/java/org/zowe/apiml/util/requests/Requests.java
  metrics-service/src/main/java/org/zowe/apiml/metrics/config/SslConfig.java
  onboarding-enabler-java/src/test/java/org/zowe/apiml/eurekaservice/client/impl/ApiMediationClientImplTest.java
  zaas-client/src/test/java/org/zowe/apiml/zaasclient/service/internal/ZaasClientTest.java
Labels: Sensitive, size/L

#3717 fix: Remove "AUTO" from jwt configuration and clean up outdated APARs from mock service
  .github/workflows/integration-tests.yml
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/config/AuthConfigurationProperties.java
  integration-tests/src/test/java/org/zowe/apiml/integration/authentication/pat/PATWithAllSchemesTest.java
  mock-services/README.md
  mock-services/src/main/java/org/zowe/apiml/client/services/apars/PH12143.java
  mock-services/src/main/java/org/zowe/apiml/client/services/apars/PH34201.java
  mock-services/src/main/java/org/zowe/apiml/client/services/apars/PH34912.java
  mock-services/src/main/java/org/zowe/apiml/client/services/apars/RSU2012.java
  mock-services/src/main/java/org/zowe/apiml/client/services/versions/AvailableApars.java
  mock-services/src/main/resources/application.yml
  mock-services/src/test/java/org/zowe/apiml/client/services/apars/PH12143Test.java
  mock-services/src/test/java/org/zowe/apiml/client/services/apars/PH34201Test.java
  mock-services/src/test/java/org/zowe/apiml/client/services/apars/PH34912Test.java
  mock-services/src/test/java/org/zowe/apiml/client/services/apars/RSU2012Test.java
  mock-services/src/test/java/org/zowe/apiml/client/services/versions/AvailableAparsTest.java
  schemas/zaas-schema.json
  zaas-package/src/main/resources/bin/start.sh
  zaas-service/src/main/java/org/zowe/apiml/zaas/security/login/Providers.java
  zaas-service/src/main/java/org/zowe/apiml/zaas/security/login/zosmf/ZosmfAuthenticationProvider.java
  zaas-service/src/main/resources/application.yml
  zaas-service/src/main/resources/zaas-log-messages.yml
  zaas-service/src/test/java/org/zowe/apiml/zaas/security/login/ProvidersTest.java
  zaas-service/src/test/java/org/zowe/apiml/zaas/security/login/zosmf/ZosmfAuthenticationProviderTest.java
Labels: Sensitive, size/XXL

#3744 fix: zaas reads configuration from GW as default, possible to overrid…
  zaas-package/src/main/resources/bin/start.sh
Labels: size/M

#3742 fix: Remove global setup of keystores (v3)
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/controllers/api/ApiCatalogController.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/controllers/api/CatalogApiDocController.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/SwaggerConfiguration.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/functional/ApiCatalogFunctionalTest.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/functional/ApiCatalogProtectedEndpointTest.java
  apiml-common/src/main/java/org/zowe/apiml/product/web/DiscoveryRestTemplateConfig.java
  apiml-common/src/main/java/org/zowe/apiml/product/web/HttpConfig.java
  common-service-core/src/main/java/org/zowe/apiml/security/HttpsFactory.java
  common-service-core/src/test/java/org/zowe/apiml/security/HttpsFactoryTest.java
  common-service-core/src/test/java/org/zowe/apiml/tomcat/TomcatHttpsTest.java
  discovery-service/src/main/java/org/zowe/apiml/discovery/config/EurekaConfig.java
  discovery-service/src/main/java/org/zowe/apiml/discovery/eureka/RefreshablePeerEurekaNodes.java
  discovery-service/src/test/java/org/zowe/apiml/discovery/eureka/RefreshablePeerEurekaNodesTest.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/ConnectionsConfig.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/SwaggerConfig.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/WebSocketConfig.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/websocket/ApimlWebSocketClient.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/acceptance/common/AcceptanceTestWithBasePath.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/config/SwaggerConfigTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/websocket/ApimlWebSocketClientTest.java
  integration-tests/src/test/java/org/zowe/apiml/functional/apicatalog/ApiCatalogEndpointIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/startup/impl/ApiMediationLayerStartupChecker.java
  mock-services/src/main/resources/apidoc.json
  onboarding-enabler-java/src/test/java/org/zowe/apiml/eurekaservice/client/impl/ApiMediationClientImplTest.java
  zaas-client/src/test/java/org/zowe/apiml/zaasclient/service/internal/ZaasClientTest.java
  zaas-service/src/test/java/org/zowe/apiml/acceptance/RefreshEndpointTest.java
  zaas-service/src/test/java/org/zowe/apiml/acceptance/ZaasTest.java
Labels: Sensitive, size/L

#3746 fix: apiml prefix for registry conf
  gateway-package/src/main/resources/bin/start.sh
Labels: size/XS

#3689 chore: Update JSON schema of the Gateway
  gateway-package/src/main/resources/bin/start.sh
  gateway-service/src/main/resources/application.yml
  schemas/gateway-schema.json
Labels: size/XL

#3722 fix: ClosableHttpClient.execute() resource leak on API catalog
  api-catalog-services/build.gradle
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/instance/InstanceRetrievalService.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/services/status/APIDocRetrievalService.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/staticapi/StaticAPIService.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/instance/InstanceRetrievalServiceTest.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/services/status/LocalApiDocServiceTest.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/staticapi/StaticAPIServiceTest.java
  api-catalog-ui/frontend/.env
  apiml-common/build.gradle
  apiml-common/src/testFixtures/java/org/zowe/apiml/util/HttpClientMockHelper.java
  apiml-common/src/testFixtures/java/org/zowe/apiml/util/config/SslContext.java
  apiml-common/src/testFixtures/java/org/zowe/apiml/util/config/SslContextConfigurer.java
  apiml-security-common/build.gradle
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/verify/TrustedCertificatesProvider.java
  apiml-security-common/src/test/java/org/zowe/apiml/security/common/verify/TrustedCertificatesProviderTest.java
  caching-service/build.gradle
  discovery-service/build.gradle
  gradle/versions.gradle
  integration-tests/build.gradle
  security-service-client-spring/build.gradle
  security-service-client-spring/src/main/java/org/zowe/apiml/security/client/handler/RestResponseHandler.java
  security-service-client-spring/src/main/java/org/zowe/apiml/security/client/service/GatewaySecurityService.java
  security-service-client-spring/src/test/java/org/zowe/apiml/security/client/service/GatewaySecurityServiceTest.java
  zaas-client/build.gradle
  zaas-client/src/main/java/org/zowe/apiml/zaasclient/exception/ZaasClientErrorCodes.java
  zaas-client/src/main/java/org/zowe/apiml/zaasclient/service/ZaasClient.java
  zaas-client/src/main/java/org/zowe/apiml/zaasclient/service/internal/PassTicketServiceImpl.java
  zaas-client/src/main/java/org/zowe/apiml/zaasclient/service/internal/TokenService.java
  zaas-client/src/main/java/org/zowe/apiml/zaasclient/service/internal/ZaasClientImpl.java
  zaas-client/src/main/java/org/zowe/apiml/zaasclient/service/internal/ZaasHttpsClientProvider.java
  zaas-client/src/main/java/org/zowe/apiml/zaasclient/service/internal/ZaasJwtService.java
  zaas-client/src/main/java/org/zowe/apiml/zaasclient/util/SimpleHttpResponse.java
  zaas-client/src/test/java/org/zowe/apiml/zaasclient/service/internal/ZaasClientImplHttpsTests.java
  zaas-client/src/test/java/org/zowe/apiml/zaasclient/service/internal/ZaasHttpsClientProviderTests.java
  zaas-client/src/test/java/org/zowe/apiml/zaasclient/service/internal/ZaasJwtServiceTest.java
  zaas-service/build.gradle
  zaas-service/src/main/java/org/zowe/apiml/zaas/security/mapping/ExternalMapper.java
  zaas-service/src/test/java/org/zowe/apiml/zaas/security/mapping/ExternalMapperTest.java
  zaas-service/src/test/java/org/zowe/apiml/zaas/security/mapping/OIDCExternalMapperTest.java
Labels: bug, Sensitive, size/XXL, chore

#3751 fix: do not resolve hostname when not required
  apiml-utility/build.gradle
  cloud-gateway-package/src/main/resources/bin/start.sh
  onboarding-enabler-java/src/main/java/org/zowe/apiml/eurekaservice/client/impl/ApiMediationClientImpl.java
  onboarding-enabler-java/src/main/java/org/zowe/apiml/eurekaservice/client/util/ApiMediationServiceConfigReader.java
  onboarding-enabler-java/src/test/java/org/zowe/apiml/eurekaservice/client/util/ApiMediationServiceConfigReaderTest.java
  onboarding-enabler-java/src/test/resources/additional-service-configuration_ip-address-null_UnknownHost.yml
  onboarding-enabler-java/src/test/resources/additional-service-configuration_ip-address-null_bad-baseUrl.yml
  onboarding-enabler-java/src/test/resources/service-configuration-without-ip-address.yml
Labels: size/M

#3765 feat: Use networking standard config (improved) (V3)
  api-catalog-package/src/main/resources/bin/start.sh
  caching-service-package/src/main/resources/bin/start.sh
  discoverable-client/src/main/resources/application.yml
  discovery-package/src/main/resources/bin/start.sh
  gateway-package/src/main/resources/bin/start.sh
  zaas-package/src/main/resources/bin/start.sh
Labels: size/L

#3767 fix: Gateway end with internal server error if cookies are invalid
  common-service-core/src/main/java/org/zowe/apiml/util/CookieUtil.java
  common-service-core/src/test/java/org/zowe/apiml/util/CookieUtilTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/acceptance/common/AcceptanceTestWithMockServices.java
  integration-tests/src/test/java/org/zowe/apiml/integration/authentication/schemes/GatewayAuthTest.java
Labels: size/M

#3766 fix: coverity findings
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/standalone/ExampleService.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/standalone/StandaloneLoaderService.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/standalone/ExampleServiceTest.java
  api-catalog-ui/frontend/src/components/DetailPage/DetailPage.jsx
  api-catalog-ui/frontend/src/components/Error/ErrorFormatter.jsx
  api-catalog-ui/frontend/src/components/Login/Login.jsx
  api-catalog-ui/frontend/src/components/ServicesNavigationBar/ServicesNavigationBar.jsx
  api-catalog-ui/frontend/src/components/Wizard/WizardComponents/WizardInputs.jsx
  api-catalog-ui/frontend/src/utils/generateSnippets.js
  caching-service/src/main/java/org/zowe/apiml/caching/service/vsam/VsamFile.java
  caching-service/src/main/java/org/zowe/apiml/caching/service/vsam/VsamInitializer.java
  common-service-core/src/main/java/org/zowe/apiml/message/core/AbstractMessageService.java
  common-service-core/src/main/java/org/zowe/apiml/message/yaml/YamlMessageService.java
  common-service-core/src/main/java/org/zowe/apiml/security/SecurityUtils.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/attls/AttlsHttpHandler.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/conformance/OpenApiV2Validator.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/conformance/OpenApiV3Validator.java
  zaas-service/src/main/java/org/zowe/apiml/zaas/config/SwaggerConfig.java
  zaas-service/src/test/java/org/zowe/apiml/zaas/config/SwaggerConfigTest.java
Labels: Sensitive, size/L

#3758 chore: zaas-client support multiple set-cookie headers
  zaas-client/src/main/java/org/zowe/apiml/zaasclient/service/internal/ZaasJwtService.java
  zaas-client/src/main/java/org/zowe/apiml/zaasclient/util/SimpleHttpResponse.java
  zaas-client/src/test/java/org/zowe/apiml/zaasclient/service/internal/ZaasClientImplHttpsTests.java
Labels: size/M

#3759 chore: prevent ApimlLogger from throwing IllegalArgumentException
  common-service-core/src/main/java/org/zowe/apiml/message/core/AbstractMessageService.java
  common-service-core/src/main/java/org/zowe/apiml/message/core/Message.java
  common-service-core/src/main/java/org/zowe/apiml/message/log/ApimlLogger.java
  common-service-core/src/test/java/org/zowe/apiml/message/log/ApimlLoggerTest.java
Labels: size/M

#3768 chore: upgrade v3 dependencies
  api-catalog-services/build.gradle
  api-catalog-ui/frontend/package-lock.json
  api-catalog-ui/frontend/package.json
  build.gradle
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/WebSecurity.java
  gradle.properties
  gradle/versions.gradle
  gradle/wrapper/gradle-wrapper.properties
  onboarding-enabler-nodejs-sample-app/package-lock.json
  onboarding-enabler-nodejs-sample-app/package.json
  zowe-cli-id-federation-plugin/__tests__/__integration__/cli/map/__scripts__/map_old_profiles.sh
  zowe-cli-id-federation-plugin/__tests__/__integration__/cli/map/__snapshots__/cli.map.integration.test.ts.snap
  zowe-cli-id-federation-plugin/__tests__/__integration__/cli/map/cli.map.integration.test.ts
  zowe-cli-id-federation-plugin/npm-shrinkwrap.json
  zowe-cli-id-federation-plugin/package.json
  zss-sample-service/package-lock.json
  zss-sample-service/package.json
Labels: size/M

#3769 chore: Fix PostProcessorRegistrationDelegate warning caused by routingFilterHandler
  api-catalog-services/src/main/resources/application.yml
  discovery-service/src/main/resources/application.yml
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/ConnectionsConfig.java
  mock-services/src/main/resources/application.yml
Labels: size/M

#3770 refactor: refactor mapper.ts in zowe cli id federation.
  zowe-cli-id-federation-plugin/src/api/Mapper.ts
Labels: size/S

#3775 fix: move security configuration back to gateway section
  containers/zaas-service/Dockerfile
  gateway-package/src/main/resources/manifest.yaml
  gateway-service/src/main/resources/application.yml
  gateway-service/src/test/resources/application.yml
  schemas/zaas-schema.json
  zaas-package/src/main/resources/manifest.yaml
Labels: size/M

#3772 refactor: Refactor mapper.ts in zowe-cli-id-federation
  .github/workflows/docs.yml
  .github/workflows/integration-tests.yml
  .github/workflows/service-registration.yml
  zowe-cli-id-federation-plugin/src/api/Mapper.ts
Labels: size/M

#3776 chore: fix Warn messages
  api-catalog-services/build.gradle
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/SubstituteSwaggerGenerator.java
  api-catalog-services/src/main/resources/application.yml
  apiml-common/src/main/resources/logback.xml
  caching-service/src/main/resources/application.yml
  caching-service/src/main/resources/logback.xml
  discoverable-client/src/main/resources/logback.xml
  discovery-service/build.gradle
  discovery-service/src/main/resources/application.yml
  gateway-service/build.gradle
  gateway-service/src/main/resources/application.yml
  gateway-service/src/main/resources/logback.xml
  onboarding-enabler-micronaut-sample-app/src/main/resources/logback.xml
  zaas-service/build.gradle
  zaas-service/src/main/resources/application.yml
  zaas-service/src/main/resources/logback.xml
  zowe-cli-id-federation-plugin/__tests__/__integration__/cli/map/cli.map.integration.test.ts
Labels: size/M

#3771 chore: fix sonar issues
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/controllers/api/ApiCatalogController.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/instance/InstanceInitializeService.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/instance/InstanceRefreshServiceTest.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/instance/InstanceRetrievalServiceTest.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/util/ContainerServiceMockUtil.java
  api-catalog-ui/frontend/src/components/Error/ErrorFormatter.jsx
  apiml-extension-loader/src/main/java/org/zowe/apiml/extension/ExtensionConfigReader.java
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/filter/CategorizeCertsFilter.java
  apiml-security-common/src/test/java/org/zowe/apiml/security/common/verify/TrustedCertificatesProviderTest.java
  apiml-tomcat-common/src/test/java/org/zowe/apiml/filter/AttlsFilterTest.java
  apiml-utility/src/main/java/org/zowe/apiml/product/logging/LogMessageTracker.java
  common-service-core/src/main/java/org/zowe/apiml/config/AdditionalRegistrationCondition.java
  common-service-core/src/main/java/org/zowe/apiml/config/AdditionalRegistrationParser.java
  common-service-core/src/main/java/org/zowe/apiml/eurekaservice/client/util/EurekaMetadataParser.java
  common-service-core/src/main/java/org/zowe/apiml/message/core/AbstractMessageService.java
  common-service-core/src/main/java/org/zowe/apiml/services/BasicInfoService.java
  common-service-core/src/main/java/org/zowe/apiml/util/CacheUtils.java
  common-service-core/src/main/java/org/zowe/apiml/util/Cookies.java
  common-service-core/src/main/java/org/zowe/apiml/util/RequestUtils.java
  common-service-core/src/test/java/org/zowe/apiml/security/HttpsFactoryTest.java
  discoverable-client/src/main/java/org/zowe/apiml/client/api/PetControllerExceptionHandler.java
  discovery-service/src/main/java/org/zowe/apiml/discovery/eureka/RefreshablePeerEurekaNodes.java
  discovery-service/src/main/java/org/zowe/apiml/discovery/staticdef/ServiceDefinitionProcessor.java
  discovery-service/src/test/java/org/zowe/apiml/discovery/EurekaInstanceRegisteredListenerTest.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/WebSecurity.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/oidc/ClientConfiguration.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/scheduled/GatewayScanJob.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/service/BasicAuthProvider.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/service/CentralApimlInfoMapper.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/service/GatewayIndexService.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/service/RouteLocator.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/acceptance/netflix/ApimlDiscoveryClientStub.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/acceptance/netflix/ApplicationRegistry.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/config/WebSecurityTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/service/RouteLocatorTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/graphql/BookControllerTest.java
  integration-tests/src/test/java/org/zowe/apiml/util/config/AuxiliaryUserList.java
  integration-tests/src/test/java/org/zowe/apiml/util/service/DiscoveryUtils.java
  integration-tests/src/test/java/org/zowe/apiml/util/service/VirtualService.java
  zaas-service/src/main/java/org/zowe/apiml/zaas/security/service/token/ApimlAccessTokenProvider.java
  zaas-service/src/main/java/org/zowe/apiml/zaas/security/webfinger/StaticWebFingerProvider.java
  zaas-service/src/test/java/org/zowe/apiml/zaas/security/service/JwtSecurityTest.java
Labels: Sensitive, size/XL

#3780 chore: update new Warn messages
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/SubstituteSwaggerGenerator.java
  caching-service/src/main/resources/infinispan.xml
Labels: size/XS

#3774 fix: fix coverity issues for v3 release
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/standalone/ExampleService.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/standalone/ExampleServiceTest.java
  common-service-core/src/main/java/org/zowe/apiml/util/UrlUtils.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/conformance/OpenApiV2Validator.java
  zaas-service/src/main/java/org/zowe/apiml/zaas/security/config/CompoundAuthProvider.java
  zaas-service/src/main/java/org/zowe/apiml/zaas/security/service/token/ApimlAccessTokenProvider.java
  zaas-service/src/main/java/org/zowe/apiml/zaas/security/service/token/SecureTokenInitializationException.java
  zaas-service/src/test/java/org/zowe/apiml/zaas/security/service/token/ApimlAccessTokenProviderTest.java
  zaas-service/src/test/java/org/zowe/apiml/zaas/security/service/token/SecureTokenInitializationExceptionTest.java
Labels: Sensitive, size/L

#3781 chore: fix sonar issues
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/services/cached/CachedProductFamilyService.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/services/status/APIDocRetrievalService.java
  api-catalog-ui/frontend/src/components/GraphQL/GraphQLUIApiml.jsx
  api-catalog-ui/frontend/src/components/ServiceTab/ServiceTab.jsx
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/config/AuthConfigurationProperties.java
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/login/SuccessfulLoginHandler.java
  discovery-service/src/test/java/org/zowe/apiml/discovery/staticdef/StaticApiRestControllerTest.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/AuthEndpointConfig.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/RoutingConfig.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/SwaggerConfig.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/oidc/ClientConfiguration.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/controllers/GatewayExceptionHandler.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/config/ConnectionsConfigTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/config/NettyRoutingFilterApimlTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/controllers/CertificatesRestControllerTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/service/CertificateChainServiceTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/graphql/BookControllerTest.java
  onboarding-enabler-micronaut/src/main/java/org/zowe/apiml/config/SslTypeConverter.java
  security-service-client-spring/src/test/java/org/zowe/apiml/security/client/service/GatewaySecurityServiceTest.java
  zaas-client/src/main/java/org/zowe/apiml/zaasclient/service/ZaasClient.java
  zaas-client/src/test/java/org/zowe/apiml/zaasclient/service/internal/ZaasClientImplHttpsTests.java
  zaas-service/src/main/java/org/zowe/apiml/zaas/cache/CachingServiceClient.java
  zaas-service/src/main/java/org/zowe/apiml/zaas/error/controllers/InternalServerErrorController.java
  zaas-service/src/main/java/org/zowe/apiml/zaas/error/controllers/NotFoundErrorController.java
  zaas-service/src/main/java/org/zowe/apiml/zaas/security/mapping/ExternalMapper.java
  zaas-service/src/main/java/org/zowe/apiml/zaas/security/refresh/SuccessfulRefreshHandler.java
  zaas-service/src/test/java/org/zowe/apiml/zaas/cache/CachingServiceClientTest.java
  zaas-service/src/test/java/org/zowe/apiml/zaas/controllers/SafResourceAccessControllerTest.java
  zaas-service/src/test/java/org/zowe/apiml/zaas/security/mapping/NativeMapperTest.java
  zaas-service/src/test/java/org/zowe/apiml/zaas/security/query/SuccessfulQueryHandlerTest.java
  zaas-service/src/test/java/org/zowe/apiml/zaas/security/service/schema/source/JwtAuthSourceServiceTest.java
  zaas-service/src/test/java/org/zowe/apiml/zaas/security/service/schema/source/PATAuthSourceServiceTest.java
  zaas-service/src/test/java/org/zowe/apiml/zaas/security/service/token/ApimlAccessTokenProviderTest.java
  zaas-service/src/test/java/org/zowe/apiml/zaas/security/service/zosmf/ZosmfServiceTest.java
Labels: Sensitive, size/XL

#3782 chore: runInBand for catalog ui tests to avoid flaky
  .github/workflows/image-specific-release.yml
  api-catalog-ui/frontend/package.json
  api-catalog-ui/frontend/src/components/Swagger/SwaggerUI.test.jsx
  build.gradle
Labels: size/S

#3789 chore: fix sonar issues
  apiml-security-common/src/test/java/org/zowe/apiml/security/common/auth/SafMethodSecurityExpressionControllerTest.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/conformance/ValidateAPIController.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/conformance/VerificationOnboardService.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/conformance/ValidateAPIControllerTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/conformance/VerificationOnboardServiceTest.java
  integration-tests/src/test/java/org/zowe/apiml/functional/gateway/AuthenticationOnDeploymentTest.java
  integration-tests/src/test/java/org/zowe/apiml/functional/gateway/ServiceHaModeTest.java
  integration-tests/src/test/java/org/zowe/apiml/util/service/VirtualService.java
  zaas-service/src/main/java/org/zowe/apiml/zaas/controllers/AuthConfigValidationController.java
  zaas-service/src/test/java/org/zowe/apiml/zaas/controllers/AuthConfigValidationControllerTest.java
Labels: Sensitive, size/L

#3788 chore: change version update scheme for catalog env file
  .github/workflows/automated-release.yml
  .github/workflows/binary-specific-release.yml
Labels: size/S

#3790 fix: v3 RC1 fixes
  api-catalog-ui/frontend/src/actions/user-actions.jsx
  api-catalog-ui/frontend/src/actions/user-actions.test.jsx
  api-catalog-ui/frontend/src/components/App/App.jsx
  caching-service/src/main/resources/application.yml
  config/docker/caching-service.yml
  config/local/caching-service-2.yml
  config/local/caching-service.yml
  config/local/gateway-service.yml
  gateway-service/src/main/java/org/zowe/apiml/gateway/GatewayServiceApplication.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/MessageServiceConfiguration.java
  gateway-service/src/main/resources/application.yml
  integration-tests/src/test/java/org/zowe/apiml/integration/zaas/PassTicketTest.java
  zowe-cli-id-federation-plugin/.npmrc
Labels: size/M

#3785 chore: Update all patch dependencies (v1.x.x)
  .github/workflows/ci-tests.yml
  .github/workflows/containers.yml
  .github/workflows/docs.yml
  api-catalog-services/build.gradle
  api-catalog-ui/frontend/package-lock.json
  api-catalog-ui/frontend/package.json
  apiml-sample-extension/build.gradle
  caching-service/build.gradle
  discoverable-client/build.gradle
  discoverable-client/src/main/resources/static/index.html
  discovery-service/build.gradle
  gateway-service/build.gradle
  gradle/coverage.gradle
  gradle/versions.gradle
  gradlew
  gradlew.bat
  metrics-service-ui/frontend/package-lock.json
  metrics-service-ui/frontend/package.json
  metrics-service/build.gradle
  mock-services/build.gradle
  onboarding-enabler-java-sample-app/build.gradle
  onboarding-enabler-micronaut-sample-app/build.gradle
  onboarding-enabler-micronaut/build.gradle
  onboarding-enabler-nodejs-sample-app/package-lock.json
  onboarding-enabler-nodejs-sample-app/package.json
Labels: size/XL, dependencies

#3793 fix: use v1 octorelease action
  .github/workflows/zowe-cli-plugin.yml
Labels: size/XS

#3794 chore: configuring custom logback file for gateway and zaas services
  gateway-service/src/main/resources/application.yml
  gateway-service/src/main/resources/logback-gateway.xml
  zaas-service/src/main/resources/application.yml
  zaas-service/src/main/resources/logback-zaas.xml
Labels: size/XS

#3792 chore: Workflows status overview
  README.md
  WORKFLOWS_STATUS_OVERVIEW.MD
Labels: size/M

#3796 chore: pin sonar badges to v2
  README.md
Labels: size/XS

#3795 fix: Fix Discovery Eureka response if the service is not registred to allow reconnect by Enabler
  apiml-common/src/testFixtures/java/org/zowe/apiml/util/config/SslContext.java
  build.gradle
  discovery-service/src/main/java/org/zowe/apiml/discovery/config/DiscoveryErrorController.java
  discovery-service/src/test/java/org/zowe/apiml/discovery/eureka/EurekaEndpointTest.java
Labels: size/L

#3797 fix: cli-plugin workflow
  .github/workflows/zowe-cli-plugin.yml
Labels: size/XS

#3800 fix: sonar analysis for v2
  gradle/sonar.gradle
Labels: size/S

#3801 chore: enable cli plugin pipeline manual execution only
  .github/workflows/zowe-cli-plugin.yml
Labels: size/XS

#3805 chore: remove cli-plugin status badge
  WORKFLOWS_STATUS_OVERVIEW.MD
Labels: size/XS

#3804 fix: zowe cli plugin
  .github/workflows/zowe-cli-plugin.yml
Labels: size/XS

#3803 chore: remove obsolete jenkins configuration for sonar
  gradle/sonar.gradle
Labels: size/S

#3806 fix: minor fixes in logs
  api-catalog-services/src/main/resources/application.yml
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/verify/CertificateValidator.java
  caching-service-package/src/main/resources/bin/start.sh
  caching-service/src/main/resources/application.yml
  discovery-service/src/main/resources/application.yml
  gateway-service/src/main/resources/application.yml
  zaas-service/src/main/resources/application.yml
Labels: Sensitive, size/S
