Repository zowe/api-layer, pull requests merged in 2024-08, with the labels that each got.

#3669 Customizable path to logback.xml
  api-catalog-package/src/main/resources/bin/start.sh
  caching-service-package/src/main/resources/bin/start.sh
  cloud-gateway-package/src/main/resources/bin/start.sh
  discovery-package/src/main/resources/bin/start.sh
  gateway-package/src/main/resources/bin/start.sh
  metrics-service-package/src/main/resources/bin/start.sh
Labels: size/M

#3667 Adding Renovate with configs
  .github/workflows/renovate-bot.yml
  renovate-config.js
  renovate.json
Labels: size/M

#3670 feat: Validation of OIDC token via user info endpoint (v2)
  gateway-package/src/main/resources/bin/start.sh
  gateway-service/src/main/java/org/zowe/apiml/gateway/controllers/AuthController.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/source/OIDCAuthSourceService.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/token/OIDCTokenProviderEndpoint.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/token/OIDCTokenProviderJWK.java
  gateway-service/src/main/resources/application.yml
  gateway-service/src/test/java/org/zowe/apiml/acceptance/OIDCTokenProviderEndpointTest.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/config/GatewayOverrideConfig.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/netflix/MetadataBuilder.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/controllers/AuthControllerTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/source/OIDCAuthSourceServiceTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/token/OIDCTokenProviderTest.java
Labels: Sensitive, size/L

#3674 feat: Validation of OIDC token via user info endpoint (v3)
  gradle/coverage.gradle
  zaas-package/src/main/resources/bin/start.sh
  zaas-service/src/main/java/org/zowe/apiml/zaas/controllers/AuthController.java
  zaas-service/src/main/java/org/zowe/apiml/zaas/security/service/schema/source/OIDCAuthSourceService.java
  zaas-service/src/main/java/org/zowe/apiml/zaas/security/service/token/OIDCTokenProviderEndpoint.java
  zaas-service/src/main/java/org/zowe/apiml/zaas/security/service/token/OIDCTokenProviderJWK.java
  zaas-service/src/main/resources/application.yml
  zaas-service/src/test/java/org/zowe/apiml/acceptance/OIDCTokenProviderEndpointTest.java
  zaas-service/src/test/java/org/zowe/apiml/zaas/controllers/AuthControllerTest.java
  zaas-service/src/test/java/org/zowe/apiml/zaas/security/service/schema/source/OIDCAuthSourceServiceTest.java
  zaas-service/src/test/java/org/zowe/apiml/zaas/security/service/token/OIDCTokenProviderTest.java
Labels: Sensitive, size/L

#3678 fix: Fix swagger API documentation for Gateway
  api-catalog-ui/frontend/cypress/e2e/detail-page/swagger-try-out-and-code-snippets.cy.js
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/SwaggerConfig.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/conformance/ValidateAPIController.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/controllers/CertificatesRestController.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/controllers/GatewayHomepageController.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/controllers/RegistryController.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/controllers/VersionController.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/services/ServicesInfoController.java
  gateway-service/src/main/resources/application.yml
  zaas-service/src/main/java/org/zowe/apiml/zaas/controllers/AuthController.java
  zaas-service/src/main/resources/application.yml
  zaas-service/src/main/resources/zaas-api-doc.json
  zaas-service/src/test/java/org/zowe/apiml/acceptance/OIDCTokenProviderJWKEndpointTest.java
  zaas-service/src/test/java/org/zowe/apiml/zaas/security/service/token/OIDCTokenProviderJWKTest.java
Labels: Sensitive, size/XL

#3681 chore: upgrade dompurify for release
  api-catalog-ui/frontend/package-lock.json
  api-catalog-ui/frontend/package.json
  gradle/versions.gradle
Labels: size/M

#3687 fix: updating Gradle Wrapper for Gradle v8.8
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: size/M

#3688 feat: Disable routing to Discovery and ZAAS from Gateway
  gateway-service/src/main/java/org/zowe/apiml/gateway/service/RouteLocator.java
  gateway-service/src/main/resources/application.yml
  gateway-service/src/test/java/org/zowe/apiml/gateway/service/RouteLocatorTest.java
Labels: size/S

#3690 chore: upgrade spring framework to 3.3.39 for Zowe 2.18.0
  gradle/versions.gradle
Labels: size/XS

#3696 chore: adding e2e test for rendering swagger
  api-catalog-ui/frontend/cypress/e2e/dashboard/dashboard.cy.js
  api-catalog-ui/frontend/cypress/e2e/dashboard/wizard-dialog.cy.js
  api-catalog-ui/frontend/cypress/e2e/detail-page/detail-page.cy.js
  api-catalog-ui/frontend/cypress/e2e/detail-page/service-version-compare.cy.js
  api-catalog-ui/frontend/cypress/e2e/detail-page/service-version-switch.cy.js
  api-catalog-ui/frontend/cypress/e2e/detail-page/swagger-rendering.cy.js
  api-catalog-ui/frontend/cypress/e2e/detail-page/swagger-try-out-and-code-snippets.cy.js
  api-catalog-ui/frontend/cypress/e2e/login/login-bad.cy.js
  api-catalog-ui/frontend/cypress/e2e/login/login-ok.cy.js
  api-catalog-ui/frontend/cypress/support/commands.js
Labels: size/L

#3677 chore: label for Dashboard
  renovate-config.js
Labels: size/XS

#3700 feat: websocket connection configuration
  .github/workflows/integration-tests.yml
  build.gradle
  discoverable-client/src/main/resources/application.yml
  gateway-package/src/main/resources/bin/start.sh
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/WebSocketConfig.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/websocket/ApimlWebSocketClient.java
  gateway-service/src/main/resources/application.yml
  gateway-service/src/test/java/org/zowe/apiml/gateway/websocket/ApimlWebSocketClientTest.java
  integration-tests/build.gradle
  integration-tests/src/test/java/org/zowe/apiml/integration/proxy/WebSocketProxyTest.java
Labels: size/L

#3660 feat: GraphiQL Playground
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/swagger/api/AbstractApiDocServiceTest.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/swagger/api/ApiDocV2ServiceTest.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/swagger/api/ApiDocV3ServiceTest.java
  api-catalog-ui/frontend/.env
  api-catalog-ui/frontend/cypress/e2e/detail-page/service-version-compare.cy.js
  api-catalog-ui/frontend/cypress/e2e/graphql/graphql-apiml.cy.js
  api-catalog-ui/frontend/package-lock.json
  api-catalog-ui/frontend/package.json
  api-catalog-ui/frontend/src/components/GraphQL/GraphQLUI.test.jsx
  api-catalog-ui/frontend/src/components/GraphQL/GraphQLUIApiml.css
  api-catalog-ui/frontend/src/components/GraphQL/GraphQLUIApiml.jsx
  api-catalog-ui/frontend/src/components/GraphQL/GraphQLUIApimlContainer.jsx
  api-catalog-ui/frontend/src/components/GraphQL/GraphQLUIContainer.test.jsx
  api-catalog-ui/frontend/src/components/ServiceTab/ServiceTab.jsx
  api-catalog-ui/frontend/src/components/Wizard/configs/wizard_defaults.jsx
  common-service-core/src/main/java/org/zowe/apiml/config/ApiInfo.java
  common-service-core/src/main/java/org/zowe/apiml/constants/EurekaMetadataDefinition.java
  common-service-core/src/main/java/org/zowe/apiml/eurekaservice/client/util/EurekaMetadataParser.java
  common-service-core/src/test/java/org/zowe/apiml/config/ApiInfoTest.java
  common-service-core/src/test/java/org/zowe/apiml/eurekaservice/client/util/EurekaMetadataParserTest.java
  config/docker/api-defs/staticclient.yml
  config/local/api-defs/staticclient.yml
  cypress.config.js
  cypress/support/commands.js
  cypress/support/e2e.js
  discoverable-client/build.gradle
  discoverable-client/graphql.config.yml
  discoverable-client/src/main/java/org/zowe/apiml/client/api/graphql/BookController.java
  discoverable-client/src/main/java/org/zowe/apiml/client/api/graphql/GraphQLExceptionResolver.java
  discoverable-client/src/main/java/org/zowe/apiml/client/configuration/SecurityConfiguration.java
  discoverable-client/src/main/java/org/zowe/apiml/client/exception/BookAlreadyExistsException.java
  discoverable-client/src/main/java/org/zowe/apiml/client/exception/BookNotFoundException.java
  discoverable-client/src/main/java/org/zowe/apiml/client/model/graphql/Author.java
  discoverable-client/src/main/java/org/zowe/apiml/client/model/graphql/Book.java
  discoverable-client/src/main/java/org/zowe/apiml/client/service/ApiMediationClientService.java
  discoverable-client/src/main/resources/application.yml
  discoverable-client/src/main/resources/graphql/schema.graphqls
  discoverable-client/src/test/java/org/zowe/apiml/client/api/graphql/GraphQLExceptionResolverTest.java
  discoverable-client/src/test/java/org/zowe/apiml/client/model/AuthorTest.java
  discoverable-client/src/test/java/org/zowe/apiml/client/model/BookTest.java
  ehcache/.lock
  gradle/versions.gradle
  integration-tests/build.gradle
  integration-tests/graphql.config.yml
  integration-tests/src/test/java/org/zowe/apiml/integration/graphql/BookControllerTest.java
  integration-tests/src/test/java/org/zowe/apiml/util/categories/BookControllerTest.java
  onboarding-enabler-java/src/test/java/org/zowe/apiml/eurekaservice/client/impl/ApiMediationClientImplTest.java
  onboarding-enabler-nodejs-sample-app/package-lock.json
  onboarding-enabler-nodejs-sample-app/package.json
  package-lock.json
  package.json
  zaas-service/ehcache/.lock
Labels: Sensitive, size/XXL

#3703 fix: Renovate excluding minor vers. in PR for v2.x.x
  .github/workflows/renovate-bot.yml
  renovate-config.js
Labels: size/M

#3699 fix: stacktrace on unreachable swagger and remove handling for depreca…
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/services/status/APIDocRetrievalService.java
  api-catalog-services/src/main/resources/apicatalog-log-messages.yml
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/services/status/LocalApiDocServiceTest.java
  apiml-utility/src/main/java/org/zowe/apiml/product/logging/ApimlLogInjector.java
Labels: size/L

#3714 fix: use zowe provided java location if available
  api-catalog-package/src/main/resources/bin/start.sh
  caching-service-package/src/main/resources/bin/start.sh
  discovery-package/src/main/resources/bin/start.sh
  gateway-package/src/main/resources/bin/start.sh
  zaas-package/src/main/resources/bin/start.sh
Labels: size/M

#3710 chore: fix sonarcloud issues in v2.x.x
  apiml-common/src/main/java/org/zowe/apiml/product/web/HttpConfig.java
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/auth/saf/SafResourceAccessEndpoint.java
  caching-service/src/main/java/org/zowe/apiml/caching/api/CachingController.java
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/config/ConnectionsConfig.java
  common-service-core/src/main/java/org/zowe/apiml/message/core/AbstractMessageService.java
  common-service-core/src/main/java/org/zowe/apiml/message/core/Message.java
  common-service-core/src/main/java/org/zowe/apiml/message/log/ApimlLogger.java
  common-service-core/src/test/java/org/zowe/apiml/message/log/ApimlLoggerTest.java
  metrics-service-ui/frontend/src/components/Error/ErrorComponent.jsx
  metrics-service-ui/frontend/src/components/Error/ErrorComponent.test.jsx
  metrics-service-ui/frontend/src/components/Login/Login.jsx
Labels: size/L
