Repository zowe/api-layer, pull requests merged in 2024-01, with the labels that each got.

#3249 fix: Fix truststore for websockets in Spring Cloud Gateway (v2)
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/config/ConnectionsConfig.java
Labels: size/XS

#3251 fixing static definition of zosmf in discovery package
  discovery-package/src/main/resources/zosmf-static-definition.yaml.template
Labels: size/S

#3248 fix: Fix truststore for websockets in Spring Cloud Gateway (v3)
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/config/ConnectionsConfig.java
Labels: size/XS

#3255 Update serviceId in gateway start.sh
  build.gradle
  config/zowe-api-dev/alternative_start.sh
  gateway-package/src/main/resources/bin/start.sh
Labels: size/XS

#3252 feat: Introduce native identity mapper as a replacement for ZSS identity mapping of x509 and OIDC identities
  apiml-security-common/src/main/resources/security-common-log-messages.yml
  apiml-tomcat-common/build.gradle
  build.gradle
  discoverable-client/build.gradle
  gateway-package/src/main/resources/bin/start.sh
  gateway-service/build.gradle
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/mapping/NativeMapper.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/mapping/NativeMapperWrapper.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/mapping/OIDCExternalMapper.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/mapping/OIDCNativeMapper.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/mapping/X509CommonNameUserMapper.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/mapping/X509ExternalMapper.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/mapping/X509NativeMapper.java
  gateway-service/src/main/resources/application.yml
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/mapping/NativeMapperTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/mapping/OIDCExternalMapperTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/mapping/OIDCNativeMapperTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/mapping/X509NativeMapperTest.java
  gradle/versions.gradle
  schemas/gateway-schema.json
Labels: size/XL, Sensitive

#3258 chore: dependency upgrades for Zowe 2.14
  api-catalog-ui/frontend/package-lock.json
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/acceptance/TokenSchemeTest.java
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/acceptance/common/AcceptanceTestWithMockServices.java
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/acceptance/common/MockService.java
  gradle/versions.gradle
  integration-tests/src/test/java/org/zowe/apiml/util/StartAndCleanApplications.java
  integration-tests/src/test/java/org/zowe/apiml/util/service/FullApiMediationLayer.java
  metrics-service-ui/frontend/package-lock.json
Labels: size/L

#3265 fix: update keyring path
  cloud-gateway-package/src/main/resources/bin/start.sh
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/config/ConnectionsConfig.java
  cloud-gateway-service/src/main/resources/application.yml
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/config/ConnectionsConfigTest.java
Labels: size/M

#3266 fix: Fix conflict of XML processing between EhCache and onboarding
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/DiscoveryClientConfig.java
Labels: size/XS

#3270 fix: cors enabled by default in attls mode in gw
  gateway-package/src/main/resources/bin/start.sh
Labels: size/XS

#3273 fix: use empty keystore for outbound calls
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/config/ConnectionsConfig.java
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/config/NettyRoutingFilterApiml.java
Labels: size/S

#3257 chore: Add the workflow that marks stale
  .github/workflows/stale.yml
Labels: size/M

#3271 fix: Fix closing WebScoket in case of 401 and other exception
  gateway-service/src/main/java/org/zowe/apiml/gateway/ws/WebSocketProxyClientHandler.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/ws/WebSocketProxyClientHandlerTest.java
  gradle/sonar.gradle
Labels: size/L

#3276 fix: Fix disabling EhCache
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/CacheConfig.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/NoOpCacheConfig.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/config/CacheConfigTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/config/NoOpCacheConfigTest.java
Labels: size/L

#3277 chore: remove unused stuff
  .circleci/config.yml
  build.gradle
  integration-tests/README.md
  integration-tests/build.gradle
Labels: size/L

#3269 chore: Build and run v3 with Java 17
  .github/actions/setup/action.yml
  .github/workflows/integration-tests.yml
  api-catalog-package/src/main/resources/bin/start.sh
  apiml-tomcat-common/src/test/java/org/zowe/apiml/product/web/ApimlTomcatCustomizerTest.java
  build.gradle
  caching-service-package/src/main/resources/bin/start.sh
  cloud-gateway-package/src/main/resources/bin/start.sh
  common-service-core/src/test/java/org/zowe/apiml/util/ClassOrDefaultProxyUtilsTest.java
  config/zowe-api-dev/alternative_start.sh
  discovery-package/src/main/resources/bin/start.sh
  discovery-service/src/test/java/org/zowe/apiml/discovery/eureka/RefreshablePeerEurekaNodesTest.java
  gateway-package/src/main/resources/bin/start.sh
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/mapping/OIDCExternalMapperTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/zosmf/ZosmfServiceTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/ws/WebSocketRoutedSessionTest.java
  gradle/jib.gradle
  gradle/versions.gradle
  integration-tests/build.gradle
  metrics-service-package/src/main/resources/bin/start.sh
  onboarding-enabler-micronaut-sample-app/build.gradle
  onboarding-enabler-micronaut/build.gradle
  package.json
Labels: Sensitive, size/L

#3275 chore: support all type of blogs for both use cases and tutorials
  api-catalog-ui/frontend/src/utils/utilFunctions.js
Labels: size/XS

#3288 chore: Sonar scanner runs with Java 17
  .github/actions/setup/action.yml
  .github/workflows/integration-tests.yml
Labels: size/S

#3280 fix: Fix disabling EhCache
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/DiscoveryClientConfig.java
Labels: size/XS

#3289 chore: Cherry-pick modifications from V2 to V3 between 2023-01-19 and 2024-01-24
  .github/workflows/integration-tests.yml
  api-catalog-ui/frontend/src/utils/utilFunctions.js
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/DiscoveryClientConfig.java
Labels: size/S

#3281 chore: add request with http client for jwt from zosmf
  integration-tests/src/test/java/org/zowe/apiml/integration/zaas/PassTicketTest.java
  integration-tests/src/test/java/org/zowe/apiml/util/SecurityUtils.java
Labels: size/L

#3293 chore: create user_story.md
  .github/ISSUE_TEMPLATE/user_story.md
Labels: size/S

#3296 fix: z/osmf serviceID in manifest
  gateway-package/src/main/resources/manifest.yaml
Labels: size/XS

#3278 chore: Update changelog for 2.14 RC2
  CHANGELOG.md
Labels: size/S

#3302 fix: correct metadata for z/OSMF routing
  discovery-package/src/main/resources/zosmf-static-definition.yaml.template
  integration-tests/src/test/java/org/zowe/apiml/util/config/ConfigReader.java
  integration-tests/src/test/java/org/zowe/apiml/util/service/FullApiMediationLayer.java
Labels: size/XS

#3301 chore: fix IT to not depend on OIDC token
  integration-tests/src/test/java/org/zowe/apiml/integration/zaas/ZaasNegativeTest.java
Labels: size/XS

#3297 fix: Fix base path in API Catalog
  apiml-common/src/test/java/org/zowe/apiml/product/routing/transform/TransformServiceTest.java
  common-service-core/src/main/java/org/zowe/apiml/product/routing/RoutedServices.java
  common-service-core/src/test/java/org/zowe/apiml/product/routing/RoutedServicesTest.java
  config/local/api-defs-http/staticclient.yml
  config/local/api-defs/staticclient.yml
Labels: size/M
