Repository zowe/api-layer, pull requests merged in 2024-05, with the labels that each got.

#3527 feat: OIDC authentication flow v2
  .github/actions/setup/action.yml
  .github/workflows/integration-tests.yml
  api-catalog-ui/frontend/cypress.config.js
  api-catalog-ui/frontend/cypress/e2e/login/login-oauth.cy.js
  api-catalog-ui/frontend/package.json
  cloud-gateway-service/build.gradle
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/CloudGatewayServiceApplication.java
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/config/WebSecurity.java
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/config/oidc/ClientConfiguration.java
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/config/oidc/Provider.java
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/config/oidc/Registration.java
  cloud-gateway-service/src/main/resources/application.yml
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/config/WebSecurityTest.java
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/config/oidc/ClientConfigurationTest.java
  config/local/cloud-gateway-service.yml
  gradle/versions.gradle
  package.json
Labels: size/XL

#3529 chore: Upgrade v1 dependencies
  .github/workflows/containers.yml
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/auth/saf/SafMethodSecurityExpressionRoot.java
  apiml-tomcat-common/src/main/java/org/zowe/apiml/filter/AttlsFilter.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/controllers/AuthController.java
  gradle/versions.gradle
  onboarding-enabler-nodejs-sample-app/package-lock.json
  onboarding-enabler-nodejs-sample-app/package.json
  package-lock.json
Labels: Sensitive, size/L

#3531 fix: Fix SSL Context switching
  integration-tests/src/test/java/org/zowe/apiml/util/config/ConfigReaderZaasClient.java
  zaas-client/src/main/java/org/zowe/apiml/zaasclient/config/ConfigProperties.java
  zaas-client/src/main/java/org/zowe/apiml/zaasclient/service/internal/ZaasHttpsClientProvider.java
Labels: size/M

#3532 fix: Fix SSL Context switching
  integration-tests/src/test/java/org/zowe/apiml/util/config/ConfigReaderZaasClient.java
  zaas-client/src/main/java/org/zowe/apiml/zaasclient/config/ConfigProperties.java
  zaas-client/src/main/java/org/zowe/apiml/zaasclient/service/internal/ZaasHttpsClientProvider.java
Labels: size/M

#3534 chore: v2 cherry pick
  api-catalog-package/src/main/resources/bin/start.sh
  api-catalog-ui/frontend/src/assets/images/swagger.png
  api-catalog-ui/frontend/src/assets/images/swagger.svg
  api-catalog-ui/frontend/src/assets/images/tutorials.png
  api-catalog-ui/frontend/src/assets/images/tutorials.svg
  api-catalog-ui/frontend/src/assets/images/usecases.png
  api-catalog-ui/frontend/src/assets/images/usecases.svg
  api-catalog-ui/frontend/src/assets/images/videos.png
  api-catalog-ui/frontend/src/assets/images/videos.svg
  api-catalog-ui/frontend/src/components/App/_app.scss
  api-catalog-ui/frontend/src/components/Dashboard/Dashboard.jsx
  api-catalog-ui/frontend/src/components/Dashboard/_dashboard.scss
  api-catalog-ui/frontend/src/components/DetailPage/DetailPage.css
  api-catalog-ui/frontend/src/components/DetailPage/DetailPage.jsx
  api-catalog-ui/frontend/src/components/DetailPage/DetailPage.test.jsx
  api-catalog-ui/frontend/src/components/DetailPage/_detailPage.scss
  api-catalog-ui/frontend/src/components/DetailPage/_models.scss
  api-catalog-ui/frontend/src/components/ExtraContents/BlogContainer.jsx
  api-catalog-ui/frontend/src/components/ExtraContents/BlogContainer.test.jsx
  api-catalog-ui/frontend/src/components/ExtraContents/BlogTile.jsx
  api-catalog-ui/frontend/src/components/ExtraContents/BlogTile.test.jsx
  api-catalog-ui/frontend/src/components/Footer/_footer.scss
  api-catalog-ui/frontend/src/components/Header/HeaderDetail.jsx
  api-catalog-ui/frontend/src/components/Header/HeaderDetail.test.jsx
  api-catalog-ui/frontend/src/components/Header/_header.scss
  api-catalog-ui/frontend/src/components/ServiceTab/ServiceTab.css
  api-catalog-ui/frontend/src/components/ServiceTab/ServiceTab.jsx
  api-catalog-ui/frontend/src/components/ServiceTab/ServiceTab.test.jsx
  api-catalog-ui/frontend/src/components/ServiceTab/_serviceTab.scss
  api-catalog-ui/frontend/src/components/ServicesNavigationBar/ServiceNavigationBar.test.jsx
  api-catalog-ui/frontend/src/components/ServicesNavigationBar/ServicesNavigationBar.jsx
  api-catalog-ui/frontend/src/components/ServicesNavigationBar/_serviceNavigationBar.scss
  api-catalog-ui/frontend/src/components/Swagger/Swagger.css
  api-catalog-ui/frontend/src/components/Swagger/SwaggerUI.test.jsx
  api-catalog-ui/frontend/src/components/Swagger/SwaggerUIApiml.jsx
  api-catalog-ui/frontend/src/components/Swagger/_swagger.scss
  api-catalog-ui/frontend/src/components/Tile/_tile.scss
  api-catalog-ui/frontend/src/utils/utilFunctions.js
  apiml-utility/src/main/resources/utility-log-messages.yml
  caching-service-package/src/main/resources/bin/start.sh
  cloud-gateway-package/src/main/resources/bin/start.sh
  discovery-package/src/main/resources/bin/start.sh
  gateway-package/src/main/resources/bin/start.sh
  gateway-service/src/main/java/org/zowe/apiml/gateway/health/GatewayHealthIndicator.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/ZoweJwtScheme.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/health/GatewayHealthIndicatorTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/ZoweJwtSchemeTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/authentication/pat/PATWithAllSchemesTest.java
Labels: size/XXL

#3535 fix: read from env instead of properties
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/config/oidc/ClientConfiguration.java
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/config/oidc/ClientConfigurationTest.java
Labels: size/L

#3536 chore: Fix release process
  .github/workflows/binary-specific-release.yml
Labels: size/XS

#3538 chore: Fix release process
  .github/workflows/automated-release.yml
Labels: size/XS

#3533 feat: add OIDC login flow schema and enable allowedUsers customization in zowe.yaml
  cloud-gateway-package/src/main/resources/bin/start.sh
  schemas/cloud-gateway-schema.json
Labels: size/M

#3540 chore: update oidc login flow schema for v2
  cloud-gateway-package/src/main/resources/bin/start.sh
  schemas/cloud-gateway-schema.json
Labels: size/M

#3541 fix: fix schema for OIDC login flow
  schemas/cloud-gateway-schema.json
Labels: size/M

#3539 chore: upgrade v3 dependencies
  api-catalog-ui/frontend/package-lock.json
  api-catalog-ui/frontend/package.json
  api-catalog-ui/frontend/src/components/Dashboard/Dashboard.test.jsx
  gradle/versions.gradle
Labels: size/S

#3542 fix: Don't log the failure messages irrelevant for all the problems.
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/source/OIDCAuthSourceService.java
Labels: Sensitive, size/XS

#3544 feat: AT-TLS handler for WebFlux
  cloud-gateway-service/build.gradle
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/attls/AttlsHttpHandler.java
  cloud-gateway-service/src/main/resources/cloud-gateway-log-messages.yml
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/attls/AttlsHttpHandlerTest.java
Labels: size/L

#3546 feat: tomcat customizer for CGW
  apiml-tomcat-common/src/main/java/org/zowe/apiml/product/web/ApimlTomcatCustomizer.java
  apiml-tomcat-common/src/test/java/org/zowe/apiml/product/web/ApimlTomcatCustomizerTest.java
Labels: size/L

#3548 fix: Independent scanning and loading of extension's classes
  apiml-extension-loader/src/main/java/org/zowe/apiml/extension/ExtensionsLoader.java
  apiml-extension-loader/src/test/java/org/zowe/apiml/extension/ExtensionsLoaderTest.java
Labels: size/M

#3543 chore: upgrade dependencies, rollback api-portal changes
  .github/workflows/integration-tests.yml
  api-catalog-ui/build.gradle
  api-catalog-ui/frontend/config-overrides.js
  api-catalog-ui/frontend/cypress.config.js
  api-catalog-ui/frontend/cypress/e2e/detail-page/service-version-compare.cy.js
  api-catalog-ui/frontend/cypress/e2e/detail-page/swagger-try-out-and-code-snippets.cy.js
  api-catalog-ui/frontend/cypress/e2e/login/login-oauth.cy.js
  api-catalog-ui/frontend/package-lock.json
  api-catalog-ui/frontend/package.json
  api-catalog-ui/frontend/src/assets/images/swagger.png
  api-catalog-ui/frontend/src/assets/images/swagger.svg
  api-catalog-ui/frontend/src/assets/images/tutorials.png
  api-catalog-ui/frontend/src/assets/images/tutorials.svg
  api-catalog-ui/frontend/src/assets/images/usecases.png
  api-catalog-ui/frontend/src/assets/images/usecases.svg
  api-catalog-ui/frontend/src/assets/images/videos.png
  api-catalog-ui/frontend/src/assets/images/videos.svg
  api-catalog-ui/frontend/src/assets/images/zowe-horizontal-color.png
  api-catalog-ui/frontend/src/components/App/AsyncModules.jsx
  api-catalog-ui/frontend/src/components/App/_app.scss
  api-catalog-ui/frontend/src/components/Dashboard/Dashboard.jsx
  api-catalog-ui/frontend/src/components/Dashboard/Dashboard.test.jsx
  api-catalog-ui/frontend/src/components/Dashboard/_dashboard.scss
  api-catalog-ui/frontend/src/components/DetailPage/DetailPage.css
  api-catalog-ui/frontend/src/components/DetailPage/DetailPage.jsx
  api-catalog-ui/frontend/src/components/DetailPage/DetailPage.test.jsx
  api-catalog-ui/frontend/src/components/DetailPage/_detailPage.scss
  api-catalog-ui/frontend/src/components/DetailPage/_models.scss
  api-catalog-ui/frontend/src/components/ExtraContents/BlogContainer.jsx
  api-catalog-ui/frontend/src/components/ExtraContents/BlogContainer.test.jsx
  api-catalog-ui/frontend/src/components/ExtraContents/BlogTile.jsx
  api-catalog-ui/frontend/src/components/ExtraContents/BlogTile.test.jsx
  api-catalog-ui/frontend/src/components/Footer/_footer.scss
  api-catalog-ui/frontend/src/components/Header/HeaderDetail.jsx
  api-catalog-ui/frontend/src/components/Header/HeaderDetail.test.jsx
  api-catalog-ui/frontend/src/components/Header/_header.scss
  api-catalog-ui/frontend/src/components/ServiceTab/ServiceTab.css
  api-catalog-ui/frontend/src/components/ServiceTab/ServiceTab.jsx
  api-catalog-ui/frontend/src/components/ServiceTab/ServiceTab.test.jsx
  api-catalog-ui/frontend/src/components/ServiceTab/_serviceTab.scss
  api-catalog-ui/frontend/src/components/ServiceVersionDiff/ServiceVersionDiffContainer.test.jsx
  api-catalog-ui/frontend/src/components/ServicesNavigationBar/ServiceNavigationBar.test.jsx
  api-catalog-ui/frontend/src/components/ServicesNavigationBar/ServicesNavigationBar.jsx
  api-catalog-ui/frontend/src/components/ServicesNavigationBar/_serviceNavigationBar.scss
  api-catalog-ui/frontend/src/components/Swagger/Swagger.css
  api-catalog-ui/frontend/src/components/Swagger/SwaggerContainer.jsx
  api-catalog-ui/frontend/src/components/Swagger/SwaggerUI.test.jsx
  api-catalog-ui/frontend/src/components/Swagger/SwaggerUIApiml.jsx
  api-catalog-ui/frontend/src/components/Swagger/_swagger.scss
  api-catalog-ui/frontend/src/components/Tile/_tile.scss
  api-catalog-ui/frontend/src/components/Wizard/WizardDialog.jsx
  api-catalog-ui/frontend/src/components/Wizard/WizardDialog.test.jsx
  api-catalog-ui/frontend/src/index.js
  api-catalog-ui/frontend/src/utils/utilFunctions.js
  api-catalog-ui/frontend/src/utils/utilFunctions.test.js
  integration-tests/build.gradle
Labels: size/XXL

#3555 chore: v2 cherry pick
  .lock
  api-catalog-ui/frontend/package-lock.json
  api-catalog-ui/frontend/package.json
  api-catalog-ui/frontend/src/assets/images/swagger.png
  api-catalog-ui/frontend/src/assets/images/swagger.svg
  api-catalog-ui/frontend/src/assets/images/tutorials.png
  api-catalog-ui/frontend/src/assets/images/tutorials.svg
  api-catalog-ui/frontend/src/assets/images/usecases.png
  api-catalog-ui/frontend/src/assets/images/usecases.svg
  api-catalog-ui/frontend/src/assets/images/videos.png
  api-catalog-ui/frontend/src/assets/images/videos.svg
  api-catalog-ui/frontend/src/assets/images/zowe-horizontal-color.png
  api-catalog-ui/frontend/src/components/App/_app.scss
  api-catalog-ui/frontend/src/components/Dashboard/Dashboard.jsx
  api-catalog-ui/frontend/src/components/Dashboard/Dashboard.test.jsx
  api-catalog-ui/frontend/src/components/Dashboard/_dashboard.scss
  api-catalog-ui/frontend/src/components/DetailPage/DetailPage.css
  api-catalog-ui/frontend/src/components/DetailPage/DetailPage.jsx
  api-catalog-ui/frontend/src/components/DetailPage/DetailPage.test.jsx
  api-catalog-ui/frontend/src/components/DetailPage/_detailPage.scss
  api-catalog-ui/frontend/src/components/DetailPage/_models.scss
  api-catalog-ui/frontend/src/components/ExtraContents/BlogContainer.jsx
  api-catalog-ui/frontend/src/components/ExtraContents/BlogContainer.test.jsx
  api-catalog-ui/frontend/src/components/ExtraContents/BlogTile.jsx
  api-catalog-ui/frontend/src/components/ExtraContents/BlogTile.test.jsx
  api-catalog-ui/frontend/src/components/Footer/_footer.scss
  api-catalog-ui/frontend/src/components/Header/HeaderDetail.jsx
  api-catalog-ui/frontend/src/components/Header/HeaderDetail.test.jsx
  api-catalog-ui/frontend/src/components/Header/_header.scss
  api-catalog-ui/frontend/src/components/PageNotFound/PageNotFound.css
  api-catalog-ui/frontend/src/components/ServiceTab/ServiceTab.css
  api-catalog-ui/frontend/src/components/ServiceTab/ServiceTab.jsx
  api-catalog-ui/frontend/src/components/ServiceTab/ServiceTab.test.jsx
  api-catalog-ui/frontend/src/components/ServiceTab/_serviceTab.scss
  api-catalog-ui/frontend/src/components/ServicesNavigationBar/ServiceNavigationBar.test.jsx
  api-catalog-ui/frontend/src/components/ServicesNavigationBar/ServicesNavigationBar.jsx
  api-catalog-ui/frontend/src/components/ServicesNavigationBar/_serviceNavigationBar.scss
  api-catalog-ui/frontend/src/components/Swagger/Swagger.css
  api-catalog-ui/frontend/src/components/Swagger/SwaggerUI.test.jsx
  api-catalog-ui/frontend/src/components/Swagger/SwaggerUIApiml.jsx
  api-catalog-ui/frontend/src/components/Swagger/_swagger.scss
  api-catalog-ui/frontend/src/components/Tile/_tile.scss
  api-catalog-ui/frontend/src/utils/utilFunctions.js
  api-catalog-ui/frontend/src/utils/utilFunctions.test.js
  cloud-gateway-package/src/main/resources/bin/start.sh
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/config/oidc/ClientConfiguration.java
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/config/oidc/ClientConfigurationTest.java
  integration-tests/build.gradle
Labels: size/XXL

#3545 feat: CGW support of AT-TLS
  .github/workflows/service-registration.yml
  api-catalog-package/src/main/resources/bin/start.sh
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/filter/CategorizeCertsFilter.java
  apiml-security-common/src/test/java/org/zowe/apiml/security/common/filter/CategorizeCertsFilterTest.java
  apiml-tomcat-common/build.gradle
  apiml-tomcat-common/src/main/java/org/zowe/apiml/filter/AttlsFilter.java
  apiml-tomcat-common/src/main/java/org/zowe/apiml/product/web/ApimlTomcatCustomizer.java
  apiml-tomcat-common/src/test/java/org/zowe/apiml/filter/AttlsFilterTest.java
  apiml-tomcat-common/src/test/java/org/zowe/apiml/product/web/ApimlTomcatCustomizerTest.java
  build.gradle
  caching-service-package/src/main/resources/bin/start.sh
  caching-service/src/main/java/org/zowe/apiml/caching/config/GeneralConfig.java
  cloud-gateway-package/src/main/resources/bin/start.sh
  cloud-gateway-service/build.gradle
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/CloudGatewayServiceApplication.java
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/attls/AttlsHttpHandler.java
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/config/WebSocketConfig.java
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/filters/RequestAttributesProvider.java
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/service/WebClientHelper.java
  cloud-gateway-service/src/main/resources/application.yml
  cloud-gateway-service/src/main/resources/cloud-gateway-log-messages.yml
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/attls/AttlsHttpHandlerTest.java
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/filters/RequestAttributesProviderTest.java
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/service/WebClientHelperTest.java
  config/zowe-api-dev/alternative_start.sh
  discoverable-client/src/main/java/org/zowe/apiml/client/api/RequestInfoController.java
  discovery-package/src/main/resources/bin/start.sh
  discovery-service/src/main/java/org/zowe/apiml/discovery/config/HttpsWebSecurityConfig.java
  gateway-package/build.gradle
  gateway-package/src/main/resources/bin/start.sh
Labels: Sensitive, size/XXL

#3564 feat: Cloud gateway support for AT-TLS
  .github/workflows/service-registration.yml
  api-catalog-package/src/main/resources/bin/start.sh
  apiml-tomcat-common/build.gradle
  apiml-tomcat-common/src/main/java/org/zowe/apiml/filter/AttlsFilter.java
  apiml-tomcat-common/src/main/java/org/zowe/apiml/product/web/ApimlTomcatCustomizer.java
  apiml-tomcat-common/src/test/java/org/zowe/apiml/product/web/ApimlTomcatCustomizerTest.java
  caching-service-package/src/main/resources/bin/start.sh
  caching-service/src/main/java/org/zowe/apiml/caching/config/GeneralConfig.java
  cloud-gateway-package/src/main/resources/bin/start.sh
  cloud-gateway-service/build.gradle
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/CloudGatewayServiceApplication.java
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/attls/AttlsHttpHandler.java
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/config/WebSocketConfig.java
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/filters/RequestAttributesProvider.java
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/service/WebClientHelper.java
  cloud-gateway-service/src/main/resources/application.yml
  cloud-gateway-service/src/main/resources/cloud-gateway-log-messages.yml
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/attls/AttlsHttpHandlerTest.java
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/filters/RequestAttributesProviderTest.java
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/service/WebClientHelperTest.java
  config/zowe-api-dev/alternative_start.sh
  discovery-package/src/main/resources/bin/start.sh
  discovery-service/src/main/java/org/zowe/apiml/discovery/config/HttpsWebSecurityConfig.java
  gateway-package/src/main/resources/bin/start.sh
Labels: size/XXL

#3566 chore: configure external protocol from zowe yaml
  gateway-package/src/main/resources/bin/start.sh
Labels: size/XS

#3565 fix: Provide the correct external URL in the ZUUL Gateway if AT-TLS is enabled
  gateway-package/src/main/resources/bin/start.sh
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/GatewayConfig.java
Labels: size/XS

#3560 Tweak gateway status page to have consistent casing
  gateway-service/src/main/java/org/zowe/apiml/gateway/controllers/GatewayHomepageController.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/controllers/GatewayHomepageControllerTest.java
Labels: size/S

#3554 feat: Catalog version in footer for Login, Dasboard and Detail pages
  api-catalog-ui/frontend/.env
  api-catalog-ui/frontend/.env.test
  api-catalog-ui/frontend/cypress/e2e/dashboard/dashboard.cy.js
  api-catalog-ui/frontend/cypress/e2e/detail-page/detail-page.cy.js
  api-catalog-ui/frontend/cypress/e2e/login/login-ok.cy.js
  api-catalog-ui/frontend/src/components/Dashboard/Dashboard.jsx
  api-catalog-ui/frontend/src/components/DetailPage/DetailPage.jsx
  api-catalog-ui/frontend/src/components/Footer/Footer.jsx
  api-catalog-ui/frontend/src/components/Footer/Footer.test.jsx
  api-catalog-ui/frontend/src/components/Footer/footer.css
  api-catalog-ui/frontend/src/components/Login/Login.jsx
  build.gradle
Labels: size/L

#3502 fix: UI titles and message consistency
  gateway-service/src/main/java/org/zowe/apiml/gateway/controllers/GatewayHomepageController.java
  gateway-service/src/main/resources/templates/home.html
  gateway-service/src/test/java/org/zowe/apiml/gateway/controllers/GatewayHomepageControllerTest.java
Labels: size/M

#3559 chore: upgrade v1 dependencies
  api-catalog-ui/frontend/config-overrides.js
  api-catalog-ui/frontend/package-lock.json
  api-catalog-ui/frontend/package.json
  api-catalog-ui/frontend/src/components/DetailPage/DetailPage.jsx
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/JwtSecurity.java
  gradle/versions.gradle
  package-lock.json
Labels: Sensitive, size/L

#3571 Adapt GH actions to support new ZAAS service
  .github/actions/dump-jacoco/action.yml
  .github/actions/validate-apiml-healthy/action.yml
  .github/workflows/build-conformant-images.yml
  .github/workflows/image-publish-branch.yml
  .github/workflows/integration-tests.yml
  keystore/README.md
  keystore/docker/all-services.ext
  keystore/docker/all-services.keystore.cer
  keystore/docker/all-services.keystore.p12
Labels: size/L

#3572 chore: SCGW conformance migration buildable and unit tests passing
  cloud-gateway-service/build.gradle
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/CloudGatewayServiceApplication.java
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/conformance/AbstractSwaggerValidator.java
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/conformance/ConformanceProblemsContainer.java
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/conformance/OpenApiV2Validator.java
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/conformance/OpenApiV3Validator.java
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/conformance/ValidateAPIController.java
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/conformance/ValidatorFactory.java
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/conformance/VerificationOnboardService.java
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/filters/AbstractAuthSchemeFactory.java
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/service/RouteLocator.java
  cloud-gateway-service/src/main/resources/cloud-gateway-log-messages.yml
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/conformance/ConformanceProblemsContainerTest.java
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/conformance/ValidateAPIControllerTest.java
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/conformance/ValidatorFactoryTest.java
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/conformance/VerificationOnboardServiceTest.java
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/service/RouteLocatorTest.java
  cloud-gateway-service/src/test/resources/api-doc-v2.json
  cloud-gateway-service/src/test/resources/api-doc.json
  cloud-gateway-service/src/test/resources/cloud-gateway-log-messages.yml
  gradle/versions.gradle
  zaas-service/src/main/java/org/zowe/apiml/zaas/controllers/AuthConfigValidationController.java
  zaas-service/src/main/java/org/zowe/apiml/zaas/controllers/AuthController.java
  zaas-service/src/main/java/org/zowe/apiml/zaas/security/service/TokenCreationService.java
  zaas-service/src/main/java/org/zowe/apiml/zaas/zaas/ZaasController.java
  zaas-service/src/main/resources/gateway-log-messages.yml
  zaas-service/src/test/java/org/zowe/apiml/zaas/controllers/AuthConfigValidationControllerTest.java
Labels: size/L

#3574 chore: move GW landing page
  cloud-gateway-service/build.gradle
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/controllers/CertificatesRestController.java
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/controllers/GatewayHomepageController.java
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/controllers/RegistryController.java
  cloud-gateway-service/src/main/resources/application.yml
  cloud-gateway-service/src/main/resources/static/images/favicon.png
  cloud-gateway-service/src/main/resources/static/images/gray-logo.png
  cloud-gateway-service/src/main/resources/static/images/icon-notification-intent-danger.png
  cloud-gateway-service/src/main/resources/static/images/icon-notification-intent-success.png
  cloud-gateway-service/src/main/resources/static/images/icon-notification-intent-warning.png
  cloud-gateway-service/src/main/resources/templates/home.html
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/controllers/CertificatesRestControllerTest.java
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/controllers/GatewayHomepageControllerTest.java
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/controllers/RegistryControllerTest.java
  package.json
  zaas-service/build.gradle
  zaas-service/src/main/resources/application.yml
  zaas-service/src/test/java/org/zowe/apiml/zaas/zaas/ExtractAuthSourceFilterTest.java
Labels: size/XL
