Repository zowe/api-layer, pull requests merged in 2024-10, with the labels that each got.

#3809 chore: remove obsolete docker
  README.md
  docker/README.md
  docker/development/Dockerfile
  docker/development/README.md
  docker/development/_run
  docker/development/_test
  docker/ha-local/docker-compose.yml
  docker/local-single/docker-compose.yml
  docker/nginx/conf/load-balancer.conf
  docker/nginx/conf/nginx.conf
  docker/nginx/docker-compose.yml
Labels: size/L

#3808 fix: Fix duplicities in the lite lib jar
  api-catalog-services/src/main/resources/application.yml
  build.gradle
  caching-service/src/main/resources/application.yml
  discovery-service/src/main/resources/application.yml
  gateway-package/src/main/resources/bin/start.sh
  gateway-service/build.gradle
  gateway-service/gradle/lite.gradle
  gateway-service/src/main/resources/application.yml
  gradle/lite.gradle
  gradle/versions.gradle
  platform/build.gradle
  zaas-package/src/main/resources/bin/start.sh
  zaas-service/build.gradle
  zaas-service/src/main/resources/application.yml
Labels: size/L

#3810 fix: throw insecureHttpWarning message only when attls is not enabled
  apiml-common/src/main/java/org/zowe/apiml/product/web/HttpConfig.java
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/config/ConnectionsConfig.java
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/config/AdditionalRegistrationTest.java
  common-service-core/src/main/java/org/zowe/apiml/security/HttpsFactory.java
  common-service-core/src/test/java/org/zowe/apiml/security/HttpsFactoryTest.java
  onboarding-enabler-java/src/main/java/org/zowe/apiml/eurekaservice/client/config/ApiMediationServiceConfig.java
  onboarding-enabler-java/src/main/java/org/zowe/apiml/eurekaservice/client/impl/ApiMediationClientImpl.java
Labels: Sensitive, size/M

#3811 fix: configure ssl context for webclient
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/ConnectionsConfig.java
Labels: size/M

#3813 fix: respect ssl strictness in enabler
  onboarding-enabler-java/src/main/java/org/zowe/apiml/eurekaservice/client/impl/ApiMediationClientImpl.java
Labels: size/XS

#3814 chore: align lock file
  onboarding-enabler-nodejs-sample-app/package-lock.json
Labels: size/XS

#3815 chore: Upgrade library javax.servlet-api
  build.gradle
Labels: size/XS

#3816 chore: Update serve-static
  api-catalog-ui/frontend/package-lock.json
  api-catalog-ui/frontend/package.json
  metrics-service-ui/frontend/package-lock.json
  metrics-service-ui/frontend/package.json
  onboarding-enabler-nodejs-sample-app/package-lock.json
  onboarding-enabler-nodejs-sample-app/package.json
Labels: size/XS

#3817 chore: Update body-parser
  api-catalog-ui/frontend/package-lock.json
  api-catalog-ui/frontend/package.json
  metrics-service-ui/frontend/package-lock.json
  metrics-service-ui/frontend/package.json
  onboarding-enabler-nodejs-sample-app/package-lock.json
  onboarding-enabler-nodejs-sample-app/package.json
Labels: size/S

#3818 chore: Remove WebJar dependency
  discoverable-client/build.gradle
  discoverable-client/src/main/resources/static/index.html
  gradle/versions.gradle
  mock-services/build.gradle
Labels: size/S

#3824 chore: update deps to the latest version
  .github/actions/setup/action.yml
  api-catalog-ui/frontend/package-lock.json
  api-catalog-ui/frontend/package.json
  gradle/versions.gradle
  scripts/docs/package.json
  zowe-cli-id-federation-plugin/npm-shrinkwrap.json
  zowe-cli-id-federation-plugin/package.json
Labels: size/M

#3822 chore: update depencencies
  .eslintrc.json
  api-catalog-ui/build.gradle
  api-catalog-ui/frontend/.eslintrc.js
  api-catalog-ui/frontend/eslint.config.mjs
  api-catalog-ui/frontend/package-lock.json
  api-catalog-ui/frontend/package.json
  api-catalog-ui/frontend/src/components/App/App.jsx
  api-catalog-ui/frontend/src/components/App/AppContainer.jsx
  api-catalog-ui/frontend/src/components/App/AsyncModules.jsx
  api-catalog-ui/frontend/src/components/ErrorBoundary/BigShield/BigShield.jsx
  api-catalog-ui/frontend/src/components/ErrorBoundary/Shield/Shield.jsx
  api-catalog-ui/frontend/src/components/ServiceTab/InstanceInfo.jsx
  api-catalog-ui/frontend/src/components/ServiceTab/ServiceTab.jsx
  api-catalog-ui/frontend/src/components/Wizard/configs/wizard_base_categories.jsx
  api-catalog-ui/frontend/src/components/Wizard/configs/wizard_categories.jsx
  api-catalog-ui/frontend/src/components/Wizard/configs/wizard_defaults.jsx
  api-catalog-ui/frontend/src/components/Wizard/configs/wizard_micronaut_categories.jsx
  api-catalog-ui/frontend/src/components/Wizard/configs/wizard_node_categories.jsx
  api-catalog-ui/frontend/src/components/Wizard/configs/wizard_onboarding_methods.jsx
  api-catalog-ui/frontend/src/components/Wizard/configs/wizard_regex_restrictions.jsx
  api-catalog-ui/frontend/src/components/Wizard/configs/wizard_spring_categories.jsx
  api-catalog-ui/frontend/src/components/Wizard/configs/wizard_static_categories.jsx
  api-catalog-ui/frontend/src/epics/fetch-tiles.jsx
  api-catalog-ui/frontend/src/epics/index.jsx
  api-catalog-ui/frontend/src/index.js
  api-catalog-ui/frontend/src/reducers/index.jsx
  api-catalog-ui/frontend/src/utils/filterApis.js
  package-lock.json
  package.json
  zowe-cli-id-federation-plugin/.eslintrc.js
  zowe-cli-id-federation-plugin/__tests__/__integration__/cli/map/__snapshots__/cli.map.integration.test.ts.snap
  zowe-cli-id-federation-plugin/__tests__/__integration__/cli/map/__snapshots__/cli.map.team.integration.test.ts.snap
  zowe-cli-id-federation-plugin/__tests__/cli/map/Map.handler.test.ts
  zowe-cli-id-federation-plugin/__tests__/imperative.test.ts
  zowe-cli-id-federation-plugin/build.gradle
  zowe-cli-id-federation-plugin/eslint.config.mjs
  zowe-cli-id-federation-plugin/npm-shrinkwrap.json
  zowe-cli-id-federation-plugin/package.json
  zowe-cli-id-federation-plugin/src/imperative.ts
Labels: size/XL

#3825 feat: support client AT-TLS setting [V2]
  api-catalog-package/src/main/resources/bin/start.sh
  caching-service-package/src/main/resources/bin/start.sh
  cloud-gateway-package/src/main/resources/bin/start.sh
  discovery-package/src/main/resources/bin/start.sh
  gateway-package/src/main/resources/bin/start.sh
  metrics-service-package/src/main/resources/bin/start.sh
Labels: size/M

#3840 chore: V3 docs site branch is master now.
  .github/workflows/docs.yml
  api-catalog-services/src/main/resources/apicatalog-log-messages.yml
  apiml-security-common/src/main/resources/security-common-log-messages.yml
  discovery-service/src/main/resources/discovery-log-messages.yml
  zaas-client/src/main/resources/zaas-client-log-messages.yml
Labels: Sensitive, size/S

#3842 chore: ignore npm deps for renovate updates
  renovate-config.js
Labels: size/XS

#3847 chore: Allow manual trigger for Error Messages
  .github/workflows/docs.yml
Labels: size/XS

#3851 chore: Update Axios, Velocity, and Send to avoid components with a security vulnerability
  api-catalog-ui/frontend/package-lock.json
  api-catalog-ui/frontend/package.json
  gradle/versions.gradle
  metrics-service-ui/frontend/package-lock.json
  metrics-service-ui/frontend/package.json
  onboarding-enabler-nodejs-sample-app/package-lock.json
  onboarding-enabler-nodejs-sample-app/package.json
Labels: size/S

#3850 chore: Correct base branch for PR
  api-catalog-services/src/main/resources/apicatalog-log-messages.yml
  discovery-service/src/main/resources/discovery-log-messages.yml
  scripts/docs/index.js
Labels: size/XS

#3855 chore: remove redundant npm registry config
  api-catalog-ui/frontend/package-lock.json
  api-catalog-ui/frontend/src/components/GraphQL/GraphQLUI.test.jsx
  api-catalog-ui/frontend/src/components/GraphQL/GraphQLUIApiml.jsx
  zowe-cli-id-federation-plugin/.npmrc
Labels: size/M

#3856 chore: Update jgroups and keyExchange port in CS schema
  schemas/caching-schema.json
Labels: size/XS

#3828 feat: support client AT-TLS setting [V3]
  api-catalog-package/src/main/resources/bin/start.sh
  caching-service-package/src/main/resources/bin/start.sh
  discovery-package/src/main/resources/bin/configure.sh
  discovery-package/src/main/resources/bin/start.sh
  discovery-package/src/main/resources/manifest.yaml
  discovery-package/src/main/resources/zosmf-static-definition.yaml.template
  gateway-package/src/main/resources/bin/start.sh
  zaas-package/src/main/resources/bin/start.sh
Labels: size/L

#3862 feat: java sample to authenticate with client certificate
  api-catalog-ui/frontend/package-lock.json
  api-catalog-ui/frontend/package.json
  client-cert-auth-sample/build.gradle
  client-cert-auth-sample/src/main/java/org/zowe/apiml/Main.java
  client-cert-auth-sample/src/test/java/org/zowe/apiml/MainTest.java
  settings.gradle
Labels: size/L

#3863 fix: AT-TLS client aware mode
  api-catalog-package/src/main/resources/bin/start.sh
  discovery-package/src/main/resources/bin/configure.sh
  discovery-package/src/main/resources/manifest.yaml
  discovery-package/src/main/resources/zosmf-static-definition.yaml.template
  gateway-package/src/main/resources/bin/start.sh
Labels: size/M

#3866 fix: use lite jar for gateway-package
  .github/workflows/integration-tests.yml
  gateway-package/build.gradle
  gradle/versions.gradle
Labels: size/S

#3867 fix: update gateway schema with oidc config parameters
  schemas/gateway-schema.json
  zaas-package/src/main/resources/bin/start.sh
  zaas-service/src/main/java/org/zowe/apiml/zaas/security/service/token/OIDCTokenProviderJWK.java
  zaas-service/src/test/java/org/zowe/apiml/zaas/security/service/token/OIDCTokenProviderJWKTest.java
Labels: Sensitive, size/M

#3864 fix: Fix error message in case of TLS error
  gateway-service/src/main/java/org/zowe/apiml/gateway/controllers/GatewayExceptionHandler.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/controllers/GatewayExceptionHandlerTest.java
Labels: size/L

#3852 chore: Add log message about processing certificate from AT-TLS
  apiml-tomcat-common/src/main/java/org/zowe/apiml/filter/AttlsFilter.java
  gradle/versions.gradle
Labels: size/M

#3845 fix: Send correct error message even the header are not possible to modify
  gateway-service/src/main/java/org/zowe/apiml/gateway/controllers/GatewayExceptionHandler.java
Labels: size/XS
