Repository zowe/api-layer, pull requests merged in 2025-09, with the labels that each got.

#4302 chore: remove obsolete caching from OIDCAuthSourceService
  zaas-service/src/main/java/org/zowe/apiml/zaas/security/service/schema/source/OIDCAuthSourceService.java
Labels: Sensitive, size/S

#4307 fix: cherry pick apiml.gateway.servicesToDisableRetry to modulith
  apiml-package/src/main/resources/bin/start.sh
Labels: size/XS

#4284 fix: API ML services log cleanup
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/config/ApiLayerServices.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/ContainerService.java
  api-catalog-services/src/main/resources/apicatalog-log-messages.yml
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/util/ApiLayerServicesTest.java
Labels: size/L

#4313 chore: V2 dependencies upgrade
  gradle/versions.gradle
Labels: size/XS

#4308 Support multi-value OIDC claims for userId mapping
  apiml-common/src/testFixtures/java/org/zowe/apiml/util/HttpClientMockHelper.java
  zaas-service/src/main/java/org/zowe/apiml/zaas/security/mapping/OIDCExternalMapper.java
  zaas-service/src/main/java/org/zowe/apiml/zaas/security/mapping/OIDCMapperHelper.java
  zaas-service/src/main/java/org/zowe/apiml/zaas/security/mapping/OIDCNativeMapper.java
  zaas-service/src/main/java/org/zowe/apiml/zaas/security/service/JwtUtils.java
  zaas-service/src/main/java/org/zowe/apiml/zaas/security/service/schema/source/OIDCAuthSource.java
  zaas-service/src/main/java/org/zowe/apiml/zaas/security/service/schema/source/OIDCAuthSourceService.java
  zaas-service/src/test/java/org/zowe/apiml/zaas/security/mapping/OIDCExternalMapperTest.java
  zaas-service/src/test/java/org/zowe/apiml/zaas/security/mapping/OIDCNativeMapperTest.java
  zaas-service/src/test/java/org/zowe/apiml/zaas/security/service/JwtUtilsTest.java
  zaas-service/src/test/java/org/zowe/apiml/zaas/security/service/schema/source/OIDCAuthSourceServiceTest.java
  zaas-service/src/test/java/org/zowe/apiml/zaas/security/service/token/OIDCTokenProviderTest.java
  zaas-service/src/test/java/org/zowe/apiml/zaas/utils/JWTUtils.java
Labels: Sensitive, size/XL

#4317 chore: Upgrade transitive dependency fileupload to 1.6.0
  gradle/versions.gradle
Labels: size/XS

#4321 feat: Support Keycloak as OIDC provider in integration tests
  .github/workflows/integration-tests.yml
  config/local/zaas-service.yml
  integration-tests/build.gradle
  integration-tests/src/test/java/org/zowe/apiml/integration/authentication/oauth2/OidcOauth2Test.java
  integration-tests/src/test/java/org/zowe/apiml/integration/authentication/schemes/GatewayAuthTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/authentication/services/ZaasClientIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/zaas/PassTicketTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/zaas/SafIdTokensTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/zaas/ZaasNegativeTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/zaas/ZosmfTokensTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/zaas/ZoweTokensTest.java
  integration-tests/src/test/java/org/zowe/apiml/util/SecurityUtils.java
  integration-tests/src/test/java/org/zowe/apiml/util/config/ConfigReader.java
  integration-tests/src/test/java/org/zowe/apiml/util/config/EnvironmentConfiguration.java
  integration-tests/src/test/java/org/zowe/apiml/util/config/IDPConfiguration.java
  integration-tests/src/test/java/org/zowe/apiml/util/config/OidcConfiguration.java
  integration-tests/src/test/resources/environment-configuration-docker-modulith-ha.yml
  integration-tests/src/test/resources/environment-configuration-docker-modulith.yml
  integration-tests/src/test/resources/environment-configuration-docker.yml
  integration-tests/src/test/resources/environment-configuration-ha.yml
  integration-tests/src/test/resources/environment-configuration.yml
  zaas-service/src/main/java/org/zowe/apiml/zaas/security/mapping/NativeMapper.java
Labels: Sensitive, size/L

#4327 fix: z/OSMF static definition for AT-TLS
  discovery-package/src/main/resources/zosmf-static-definition.yaml.template
Labels: size/XS

#4332 chore: debug log
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/PageRedirectionFilterFactory.java
Labels: size/XS

#4333 fix: update modulith version of z/OSMF static definition
  apiml-package/src/main/resources/zosmf-static-definition.yaml.template
  discovery-package/src/main/resources/zosmf-static-definition.yaml.template
Labels: size/S

#4330 fix: z/OSMF static definition for AT-TLS (v2.18.x)
  discovery-package/src/main/resources/zosmf-static-definition.yaml.template
Labels: size/XS
