Repository zowe/api-layer, pull requests merged in 2025-03, with the labels that each got.

#4020 fix: file log appender for debug profile
  apiml-utility/src/main/java/org/zowe/apiml/product/logging/ApimlRollingFileAppender.java
  apiml-utility/src/test/java/org/zowe/apiml/product/logging/ApimlRollingFileAppenderTest.java
Labels: size/S

#4024 chore: Update github cache action
  .github/workflows/integration-tests.yml
Labels: size/XS

#4025 fix: update ciphers list v3
  api-catalog-package/src/main/resources/bin/start.sh
  caching-service-package/src/main/resources/bin/start.sh
  discovery-package/src/main/resources/bin/start.sh
  gateway-package/src/main/resources/bin/start.sh
  zaas-package/src/main/resources/bin/start.sh
Labels: size/S

#4023 fix: default ciphers list
  api-catalog-package/src/main/resources/bin/start.sh
  caching-service-package/src/main/resources/bin/start.sh
  cloud-gateway-package/src/main/resources/bin/start.sh
  discovery-package/src/main/resources/bin/start.sh
  gateway-package/src/main/resources/bin/start.sh
  metrics-service-package/src/main/resources/bin/start.sh
Labels: size/S

#4026 fix: ciphers list v2
  api-catalog-package/src/main/resources/bin/start.sh
  caching-service-package/src/main/resources/bin/start.sh
  cloud-gateway-package/src/main/resources/bin/start.sh
  discovery-package/src/main/resources/bin/start.sh
  metrics-service-package/src/main/resources/bin/start.sh
Labels: size/S

#4022 chore: Integration tests runnable with API ML v2 on z/OS
  .github/workflows/integration-tests.yml
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/auth/saf/SafResourceAccessSaf.java
  apiml-security-common/src/test/java/org/zowe/apiml/security/common/auth/saf/SafResourceAccessSafTest.java
  common-service-core/src/main/java/org/zowe/apiml/passticket/AbstractIRRPassTicketException.java
  common-service-core/src/test/java/org/zowe/apiml/passticket/AbstractIRRPassTicketExceptionTest.java
  config/local/gateway-service.yml
  discoverable-client/build.gradle
  gateway-service/src/main/java/org/zowe/apiml/gateway/controllers/AuthController.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/config/NewSecurityConfiguration.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/source/PATAuthSourceService.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/token/ApimlAccessTokenProvider.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/ticket/SuccessfulTicketHandlerTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/token/ApimlAccessTokenProviderTest.java
  integration-tests/build.gradle
  integration-tests/src/test/java/org/zowe/apiml/functional/apicatalog/ApiCatalogEndpointIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/functional/discovery/DiscoveryServiceAuthenticationTest.java
  integration-tests/src/test/java/org/zowe/apiml/functional/gateway/GatewayAuthenticationTest.java
  integration-tests/src/test/java/org/zowe/apiml/functional/gateway/GatewayTimeoutTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/authentication/pat/AccessTokenServiceTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/authentication/pat/PATWithAllSchemesTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/authentication/providers/LogoutTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/authentication/providers/QueryTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/authentication/providers/ZosmfLoginTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/authentication/schemes/CloudGatewayAuthTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/authentication/schemes/PassticketSchemeTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/authentication/services/ServiceProtectedEndpointIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/ha/ApiCatalogMultipleInstancesTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/penetration/JwtPenTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/proxy/WebSocketProxyTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/zaas/PassTicketTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/zaas/SafIdTokensTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/zos/PassTicketTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/zos/ServicesInfoTest.java
  integration-tests/src/test/java/org/zowe/apiml/util/SecurityUtils.java
  integration-tests/src/test/java/org/zowe/apiml/util/categories/TestsNotMeantForZowe.java
  integration-tests/src/test/java/org/zowe/apiml/util/config/ConfigReader.java
  integration-tests/src/test/java/org/zowe/apiml/util/config/ConfigReaderZaasClient.java
  integration-tests/src/test/java/org/zowe/apiml/util/config/GatewayServiceConfiguration.java
  integration-tests/src/test/java/org/zowe/apiml/util/config/ZosmfServiceConfiguration.java
  integration-tests/src/test/java/org/zowe/apiml/util/http/HttpRequestUtils.java
  integration-tests/src/test/java/org/zowe/apiml/util/requests/ApiCatalogRequests.java
  keystore/README.md
  keystore/client_cert/client-certs.p12
  onboarding-enabler-nodejs/.gitignore
  package.json
Labels: Sensitive, size/XXL

#4038 fix: non-strict hostname verification in Jetty client for WebSockets
  apiml-common/src/main/java/org/zowe/apiml/product/web/HttpConfig.java
  package.json
Labels: size/XS

#4039 chore: upgrade axios
  api-catalog-ui/frontend/package-lock.json
  api-catalog-ui/frontend/package.json
  metrics-service-ui/frontend/package-lock.json
  metrics-service-ui/frontend/package.json
Labels: size/XS

#4041 chore: upgrade common java to latest
  gradle/versions.gradle
Labels: size/XS

#4040 chore: upgrade common java
  gradle/versions.gradle
Labels: size/XS

#4027 feat: v2 with java 21
  .run/GatewayApplication.run.xml
  api-catalog-package/src/main/resources/bin/start.sh
  apiml-common/src/main/resources/logback.xml
  caching-service-package/src/main/resources/bin/start.sh
  caching-service/src/main/resources/logback.xml
  cloud-gateway-package/src/main/resources/bin/start.sh
  cloud-gateway-service/src/main/resources/logback.xml
  discoverable-client/src/main/resources/logback.xml
  discovery-package/src/main/resources/bin/start.sh
  gateway-package/src/main/resources/bin/start.sh
  gradle/versions.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  integration-tests/src/test/resources/logback.xml
  metrics-service-package/src/main/resources/bin/start.sh
  metrics-service/src/main/resources/logback.xml
  onboarding-enabler-micronaut-sample-app/src/main/resources/logback.xml
Labels: size/XL

#4028 feat: v3 with java 21
  api-catalog-package/src/main/resources/bin/start.sh
  apiml-common/src/main/resources/logback.xml
  caching-service-package/src/main/resources/bin/start.sh
  caching-service/src/main/resources/logback.xml
  discoverable-client/src/main/resources/logback.xml
  discovery-package/src/main/resources/bin/start.sh
  gateway-package/src/main/resources/bin/start.sh
  gateway-service/src/main/resources/logback-gateway.xml
  gradle/jib.gradle
  integration-tests/src/test/resources/logback.xml
  onboarding-enabler-micronaut-sample-app/src/main/resources/logback.xml
  zaas-package/src/main/resources/bin/start.sh
  zaas-service/src/main/resources/logback-zaas.xml
Labels: size/M

#4046 feat: eureka client connection timeout
  discoverable-client/src/main/java/org/zowe/apiml/client/model/DiscoverableClientConfig.java
  discoverable-client/src/main/java/org/zowe/apiml/client/service/ApiMediationClientService.java
  discoverable-client/src/main/resources/application.yml
  onboarding-enabler-java/src/main/java/org/zowe/apiml/eurekaservice/client/config/ApiMediationServiceConfig.java
  onboarding-enabler-java/src/main/java/org/zowe/apiml/eurekaservice/client/config/EurekaClientConfiguration.java
Labels: size/M

#4043 fix: change error code SERVICE_UNAVAILABLE to INTERNAL_SERVER_ERROR when ticket generation fails
  zaas-client/src/main/java/org/zowe/apiml/zaasclient/exception/ZaasClientErrorCodes.java
  zaas-client/src/main/java/org/zowe/apiml/zaasclient/service/internal/PassTicketServiceImpl.java
  zaas-client/src/main/resources/zaas-client-log-messages.yml
  zaas-client/src/test/java/org/zowe/apiml/zaasclient/service/internal/ZaasClientImplHttpsTests.java
  zaas-client/src/test/java/org/zowe/apiml/zaasclient/service/internal/ZaasClientTest.java
Labels: Sensitive, size/M

#4047 fix: change error code SERVICE_UNAVAILABLE to INTERNAL_SERVER_ERROR when ticket generation fails in v3
  zaas-client/src/main/java/org/zowe/apiml/zaasclient/exception/ZaasClientErrorCodes.java
  zaas-client/src/main/java/org/zowe/apiml/zaasclient/service/internal/PassTicketServiceImpl.java
  zaas-client/src/main/resources/zaas-client-log-messages.yml
  zaas-client/src/test/java/org/zowe/apiml/zaasclient/service/internal/ZaasClientImplHttpsTests.java
  zaas-client/src/test/java/org/zowe/apiml/zaasclient/service/internal/ZaasClientTest.java
Labels: size/M
