Repository zowe/api-layer, pull requests merged in 2025-07, with the labels that each got.

#4195 fix: NPE in ApimlPeerEurekaNode stops heartbeats
  apiml-common/src/main/java/org/zowe/apiml/product/eureka/client/ApimlPeerEurekaNode.java
Labels: size/M

#4188 fix: Secure x-forwarded-* headers from untrusted proxies but trust all apiml proxies (v2)
  .github/workflows/integration-tests.yml
  apiml-utility/build.gradle
  apiml-utility/src/main/java/org/zowe/apiml/product/gateway/AdditionalRegistrationGatewayRegistry.java
  apiml-utility/src/test/java/org/zowe/apiml/product/gateway/AdditionalRegistrationGatewayRegistryTest.java
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/config/ConnectionsConfig.java
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/config/WebSecurity.java
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/filters/X509awareXForwardedHeadersFilter.java
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/acceptance/common/AcceptanceTestWithMockServices.java
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/acceptance/xForwardHeaders/MutateRemoteAddressFilter.java
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/acceptance/xForwardHeaders/XForwardedHeadersProxyTest.java
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/acceptance/xForwardHeaders/XForwardedHeadersTrustedProxyTest.java
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/config/AdditionalRegistrationTest.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/DiscoveryClientConfig.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/GatewayConfig.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/pre/ApimlPreDecorationFilter.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/ForwardedHeadersProxyTest.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/ForwardedHeadersTrustedProxyTest.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/ForwardedProxyHeadersTest.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/common/AcceptanceTestWithBasePath.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/config/GatewayOverrideConfig.java
  gateway-service/src/test/java/org/zowe/apiml/acceptance/config/MutateRemoteAddressFilter.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/config/DiscoveryClientBeanTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/config/DiscoveryClientConfigTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/proxy/XForwardHeadersProxyTest.java
Labels: size/XXL

#4214 chore: swagger-ui-react 5.22.0 upgrade
  api-catalog-ui/frontend/config-overrides.js
  api-catalog-ui/frontend/package-lock.json
  api-catalog-ui/frontend/package.json
Labels: size/S

#4216 fix: API ML startup message in modulith mode
  apiml-utility/src/main/java/org/zowe/apiml/product/logging/ApimlLogInjector.java
  apiml-utility/src/test/java/org/zowe/apiml/product/logging/ApimlLogInjectorTest.java
  apiml/src/main/java/org/zowe/apiml/GatewayHealthIndicator.java
  apiml/src/test/java/org/zowe/apiml/acceptance/AcceptanceTestWithMockServices.java
  apiml/src/test/java/org/zowe/apiml/acceptance/StartupMessageAcceptanceTest.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/GatewayHealthIndicator.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/config/GatewayHealthIndicatorTest.java
Labels: size/L

#4221 fix: gateway returns empty auth keys from zosmf when jwtAutoconfiguration is jwt
  apiml-common/src/main/java/org/zowe/apiml/product/web/HttpConfig.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/config/ComponentsConfiguration.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/zosmf/ZosmfService.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/login/zosmf/ZosmfAuthenticationProviderTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/query/SuccessfulQueryHandlerTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/zosmf/ZosmfServiceTest.java
Labels: Sensitive, size/M

#4223 fix: unresponsive eureka
  .github/workflows/integration-tests.yml
  apiml/src/main/java/org/zowe/apiml/EurekaRestController.java
  apiml/src/main/java/org/zowe/apiml/ModulithConfig.java
  apiml/src/main/resources/application.yml
  apiml/src/test/resources/application.yml
  caching-service/src/main/resources/application.yml
  config/docker/api-catalog-services-standalone.yml
  config/docker/api-catalog-services.yml
  config/docker/apiml.yml
  config/docker/discoverable-client.yml
  config/docker/discovery-service.yml
  config/docker/gateway-service.yml
  config/docker/zaas-service.yml
  config/local-multi/discovery-service-1.yml
  config/local-multi/discovery-service-2.yml
  config/local-multi/gateway-service-1.yml
  config/local-multi/gateway-service-2.yml
  config/local-multi/zaas-service-1.yml
  config/local-multi/zaas-service-2.yml
  config/local/api-catalog-service.yml
  config/local/api-catalog-services-standalone.yml
  config/local/discoverable-client.yml
  discoverable-client/src/main/resources/application.yml
  discovery-service/src/main/resources/application.yml
  gateway-service/src/main/resources/application.yml
  integration-tests/src/test/java/org/zowe/apiml/util/service/VirtualService.java
  mock-services/src/main/resources/application.yml
  zaas-service/src/main/java/org/zowe/apiml/zaas/ZaasStartupListener.java
Labels: size/L

#4226 fix: update start.sh settings for caching service
  apiml-package/src/main/resources/bin/start.sh
  config/docker/apiml.yml
  config/local/gateway-service.yml
Labels: size/S

#4203 refactor: Replacement EurekaClient by DiscoveryClient
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/ApiDocRetrievalServiceRest.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/ContainerService.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/SubstituteSwaggerGenerator.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/TransformApiDocService.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/controllers/api/ServicesControllerTests.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/swagger/ContainerServiceTest.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/swagger/LocalApiDocServiceTest.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/swagger/SubstituteSwaggerGeneratorTest.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/util/ServicesBuilder.java
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/error/ResourceAccessExceptionHandler.java
  common-service-core/build.gradle
  common-service-core/src/main/java/org/zowe/apiml/util/EurekaUtils.java
  common-service-core/src/test/java/org/zowe/apiml/util/EurekaUtilsTest.java
Labels: size/XL

#4206 fix: Fix choosing correct parser for api doc
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/api/ApiTransformationConfig.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/swagger/api/ApiTransformationConfigTest.java
Labels: size/M

#4171 fix: Secure x-forwarded-* headers from untrusted proxies
  .github/workflows/integration-tests.yml
  apiml-common/src/main/java/org/zowe/apiml/product/web/HttpConfig.java
  apiml-common/src/test/java/org/zowe/apiml/product/web/HttpConfigTest.java
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/verify/CertificateValidator.java
  common-service-core/src/main/java/org/zowe/apiml/security/SecurityUtils.java
  gateway-package/src/main/resources/bin/start.sh
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/ConnectionsConfig.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/WebSecurity.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/proxyheaders/AdditionalRegistrationGatewayRegistry.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/proxyheaders/X509AndGwAwareXForwardedHeadersFilter.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/service/CertificateChainService.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/acceptance/common/AcceptanceTestWithMockServices.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/acceptance/xForwardHeaders/MutateRemoteAddressFilter.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/acceptance/xForwardHeaders/XForwardedHeadersProxyTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/acceptance/xForwardHeaders/XForwardedHeadersTrustedProxyTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/config/AdditionalRegistrationTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/config/ConnectionsConfigTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/filters/proxyheaders/AdditionalRegistrationGatewayRegistryTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/service/CertificateChainServiceTest.java
  gateway-service/src/test/resources/application.yml
  integration-tests/build.gradle
  integration-tests/src/test/java/org/zowe/apiml/functional/gateway/CentralRegistryTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/proxy/XForwardHeadersProxyTest.java
Labels: Sensitive, size/XXL

#4209 feat: Loading API doc locally if possible to avoid REST call
  api-catalog-services/build.gradle
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/controllers/api/ApiDocController.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/controllers/api/ServicesController.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/staticapi/StaticDefinitionController.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/ApiDocInfo.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/ApiDocRetrievalService.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/ApiDocRetrievalServiceLocal.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/ApiDocRetrievalServiceRest.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/ApiDocService.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/ContainerService.java
  api-catalog-services/src/main/resources/application.yml
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/controllers/api/ApiDocControllerApiDocNotFoundTest.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/controllers/api/ApiDocControllerServiceNotFoundTest.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/controllers/api/ApiDocControllerTest.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/controllers/api/ServicesControllerContainerRetrievalTest.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/controllers/api/ServicesControllerTests.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/swagger/ApiDocRetrievalServiceLocalTest.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/swagger/ApiDocServiceTest.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/swagger/LocalApiDocServiceTest.java
  api-catalog-services/src/test/resources/application.yml
  apiml-common/src/main/java/org/zowe/apiml/product/routing/transform/TransformService.java
  integration-tests/src/test/java/org/zowe/apiml/functional/apicatalog/ApiCatalogEndpointIntegrationTest.java
Labels: size/XXL

#4232 refactor: use StepVerifier in WebFlux tests
  .gitignore
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/controllers/api/ApiDocControllerTest.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/controllers/api/ServicesControllerTests.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/security/ApiCatalogLogoutSuccessHandlerTest.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/swagger/ApiDocServiceTest.java
  apiml/.gitignore
  gateway-service/src/test/java/org/zowe/apiml/gateway/caching/LoadBalancerCacheTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/filters/ForbidEncodedCharactersFilterFactoryTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/filters/InMemoryRateLimiterTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/filters/KeyResolverTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/filters/X509FilterFactoryTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/x509/ClientCertFilterFactoryTest.java
Labels: size/XL

#4234 chore: Clean up Catalog after refactoring (to be part of modulith)
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/AppReadyListener.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/config/ApiTransformationConfig.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/config/SecurityConfiguration.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/config/SwaggerConfiguration.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/config/TomcatConfiguration.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/controllers/api/OidcController.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/controllers/api/StaticAPIRefreshController.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/controllers/api/StaticDefinitionController.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/controllers/handlers/CustomErrorStatusHandlingBean.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/controllers/handlers/DefaultExceptionHandler.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/controllers/handlers/StaticAPIRefreshControllerExceptionHandler.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/controllers/handlers/StaticDefinitionControllerExceptionHandler.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/exceptions/ApiDocTransformationException.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/health/ApiCatalogHealthIndicator.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/model/ApiDocInfo.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/oidc/OidcUtils.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/staticapi/DiscoveryConfigProperties.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/staticapi/StaticAPIService.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/ApiDocRetrievalServiceLocal.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/ApiDocRetrievalServiceRest.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/ApiDocService.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/TransformApiDocService.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/api/AbstractApiDocService.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/api/ApiDocV2Service.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/api/ApiDocV3Service.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/controllers/api/ServicesControllerTests.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/controllers/api/StaticAPIRefreshControllerTest.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/controllers/api/StaticDefinitionControllerTest.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/exceptions/ApiDiffNotAvailableExceptionTest.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/instance/InstanceServicesContextConfiguration.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/staticapi/StaticAPIServiceTest.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/swagger/ApiDocServiceTest.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/swagger/ApiDocTransformationExceptionTest.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/swagger/TransformApiDocServiceTest.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/swagger/api/AbstractApiDocServiceTest.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/swagger/api/ApiDocV2ServiceTest.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/swagger/api/ApiDocV3ServiceTest.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/swagger/api/ApiTransformationConfigTest.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/swagger/api/DummyApiDocService.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/util/ApplicationsWrapper.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/util/ContainerServiceState.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/util/ServicesBuilder.java
  api-catalog-services/src/test/resources/localhost_truststore.jks
Labels: size/L

#4235 feat: Allow redirect on downloading OpenAPI / Swagger
  common-service-core/src/main/java/org/zowe/apiml/security/HttpsFactory.java
Labels: size/S

#4238 chore: Sonar fixes (Catalog as part of Modulith)
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/config/SecurityConfiguration.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/config/WebConfig.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/controllers/api/ApiDocController.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/oidc/OidcUtils.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/ApiDocRetrievalServiceLocal.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/swagger/api/DummyApiDocService.java
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/error/AuthExceptionHandler.java
  common-service-core/src/main/java/org/zowe/apiml/util/EurekaUtils.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/SwaggerConfig.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/PageRedirectionFilterFactory.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/X509FilterFactory.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/filters/X509FilterFactoryTest.java
Labels: size/M

#4242 refactor: Call refresh of static services endpoint via API to reduce REST calls in Modulith
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/controllers/api/StaticAPIRefreshController.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/staticapi/StaticRegistrationService.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/staticapi/StaticRegistrationServiceApi.java
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/staticapi/StaticRegistrationServiceRest.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/controllers/api/StaticAPIRefreshControllerTest.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/staticapi/StaticRegistrationServiceApiTest.java
  api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/staticapi/StaticRegistrationServiceRestTest.java
  apiml-common/src/main/java/org/zowe/apiml/product/discovery/Route.java
  apiml-common/src/main/java/org/zowe/apiml/product/discovery/Service.java
  apiml-common/src/main/java/org/zowe/apiml/product/discovery/ServiceOverride.java
  apiml-common/src/main/java/org/zowe/apiml/product/discovery/ServiceOverrideData.java
  apiml-common/src/main/java/org/zowe/apiml/product/discovery/StaticRegistrationResult.java
  apiml-common/src/main/java/org/zowe/apiml/product/discovery/StaticServicesRegistration.java
  apiml/src/main/java/org/zowe/apiml/StaticDefinitionsRefreshRestController.java
  apiml/src/test/java/org/zowe/apiml/StaticDefinitionsRefreshRestControllerTest.java
  discovery-service/src/main/java/org/zowe/apiml/discovery/metadata/MetadataDefaultsService.java
  discovery-service/src/main/java/org/zowe/apiml/discovery/staticdef/Definition.java
  discovery-service/src/main/java/org/zowe/apiml/discovery/staticdef/ServiceDefinitionProcessor.java
  discovery-service/src/main/java/org/zowe/apiml/discovery/staticdef/StaticApiRestController.java
  discovery-service/src/main/java/org/zowe/apiml/discovery/staticdef/StaticServicesRegistrationService.java
  discovery-service/src/test/java/org/zowe/apiml/discovery/metadata/MetadataDefaultsServiceTest.java
  discovery-service/src/test/java/org/zowe/apiml/discovery/staticdef/ServiceDefinitionProcessorTest.java
  discovery-service/src/test/java/org/zowe/apiml/discovery/staticdef/StaticApiRestControllerTest.java
  discovery-service/src/test/java/org/zowe/apiml/discovery/staticdef/StaticServicesRegistrationServiceTest.java
Labels: size/L

#4249 fix: multi-tenancy deployment in single-service(modulit) mode
  .github/workflows/integration-tests.yml
  api-catalog-ui/frontend/.env
  api-catalog-ui/frontend/.env.production
  api-catalog-ui/frontend/cypress.modulith.config.js
  api-catalog-ui/frontend/cypress/e2e/dashboard/dashboard.cy.js
  api-catalog-ui/frontend/cypress/e2e/detail-page/detail-page.cy.js
  api-catalog-ui/frontend/cypress/e2e/detail-page/service-version-compare.cy.js
  api-catalog-ui/frontend/cypress/e2e/login/login-ok.cy.js
  api-catalog-ui/frontend/package.json
  apiml/src/main/java/org/zowe/apiml/ModulithConfig.java
  apiml/src/main/java/org/zowe/apiml/WebSecurityConfig.java
  apiml/src/test/java/org/zowe/apiml/ModulithConfigTest.java
  build.gradle
  caching-service/src/main/resources/infinispan.xml
  common-service-core/src/main/java/org/zowe/apiml/services/BasicInfoService.java
  config/local/apiml-service-2.yml
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/ConnectionsConfig.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/RegistryConfig.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/services/ServicesInfoService.java
  integration-tests/build.gradle
  integration-tests/src/test/java/org/zowe/apiml/functional/gateway/CentralRegistryTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/authentication/providers/SafLoginTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/zos/ServicesInfoTest.java
  zaas-service/src/main/java/org/zowe/apiml/zaas/security/login/Providers.java
Labels: Sensitive, size/XL
