Repository zowe/api-layer, pull requests merged in 2025-01, with the labels that each got.

#3938 fix: zosmf static definition conversion
  discovery-package/src/main/resources/bin/configure.sh
  discovery-package/src/main/resources/manifest.yaml
  discovery-package/src/main/resources/zosmf-static-definition.yaml.template
Labels: size/M

#3937 fix: Make native the default saf auth provider
  api-catalog-package/src/main/resources/bin/start.sh
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/auth/saf/SafResourceAccessConfig.java
  apiml-security-common/src/test/java/org/zowe/apiml/security/common/auth/saf/SafResourceAccessConfigTest.java
  gateway-package/src/main/resources/bin/start.sh
  integration-tests/src/test/resources/environment-configuration.yml
  zaas-package/src/main/resources/bin/start.sh
Labels: Sensitive, size/S

#3943 fix: tls version and cipher suit configuration
  api-catalog-package/src/main/resources/bin/start.sh
  caching-service-package/src/main/resources/bin/start.sh
  cloud-gateway-package/src/main/resources/bin/start.sh
  discovery-package/src/main/resources/bin/start.sh
  gateway-package/src/main/resources/bin/start.sh
  metrics-service-package/src/main/resources/bin/start.sh
Labels: size/L

#3935 feat: override external URL for additional registration
  .github/workflows/integration-tests.yml
  containers/gateway-service/prepare.sh
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/ConnectionsConfig.java
  gateway-service/src/main/resources/application.yml
  gateway-service/src/test/java/org/zowe/apiml/gateway/config/AdditionalRegistrationTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/config/ConnectionsConfigTest.java
Labels: size/L

#3947 chore: Fix pipeline to generate changelog
  .github/workflows/changelog.yml
Labels: size/XS

#3956 fix: Fix Cloud Gateway configuration
  cloud-gateway-service/src/main/resources/application.yml
Labels: size/S

#3954 fix: logback turbofilters configuration
  apiml-common/src/main/resources/logback.xml
  apiml-utility/src/main/java/org/zowe/apiml/product/logging/LogLevelInfoFilter.java
  apiml-utility/src/test/java/org/zowe/apiml/product/logging/LogLevelInfoFilterTest.java
  caching-service/src/main/resources/logback.xml
  gateway-service/src/main/resources/logback-gateway.xml
  zaas-service/src/main/resources/logback-zaas.xml
Labels: size/M

#3958 chore: Update changelog for 3.1.3
  CHANGELOG.md
Labels: size/XS

#3962 fix: debug for production
  api-catalog-package/src/main/resources/bin/start.sh
  caching-service-package/src/main/resources/bin/start.sh
  config/zowe-api-dev/alternative_start.sh
  discovery-package/src/main/resources/bin/start.sh
  gateway-package/src/main/resources/bin/start.sh
  integration-tests/src/test/resources/environment-configuration.yml
  onboarding-enabler-nodejs-sample-app/build.gradle
  onboarding-enabler-nodejs-sample-app/package-lock.json
  onboarding-enabler-nodejs/build.gradle
  onboarding-enabler-nodejs/license-checker-config.json
  zaas-package/src/main/resources/bin/start.sh
Labels: size/M

#3966 fix: Use writeble headers on first. Solve the conflict with RequestAttributesProvider
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/RequestAttributesProvider.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/filters/RequestAttributesProviderTest.java
Labels: size/S

#3963 fix: gradle release version to 3.1.5-SNAPSHOT
  api-catalog-ui/frontend/.env
  gradle.properties
  onboarding-enabler-nodejs/package-lock.json
  onboarding-enabler-nodejs/package.json
Labels: size/XS

#3965 fix: Use writeble headers on first. Solve the conflict with RequestAttributesProvider
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/filters/RequestAttributesProvider.java
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/filters/RequestAttributesProviderTest.java
Labels: size/XS

#3959 fix: Fix initialization of the API Catalog
  api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/services/status/listeners/GatewayLookupEventListener.java
Labels: size/S

#3960 fix: Use HA instance ID in path to infinispan storage location (v3)
  caching-service-package/src/main/resources/bin/start.sh
  caching-service/src/main/java/org/zowe/apiml/caching/service/infinispan/config/InfinispanConfig.java
  caching-service/src/main/resources/infinispan.xml
  caching-service/src/test/java/org/zowe/apiml/caching/service/infinispan/config/InfinispanConfigTest.java
Labels: size/L

#3964 chore: Update CHANGELOG.md for 3.1.5
  CHANGELOG.md
Labels: size/XS

#3967 chore: Integration tests runnable with API ML on z/OS
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/auth/saf/SafResourceAccessSaf.java
  apiml-security-common/src/test/java/org/zowe/apiml/security/common/auth/saf/SafResourceAccessSafTest.java
  common-service-core/src/main/java/org/zowe/apiml/passticket/AbstractIRRPassTicketException.java
  common-service-core/src/test/java/org/zowe/apiml/passticket/AbstractIRRPassTicketExceptionTest.java
  config/local/gateway-service.yml
  integration-tests/build.gradle
  integration-tests/src/test/java/org/zowe/apiml/functional/apicatalog/ApiCatalogEndpointIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/functional/apicatalog/ApiCatalogLoginIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/functional/discovery/DiscoveryServiceAuthenticationTest.java
  integration-tests/src/test/java/org/zowe/apiml/functional/gateway/GatewayAuthenticationTest.java
  integration-tests/src/test/java/org/zowe/apiml/functional/gateway/InMemoryRateLimiterFilterFactoryIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/authentication/pat/AccessTokenServiceTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/authentication/pat/PATWithAllSchemesTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/authentication/providers/LoginTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/authentication/providers/LogoutTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/authentication/providers/QueryTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/authentication/providers/ZosmfLoginTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/authentication/schemes/GatewayAuthTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/authentication/services/ServiceProtectedEndpointIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/discovery/ApiCatalogDiscoverableClientIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/external/CachingStorageTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/graphql/BookControllerTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/ha/ApiCatalogMultipleInstancesTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/ha/DeterministicLoadBalancingTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/penetration/JwtPenTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/proxy/WebSocketProxyTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/zaas/PassTicketTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/zos/PassTicketTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/zos/ServicesInfoTest.java
  integration-tests/src/test/java/org/zowe/apiml/util/SecurityUtils.java
  integration-tests/src/test/java/org/zowe/apiml/util/categories/GraphQLTest.java
  integration-tests/src/test/java/org/zowe/apiml/util/categories/TestsNotMeantForZowe.java
  integration-tests/src/test/java/org/zowe/apiml/util/config/ConfigReader.java
  integration-tests/src/test/java/org/zowe/apiml/util/config/ConfigReaderZaasClient.java
  integration-tests/src/test/java/org/zowe/apiml/util/config/GatewayServiceConfiguration.java
  integration-tests/src/test/java/org/zowe/apiml/util/config/ZosmfServiceConfiguration.java
  integration-tests/src/test/java/org/zowe/apiml/util/http/HttpRequestUtils.java
  integration-tests/src/test/java/org/zowe/apiml/util/requests/ApiCatalogRequests.java
  integration-tests/src/test/java/org/zowe/apiml/util/requests/GatewayRequests.java
  keystore/README.md
  keystore/client_cert/client-certs.p12
  onboarding-enabler-nodejs/.gitignore
  package.json
  zaas-service/build.gradle
  zaas-service/src/main/resources/application.yml
  zaas-service/src/test/java/org/zowe/apiml/zaas/security/service/ticket/SuccessfulTicketHandlerTest.java
Labels: Sensitive, size/XXL
