Repository zowe/api-layer, pull requests merged in 2025-05, with the labels that each got.

#4073 fix: non-strict hostname verification in Jetty client for WebSockets
  apiml-common/src/main/java/org/zowe/apiml/product/web/HttpConfig.java
  common-service-core/src/main/java/org/zowe/apiml/security/HttpsFactory.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/ConnectionsConfig.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/WebSocketConfig.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/websocket/ApimlWebSocketClient.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/websocket/ApimlWebSocketSession.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/websocket/ApimlWebSocketClientTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/websocket/ApimlWebSocketSessionTest.java
  gradle/versions.gradle
  integration-tests/src/test/java/org/zowe/apiml/integration/proxy/WebSocketProxyTest.java
Labels: Sensitive, size/L

#4080 chore: remove python enabler form automated release
  .github/workflows/automated-release.yml
Labels: size/M

#4071 fix: Adding HSTS header when AT-TLS enabled V2
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/config/CustomHstsServerHttpHeadersWriter.java
  cloud-gateway-service/src/main/java/org/zowe/apiml/cloudgatewayservice/config/WebSecurity.java
  cloud-gateway-service/src/test/java/org/zowe/apiml/cloudgatewayservice/config/CustomHstsServerHttpHeadersWriterTest.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/config/CustomHstsHeadersWriter.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/config/NewSecurityConfiguration.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/security/config/CustomHstsHeadersWriterTest.java
Labels: Sensitive, size/L

#4052 fix: Adding HSTS header when AT-TLS enabled V3
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/CustomHstsServerHttpHeadersWriter.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/WebSecurity.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/config/CustomHstsServerHttpHeadersWriterTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/config/WebSecurityTest.java
Labels: size/L

#4009 feat: Add java sample app to authenticate client certificate
  client-cert-auth-sample/README.md
  client-cert-auth-sample/build.gradle
  client-cert-auth-sample/src/main/java/org/zowe/apiml/ClientCertificateAuthentication.java
  client-cert-auth-sample/src/main/java/org/zowe/apiml/Main.java
  client-cert-auth-sample/src/test/java/org/zowe/apiml/ClientCertificateAuthenticationTest.java
  gradle/coverage.gradle
  settings.gradle
Labels: size/L

#4097 chore: Update JXPath to version 1.4.0 (v2)
  gradle/versions.gradle
Labels: size/XS

#4096 chore: Update JXPath to version 1.4.0
  gradle/versions.gradle
Labels: size/XS

#4102 chore: move pipfiles to root location of the python sample app package
  .gitignore
  onboarding-enabler-python-sample-app/Pipfile
  onboarding-enabler-python-sample-app/Pipfile.lock
Labels: size/XS

#4103 chore: enable python enabler dependencies to be updated by renovate
  onboarding-enabler-python-sample-app/Pipfile
  onboarding-enabler-python-sample-app/Pipfile.lock
  onboarding-enabler-python/Pipfile
  onboarding-enabler-python/Pipfile.lock
Labels: size/L

#4112 chore: update catalog dependencies (v2)
  api-catalog-ui/frontend/package-lock.json
  api-catalog-ui/frontend/package.json
Labels: size/S
