Repository zowe/api-layer, pull requests merged in 2025-08, with the labels that each got.

#4253 chore: add modulith on z/os integration test tasks
  integration-tests/build.gradle
Labels: size/M

#4258 fix: prefer legacy component properties in modulith mode
  apiml-package/src/main/resources/bin/start.sh
  apiml-package/src/main/resources/manifest.yaml
  zaas-package/src/main/resources/bin/start.sh
Labels: size/L

#4260 fix: Caching Service failing to start when not all ports avaliable on the system
  caching-service/src/main/resources/infinispan.xml
Labels: size/XS

#4254 feat: adding PATCH in the list of CORS allowed methods
  common-service-core/src/main/java/org/zowe/apiml/util/CorsUtils.java
  common-service-core/src/test/java/org/zowe/apiml/util/CorsUtilsTest.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/ConnectionsConfig.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/config/ConnectionsConfigTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/config/ServiceCorsUpdaterTest.java
  zaas-service/src/test/java/org/zowe/apiml/zaas/metadata/service/CorsMetadataProcessorTest.java
Labels: size/L

#4265 Disable retry for configured services
  .github/workflows/integration-tests.yml
  gateway-package/src/main/resources/bin/start.sh
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/RoutingConfig.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/service/RouteLocator.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/acceptance/RetryPerServiceTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/service/RouteLocatorTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/proxy/MultipartPutIntegrationTest.java
  schemas/gateway-schema.json
Labels: size/L

#4295 feat: multiple OIDC providers at the same time
  api-catalog-ui/frontend/cypress.config.js
  api-catalog-ui/frontend/cypress/e2e/graphql/graphql-apiml.cy.js
  apiml/src/main/java/org/zowe/apiml/controller/ReactivePublicJWKController.java
  apiml/src/test/java/org/zowe/apiml/controller/ReactivePublicJWKControllerTest.java
  zaas-service/src/main/java/org/zowe/apiml/zaas/controllers/AuthController.java
  zaas-service/src/main/java/org/zowe/apiml/zaas/security/service/token/OIDCTokenProvider.java
  zaas-service/src/main/java/org/zowe/apiml/zaas/security/service/token/OIDCTokenProviderEndpoint.java
  zaas-service/src/test/java/org/zowe/apiml/acceptance/OIDCTokenProviderEndpointTest.java
  zaas-service/src/test/java/org/zowe/apiml/zaas/controllers/AuthControllerTest.java
  zaas-service/src/test/java/org/zowe/apiml/zaas/security/service/token/OIDCTokenProviderJWKTest.java
  zaas-service/src/test/java/org/zowe/apiml/zaas/security/service/token/OIDCTokenProviderTest.java
Labels: Sensitive, size/XL
