Repository zowe/api-layer, pull requests merged in 2025-02, with the labels that each got.

#3975 fix: z/OSMF static definition file processing (v2)
  .github/workflows/service-registration.yml
  discovery-package/src/main/resources/bin/configure.sh
  discovery-package/src/main/resources/manifest.yaml
  discovery-package/src/main/resources/zosmf-static-definition.yaml.template
Labels: size/M

#3971 fix: replace default spring x509 authentication in zaas
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/auth/saf/SafResourceAccessSaf.java
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/filter/CategorizeCertsFilter.java
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/login/NonCompulsoryAuthenticationProcessingFilter.java
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/login/X509AuthAwareFilter.java
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/login/X509ForwardingAwareAuthenticationFilter.java
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/verify/CertificateValidator.java
  apiml-security-common/src/test/java/org/zowe/apiml/security/common/auth/saf/SafResourceAccessSafTest.java
  apiml-security-common/src/test/java/org/zowe/apiml/security/common/filter/CategorizeCertsFilterTest.java
  apiml-security-common/src/test/java/org/zowe/apiml/security/common/verify/CertificateValidatorTest.java
  gateway-service/src/main/java/org/zowe/apiml/gateway/x509/AcceptForwardedClientCertFilterFactory.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/x509/AcceptForwardedClientCertFilterFactoryTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/authentication/pat/AccessTokenServiceTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/zos/PassTicketTest.java
  zaas-service/src/main/java/org/zowe/apiml/zaas/security/config/NewSecurityConfiguration.java
  zaas-service/src/main/java/org/zowe/apiml/zaas/zaas/ZaasAuthenticationFilter.java
  zaas-service/src/test/java/org/zowe/apiml/zaas/security/config/X509ForwardingAwareAuthenticationFilterTest.java
  zaas-service/src/test/resources/application-test.yml
  zaas-service/src/test/resources/application.yml
Labels: Sensitive, size/L

#3979 chore: remove deprecated and fix warnings in AttlsFilter (v2)
  apiml-tomcat-common/src/main/java/org/zowe/apiml/filter/AttlsFilter.java
Labels: size/S

#3969 chore: Add debug message for passticket generation during authentication transformation to detect real issue with configuration (v2)
  gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/HttpBasicPassTicketScheme.java
Labels: Sensitive, size/XS

#3970 chore: Improve logging (v3)
  api-catalog-services/src/main/resources/application.yml
  caching-service/src/main/resources/application.yml
  common-service-core/src/main/java/org/zowe/apiml/passticket/AbstractIRRPassTicketException.java
  common-service-core/src/main/java/org/zowe/apiml/passticket/PassTicketService.java
  common-service-core/src/test/java/org/zowe/apiml/passticket/IRRPassTicketEvaluationExceptionTest.java
  common-service-core/src/test/java/org/zowe/apiml/passticket/IRRPassTicketGenerationExceptionTest.java
  common-service-core/src/test/java/org/zowe/apiml/passticket/PassTicketServiceTest.java
  discovery-service/src/main/resources/application.yml
  gateway-service/src/main/resources/application.yml
  zaas-service/src/main/resources/application.yml
  zaas-service/src/test/java/org/zowe/apiml/zaas/security/service/TokenCreationServiceTest.java
Labels: Sensitive, size/M

#3986 chore: publish enabler to npmjs for v2.x.x
  .github/workflows/automated-release.yml
  .github/workflows/binary-specific-release.yml
  gradle.properties
  onboarding-enabler-nodejs/.npmrc
Labels: size/S

#3988 chore: fix release actions
  .github/workflows/automated-release.yml
  .github/workflows/binary-specific-release.yml
Labels: size/XS

#3989 chore: upgrade nodejs enabler version
  onboarding-enabler-nodejs/package.json
Labels: size/XS

#3991 chore: fix v2.x.x changelog github action
  .github/workflows/changelog.yml
Labels: size/XS

#3984 fix: LoginFilter failing in AccessToken generate filter chain
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/login/LoginFilter.java
  apiml-security-common/src/test/java/org/zowe/apiml/security/common/login/LoginFilterTest.java
Labels: Sensitive, size/M

#3994 fix: ssl.protocol default value
  api-catalog-package/src/main/resources/bin/start.sh
  caching-service-package/src/main/resources/bin/start.sh
  cloud-gateway-package/src/main/resources/bin/start.sh
  discovery-package/src/main/resources/bin/start.sh
  gateway-package/src/main/resources/bin/start.sh
  metrics-service-package/src/main/resources/bin/start.sh
Labels: size/S

#3999 fix: Add newPassword to the Swagger
  zaas-service/src/main/resources/zaas-api-doc.json
Labels: size/XS

#3998 fix: support authorization header in deterministic routing
  gateway-service/src/main/java/org/zowe/apiml/gateway/loadbalancer/DeterministicLoadBalancer.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/loadbalancer/DeterministicLoadBalancerTest.java
Labels: size/L

#4001 fix: fix four slashes support in SSE class
  gateway-service/src/main/java/org/zowe/apiml/gateway/sse/ServerSentEventProxyHandler.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/sse/ServerSentEventProxyHandlerTest.java
Labels: size/M

#4002 fix: Add newPassword to Open API Documentation of the login endpoint.
  gateway-service/src/main/resources/gateway-api-doc.json
Labels: size/XS

#4005 chore: runnable client cert sample
  client-cert-auth-sample/README.md
  client-cert-auth-sample/build.gradle
  client-cert-auth-sample/src/main/java/org/zowe/apiml/Main.java
Labels: size/M

#4000 fix: authentication header for routed requests
  gateway-service/src/main/java/org/zowe/apiml/gateway/filters/AbstractTokenFilterFactory.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/acceptance/TokenSchemeTest.java
  gateway-service/src/test/java/org/zowe/apiml/gateway/filters/AbstractTokenFilterFactoryTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/authentication/pat/PATWithAllSchemesTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/authentication/schemes/GatewayAuthTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/authentication/schemes/ZoweJwtSchemeTest.java
  integration-tests/src/test/java/org/zowe/apiml/integration/authentication/services/ServiceProtectedEndpointIntegrationTest.java
  mock-services/src/main/java/org/zowe/apiml/client/services/apars/FunctionalApar.java
  mock-services/src/main/java/org/zowe/apiml/client/services/apars/PHBase.java
Labels: size/M

#4007 fix: Workaround for api catalog redirect behavior in desktop
  api-catalog-package/src/main/resources/plugin/pluginDefinition.json
Labels: size/XS

#4008 fix: allow special characters in url
  discoverable-client/src/main/java/org/zowe/apiml/client/configuration/SecurityConfiguration.java
  discoverable-client/src/main/java/org/zowe/apiml/client/configuration/TomcatConfiguration.java
  discoverable-client/src/main/resources/application.yml
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/WebSecurity.java
  integration-tests/src/test/java/org/zowe/apiml/functional/gateway/GatewayRoutingTest.java
Labels: size/M

#3997 chore: include useful category in v3 debug logging
  gateway-service/src/main/resources/application.yml
Labels: size/XS

#4011 chore: Add forgotten breaking change
  CHANGELOG.md
Labels: size/XS

#4014 fix: fix issue with login filter
  apiml-security-common/src/main/java/org/zowe/apiml/security/common/login/LoginFilter.java
Labels: Sensitive, size/S

#4013 fix: Add missing OIDC documentation to OpenAPI
  gateway-service/src/main/resources/gateway-api-doc.json
Labels: size/M
