Repository zowe/api-layer, pull requests merged in 2025-04, with the labels that each got.

#4060 fix: jacoco in jib supports Java 21
  .gitignore
  scripts/README.md
  scripts/jacocoagent.jar
  scripts/jacococli.jar
Labels: size/XS

#4061 chore: add docs link to ZWEAG141 pasticket error
  common-service-core/src/main/resources/core-log-messages.yml
  zaas-service/src/test/resources/zaas-messages.yml
Labels: size/XS

#3990 chore: expect resposne code for positive cases
  integration-tests/src/test/java/org/zowe/apiml/functional/gateway/InMemoryRateLimiterFilterFactoryIntegrationTest.java
  integration-tests/src/test/java/org/zowe/apiml/util/config/ConfigReader.java
  integration-tests/src/test/java/org/zowe/apiml/util/config/GatewayServiceConfiguration.java
  integration-tests/src/test/resources/environment-configuration-attls.yml
  integration-tests/src/test/resources/environment-configuration-docker.yml
  integration-tests/src/test/resources/environment-configuration-ha.yml
  integration-tests/src/test/resources/environment-configuration.yml
Labels: size/S

#4066 chore: improve mock service info message
  mock-services/src/main/java/org/zowe/apiml/client/services/apars/PHBase.java
Labels: size/XS

#4062 chore: change gradle release version of enabler nodejs
  .github/workflows/integration-tests.yml
  api-catalog-ui/frontend/.env
  config/docker/api-catalog-services.yml
  config/docker/caching-service.yml
  config/docker/cloud-gateway-service.yml
  config/docker/discoverable-client.yml
  config/docker/discovery-service.yml
  config/docker/gateway-service.yml
  config/docker/mock-services.yml
  config/docker/zaas-service.yml
  gateway-service/src/main/resources/logback-gateway.xml
  gradle.properties
  gradle/jib.gradle
  integration-tests/src/test/java/org/zowe/apiml/startup/impl/ApiMediationLayerStartupChecker.java
  onboarding-enabler-nodejs/package-lock.json
  onboarding-enabler-nodejs/package.json
Labels: size/L

#4067 chore: temporarily remove publishing of nodejs enabler on binary release
  .github/workflows/automated-release.yml
Labels: size/M

#4054 fix: Empty username does not cause NPE during Pass Ticket generation
  common-service-core/src/main/java/org/zowe/apiml/passticket/AbstractIRRPassTicketException.java
  common-service-core/src/main/java/org/zowe/apiml/passticket/ApplicationNameNotProvidedException.java
  common-service-core/src/main/java/org/zowe/apiml/passticket/PassTicketException.java
  common-service-core/src/main/java/org/zowe/apiml/passticket/PassTicketService.java
  common-service-core/src/main/java/org/zowe/apiml/passticket/UsernameNotProvidedException.java
  common-service-core/src/test/java/org/zowe/apiml/passticket/PassTicketServiceTest.java
  config/docker/zaas-service.yml
  config/local/zaas-service.yml
  discoverable-client/src/main/java/org/zowe/apiml/client/api/PassTicketTestController.java
  integration-tests/src/test/java/org/zowe/apiml/integration/zaas/ZaasNegativeTest.java
  zaas-service/src/main/java/org/zowe/apiml/zaas/security/mapping/X509CommonNameUserMapper.java
  zaas-service/src/main/java/org/zowe/apiml/zaas/security/mapping/X509DummyCommonNameUserMapper.java
  zaas-service/src/main/java/org/zowe/apiml/zaas/security/mapping/X509NativeMapper.java
  zaas-service/src/main/java/org/zowe/apiml/zaas/security/service/PassTicketException.java
  zaas-service/src/main/java/org/zowe/apiml/zaas/security/service/TokenCreationService.java
  zaas-service/src/main/java/org/zowe/apiml/zaas/security/ticket/SuccessfulTicketHandler.java
  zaas-service/src/main/java/org/zowe/apiml/zaas/zaas/SchemeController.java
  zaas-service/src/main/java/org/zowe/apiml/zaas/zaas/ZaasAuthenticationFilter.java
  zaas-service/src/main/java/org/zowe/apiml/zaas/zaas/ZaasExceptionHandler.java
  zaas-service/src/test/java/org/zowe/apiml/zaas/security/mapping/X509NativeMapperTest.java
  zaas-service/src/test/java/org/zowe/apiml/zaas/security/service/TokenCreationServiceTest.java
  zaas-service/src/test/java/org/zowe/apiml/zaas/security/service/ticket/SuccessfulTicketHandlerTest.java
  zaas-service/src/test/java/org/zowe/apiml/zaas/zaas/SchemeControllerTest.java
  zaas-service/src/test/java/org/zowe/apiml/zaas/zaas/ZaasAuthenticationFilterTest.java
Labels: Sensitive, size/L

#4069 fix: disable hostname verification with nonStrict
  gateway-service/src/main/java/org/zowe/apiml/gateway/config/ConnectionsConfig.java
Labels: size/XS

#4070 fix: fix SSO issue in the API Catalog
  api-catalog-ui/frontend/cypress.config.js
  api-catalog-ui/frontend/cypress/e2e/dashboard/dashboard.cy.js
  api-catalog-ui/frontend/mocked-backend/routes/routes.js
  api-catalog-ui/frontend/package.json
  api-catalog-ui/frontend/src/actions/user-actions.jsx
  api-catalog-ui/frontend/src/actions/user-actions.test.jsx
  api-catalog-ui/frontend/src/components/App/App.jsx
  api-catalog-ui/frontend/src/components/App/App.test.jsx
  api-catalog-ui/frontend/src/components/App/AppContainer.jsx
  api-catalog-ui/frontend/src/components/App/AppContainer.test.jsx
  api-catalog-ui/frontend/src/components/DetailPage/DetailPage.css
  api-catalog-ui/frontend/src/components/DetailPage/DetailPage.jsx
  api-catalog-ui/frontend/src/components/DetailPage/DetailPage.test.jsx
  api-catalog-ui/frontend/src/components/DetailPage/DetailPageContainer.jsx
  api-catalog-ui/frontend/src/components/ServicesNavigationBar/ServicesNavigationBar.jsx
  api-catalog-ui/frontend/src/components/Tile/Tile.jsx
  api-catalog-ui/frontend/src/reducers/authentication-reducer.jsx
  api-catalog-ui/frontend/src/reducers/authentication-reducer.test.jsx
  api-catalog-ui/frontend/src/reducers/tiles-reducer.jsx
  api-catalog-ui/frontend/src/services/user.service.jsx
  api-catalog-ui/frontend/src/services/user.service.test.jsx
Labels: size/L

#4068 feat: Onboarding Python Enabler
  .github/workflows/automated-release.yml
  .github/workflows/binary-specific-release.yml
  CONTRIBUTING.md
  README.md
  api-catalog-ui/frontend/cypress/e2e/dashboard/wizard-dialog.cy.js
  api-catalog-ui/frontend/cypress/fixtures/enabler-test-files/testEnabler5.yaml
  api-catalog-ui/frontend/cypress/fixtures/enabler-test-files/testEnabler6.yaml
  api-catalog-ui/frontend/src/components/Wizard/configs/wizard_categories.jsx
  api-catalog-ui/frontend/src/components/Wizard/configs/wizard_defaults.jsx
  api-catalog-ui/frontend/src/components/Wizard/configs/wizard_node_categories.jsx
  api-catalog-ui/frontend/src/components/Wizard/configs/wizard_non_java_categories.jsx
  api-catalog-ui/frontend/src/components/Wizard/configs/wizard_onboarding_methods.jsx
  gradle/license.gradle
  gradle/sonar.gradle
  onboarding-enabler-python-sample-app/README.md
  onboarding-enabler-python-sample-app/build.gradle
  onboarding-enabler-python-sample-app/src/Pipfile
  onboarding-enabler-python-sample-app/src/Pipfile.lock
  onboarding-enabler-python-sample-app/src/__init__.py
  onboarding-enabler-python-sample-app/src/app.py
  onboarding-enabler-python-sample-app/src/config/service-configuration.yml
  onboarding-enabler-python-sample-app/src/pythonSwagger.json
  onboarding-enabler-python-sample-app/tests/__init__.py
  onboarding-enabler-python-sample-app/tests/test_app.py
  onboarding-enabler-python/.gitignore
  onboarding-enabler-python/Pipfile
  onboarding-enabler-python/Pipfile.lock
  onboarding-enabler-python/README.md
  onboarding-enabler-python/build.gradle
  onboarding-enabler-python/pyproject.toml
  onboarding-enabler-python/release.config.js
  onboarding-enabler-python/src/zowe_apiml_onboarding_enabler_python/__init__.py
  onboarding-enabler-python/src/zowe_apiml_onboarding_enabler_python/config.py
  onboarding-enabler-python/src/zowe_apiml_onboarding_enabler_python/custom_http_client.py
  onboarding-enabler-python/src/zowe_apiml_onboarding_enabler_python/registration.py
  onboarding-enabler-python/tests/__init__.py
  onboarding-enabler-python/tests/test_config.py
  onboarding-enabler-python/tests/test_custom_http_client.py
  onboarding-enabler-python/tests/test_registration.py
  settings.gradle
Labels: size/XXL

#4017 feat: Certificate validation improvements
  certificate-analyser/src/main/java/org/zowe/apiml/Analyser.java
  certificate-analyser/src/main/java/org/zowe/apiml/ApimlConf.java
  certificate-analyser/src/main/java/org/zowe/apiml/LocalHandshake.java
  certificate-analyser/src/main/java/org/zowe/apiml/LocalVerifier.java
  certificate-analyser/src/main/java/org/zowe/apiml/RemoteHandshake.java
  certificate-analyser/src/main/java/org/zowe/apiml/Verifier.java
  certificate-analyser/src/test/java/org/zowe/apiml/AnalyserTest.java
  certificate-analyser/src/test/java/org/zowe/apiml/LocalVerifierTest.java
Labels: size/L
